version: '2'
services:
  previsora_proxy:
    image: joagranadosme/proxy:Certificate
    depends_on:
      - previsora_ms
    ports:
      - 80:80
  previsora_db:
    image: postgres
    ports:
      - "4000:5432"
  previsora_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - previsora_db
