version: '2'
services:
  previsora_proxy:
    image: joagranadosme/proxy
    depends_on:
      - previsora_ms
    ports:
      - 80:80
  previsora_db:
    image: postgres
    ports:
      - "5432:5432"
  previsora_ms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:'
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - previsora_db
