User.create([
  {document: "12345678", name: "USUARIO MIGRACION", charge: 'MIGRACION', password: "JonathanG123", password_confirmation: "JonathanG123", role: 1},
  {document: "1032459412", name: "JONATHAN GRANADOS", charge: 'INGENIERO PYO', password: "JonathanG123", password_confirmation: "JonathanG123", role: 1},
  {document: "1", name: "COORDINADOR OPERATIVO", charge: 'INGENIERO PYO', password: "CoordinadorOperativo2018", password_confirmation: "CoordinadorOperativo2018", role: 2},
  {document: "2", name: "COORDINADOR LEGAL", charge: 'INGENIERO PYO', password: "CoordinadorLegal2018", password_confirmation: "CoordinadorLegal2018", role: 3},
  {document: "3", name: "ADMINISTRADOR", charge: 'INGENIERO PYO', password: "Administrador2018", password_confirmation: "Administrador2018", role: 4},
  {document: "1234", name: "JONATHAN PRIETO", charge: 'INGENIERO PYO', password: "JonathanP123", password_confirmation: "JonathanP123", role: 1},
  {document: '1020729468', name: 'NATALIA ALEJANDRA  MONCAYO RODRIGUEZ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'EO0wDxJX', password_confirmation: 'EO0wDxJX', role: 1},
  {document: '49797396', name: 'BETSABE  MANTILLA DIAZ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'EGag5iL7', password_confirmation: 'EGag5iL7', role: 1},
  {document: '1010169121', name: 'ANGELA LILIANA LOPEZ ALVAREZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'QBa5OIEM', password_confirmation: 'QBa5OIEM', role: 1},
  {document: '1031138340', name: 'LUIS EDUARDO LOPEZ  MORA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: '0kRu6WCg', password_confirmation: '0kRu6WCg', role: 1},
  {document: '1026252607', name: 'LUZ ANDREA JIMENEZ MUÑOZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'ryo7CYYH', password_confirmation: 'ryo7CYYH', role: 1},
  {document: '52780795', name: 'CRYSTHEL EMANUELLA GUTIERREZ RAMIREZ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'yFkj3sf8', password_confirmation: 'yFkj3sf8', role: 1},
  {document: '39567180', name: 'LIDA MORELIA CALDERON RODRIGUEZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: '0LeEPo7f', password_confirmation: '0LeEPo7f', role: 1},
  {document: '1026570699', name: 'CHRISTIAN CAMILO  HERNANDEZ VEGA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: '0M1U3p1R', password_confirmation: '0M1U3p1R', role: 1},
  {document: '7181859', name: 'DANNY FABIAN GUIO MUÑOZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'XGy9iCsT', password_confirmation: 'XGy9iCsT', role: 1},
  {document: '80525785', name: 'FREDDY LEONEL ROJAS RIOS', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: '2ymcnbQx', password_confirmation: '2ymcnbQx', role: 1},
  {document: '40216726', name: 'FLOR ANGELA TORRES HUERTAS', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'YbsUyrmI', password_confirmation: 'YbsUyrmI', role: 1},
  {document: '1015441384', name: 'DANIEL ALEJANDRO PALACIOS BALLEN', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'FMfqHar4', password_confirmation: 'FMfqHar4', role: 1},
  {document: '79828072', name: 'LEONARDO FABIO CALDERON GALLEGO', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'giZPnjWt', password_confirmation: 'giZPnjWt', role: 1},
  {document: '51779870', name: 'ANA PATRICIA MOLANO GACHANCIPA', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'TCTKnskD', password_confirmation: 'TCTKnskD', role: 1},
  {document: '1018469232', name: 'AURA JESSICA MEDINA FANDIÑO', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'pl5BWtBD', password_confirmation: 'pl5BWtBD', role: 1},
  {document: '79993930', name: 'EMIRO ANTONIO VAGAS ', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'xr2PmYT4', password_confirmation: 'xr2PmYT4', role: 1},
  {document: '71683546', name: 'FABIAN DE JESUS PASADA VELEZ', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'q3iNLtfU', password_confirmation: 'q3iNLtfU', role: 1},
  {document: '1118532099', name: 'MAYRA  MORENO ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'KC6vrchA', password_confirmation: 'KC6vrchA', role: 1},
  {document: '1016039726', name: 'MARIA ALEJANDRA  GUTIERREZ BECERRA', charge: 'PROFESIONAL GERENCIA DE PROCESOS JUDICIALES', password: 'sURn9FFC', password_confirmation: 'sURn9FFC', role: 1},
  {document: '52976920', name: 'EDITH JOHANNA VELASQUEZ GONZALEZ', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'itkDKpR9', password_confirmation: 'itkDKpR9', role: 1},
  {document: '63358777', name: 'DALILA CRISTINA TAPIAS ACEVEDO', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'jZAMJL2o', password_confirmation: 'jZAMJL2o', role: 1},
  {document: '37901644', name: 'LUISA FERNANDA ORTEGA SOLANO', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'TiFXWbff', password_confirmation: 'TiFXWbff', role: 1},
  {document: '72272660', name: 'ARON JOSE ORTIZ ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: '3slGfSSq', password_confirmation: '3slGfSSq', role: 1},
  {document: '1018442399', name: 'YURANY HASLEYDI NORE ORTEGA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'k38pVBV8', password_confirmation: 'k38pVBV8', role: 1},
  {document: '1018407179', name: 'IVAN  ORDOÑEZ ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'NbdP6l6Z', password_confirmation: 'NbdP6l6Z', role: 1},
  {document: '80212112', name: 'JUAN MANUEL PEÑA TORRES', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'ftSqd3NO', password_confirmation: 'ftSqd3NO', role: 1},
  {document: '1022372499', name: 'DAYANE ACOSTA AVILA ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: '4ggtKVFN', password_confirmation: '4ggtKVFN', role: 1},
  {document: '20370708', name: 'SANDRA MILENA SANCHEZ RUIZ', charge: 'CONTADOR PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: '2dCi6SSc', password_confirmation: '2dCi6SSc', role: 1},
  {document: '28554902', name: 'CLAUDIA  RODRIGUEZ PATRON', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'hiecZniO', password_confirmation: 'hiecZniO', role: 1},
  {document: '1047404034', name: 'CRISTIAN D POMARES ', charge: 'CONTADOR PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'uU9YYPlD', password_confirmation: 'uU9YYPlD', role: 1},
  {document: '1012329910', name: 'INDIRA ALEXANDRA BEJARANO RAMIREZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'ouqWmkJs', password_confirmation: 'ouqWmkJs', role: 1},
  {document: '80110210', name: 'VICTOR ANDRES GOMEZ HENAO', charge: 'GERENTE DE PROCESOS JUDICIALES', password: 'H5cF44L0', password_confirmation: 'H5cF44L0', role: 1},
  {document: '51575744', name: 'NOHORA MARLENI BOJACA MARTIN', charge: 'SUBGERENTE DE LITIGIOS', password: 'WLRWVHaK', password_confirmation: 'WLRWVHaK', role: 1}
])

ProcessClass.create([
  {name: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO', n_type:	2},
  {name: 'JURISDICCION CIVIL', n_type: 2},
  {name: 'JURISDICCION PENAL', n_type: 2},
  {name: 'JURISDICCION LABORAL', n_type: 2},
  {name: 'RESPONSABILIDAD FISCAL', n_type: 3},
  {name: 'TUTELA', n_type: 5},
  {name: "PROCESO ARBITRAL", n_type: 2},
  {name: "PREJUDICIAL REQUISITO DE PROCEDIBILIDAD", n_type: 1},
  {name: "PROCEDIMIENTO ADMINISTRATIVO" , n_type: 4},
  {name: 'NO PRESENTA', n_type: 0}
])

SubprocessClass.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'PROCESOS PENALES', n_type: 21},
  {name: 'NULIDAD POR INCONSTITUCIONALIDAD', n_type: 22},
  {name: 'CONTROL INMEDIATO DE LEGALIDAD', n_type: 22},
  {name: 'NULIDAD', n_type: 22},
  {name: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO', n_type: 22},
  {name: 'NULIDAD ELECTORAL', n_type: 22},
  {name: 'REPARACION DIRECTA', n_type: 22},
  {name: 'CONTROVERSIAS CONTRACTUALES', n_type: 22},
  {name: 'REPETICION', n_type: 22},
  {name: 'PERDIDA DE INVESTIDURA', n_type: 22},
  {name: 'ACCION POPULAR', n_type: 22},
  {name: 'ACCION DE GRUPO', n_type: 22},
  {name: 'CUMPLIMIENTO DE NORMAS CON FUERZA MATERIAL DE LEY O DE ACTOS ADMINISTRATIVOS', n_type: 22},
  {name: 'NULIDAD DE LAS CARTAS DE NATURALEZA Y DE LAS RESOLUCIONES DE AUTORIZACION DE INSCRIPCION', n_type: 23},
  {name: 'CONTROL POR VIA DE EXCEPCION', n_type: 23},
  {name: 'PROCESO VERBAL', n_type: 23},
  {name: 'PROCESO VERBAL SUMARIO', n_type: 23},
  {name: 'PROCESOS DECLARATIVOS ESPECIALES', n_type: 23},
  {name: 'PROCESO EJECUTIVO', n_type: 23},
  {name: 'PROCESO DE SUCESION', n_type: 23},
  {name: 'PROCESO DE LIQUIDACION DE SOCIEDADES CONYUGALES O PATRIMONIALES POR CAUSA DISTINTA DE LA MUERTE DE LOS CONYUGES O COMPANEROS PERMANENTES', n_type: 23},
  {name: 'DISOLUCION, NULIDAD Y LIQUIDACION DE SOCIEDADES', n_type: 23},
  {name: 'INSOLVENCIA DE LA PERSONA NATURAL NO COMERCIANTE', n_type: 23},
  {name: 'PROCESO ORDINARIO', n_type: 23},
  {name: 'PROCESO ARBITRAL', n_type: 24},
  {name: 'ESPECIAL', n_type: 25},
  {name: 'ORDINARIO', n_type: 25},
  {name: 'VERBAL', n_type: 3},
  {name: 'ORDINARIO', n_type: 3},
  {name: 'ORDINARIO', n_type: 4},
  {name: 'COLJUEGOS', n_type: 4},
  {name: 'JUNTA DE CALIFICACION', n_type: 5},
  {name: 'CONTRA PROVIDENCIA JUDICIAL', n_type: 5},
  {name: 'CONTRA PROVIDENCIA (PROCESO FISCAL)', n_type: 5},
  {name: 'CONTRATO DE SEGUROS', n_type: 5},
  {name: 'DERECHO DE PETICION', n_type: 5},
  {name: 'EXPEDICION POLIZAS (PRESUNCION DE RIESGOS)', n_type: 5},
  {name: 'FALTA DE LEGITIMACION', n_type: 5},
  {name: 'INCAPACIDAD TEMPORAL', n_type: 5},
  {name: 'POLIZA VIDA GRUPO', n_type: 5},
  {name: 'ACCIDENTES PERSONALES', n_type: 5},
  {name: 'SOAT - AUTORIZACIONES EPS', n_type: 5},
  {name: 'SOAT - PAGO INDEMNIZACIONES', n_type: 5},
  {name: 'EXPEDICION DE POLIZAS DE SERIDAD CANDIDATURA NO ASEGURABLE', n_type: 5},
  {name: 'ACTUACION TEMERARIA', n_type: 5}
])

LinkType.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'CONVOCANTE', n_type: 1},
  {name: 'CONVOCADO', n_type: 1},
  {name: 'DEMANDANTE', n_type: 2},
  {name: 'TERCERO CIVILMENTE RESPONSABLE', n_type: 2},
  {name: 'LLAMADA EN GARANTIA', n_type: 2},
  {name: 'DEMANDADO', n_type: 3},
  {name: 'GARANTE', n_type: 4},
  {name: 'ACCIONADO', n_type: 5},
  {name: 'VINCULADO', n_type: 5},
  {name: 'ACCIONADO', n_type: 6},
  {name: 'VINCULADO', n_type: 6},
  {name: 'TERCERO CIVILMENTE RESPONSABLE', n_type: 8}
])

BranchPolicy.create([
  {name: 'NO PRESENTA', num: 0},
  {name: 'ARMENIA', num: 1},
  {name: 'BARRANQUILLA', num: 2},
  {name: 'BUCARAMANGA', num: 3},
  {name: 'CALI', num: 4},
  {name: 'CARTAGENA', num: 5},
  {name: 'CUCUTA', num: 6},
  {name: 'FLORENCIA', num: 7},
  {name: 'IBAGUE', num: 8},
  {name: 'MANIZALES', num: 9},
  {name: 'MEDELLIN', num: 10},
  {name: 'MOCOA', num: 11},
  {name: 'MONTERIA', num: 12},
  {name: 'NEIVA', num: 13},
  {name: 'PASTO', num: 14},
  {name: 'PEREIRA', num: 15},
  {name: 'POPAYAN', num: 16},
  {name: 'QUIBDO', num: 17},
  {name: 'RIOHACHA', num: 18},
  {name: 'SAN ANDRES', num: 19},
  {name: 'SANTA MARTA', num: 20},
  {name: 'SINCELEJO', num: 21},
  {name: 'TUNJA', num: 23},
  {name: 'VALLEDUPAR', num: 24},
  {name: 'VILLAVICENCIO', num: 25},
  {name: 'YOPAL', num: 26},
  {name: 'BUENAVENTURA', num: 27},
  {name: 'ARAUCA', num: 28},
  {name: 'CENTRO EMPRESARIAL CORPORATIVO', num: 32},
  {name: 'CENTRO DE SERVICIOS MASIVOS', num: 33},
  {name: 'VIRTUAL BARRANQUILLA', num: 35},
  {name: 'REGIONAL ESTATAL', num: 70},
  {name: 'CASA MATRIZ', num: 80},
  {name: 'BOGOTA', num: 90}
])

BranchCommercial.create([
  {name: 'NO PRESENTA', num: 0},
  {name: 'MANEJO', num: 1},
  {name: 'CUMPLIMIENTO', num: 2},
  {name: 'INCENDIO', num: 3},
  {name: 'SUSTRACCION', num: 4},
  {name: 'TRANSPORTES', num: 5},
  {name: 'CASCO BARCO', num: 6},
  {name: 'AUTOMOVILES', num: 7},
  {name: 'SOAT', num: 8},
  {name: 'VIDRIOS PLANOS', num: 9},
  {name: 'CASCO AVIACION', num: 10},
  {name: 'TERREMOTO (AMP. INCENDIO)', num: 11},
  {name: 'TERREMOTO (AMP. CORRIENTE DEBIL)', num: 12},
  {name: 'RESPONSABILIDAD CIVIL', num: 13},
  {name: 'SEGURO AGRICOLA', num: 14},
  {name: 'INFIDELIDAD DE RIESGOS FINANCIEROS', num: 15},
  {name: 'VIDA COLECTIVO', num: 16},
  {name: 'VIDA GRUPO', num: 17},
  {name: 'VIDA GRUPO DEUDORES', num: 18},
  {name: 'ACCIDENTES PERSONALES', num: 19},
  {name: 'ESTABILIDAD Y CALIDAD DE VIVIENDA', num: 20},
  {name: 'OBRAS CIVILES', num: 21},
  {name: 'SALUD', num: 22},
  {name: 'DESEMPLEO', num: 23},
  {name: 'ADMINIST. RIESGOS PROFESIONALES', num: 24},
  {name: 'VIDA INDIVIDUAL', num: 25},
  {name: 'CAUCION JUDICIAL', num: 29},
  {name: 'ROTURA DE MAQUINARIA', num: 81},
  {name: 'MONTAJE DE MAQUINARIA', num: 82},
  {name: 'CORRIENTE DEBIL', num: 83},
  {name: 'TODO RIESGO CONTRATISTA', num: 84},
  {name: 'MINAS Y PETROLEOS', num: 85},
  {name: 'PREVIHOSPITAL', num: 86},
  {name: 'PREVIALCALDIAS', num: 87},
  {name: 'PREVIPYME', num: 88},
  {name: 'PREVIHOGAR', num: 89},
  {name: 'AREAS COMUNES', num: 90},
  {name: 'PREVITURISMO', num: 91},
  {name: 'PREVIQUIMICOS', num: 92},
  {name: 'PREVIEDUCATIVO', num: 93},
  {name: 'TODO RIESGO EMPRESARIAL', num: 94},
  {name: 'PREVICAMPO', num: 95},
  {name: 'DANOS MATERIALES', num: 98}
])

LitigationSource.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'SINIESTRO', n_type: 1},
  {name: 'PROVISION', n_type: 1},
  {name: 'ESTIMACION RECOBRO', n_type: 1},
  {name: 'VINCULACION ERRADA', n_type: 1},
  {name: 'CONTRATO LABORAL', n_type: 1},
  {name: 'CREDITO HIPOTECARIO', n_type: 1},
  {name: 'DOLO O CULPA GRAVE', n_type: 1},
  {name: 'PRIMAS', n_type: 1}
])

Protection.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL', n_type: 1},
  {name: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA', n_type: 1},
  {name: 'DANOS EXTRAPATRIMONIALES', n_type: 1},
  {name: 'ERRORES U OMISIONES PROFESIONALES', n_type: 1},
  {name: 'COBERTURA R.C CLINICAS Y HOSPITALES', n_type: 1},
  {name: 'FALLOS CON RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'RENDICION Y RECONSTRUCCION DE CUENTAS', n_type: 1},
  {name: 'PREDIOS LABORES Y OPERACIONES', n_type: 1},
  {name: 'EMPLEADOS NO IDENTIFICADOS ( CLAUSULA)', n_type: 1},
  {name: 'ACTOS INCORRECTOS', n_type: 1},
  {name: 'INCAPACIDAD PERMANENTE', n_type: 1},
  {name: 'RC. PATRONAL', n_type: 1},
  {name: 'ABUSO DE CONFIANZA', n_type: 1},
  {name: 'ASISTENCIA JURIDICA PENAL', n_type: 1},
  {name: 'ASISTENCIA JURIDICA CIVIL', n_type: 1},
  {name: 'HONORARIOS PROFESIONALES', n_type: 1},
  {name: 'PAGO DE SALARIOS PRESTACIONES SOCIALES E INDEMNIZACIONES', n_type: 1},
  {name: 'HURTO CALIFICADO', n_type: 1},
  {name: 'BUEN MANEJO DEL ANTICIPO', n_type: 1},
  {name: 'ACTOS QUE GENEREN JUICIOS DE RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'PERJUICIOS MODALIDAD DANO EMERGENTE', n_type: 1},
  {name: 'RESPONSABILIDAD CIVIL CRUZADA', n_type: 1},
  {name: 'CONVERSION', n_type: 1},
  {name: 'CUMPLIMIENTO DE CONTRATO', n_type: 1},
  {name: 'INFIDELIDAD DE EMPLEADOS', n_type: 1},
  {name: 'AVERIAS', n_type: 1},
  {name: 'EXTENDED COVERAGE (OTROS AMPAROS ADICIONALES)', n_type: 1},
  {name: 'PERDIDA PARCIAL DANOS', n_type: 1},
  {name: 'FALTA DE ENTREGA', n_type: 1},
  {name: 'ENFERMEDADES DE ALTO COSTO SUBSIDIADO', n_type: 1},
  {name: 'COBERTURA OBRAS CIVILES ( CONSTRUCCION)', n_type: 1},
  {name: 'COBERTURA R.C EXTRACONTRACTUAL', n_type: 1},
  {name: 'PERDIDA SEVERA POR HURTO', n_type: 1},
  {name: 'TERAPEUTICOS', n_type: 1},
  {name: 'CUMPLIMIENTO', n_type: 41},
  {name: 'CUMPLIMIENTO', n_type: 42},
  {name: 'ESTABILIDAD LABORAL', n_type: 42},
  {name: 'SALARIOS Y PRESTACIONES E INDEMNIZACIONES', n_type: 42},
  {name: 'BUEN MANEJO DEL ANTICIPO', n_type: 42},
  {name: 'COBERTURA GLOBAL DEL MANEJO', n_type: 1},
  {name: 'OTRO', n_type: 1}
])

ScoreContingency.create([
  {name: 'NO PRESENTA'},
  {name: 'EVENTUAL'},
  {name: 'REMOTA'},
  {name: 'PROBABLE'}
])

CurrentStage.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'AUTO DE APERTURA', n_type: 1},
  {name: 'AUTO DE IMPUTACION', n_type: 1},
  {name: 'AUTO DE APERTURA E IMPUTACION', n_type: 1},
  {name: 'ARGUMENTOS DE DEFENSA', n_type: 1},
  {name: 'ALEGATOS DE CONCLUSION', n_type: 1},
  {name: 'FALLO CON RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'RECURSO DE REPOSICION', n_type: 1},
  {name: 'AUTO QUE RESUELVE LA REPOSICION', n_type: 1},
  {name: 'RECURSO DE APELACION', n_type: 1},
  {name: 'AUTO QUE RESUELVE APELACION', n_type: 1},
  {name: 'FALLO SIN RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA', n_type: 1},
  {name: 'AUTO DE APERTURA', n_type: 2},
  {name: 'AUTO DE IMPUTACION', n_type: 2},
  {name: 'AUTO DE APERTURA E IMPUTACION', n_type: 2},
  {name: 'AUDIENCIA DE DESCARGOS', n_type: 2},
  {name: 'AUDIENCIA DE DECISION', n_type: 2},
  {name: 'FALLO CON RESPONSABILIDAD FISCAL', n_type: 2},
  {name: 'RECURSO DE REPOSICION', n_type: 2},
  {name: 'AUTO QUE RESUELVE LA REPOSICION', n_type: 2},
  {name: 'RECURSO DE APELACION', n_type: 2},
  {name: 'AUTO QUE RESUELVE APELACION', n_type: 2},
  {name: 'FALLO SIN RESPONSABILIDAD FISCAL', n_type: 2},
  {name: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA', n_type: 2},
  {name: 'INDAGACION', n_type: 5},
  {name: 'INVESTIGACION', n_type: 5},
  {name: 'ETAPA DE JUZGAMIENTO', n_type: 5},
  {name: 'AUDIENCIA DE ACUSACION', n_type: 5},
  {name: 'AUDIENCIA PREPARATORIA', n_type: 5},
  {name: 'AUDIENCIA DE JUICIO ORAL', n_type: 5},
  {name: 'AUDIENCIA DE INCIDENTE DE REPARACION INTEGRAL', n_type: 5},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 5},
  {name: 'AUDIENCIA DE PRUEBAS Y ALEGACIONES', n_type: 5},
  {name: 'SENTENCIA DE INCIDENTE DE REPARACION INTEGRAL', n_type: 5},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 3},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 3},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 3},
  {name: 'DEMANDA DE RECONVENCION', n_type: 3},
  {name: 'PRUEBAS', n_type: 3},
  {name: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA', n_type: 3},
  {name: 'SENTENCIA DE PRIMERA INSTANCIA', n_type: 3},
  {name: 'APELACION', n_type: 3},
  {name: 'AUDIENCIA DE CONCILIACION (ART 70)', n_type: 3},
  {name: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA', n_type: 3},
  {name: 'SENTENCIA SEGUNDA INSTANCIA', n_type: 3},
  {name: 'RECURSO EXTRAORDINARIO DE UNIFICACION DE JURISPRUDENCIA', n_type: 3},
  {name: 'RECURSO DE REVISION', n_type: 3},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 4},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 4},
  {name: 'DEMANDA DE RECONVENCION', n_type: 4},
  {name: 'AUDIENCIA Y FALLO', n_type: 4},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 4},
  {name: 'AUDIENCIA PUBLICA', n_type: 4},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 4},
  {name: 'AUDIENCIA DE TRAMITE O PRUEBA', n_type: 4},
  {name: 'AUDIENCIA DE JUZGAMIENTO', n_type: 4},
  {name: 'APELACION', n_type: 4},
  {name: 'AUDIENCIA DE ALEGACIONES Y FALLO', n_type: 4},
  {name: 'AUDIENCIA DE ALEGACIONES', n_type: 4},
  {name: 'AUDIENCIA DE FALLO', n_type: 4},
  {name: 'DEMANDA DE CASACION', n_type: 4},
  {name: 'ADMISION DEMANDA DE CASACION', n_type: 4},
  {name: 'OPOSICION DEMANDA DE CASACION', n_type: 4},
  {name: 'SENTENCIA DE CASACION', n_type: 4},
  {name: 'INTEGRACION DEL TRIBUNAL ARBITRAL', n_type: 6},
  {name: 'IMPEDIMENTOS Y RECUSACIONES ', n_type: 6},
  {name: 'INSTALACION DEL TRIBUNAL ARBITRAL', n_type: 6},
  {name: 'ADMISION DE LA DEMANDA', n_type: 6},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 6},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 6},
  {name: 'ACTA DE FIJACION DE HONORARIOS Y GASTOS DEL TRIBUNAL', n_type: 6},
  {name: 'PRIMERA AUDIENCIA DE TRAMITE', n_type: 6},
  {name: 'AUDIENCIAS Y PRUEBAS', n_type: 6},
  {name: 'AUDIENCIA DE ALEGATOS Y FALLO', n_type: 6},
  {name: 'LAUDO ARBITRAL', n_type: 6},
  {name: 'RECURSO EXTRAORDINARIO DE ANULACION', n_type: 6},
  {name: 'SENTENCIA SOBRE ANULACION', n_type: 6},
  {name: 'RECURSO DE REVISION', n_type: 6},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 7},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 7},
  {name: 'DEMANDA DE RECONVENCION', n_type: 7},
  {name: 'AUDIENCIA INICIAL', n_type: 7},
  {name: 'PRUEBAS PRIMERA INSTANCIA', n_type: 7},
  {name: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO', n_type: 7},
  {name: 'APELACION', n_type: 7},
  {name: 'AUDIENCIA DE SUSTENTACION Y FALLO', n_type: 7},
  {name: 'DEMANDA DE CASACION', n_type: 7},
  {name: 'ADMISION DEMANDA DE CASACION', n_type: 7},
  {name: 'OPOSICION DEMANDA DE CASACION', n_type: 7},
  {name: 'SENTENCIA DE CASACION', n_type: 7},
  {name: 'RECURSO DE QUEJA', n_type: 7},
  {name: 'RECURSO DE REVISION', n_type: 7},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 8},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 8},
  {name: 'DEMANDA DE RECONVENCION', n_type: 8},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 8},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 9},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 9},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 9},
  {name: 'SENTENCIA DE UNICA INSTANCIA', n_type: 9},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 9},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 10},
  {name: 'MANDAMIENTO EJECUTIVO', n_type: 10},
  {name: 'PRESENTACION DE EXCEPCIONES Y/O RECURSO DE REPOSICION', n_type: 10},
  {name: 'PRUEBAS', n_type: 10},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 10},
  {name: 'AUDIENCIA INICIAL', n_type: 10},
  {name: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO', n_type: 10},
  {name: 'AUTO ORDENA SEGUIR ADELANTE LA EJECUCION', n_type: 10},
  {name: 'LIQUIDACION DEL CREDITO POR LAS PARTES', n_type: 10},
  {name: 'AUTO QUE APRUEBA O MODIFICA LIQUIDACION DEL CREDITO', n_type: 10},
  {name: 'REMATE DE BIENES', n_type: 10},
  {name: 'DILIGENCIA DE DESLINDE', n_type: 11},
  {name: 'SOLICITUD DE LICENCIA PREVIA', n_type: 11},
  {name: 'AUTODECRETA DIVISION', n_type: 11},
  {name: 'INSCRIPCION DE LA PARTICION', n_type: 11},
  {name: 'ENTREGA DE PARTE ADJUDICADA', n_type: 11},
  {name: 'REMATE', n_type: 11},
  {name: 'APERTURA', n_type: 12},
  {name: 'POR NOTARIO O JUZGADO', n_type: 12},
  {name: 'PUBLICACION JUDICIAL DEL TESTAMENTO CERRADO', n_type: 12},
  {name: 'PRESENTACION DE OPOSICION', n_type: 12},
  {name: 'RECHAZO DE OPOSICION', n_type: 12},
  {name: 'AUDIENCIA DE PRUEBAS', n_type: 12},
  {name: 'PUBLICACION DEL TESTAMENTO ANTE CINCO TESTIGOS', n_type: 12},
  {name: 'TESTAMENTO VERBAL', n_type: 12},
  {name: 'EMBARGO Y SECUESTRO', n_type: 12},
  {name: 'TERMINACION DE SECUESTRO', n_type: 12},
  {name: 'HERENCIA YACENTE', n_type: 12},
  {name: 'RECONOCIMIENTO DE INTERESADOS', n_type: 12},
  {name: 'REQUERIMIENTO PARA EJERCER DERECHO DE OPCION', n_type: 12},
  {name: 'ACEPTACION DE ACREEDORES DEL ASIGNATARIO', n_type: 12},
  {name: 'REPUDIACION DE ASIGNACIONES A FAVOR DE INCAPACES', n_type: 12},
  {name: 'ADMINISTRACION DE HERENCIA', n_type: 12},
  {name: 'RESTITUCION DE BIENES', n_type: 12},
  {name: 'PAGO DE DEUDAS', n_type: 12},
  {name: 'DECRETO DE PARTICION Y DESIGANCION DE PARTIDOR', n_type: 12},
  {name: 'ENTREGA DE BIENES A ADJUDICATARIOS', n_type: 12},
  {name: 'DEMANDA', n_type: 13},
  {name: 'ADMISION DEMANDA', n_type: 13},
  {name: 'POTESTACION DEMANDA', n_type: 13},
  {name: 'EMPLAZAMIENTO DE ACREEDORES DE LA SOCIEDAD', n_type: 13},
  {name: 'AUDIENCIA INICIAL', n_type: 13},
  {name: 'SENTENCIA', n_type: 13},
  {name: 'LIQUIDACION', n_type: 13},
  {name: 'SOLICITUD DE NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'DESIGNACION CONCILIADOR', n_type: 14},
  {name: 'ACEPTACION SOLICITUD DE NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'COMUNICACION DE LA ACEPTACION', n_type: 14},
  {name: 'AUDIENCIA NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'ACUERDO DE PAGO', n_type: 14},
  {name: 'IMPUGNACION DEL ACUERDO', n_type: 14},
  {name: 'CUMPLIMIENTO DEL ACUERDO', n_type: 14},
  {name: 'FRACASO DE NEGOCIACION', n_type: 14},
  {name: 'INCUMPLIMIENTO DE ACUERDO', n_type: 14},
  {name: 'APERTURA DE LIQUIDACION PATRIMONIAL', n_type: 14},
  {name: 'PRESENTACION DE OBJECIONES POR ACREEDORES', n_type: 14},
  {name: 'RESOLUCION DE OBJECIONES', n_type: 14},
  {name: 'ACUERDO RESOLUTORIO DENTRO DE LIQUIDACION PATRIMONIAL', n_type: 14},
  {name: 'AUDIENCIA DE ADJUTICACION', n_type: 14},
  {name: 'DEMANDA ', n_type: 15},
  {name: 'PRUEBAS', n_type: 15},
  {name: 'SENTENCIA', n_type: 15},
  {name: 'DEMANDA', n_type: 17},
  {name: 'ADMISION DEMANDA', n_type: 17},
  {name: 'CONTESTACION DEMANDA', n_type: 17},
  {name: 'AUTO ORDENA AVALUO DE BIEN COMUN', n_type: 17},
  {name: 'OBJECIONES AL AVALUO', n_type: 17},
  {name: 'DESIGNACION PARTIDOR', n_type: 17},
  {name: 'POSESION PARTIDOR', n_type: 17},
  {name: 'ENTREGA DE LO ADJUDICADO', n_type: 17},
  {name: 'AUTO DECRETA VENTA DE COSA COMUN', n_type: 17},
  {name: 'REMATE', n_type: 17},
  {name: 'DEMANDA', n_type: 16},
  {name: 'ADMISION DEMANDA', n_type: 16},
  {name: 'CONTESTACION DEMANDA', n_type: 16},
  {name: 'AUDIENCIA CONCILIACION', n_type: 16},
  {name: 'PRUEBAS - ALEGATOS CONCLUSION', n_type: 16},
  {name: 'SENTENCIA PRIMERA INSTANCIA', n_type: 16},
  {name: 'ALEGATOS SEGUNDA INSTANCIA', n_type: 16},
  {name: 'SENTENCIA SEGUNDA INSTANCIA', n_type: 16},
  {name: 'DEMANDA CASACION - ADMINISION DEMANDA CASACION', n_type: 16},
  {name: 'OPOSICION DEMANDA CASACION', n_type: 16},
  {name: 'SENTENCIA CASACION', n_type: 16},
  {name: 'RECURSO SUPLICA', n_type: 16},
  {name: 'RECURSO QUEJA', n_type: 16},
  {name: 'RECURSO REVISION', n_type: 16},
  {name: 'EN TERMINOS PARA RESOLVER RECURSOS DE REPOSICION', n_type: 18},
  {name: 'AUDIENCIA SUSPENDIDA', n_type: 18},
  {name: 'AUDIENCIA QUE RESUELVE', n_type: 18},
  {name: 'SANCION EN FIRME', n_type: 18},
  {name: 'PREJUDICIAL', n_type: 19},
])

JoinCommittee.create([
  {name: 'NO PRESENTA'},
  {name: 'SI'},
  {name: 'NO'}
])

Committee.create([
  {name: 'NO PRESENTA'},
  {name: 'CONCILIA'},
  {name: 'NO CONCILIA'},
  {name: 'INVIABLE'}
])

Instance.create([
  {name: 'NO PRESENTA'},
  {name: 'PRIMERA'},
  {name: 'SEGUNDA'},
  {name: 'UNICA'},
  {name: 'GRADO DE CONSULTA'},
  {name: 'RECURSO EXTRAORDINARIO'}
])

CaseTermination.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'TERMINADO CON PAGO: EN CONTRA', n_type: 1},
  {name: 'TERMINADO SIN PAGO: A FAVOR', n_type: 1},
  {name: 'TERMINADO SIN PAGO: EN CONTRA', n_type: 3},
  {name: 'FAVORABLE', n_type: 2},
  {name: 'DESFAVORABLE', n_type: 2}
])

GubernatorialWay.create([
  {name: 'NO PRESENTA', n_type: 0},
  {name: 'CONEXION', n_type: 1},
  {name: 'SIPLAFT', n_type: 1},
  {name: 'ESTADOS FINANCIEROS', n_type: 1},
  {name: 'MORA', n_type: 1},
  {name: 'POLIZA', n_type: 1},
  {name: 'VISITA FISCALIZACION', n_type: 1},
  {name: 'INEXACTITUD', n_type: 1},
  {name: 'NO APLICA', n_type: 2}
])

ReinsuranceType.create([
  {name: 'NO PRESENTA'},
  {name: 'FACULTATIVO'},
  {name: 'CUOTA PARTE'}
])

MoneyType.create([
  {name: 'PESOS'},
  {name: 'DOLAR'}
])

ReservedReleased.create([
  {name: 'NO PRESENTA'},
  {name: 'NO'},
  {name: 'SI'}
])

CoensuranceType.create([
  {name: 'NO PRESENTA'},
  {name: 'CEDIDO'},
  {name: 'ACEPTADO'}
])

CaseState.create([
  {name: 'EN CURSO'},
  {name: 'TERMINADO'}
])

LastPerformance.create([
  {name: 'NO PRESENTA'},
  {name: 'OTRO'},
  {name: 'ALEGATOS'},
  {name: 'AUTO QUE TERMINA PROCESO POR CONCILIACION'},
  {name: 'AUTO QUE TERMINA PROCESO POR TRANSACCION'},
  {name: 'DESCARGOS'},
  {name: 'GRADO DE CONSULTA'},
  {name: 'RECURSO DE REPOSICION'},
  {name: 'RECURSO DE APELACION'},
  {name: 'SENTENCIA Y AUTOS GENERALES'}
])

Departament.create([
	{name: '01', code: 'AMAZONAS'},
	{name: '02', code: 'ANTIOQUIA'},
	{name: '03', code: 'ARAUCA'},
	{name: '04', code: 'ATLANTICO'},
	{name: '05', code: 'BOGOTA DC'},
	{name: '06', code: 'BOLIVAR'},
	{name: '07', code: 'BOYACA'},
	{name: '08', code: 'CALDAS'},
	{name: '09', code: 'CAQUETA'},
	{name: '10', code: 'CASANARE'},
	{name: '11', code: 'CAUCA'},
	{name: '12', code: 'CESAR'},
	{name: '13', code: 'CHOCO'},
	{name: '14', code: 'CORDOBA'},
	{name: '15', code: 'CUNDINAMARCA'},
	{name: '16', code: 'GUAINIA'},
	{name: '17', code: 'GUAJIRA'},
	{name: '18', code: 'GUAVIARE'},
	{name: '19', code: 'HUILA'},
	{name: '20', code: 'MAGDALENA'},
	{name: '21', code: 'META'},
	{name: '22', code: 'NARINO'},
	{name: '23', code: 'NORTE DE SANTANDER'},
	{name: '24', code: 'PUTUMAYO'},
	{name: '25', code: 'QUINDIO'},
	{name: '26', code: 'RISARALDA'},
	{name: '27', code: 'SAN ANDRES Y PROVIDENCIA'},
	{name: '28', code: 'SANTANDER'},
	{name: '29', code: 'SUCRE'},
	{name: '30', code: 'TOLIMA'},
	{name: '31', code: 'VALLE DEL CAUCA'},
	{name: '32', code: 'VAUPES'},
	{name: '33', code: 'VICHADA'},
])
CityCase.create([
	{name: 'LETICIA', code: '01', departament: '01'},
	{name: 'EL ENCANTO', code: '02', departament: '01'},
	{name: 'LA CHORRERA', code: '03', departament: '01'},
	{name: 'LA PEDRERA', code: '04', departament: '01'},
	{name: 'LA VICTORIA', code: '05', departament: '01'},
	{name: 'MIRITI - PARANA', code: '06', departament: '01'},
	{name: 'PUERTO ALEGRIA', code: '07', departament: '01'},
	{name: 'PUERTO ARICA', code: '08', departament: '01'},
	{name: 'PUERTO NARINO', code: '09', departament: '01'},
	{name: 'PUERTO SANTANDER', code: '10', departament: '01'},
	{name: 'TARAPACA', code: '11', departament: '01'},
	{name: 'MEDELLIN', code: '01', departament: '02'},
	{name: 'ABEJORRAL', code: '02', departament: '02'},
	{name: 'ABRIAQUI', code: '03', departament: '02'},
	{name: 'ALEJANDRIA', code: '04', departament: '02'},
	{name: 'AMAGA', code: '05', departament: '02'},
	{name: 'AMALFI', code: '06', departament: '02'},
	{name: 'ANDES', code: '07', departament: '02'},
	{name: 'ANGELOPOLIS', code: '08', departament: '02'},
	{name: 'ANGOSTURA', code: '09', departament: '02'},
	{name: 'ANORI', code: '10', departament: '02'},
	{name: 'SAN VICENTE FERRER', code: '100', departament: '02'},
	{name: 'SANTA BARBARA', code: '101', departament: '02'},
	{name: 'SANTA ROSA DE OSOS', code: '102', departament: '02'},
	{name: 'SANTO DOMINGO', code: '103', departament: '02'},
	{name: 'EL SANTUARIO', code: '104', departament: '02'},
	{name: 'SEGOVIA', code: '105', departament: '02'},
	{name: 'SONSON', code: '106', departament: '02'},
	{name: 'SOPETRAN', code: '107', departament: '02'},
	{name: 'TAMESIS', code: '108', departament: '02'},
	{name: 'TARAZA', code: '109', departament: '02'},
	{name: 'SANTA FE DE ANTIOQUIA', code: '11', departament: '02'},
	{name: 'TARSO', code: '110', departament: '02'},
	{name: 'TITIRIBI', code: '111', departament: '02'},
	{name: 'TOLEDO', code: '112', departament: '02'},
	{name: 'TURBO', code: '113', departament: '02'},
	{name: 'URAMITA', code: '114', departament: '02'},
	{name: 'URRAO', code: '115', departament: '02'},
	{name: 'VALDIVIA', code: '116', departament: '02'},
	{name: 'VALPARAISO', code: '117', departament: '02'},
	{name: 'VEGACHI', code: '118', departament: '02'},
	{name: 'VENECIA', code: '119', departament: '02'},
	{name: 'ANZA', code: '12', departament: '02'},
	{name: 'VIGIA DEL FUERTE', code: '120', departament: '02'},
	{name: 'YALI', code: '121', departament: '02'},
	{name: 'YARUMAL', code: '122', departament: '02'},
	{name: 'YOLOMBO', code: '123', departament: '02'},
	{name: 'YONDO', code: '124', departament: '02'},
	{name: 'ZARAGOZA', code: '125', departament: '02'},
	{name: 'APARTADO', code: '13', departament: '02'},
	{name: 'ARBOLETES', code: '14', departament: '02'},
	{name: 'ARGELIA', code: '15', departament: '02'},
	{name: 'ARMENIA', code: '16', departament: '02'},
	{name: 'BARBOSA', code: '17', departament: '02'},
	{name: 'BELMIRA', code: '18', departament: '02'},
	{name: 'BELLO', code: '19', departament: '02'},
	{name: 'BETANIA', code: '20', departament: '02'},
	{name: 'BETULIA', code: '21', departament: '02'},
	{name: 'CIUDAD BOLIVAR', code: '22', departament: '02'},
	{name: 'BRICENO', code: '23', departament: '02'},
	{name: 'BURITICA', code: '24', departament: '02'},
	{name: 'CACERES', code: '25', departament: '02'},
	{name: 'CAICEDO', code: '26', departament: '02'},
	{name: 'CALDAS', code: '27', departament: '02'},
	{name: 'CAMPAMENTO', code: '28', departament: '02'},
	{name: 'CANASGORDAS', code: '29', departament: '02'},
	{name: 'CARACOLI', code: '30', departament: '02'},
	{name: 'CARAMANTA', code: '31', departament: '02'},
	{name: 'CAREPA', code: '32', departament: '02'},
	{name: 'EL CARMEN DE VIBORAL', code: '33', departament: '02'},
	{name: 'CAROLINA', code: '34', departament: '02'},
	{name: 'CAUCASIA', code: '35', departament: '02'},
	{name: 'CHIGORODO', code: '36', departament: '02'},
	{name: 'CISNEROS', code: '37', departament: '02'},
	{name: 'COCORNA', code: '38', departament: '02'},
	{name: 'CONCEPCION', code: '39', departament: '02'},
	{name: 'CONCORDIA', code: '40', departament: '02'},
	{name: 'COPACABANA', code: '41', departament: '02'},
	{name: 'DABEIBA', code: '42', departament: '02'},
	{name: 'DONMATIAS', code: '43', departament: '02'},
	{name: 'EBEJICO', code: '44', departament: '02'},
	{name: 'EL BAGRE', code: '45', departament: '02'},
	{name: 'ENTRERRIOS', code: '46', departament: '02'},
	{name: 'ENVIGADO', code: '47', departament: '02'},
	{name: 'FREDONIA', code: '48', departament: '02'},
	{name: 'FRONTINO', code: '49', departament: '02'},
	{name: 'GIRALDO', code: '50', departament: '02'},
	{name: 'GIRARDOTA', code: '51', departament: '02'},
	{name: 'GOMEZ PLATA', code: '52', departament: '02'},
	{name: 'GRANADA', code: '53', departament: '02'},
	{name: 'GUADALUPE', code: '54', departament: '02'},
	{name: 'GUARNE', code: '55', departament: '02'},
	{name: 'GUATAPE', code: '56', departament: '02'},
	{name: 'HELICONIA', code: '57', departament: '02'},
	{name: 'HISPANIA', code: '58', departament: '02'},
	{name: 'ITAGUI', code: '59', departament: '02'},
	{name: 'ITUANGO', code: '60', departament: '02'},
	{name: 'JARDIN', code: '61', departament: '02'},
	{name: 'JERICO', code: '62', departament: '02'},
	{name: 'LA CEJA', code: '63', departament: '02'},
	{name: 'LA ESTRELLA', code: '64', departament: '02'},
	{name: 'LA PINTADA', code: '65', departament: '02'},
	{name: 'LA UNION', code: '66', departament: '02'},
	{name: 'LIBORINA', code: '67', departament: '02'},
	{name: 'MACEO', code: '68', departament: '02'},
	{name: 'MARINILLA', code: '69', departament: '02'},
	{name: 'MONTEBELLO', code: '70', departament: '02'},
	{name: 'MURINDO', code: '71', departament: '02'},
	{name: 'MUTATA', code: '72', departament: '02'},
	{name: 'NARINO', code: '73', departament: '02'},
	{name: 'NECOCLI', code: '74', departament: '02'},
	{name: 'NECHI', code: '75', departament: '02'},
	{name: 'OLAYA', code: '76', departament: '02'},
	{name: 'PENOL', code: '77', departament: '02'},
	{name: 'PEQUE', code: '78', departament: '02'},
	{name: 'PUEBLORRICO', code: '79', departament: '02'},
	{name: 'PUERTO BERRIO', code: '80', departament: '02'},
	{name: 'PUERTO NARE', code: '81', departament: '02'},
	{name: 'PUERTO TRIUNFO', code: '82', departament: '02'},
	{name: 'REMEDIOS', code: '83', departament: '02'},
	{name: 'RETIRO', code: '84', departament: '02'},
	{name: 'RIONEGRO', code: '85', departament: '02'},
	{name: 'SABANALARGA', code: '86', departament: '02'},
	{name: 'SABANETA', code: '87', departament: '02'},
	{name: 'SALGAR', code: '88', departament: '02'},
	{name: 'SAN ANDRES DE CUERQUIA', code: '89', departament: '02'},
	{name: 'SAN CARLOS', code: '90', departament: '02'},
	{name: 'SAN FRANCISCO', code: '91', departament: '02'},
	{name: 'SAN JERONIMO', code: '92', departament: '02'},
	{name: 'SAN JOSE DE LA MONTANA', code: '93', departament: '02'},
	{name: 'SAN JUAN DE URABA', code: '94', departament: '02'},
	{name: 'SAN LUIS', code: '95', departament: '02'},
	{name: 'SAN PEDRO DE LOS MILAGROS', code: '96', departament: '02'},
	{name: 'SAN PEDRO DE URABA', code: '97', departament: '02'},
	{name: 'SAN RAFAEL', code: '98', departament: '02'},
	{name: 'SAN ROQUE', code: '99', departament: '02'},
	{name: 'ARAUCA', code: '01', departament: '03'},
	{name: 'ARAUQUITA', code: '02', departament: '03'},
	{name: 'CRAVO NORTE', code: '03', departament: '03'},
	{name: 'FORTUL', code: '04', departament: '03'},
	{name: 'PUERTO RONDON', code: '05', departament: '03'},
	{name: 'SARAVENA', code: '06', departament: '03'},
	{name: 'BARRANQUILLA', code: '01', departament: '04'},
	{name: 'BARANOA', code: '02', departament: '04'},
	{name: 'CAMPO DE LA CRUZ', code: '03', departament: '04'},
	{name: 'CANDELARIA', code: '04', departament: '04'},
	{name: 'GALAPA', code: '05', departament: '04'},
	{name: 'JUAN DE ACOSTA', code: '06', departament: '04'},
	{name: 'LURUACO', code: '07', departament: '04'},
	{name: 'MALAMBO', code: '08', departament: '04'},
	{name: 'MANATI', code: '09', departament: '04'},
	{name: 'PALMAR DE VARELA', code: '10', departament: '04'},
	{name: 'PIOJO', code: '11', departament: '04'},
	{name: 'POLONUEVO', code: '12', departament: '04'},
	{name: 'PONEDERA', code: '13', departament: '04'},
	{name: 'PUERTO COLOMBIA', code: '14', departament: '04'},
	{name: 'REPELON', code: '15', departament: '04'},
	{name: 'SABANAGRANDE', code: '16', departament: '04'},
	{name: 'SABANALARGA', code: '17', departament: '04'},
	{name: 'SANTA LUCIA', code: '18', departament: '04'},
	{name: 'SANTO TOMAS', code: '19', departament: '04'},
	{name: 'SOLEDAD', code: '20', departament: '04'},
	{name: 'SUAN', code: '21', departament: '04'},
	{name: 'TUBARA', code: '22', departament: '04'},
	{name: 'USIACURI', code: '23', departament: '04'},
	{name: 'BOGOTA DC', code: '01', departament: '05'},
	{name: 'CARTAGENA DE INDIAS', code: '01', departament: '06'},
	{name: 'ACHI', code: '02', departament: '06'},
	{name: 'ALTOS DEL ROSARIO', code: '03', departament: '06'},
	{name: 'ARENAL', code: '04', departament: '06'},
	{name: 'ARJONA', code: '05', departament: '06'},
	{name: 'ARROYOHONDO', code: '06', departament: '06'},
	{name: 'BARRANCO DE LOBA', code: '07', departament: '06'},
	{name: 'CALAMAR', code: '08', departament: '06'},
	{name: 'CANTAGALLO', code: '09', departament: '06'},
	{name: 'CICUCO', code: '10', departament: '06'},
	{name: 'CORDOBA', code: '11', departament: '06'},
	{name: 'CLEMENCIA', code: '12', departament: '06'},
	{name: 'EL CARMEN DE BOLIVAR', code: '13', departament: '06'},
	{name: 'EL GUAMO', code: '14', departament: '06'},
	{name: 'EL PENON', code: '15', departament: '06'},
	{name: 'HATILLO DE LOBA', code: '16', departament: '06'},
	{name: 'MAGANGUE', code: '17', departament: '06'},
	{name: 'MAHATES', code: '18', departament: '06'},
	{name: 'MARGARITA', code: '19', departament: '06'},
	{name: 'MARIA LA BAJA', code: '20', departament: '06'},
	{name: 'MONTECRISTO', code: '21', departament: '06'},
	{name: 'MOMPOS', code: '22', departament: '06'},
	{name: 'MORALES', code: '23', departament: '06'},
	{name: 'NOROSI', code: '24', departament: '06'},
	{name: 'PINILLOS', code: '25', departament: '06'},
	{name: 'REGIDOR', code: '26', departament: '06'},
	{name: 'RIO VIEJO', code: '27', departament: '06'},
	{name: 'SAN CRISTOBAL', code: '28', departament: '06'},
	{name: 'SAN ESTANISLAO', code: '29', departament: '06'},
	{name: 'SAN FERNANDO', code: '30', departament: '06'},
	{name: 'SAN JACINTO', code: '31', departament: '06'},
	{name: 'SAN JACINTO DEL CAUCA', code: '32', departament: '06'},
	{name: 'SAN JUAN NEPOMUCENO', code: '33', departament: '06'},
	{name: 'SAN MARTIN DE LOBA', code: '34', departament: '06'},
	{name: 'SAN PABLO', code: '35', departament: '06'},
	{name: 'SANTA CATALINA', code: '36', departament: '06'},
	{name: 'SANTA ROSA', code: '37', departament: '06'},
	{name: 'SANTA ROSA DEL SUR', code: '38', departament: '06'},
	{name: 'SIMITI', code: '39', departament: '06'},
	{name: 'SOPLAVIENTO', code: '40', departament: '06'},
	{name: 'TALAIGUA NUEVO', code: '41', departament: '06'},
	{name: 'TIQUISIO', code: '42', departament: '06'},
	{name: 'TURBACO', code: '43', departament: '06'},
	{name: 'TURBANA', code: '44', departament: '06'},
	{name: 'VILLANUEVA', code: '45', departament: '06'},
	{name: 'ZAMBRANO', code: '46', departament: '06'},
	{name: 'TUNJA', code: '01', departament: '07'},
	{name: 'ALMEIDA', code: '02', departament: '07'},
	{name: 'AQUITANIA', code: '03', departament: '07'},
	{name: 'ARCABUCO', code: '04', departament: '07'},
	{name: 'BELEN', code: '05', departament: '07'},
	{name: 'BERBEO', code: '06', departament: '07'},
	{name: 'BETEITIVA', code: '07', departament: '07'},
	{name: 'BOAVITA', code: '08', departament: '07'},
	{name: 'BOYACA', code: '09', departament: '07'},
	{name: 'BRICENO', code: '10', departament: '07'},
	{name: 'SORA', code: '100', departament: '07'},
	{name: 'SOTAQUIRA', code: '101', departament: '07'},
	{name: 'SORACA', code: '102', departament: '07'},
	{name: 'SUSACON', code: '103', departament: '07'},
	{name: 'SUTAMARCHAN', code: '104', departament: '07'},
	{name: 'SUTATENZA', code: '105', departament: '07'},
	{name: 'TASCO', code: '106', departament: '07'},
	{name: 'TENZA', code: '107', departament: '07'},
	{name: 'TIBANA', code: '108', departament: '07'},
	{name: 'TIBASOSA', code: '109', departament: '07'},
	{name: 'BUENAVISTA', code: '11', departament: '07'},
	{name: 'TINJACA', code: '110', departament: '07'},
	{name: 'TIPACOQUE', code: '111', departament: '07'},
	{name: 'TOCA', code: '112', departament: '07'},
	{name: 'TOGUI', code: '113', departament: '07'},
	{name: 'TOPAGA', code: '114', departament: '07'},
	{name: 'TOTA', code: '115', departament: '07'},
	{name: 'TUNUNGUA', code: '116', departament: '07'},
	{name: 'TURMEQUE', code: '117', departament: '07'},
	{name: 'TUTA', code: '118', departament: '07'},
	{name: 'TUTAZA', code: '119', departament: '07'},
	{name: 'BUSBANZA', code: '12', departament: '07'},
	{name: 'UMBITA', code: '120', departament: '07'},
	{name: 'VENTAQUEMADA', code: '121', departament: '07'},
	{name: 'VIRACACHA', code: '122', departament: '07'},
	{name: 'ZETAQUIRA', code: '123', departament: '07'},
	{name: 'CALDAS', code: '13', departament: '07'},
	{name: 'CAMPOHERMOSO', code: '14', departament: '07'},
	{name: 'CERINZA', code: '15', departament: '07'},
	{name: 'CHINAVITA', code: '16', departament: '07'},
	{name: 'CHIQUINQUIRA', code: '17', departament: '07'},
	{name: 'CHISCAS', code: '18', departament: '07'},
	{name: 'CHITA', code: '19', departament: '07'},
	{name: 'CHITARAQUE', code: '20', departament: '07'},
	{name: 'CHIVATA', code: '21', departament: '07'},
	{name: 'CIENEGA', code: '22', departament: '07'},
	{name: 'COMBITA', code: '23', departament: '07'},
	{name: 'COPER', code: '24', departament: '07'},
	{name: 'CORRALES', code: '25', departament: '07'},
	{name: 'COVARACHIA', code: '26', departament: '07'},
	{name: 'CUBARA', code: '27', departament: '07'},
	{name: 'CUCAITA', code: '28', departament: '07'},
	{name: 'CUITIVA', code: '29', departament: '07'},
	{name: 'CHIQUIZA', code: '30', departament: '07'},
	{name: 'CHIVOR', code: '31', departament: '07'},
	{name: 'DUITAMA', code: '32', departament: '07'},
	{name: 'EL COCUY', code: '33', departament: '07'},
	{name: 'EL ESPINO', code: '34', departament: '07'},
	{name: 'FIRAVITOBA', code: '35', departament: '07'},
	{name: 'FLORESTA', code: '36', departament: '07'},
	{name: 'GACHANTIVA', code: '37', departament: '07'},
	{name: 'GAMEZA', code: '38', departament: '07'},
	{name: 'GARAGOA', code: '39', departament: '07'},
	{name: 'GUACAMAYAS', code: '40', departament: '07'},
	{name: 'GUATEQUE', code: '41', departament: '07'},
	{name: 'GUAYATA', code: '42', departament: '07'},
	{name: 'GUICAN', code: '43', departament: '07'},
	{name: 'IZA', code: '44', departament: '07'},
	{name: 'JENESANO', code: '45', departament: '07'},
	{name: 'JERICO', code: '46', departament: '07'},
	{name: 'LABRANZAGRANDE', code: '47', departament: '07'},
	{name: 'LA CAPILLA', code: '48', departament: '07'},
	{name: 'LA VICTORIA', code: '49', departament: '07'},
	{name: 'LA UVITA', code: '50', departament: '07'},
	{name: 'VILLA DE LEYVA', code: '51', departament: '07'},
	{name: 'MACANAL', code: '52', departament: '07'},
	{name: 'MARIPI', code: '53', departament: '07'},
	{name: 'MIRAFLORES', code: '54', departament: '07'},
	{name: 'MONGUA', code: '55', departament: '07'},
	{name: 'MONGUI', code: '56', departament: '07'},
	{name: 'MONIQUIRA', code: '57', departament: '07'},
	{name: 'MOTAVITA', code: '58', departament: '07'},
	{name: 'MUZO', code: '59', departament: '07'},
	{name: 'NOBSA', code: '60', departament: '07'},
	{name: 'NUEVO COLON', code: '61', departament: '07'},
	{name: 'OICATA', code: '62', departament: '07'},
	{name: 'OTANCHE', code: '63', departament: '07'},
	{name: 'PACHAVITA', code: '64', departament: '07'},
	{name: 'PAEZ', code: '65', departament: '07'},
	{name: 'PAIPA', code: '66', departament: '07'},
	{name: 'PAJARITO', code: '67', departament: '07'},
	{name: 'PANQUEBA', code: '68', departament: '07'},
	{name: 'PAUNA', code: '69', departament: '07'},
	{name: 'PAYA', code: '70', departament: '07'},
	{name: 'PAZ DE RIO', code: '71', departament: '07'},
	{name: 'PESCA', code: '72', departament: '07'},
	{name: 'PISBA', code: '73', departament: '07'},
	{name: 'PUERTO BOYACA', code: '74', departament: '07'},
	{name: 'QUIPAMA', code: '75', departament: '07'},
	{name: 'RAMIRIQUI', code: '76', departament: '07'},
	{name: 'RAQUIRA', code: '77', departament: '07'},
	{name: 'RONDON', code: '78', departament: '07'},
	{name: 'SABOYA', code: '79', departament: '07'},
	{name: 'SACHICA', code: '80', departament: '07'},
	{name: 'SAMACA', code: '81', departament: '07'},
	{name: 'SAN EDUARDO', code: '82', departament: '07'},
	{name: 'SAN JOSE DE PARE', code: '83', departament: '07'},
	{name: 'SAN LUIS DE GACENO', code: '84', departament: '07'},
	{name: 'SAN MATEO', code: '85', departament: '07'},
	{name: 'SAN MIGUEL DE SEMA', code: '86', departament: '07'},
	{name: 'SAN PABLO DE BORBUR', code: '87', departament: '07'},
	{name: 'SANTANA', code: '88', departament: '07'},
	{name: 'SANTA MARIA', code: '89', departament: '07'},
	{name: 'SANTA ROSA DE VITERBO', code: '90', departament: '07'},
	{name: 'SANTA SOFIA', code: '91', departament: '07'},
	{name: 'SATIVANORTE', code: '92', departament: '07'},
	{name: 'SATIVASUR', code: '93', departament: '07'},
	{name: 'SIACHOQUE', code: '94', departament: '07'},
	{name: 'SOATA', code: '95', departament: '07'},
	{name: 'SOCOTA', code: '96', departament: '07'},
	{name: 'SOCHA', code: '97', departament: '07'},
	{name: 'SOGAMOSO', code: '98', departament: '07'},
	{name: 'SOMONDOCO', code: '99', departament: '07'},
	{name: 'MANIZALES', code: '01', departament: '08'},
	{name: 'AGUADAS', code: '02', departament: '08'},
	{name: 'ANSERMA', code: '03', departament: '08'},
	{name: 'ARANZAZU', code: '04', departament: '08'},
	{name: 'BELALCAZAR', code: '05', departament: '08'},
	{name: 'CHINCHINA', code: '06', departament: '08'},
	{name: 'FILADELFIA', code: '07', departament: '08'},
	{name: 'LA DORADA', code: '08', departament: '08'},
	{name: 'LA MERCED', code: '09', departament: '08'},
	{name: 'MANZANARES', code: '10', departament: '08'},
	{name: 'MARMATO', code: '11', departament: '08'},
	{name: 'MARQUETALIA', code: '12', departament: '08'},
	{name: 'MARULANDA', code: '13', departament: '08'},
	{name: 'NEIRA', code: '14', departament: '08'},
	{name: 'NORCASIA', code: '15', departament: '08'},
	{name: 'PACORA', code: '16', departament: '08'},
	{name: 'PALESTINA', code: '17', departament: '08'},
	{name: 'PENSILVANIA', code: '18', departament: '08'},
	{name: 'RIOSUCIO', code: '19', departament: '08'},
	{name: 'RISARALDA', code: '20', departament: '08'},
	{name: 'SALAMINA', code: '21', departament: '08'},
	{name: 'SAMANA', code: '22', departament: '08'},
	{name: 'SAN JOSE', code: '23', departament: '08'},
	{name: 'SUPIA', code: '24', departament: '08'},
	{name: 'VICTORIA', code: '25', departament: '08'},
	{name: 'VILLAMARIA', code: '26', departament: '08'},
	{name: 'VITERBO', code: '27', departament: '08'},
	{name: 'FLORENCIA', code: '01', departament: '09'},
	{name: 'ALBANIA', code: '02', departament: '09'},
	{name: 'BELEN DE LOS ANDAQUIES', code: '03', departament: '09'},
	{name: 'CARTAGENA DEL CHAIRA', code: '04', departament: '09'},
	{name: 'CURILLO', code: '05', departament: '09'},
	{name: 'EL DONCELLO', code: '06', departament: '09'},
	{name: 'EL PAUJIL', code: '07', departament: '09'},
	{name: 'LA MONTANITA', code: '08', departament: '09'},
	{name: 'MILAN', code: '09', departament: '09'},
	{name: 'MORELIA', code: '10', departament: '09'},
	{name: 'PUERTO RICO', code: '11', departament: '09'},
	{name: 'SAN JOSE DEL FRAGUA', code: '12', departament: '09'},
	{name: 'SAN VICENTE DEL CAGUAN', code: '13', departament: '09'},
	{name: 'SOLANO', code: '14', departament: '09'},
	{name: 'SOLITA', code: '15', departament: '09'},
	{name: 'VALPARAISO', code: '16', departament: '09'},
	{name: 'YOPAL', code: '01', departament: '10'},
	{name: 'AGUAZUL', code: '02', departament: '10'},
	{name: 'CHAMEZA', code: '03', departament: '10'},
	{name: 'HATO COROZAL', code: '04', departament: '10'},
	{name: 'LA SALINA', code: '05', departament: '10'},
	{name: 'MANI', code: '06', departament: '10'},
	{name: 'MONTERREY', code: '07', departament: '10'},
	{name: 'NUNCHIA', code: '08', departament: '10'},
	{name: 'OROCUE', code: '09', departament: '10'},
	{name: 'PAZ DE ARIPORO', code: '10', departament: '10'},
	{name: 'PORE', code: '11', departament: '10'},
	{name: 'RECETOR', code: '12', departament: '10'},
	{name: 'SABANALARGA', code: '13', departament: '10'},
	{name: 'SACAMA', code: '14', departament: '10'},
	{name: 'SAN LUIS DE PALENQUE', code: '15', departament: '10'},
	{name: 'TAMARA', code: '16', departament: '10'},
	{name: 'TAURAMENA', code: '17', departament: '10'},
	{name: 'TRINIDAD', code: '18', departament: '10'},
	{name: 'VILLANUEVA', code: '19', departament: '10'},
	{name: 'POPAYAN', code: '01', departament: '11'},
	{name: 'ALMAGUER', code: '02', departament: '11'},
	{name: 'ARGELIA', code: '03', departament: '11'},
	{name: 'BALBOA', code: '04', departament: '11'},
	{name: 'BOLIVAR', code: '05', departament: '11'},
	{name: 'BUENOS AIRES', code: '06', departament: '11'},
	{name: 'CAJIBIO', code: '07', departament: '11'},
	{name: 'CALDONO', code: '08', departament: '11'},
	{name: 'CALOTO', code: '09', departament: '11'},
	{name: 'CORINTO', code: '10', departament: '11'},
	{name: 'EL TAMBO', code: '11', departament: '11'},
	{name: 'FLORENCIA', code: '12', departament: '11'},
	{name: 'GUACHENE', code: '13', departament: '11'},
	{name: 'GUAPI', code: '14', departament: '11'},
	{name: 'INZA', code: '15', departament: '11'},
	{name: 'JAMBALO', code: '16', departament: '11'},
	{name: 'LA SIERRA', code: '17', departament: '11'},
	{name: 'LA VEGA', code: '18', departament: '11'},
	{name: 'LOPEZ DE MICAY', code: '19', departament: '11'},
	{name: 'MERCADERES', code: '20', departament: '11'},
	{name: 'MIRANDA', code: '21', departament: '11'},
	{name: 'MORALES', code: '22', departament: '11'},
	{name: 'PADILLA', code: '23', departament: '11'},
	{name: 'PAEZ', code: '24', departament: '11'},
	{name: 'PATIA', code: '25', departament: '11'},
	{name: 'PIAMONTE', code: '26', departament: '11'},
	{name: 'PIENDAMO', code: '27', departament: '11'},
	{name: 'PUERTO TEJADA', code: '28', departament: '11'},
	{name: 'PURACE', code: '29', departament: '11'},
	{name: 'ROSAS', code: '30', departament: '11'},
	{name: 'SAN SEBASTIAN', code: '31', departament: '11'},
	{name: 'SANTANDER DE QUILICHAO', code: '32', departament: '11'},
	{name: 'SANTA ROSA', code: '33', departament: '11'},
	{name: 'SILVIA', code: '34', departament: '11'},
	{name: 'SOTARA', code: '35', departament: '11'},
	{name: 'SUAREZ', code: '36', departament: '11'},
	{name: 'SUCRE', code: '37', departament: '11'},
	{name: 'TIMBIO', code: '38', departament: '11'},
	{name: 'TIMBIQUI', code: '39', departament: '11'},
	{name: 'TORIBIO', code: '40', departament: '11'},
	{name: 'TOTORO', code: '41', departament: '11'},
	{name: 'VILLA RICA', code: '42', departament: '11'},
	{name: 'VALLEDUPAR', code: '01', departament: '12'},
	{name: 'AGUACHICA', code: '02', departament: '12'},
	{name: 'AGUSTIN CODAZZI', code: '03', departament: '12'},
	{name: 'ASTREA', code: '04', departament: '12'},
	{name: 'BECERRIL', code: '05', departament: '12'},
	{name: 'BOSCONIA', code: '06', departament: '12'},
	{name: 'CHIMICHAGUA', code: '07', departament: '12'},
	{name: 'CHIRIGUANA', code: '08', departament: '12'},
	{name: 'CURUMANI', code: '09', departament: '12'},
	{name: 'EL COPEY', code: '10', departament: '12'},
	{name: 'EL PASO', code: '11', departament: '12'},
	{name: 'GAMARRA', code: '12', departament: '12'},
	{name: 'GONZALEZ', code: '13', departament: '12'},
	{name: 'LA GLORIA', code: '14', departament: '12'},
	{name: 'LA JAGUA DE IBIRICO', code: '15', departament: '12'},
	{name: 'MANAURE BALCON DEL CESAR', code: '16', departament: '12'},
	{name: 'PAILITAS', code: '17', departament: '12'},
	{name: 'PELAYA', code: '18', departament: '12'},
	{name: 'PUEBLO BELLO', code: '19', departament: '12'},
	{name: 'RIO DE ORO', code: '20', departament: '12'},
	{name: 'LA PAZ', code: '21', departament: '12'},
	{name: 'SAN ALBERTO', code: '22', departament: '12'},
	{name: 'SAN DIEGO', code: '23', departament: '12'},
	{name: 'SAN MARTIN', code: '24', departament: '12'},
	{name: 'TAMALAMEQUE', code: '25', departament: '12'},
	{name: 'QUIBDO', code: '01', departament: '13'},
	{name: 'ACANDI', code: '02', departament: '13'},
	{name: 'ALTO BAUDO', code: '03', departament: '13'},
	{name: 'ATRATO', code: '04', departament: '13'},
	{name: 'BAGADO', code: '05', departament: '13'},
	{name: 'BAHIA SOLANO', code: '06', departament: '13'},
	{name: 'BAJO BAUDO', code: '07', departament: '13'},
	{name: 'BOJAYA', code: '08', departament: '13'},
	{name: 'EL CANTON DEL SAN PABLO', code: '09', departament: '13'},
	{name: 'CARMEN DEL DARIEN', code: '10', departament: '13'},
	{name: 'CERTEGUI', code: '11', departament: '13'},
	{name: 'CONDOTO', code: '12', departament: '13'},
	{name: 'EL CARMEN DE ATRATO', code: '13', departament: '13'},
	{name: 'EL LITORAL DEL SAN JUAN', code: '14', departament: '13'},
	{name: 'ISTMINA', code: '15', departament: '13'},
	{name: 'JURADO', code: '16', departament: '13'},
	{name: 'LLORO', code: '17', departament: '13'},
	{name: 'MEDIO ATRATO', code: '18', departament: '13'},
	{name: 'MEDIO BAUDO', code: '19', departament: '13'},
	{name: 'MEDIO SAN JUAN', code: '20', departament: '13'},
	{name: 'NOVITA', code: '21', departament: '13'},
	{name: 'NUQUI', code: '22', departament: '13'},
	{name: 'RIO IRO', code: '23', departament: '13'},
	{name: 'RIO QUITO', code: '24', departament: '13'},
	{name: 'RIOSUCIO', code: '25', departament: '13'},
	{name: 'SAN JOSE DEL PALMAR', code: '26', departament: '13'},
	{name: 'SIPI', code: '27', departament: '13'},
	{name: 'TADO', code: '28', departament: '13'},
	{name: 'UNGUIA', code: '29', departament: '13'},
	{name: 'UNION PANAMERICANA', code: '30', departament: '13'},
	{name: 'MONTERIA', code: '01', departament: '14'},
	{name: 'AYAPEL', code: '02', departament: '14'},
	{name: 'BUENAVISTA', code: '03', departament: '14'},
	{name: 'CANALETE', code: '04', departament: '14'},
	{name: 'CERETE', code: '05', departament: '14'},
	{name: 'CHIMA', code: '06', departament: '14'},
	{name: 'CHINU', code: '07', departament: '14'},
	{name: 'CIENAGA DE ORO', code: '08', departament: '14'},
	{name: 'COTORRA', code: '09', departament: '14'},
	{name: 'LA APARTADA', code: '10', departament: '14'},
	{name: 'LORICA', code: '11', departament: '14'},
	{name: 'LOS CORDOBAS', code: '12', departament: '14'},
	{name: 'MOMIL', code: '13', departament: '14'},
	{name: 'MONTELIBANO', code: '14', departament: '14'},
	{name: 'MONITOS', code: '15', departament: '14'},
	{name: 'PLANETA RICA', code: '16', departament: '14'},
	{name: 'PUEBLO NUEVO', code: '17', departament: '14'},
	{name: 'PUERTO ESCONDIDO', code: '18', departament: '14'},
	{name: 'PUERTO LIBERTADOR', code: '19', departament: '14'},
	{name: 'PURISIMA DE LA CONCEPCION', code: '20', departament: '14'},
	{name: 'SAHAGUN', code: '21', departament: '14'},
	{name: 'SAN ANDRES DE SOTAVENTO', code: '22', departament: '14'},
	{name: 'SAN ANTERO', code: '23', departament: '14'},
	{name: 'SAN BERNARDO DEL VIENTO', code: '24', departament: '14'},
	{name: 'SAN CARLOS', code: '25', departament: '14'},
	{name: 'SAN JOSE DE URE', code: '26', departament: '14'},
	{name: 'SAN PELAYO', code: '27', departament: '14'},
	{name: 'TIERRALTA', code: '28', departament: '14'},
	{name: 'TUCHIN', code: '29', departament: '14'},
	{name: 'VALENCIA', code: '30', departament: '14'},
	{name: 'AGUA DE DIOS', code: '01', departament: '15'},
	{name: 'ALBAN', code: '02', departament: '15'},
	{name: 'ANAPOIMA', code: '03', departament: '15'},
	{name: 'ANOLAIMA', code: '04', departament: '15'},
	{name: 'ARBELAEZ', code: '05', departament: '15'},
	{name: 'BELTRAN', code: '06', departament: '15'},
	{name: 'BITUIMA', code: '07', departament: '15'},
	{name: 'BOJACA', code: '08', departament: '15'},
	{name: 'CABRERA', code: '09', departament: '15'},
	{name: 'CACHIPAY', code: '10', departament: '15'},
	{name: 'TOCAIMA', code: '100', departament: '15'},
	{name: 'TOCANCIPA', code: '101', departament: '15'},
	{name: 'TOPAIPI', code: '102', departament: '15'},
	{name: 'UBALA', code: '103', departament: '15'},
	{name: 'UBAQUE', code: '104', departament: '15'},
	{name: 'VILLA DE SAN DIEGO DE UBATE', code: '105', departament: '15'},
	{name: 'UNE', code: '106', departament: '15'},
	{name: 'UTICA', code: '107', departament: '15'},
	{name: 'VERGARA', code: '108', departament: '15'},
	{name: 'VIANI', code: '109', departament: '15'},
	{name: 'CAJICA', code: '11', departament: '15'},
	{name: 'VILLAGOMEZ', code: '110', departament: '15'},
	{name: 'VILLAPINZON', code: '111', departament: '15'},
	{name: 'VILLETA', code: '112', departament: '15'},
	{name: 'VIOTA', code: '113', departament: '15'},
	{name: 'YACOPI', code: '114', departament: '15'},
	{name: 'ZIPACON', code: '115', departament: '15'},
	{name: 'ZIPAQUIRA', code: '116', departament: '15'},
	{name: 'CAPARRAPI', code: '12', departament: '15'},
	{name: 'CAQUEZA', code: '13', departament: '15'},
	{name: 'CARMEN DE CARUPA', code: '14', departament: '15'},
	{name: 'CHAGUANI', code: '15', departament: '15'},
	{name: 'CHIA', code: '16', departament: '15'},
	{name: 'CHIPAQUE', code: '17', departament: '15'},
	{name: 'CHOACHI', code: '18', departament: '15'},
	{name: 'CHOCONTA', code: '19', departament: '15'},
	{name: 'COGUA', code: '20', departament: '15'},
	{name: 'COTA', code: '21', departament: '15'},
	{name: 'CUCUNUBA', code: '22', departament: '15'},
	{name: 'EL COLEGIO', code: '23', departament: '15'},
	{name: 'EL PENON', code: '24', departament: '15'},
	{name: 'EL ROSAL', code: '25', departament: '15'},
	{name: 'FACATATIVA', code: '26', departament: '15'},
	{name: 'FOMEQUE', code: '27', departament: '15'},
	{name: 'FOSCA', code: '28', departament: '15'},
	{name: 'FUNZA', code: '29', departament: '15'},
	{name: 'FUQUENE', code: '30', departament: '15'},
	{name: 'FUSAGASUGA', code: '31', departament: '15'},
	{name: 'GACHALA', code: '32', departament: '15'},
	{name: 'GACHANCIPA', code: '33', departament: '15'},
	{name: 'GACHETA', code: '34', departament: '15'},
	{name: 'GAMA', code: '35', departament: '15'},
	{name: 'GIRARDOT', code: '36', departament: '15'},
	{name: 'GRANADA', code: '37', departament: '15'},
	{name: 'GUACHETA', code: '38', departament: '15'},
	{name: 'GUADUAS', code: '39', departament: '15'},
	{name: 'GUASCA', code: '40', departament: '15'},
	{name: 'GUATAQUI', code: '41', departament: '15'},
	{name: 'GUATAVITA', code: '42', departament: '15'},
	{name: 'GUAYABAL DE SIQUIMA', code: '43', departament: '15'},
	{name: 'GUAYABETAL', code: '44', departament: '15'},
	{name: 'GUTIERREZ', code: '45', departament: '15'},
	{name: 'JERUSALEN', code: '46', departament: '15'},
	{name: 'JUNIN', code: '47', departament: '15'},
	{name: 'LA CALERA', code: '48', departament: '15'},
	{name: 'LA MESA', code: '49', departament: '15'},
	{name: 'LA PALMA', code: '50', departament: '15'},
	{name: 'LA PENA', code: '51', departament: '15'},
	{name: 'LA VEGA', code: '52', departament: '15'},
	{name: 'LENGUAZAQUE', code: '53', departament: '15'},
	{name: 'MACHETA', code: '54', departament: '15'},
	{name: 'MADRID', code: '55', departament: '15'},
	{name: 'MANTA', code: '56', departament: '15'},
	{name: 'MEDINA', code: '57', departament: '15'},
	{name: 'MOSQUERA', code: '58', departament: '15'},
	{name: 'NARINO', code: '59', departament: '15'},
	{name: 'NEMOCON', code: '60', departament: '15'},
	{name: 'NILO', code: '61', departament: '15'},
	{name: 'NIMAIMA', code: '62', departament: '15'},
	{name: 'NOCAIMA', code: '63', departament: '15'},
	{name: 'VENECIA', code: '64', departament: '15'},
	{name: 'PACHO', code: '65', departament: '15'},
	{name: 'PAIME', code: '66', departament: '15'},
	{name: 'PANDI', code: '67', departament: '15'},
	{name: 'PARATEBUENO', code: '68', departament: '15'},
	{name: 'PASCA', code: '69', departament: '15'},
	{name: 'PUERTO SALGAR', code: '70', departament: '15'},
	{name: 'PULI', code: '71', departament: '15'},
	{name: 'QUEBRADANEGRA', code: '72', departament: '15'},
	{name: 'QUETAME', code: '73', departament: '15'},
	{name: 'QUIPILE', code: '74', departament: '15'},
	{name: 'APULO', code: '75', departament: '15'},
	{name: 'RICAURTE', code: '76', departament: '15'},
	{name: 'SAN ANTONIO DEL TEQUENDAMA', code: '77', departament: '15'},
	{name: 'SAN BERNARDO', code: '78', departament: '15'},
	{name: 'SAN CAYETANO', code: '79', departament: '15'},
	{name: 'SAN FRANCISCO', code: '80', departament: '15'},
	{name: 'SAN JUAN DE RIOSECO', code: '81', departament: '15'},
	{name: 'SASAIMA', code: '82', departament: '15'},
	{name: 'SESQUILE', code: '83', departament: '15'},
	{name: 'SIBATE', code: '84', departament: '15'},
	{name: 'SILVANIA', code: '85', departament: '15'},
	{name: 'SIMIJACA', code: '86', departament: '15'},
	{name: 'SOACHA', code: '87', departament: '15'},
	{name: 'SOPO', code: '88', departament: '15'},
	{name: 'SUBACHOQUE', code: '89', departament: '15'},
	{name: 'SUESCA', code: '90', departament: '15'},
	{name: 'SUPATA', code: '91', departament: '15'},
	{name: 'SUSA', code: '92', departament: '15'},
	{name: 'SUTATAUSA', code: '93', departament: '15'},
	{name: 'TABIO', code: '94', departament: '15'},
	{name: 'TAUSA', code: '95', departament: '15'},
	{name: 'TENA', code: '96', departament: '15'},
	{name: 'TENJO', code: '97', departament: '15'},
	{name: 'TIBACUY', code: '98', departament: '15'},
	{name: 'TIBIRITA', code: '99', departament: '15'},
	{name: 'INIRIDA', code: '01', departament: '16'},
	{name: 'BARRANCO MINAS', code: '02', departament: '16'},
	{name: 'MAPIRIPANA', code: '03', departament: '16'},
	{name: 'SAN FELIPE', code: '04', departament: '16'},
	{name: 'PUERTO COLOMBIA', code: '05', departament: '16'},
	{name: 'LA GUADALUPE', code: '06', departament: '16'},
	{name: 'CACAHUAL', code: '07', departament: '16'},
	{name: 'PANA PANA', code: '08', departament: '16'},
	{name: 'MORICHAL', code: '09', departament: '16'},
	{name: 'SAN JOSE DEL GUAVIARE', code: '01', departament: '17'},
	{name: 'CALAMAR', code: '02', departament: '17'},
	{name: 'EL RETORNO', code: '03', departament: '17'},
	{name: 'MIRAFLORES', code: '04', departament: '17'},
	{name: 'NEIVA', code: '01', departament: '18'},
	{name: 'ACEVEDO', code: '02', departament: '18'},
	{name: 'AGRADO', code: '03', departament: '18'},
	{name: 'AIPE', code: '04', departament: '18'},
	{name: 'ALGECIRAS', code: '05', departament: '18'},
	{name: 'ALTAMIRA', code: '06', departament: '18'},
	{name: 'BARAYA', code: '07', departament: '18'},
	{name: 'CAMPOALEGRE', code: '08', departament: '18'},
	{name: 'COLOMBIA', code: '09', departament: '18'},
	{name: 'ELIAS', code: '10', departament: '18'},
	{name: 'GARZON', code: '11', departament: '18'},
	{name: 'GIGANTE', code: '12', departament: '18'},
	{name: 'GUADALUPE', code: '13', departament: '18'},
	{name: 'HOBO', code: '14', departament: '18'},
	{name: 'IQUIRA', code: '15', departament: '18'},
	{name: 'ISNOS', code: '16', departament: '18'},
	{name: 'LA ARGENTINA', code: '17', departament: '18'},
	{name: 'LA PLATA', code: '18', departament: '18'},
	{name: 'NATAGA', code: '19', departament: '18'},
	{name: 'OPORAPA', code: '20', departament: '18'},
	{name: 'PAICOL', code: '21', departament: '18'},
	{name: 'PALERMO', code: '22', departament: '18'},
	{name: 'PALESTINA', code: '23', departament: '18'},
	{name: 'PITAL', code: '24', departament: '18'},
	{name: 'PITALITO', code: '25', departament: '18'},
	{name: 'RIVERA', code: '26', departament: '18'},
	{name: 'SALADOBLANCO', code: '27', departament: '18'},
	{name: 'SAN AGUSTIN', code: '28', departament: '18'},
	{name: 'SANTA MARIA', code: '29', departament: '18'},
	{name: 'SUAZA', code: '30', departament: '18'},
	{name: 'TARQUI', code: '31', departament: '18'},
	{name: 'TESALIA', code: '32', departament: '18'},
	{name: 'TELLO', code: '33', departament: '18'},
	{name: 'TERUEL', code: '34', departament: '18'},
	{name: 'TIMANA', code: '35', departament: '18'},
	{name: 'VILLAVIEJA', code: '36', departament: '18'},
	{name: 'YAGUARA', code: '37', departament: '18'},
	{name: 'RIOHACHA', code: '01', departament: '19'},
	{name: 'ALBANIA', code: '02', departament: '19'},
	{name: 'BARRANCAS', code: '03', departament: '19'},
	{name: 'DIBULLA', code: '04', departament: '19'},
	{name: 'DISTRACCION', code: '05', departament: '19'},
	{name: 'EL MOLINO', code: '06', departament: '19'},
	{name: 'FONSECA', code: '07', departament: '19'},
	{name: 'HATONUEVO', code: '08', departament: '19'},
	{name: 'LA JAGUA DEL PILAR', code: '09', departament: '19'},
	{name: 'MAICAO', code: '10', departament: '19'},
	{name: 'MANAURE', code: '11', departament: '19'},
	{name: 'SAN JUAN DEL CESAR', code: '12', departament: '19'},
	{name: 'URIBIA', code: '13', departament: '19'},
	{name: 'URUMITA', code: '14', departament: '19'},
	{name: 'VILLANUEVA', code: '15', departament: '19'},
	{name: 'SANTA MARTA', code: '01', departament: '20'},
	{name: 'ALGARROBO', code: '02', departament: '20'},
	{name: 'ARACATACA', code: '03', departament: '20'},
	{name: 'ARIGUANI', code: '04', departament: '20'},
	{name: 'CERRO DE SAN ANTONIO', code: '05', departament: '20'},
	{name: 'CHIVOLO', code: '06', departament: '20'},
	{name: 'CIENAGA', code: '07', departament: '20'},
	{name: 'CONCORDIA', code: '08', departament: '20'},
	{name: 'EL BANCO', code: '09', departament: '20'},
	{name: 'EL PINON', code: '10', departament: '20'},
	{name: 'EL RETEN', code: '11', departament: '20'},
	{name: 'FUNDACION', code: '12', departament: '20'},
	{name: 'GUAMAL', code: '13', departament: '20'},
	{name: 'NUEVA GRANADA', code: '14', departament: '20'},
	{name: 'PEDRAZA', code: '15', departament: '20'},
	{name: 'PIJINO DEL CARMEN', code: '16', departament: '20'},
	{name: 'PIVIJAY', code: '17', departament: '20'},
	{name: 'PLATO', code: '18', departament: '20'},
	{name: 'PUEBLOVIEJO', code: '19', departament: '20'},
	{name: 'REMOLINO', code: '20', departament: '20'},
	{name: 'SABANAS DE SAN ANGEL', code: '21', departament: '20'},
	{name: 'SALAMINA', code: '22', departament: '20'},
	{name: 'SAN SEBASTIAN DE BUENAVISTA', code: '23', departament: '20'},
	{name: 'SAN ZENON', code: '24', departament: '20'},
	{name: 'SANTA ANA', code: '25', departament: '20'},
	{name: 'SANTA BARBARA DE PINTO', code: '26', departament: '20'},
	{name: 'SITIONUEVO', code: '27', departament: '20'},
	{name: 'TENERIFE', code: '28', departament: '20'},
	{name: 'ZAPAYAN', code: '29', departament: '20'},
	{name: 'ZONA BANANERA', code: '30', departament: '20'},
	{name: 'VILLAVICENCIO', code: '01', departament: '21'},
	{name: 'ACACIAS', code: '02', departament: '21'},
	{name: 'BARRANCA DE UPIA', code: '03', departament: '21'},
	{name: 'CABUYARO', code: '04', departament: '21'},
	{name: 'CASTILLA LA NUEVA', code: '05', departament: '21'},
	{name: 'SAN LUIS DE CUBARRAL', code: '06', departament: '21'},
	{name: 'CUMARAL', code: '07', departament: '21'},
	{name: 'EL CALVARIO', code: '08', departament: '21'},
	{name: 'EL CASTILLO', code: '09', departament: '21'},
	{name: 'EL DORADO', code: '10', departament: '21'},
	{name: 'FUENTE DE ORO', code: '11', departament: '21'},
	{name: 'GRANADA', code: '12', departament: '21'},
	{name: 'GUAMAL', code: '13', departament: '21'},
	{name: 'MAPIRIPAN', code: '14', departament: '21'},
	{name: 'MESETAS', code: '15', departament: '21'},
	{name: 'LA MACARENA', code: '16', departament: '21'},
	{name: 'URIBE', code: '17', departament: '21'},
	{name: 'LEJANIAS', code: '18', departament: '21'},
	{name: 'PUERTO CONCORDIA', code: '19', departament: '21'},
	{name: 'PUERTO GAITAN', code: '20', departament: '21'},
	{name: 'PUERTO LOPEZ', code: '21', departament: '21'},
	{name: 'PUERTO LLERAS', code: '22', departament: '21'},
	{name: 'PUERTO RICO', code: '23', departament: '21'},
	{name: 'RESTREPO', code: '24', departament: '21'},
	{name: 'SAN CARLOS DE GUAROA', code: '25', departament: '21'},
	{name: 'SAN JUAN DE ARAMA', code: '26', departament: '21'},
	{name: 'SAN JUANITO', code: '27', departament: '21'},
	{name: 'SAN MARTIN', code: '28', departament: '21'},
	{name: 'VISTAHERMOSA', code: '29', departament: '21'},
	{name: 'PASTO', code: '01', departament: '22'},
	{name: 'ALBAN', code: '02', departament: '22'},
	{name: 'ALDANA', code: '03', departament: '22'},
	{name: 'ANCUYA', code: '04', departament: '22'},
	{name: 'ARBOLEDA', code: '05', departament: '22'},
	{name: 'BARBACOAS', code: '06', departament: '22'},
	{name: 'BELEN', code: '07', departament: '22'},
	{name: 'BUESACO', code: '08', departament: '22'},
	{name: 'COLON', code: '09', departament: '22'},
	{name: 'CONSACA', code: '10', departament: '22'},
	{name: 'CONTADERO', code: '11', departament: '22'},
	{name: 'CORDOBA', code: '12', departament: '22'},
	{name: 'CUASPUD', code: '13', departament: '22'},
	{name: 'CUMBAL', code: '14', departament: '22'},
	{name: 'CUMBITARA', code: '15', departament: '22'},
	{name: 'CHACHAGUI', code: '16', departament: '22'},
	{name: 'EL CHARCO', code: '17', departament: '22'},
	{name: 'EL PENOL', code: '18', departament: '22'},
	{name: 'EL ROSARIO', code: '19', departament: '22'},
	{name: 'EL TABLON DE GOMEZ', code: '20', departament: '22'},
	{name: 'EL TAMBO', code: '21', departament: '22'},
	{name: 'FUNES', code: '22', departament: '22'},
	{name: 'GUACHUCAL', code: '23', departament: '22'},
	{name: 'GUAITARILLA', code: '24', departament: '22'},
	{name: 'GUALMATAN', code: '25', departament: '22'},
	{name: 'ILES', code: '26', departament: '22'},
	{name: 'IMUES', code: '27', departament: '22'},
	{name: 'IPIALES', code: '28', departament: '22'},
	{name: 'LA CRUZ', code: '29', departament: '22'},
	{name: 'LA FLORIDA', code: '30', departament: '22'},
	{name: 'LA LLANADA', code: '31', departament: '22'},
	{name: 'LA TOLA', code: '32', departament: '22'},
	{name: 'LA UNION', code: '33', departament: '22'},
	{name: 'LEIVA', code: '34', departament: '22'},
	{name: 'LINARES', code: '35', departament: '22'},
	{name: 'LOS ANDES', code: '36', departament: '22'},
	{name: 'MAGUI', code: '37', departament: '22'},
	{name: 'MALLAMA', code: '38', departament: '22'},
	{name: 'MOSQUERA', code: '39', departament: '22'},
	{name: 'NARINO', code: '40', departament: '22'},
	{name: 'OLAYA HERRERA', code: '41', departament: '22'},
	{name: 'OSPINA', code: '42', departament: '22'},
	{name: 'FRANCISCO PIZARRO', code: '43', departament: '22'},
	{name: 'POLICARPA', code: '44', departament: '22'},
	{name: 'POTOSI', code: '45', departament: '22'},
	{name: 'PROVIDENCIA', code: '46', departament: '22'},
	{name: 'PUERRES', code: '47', departament: '22'},
	{name: 'PUPIALES', code: '48', departament: '22'},
	{name: 'RICAURTE', code: '49', departament: '22'},
	{name: 'ROBERTO PAYAN', code: '50', departament: '22'},
	{name: 'SAMANIEGO', code: '51', departament: '22'},
	{name: 'SANDONA', code: '52', departament: '22'},
	{name: 'SAN BERNARDO', code: '53', departament: '22'},
	{name: 'SAN LORENZO', code: '54', departament: '22'},
	{name: 'SAN PABLO', code: '55', departament: '22'},
	{name: 'SAN PEDRO DE CARTAGO', code: '56', departament: '22'},
	{name: 'SANTA BARBARA', code: '57', departament: '22'},
	{name: 'SANTACRUZ', code: '58', departament: '22'},
	{name: 'SAPUYES', code: '59', departament: '22'},
	{name: 'TAMINANGO', code: '60', departament: '22'},
	{name: 'TANGUA', code: '61', departament: '22'},
	{name: 'SAN ANDRES DE TUMACO', code: '62', departament: '22'},
	{name: 'TUQUERRES', code: '63', departament: '22'},
	{name: 'YACUANQUER', code: '64', departament: '22'},
	{name: 'CUCUTA', code: '01', departament: '23'},
	{name: 'ABREGO', code: '02', departament: '23'},
	{name: 'ARBOLEDAS', code: '03', departament: '23'},
	{name: 'BOCHALEMA', code: '04', departament: '23'},
	{name: 'BUCARASICA', code: '05', departament: '23'},
	{name: 'CACOTA', code: '06', departament: '23'},
	{name: 'CACHIRA', code: '07', departament: '23'},
	{name: 'CHINACOTA', code: '08', departament: '23'},
	{name: 'CHITAGA', code: '09', departament: '23'},
	{name: 'CONVENCION', code: '10', departament: '23'},
	{name: 'CUCUTILLA', code: '11', departament: '23'},
	{name: 'DURANIA', code: '12', departament: '23'},
	{name: 'EL CARMEN', code: '13', departament: '23'},
	{name: 'EL TARRA', code: '14', departament: '23'},
	{name: 'EL ZULIA', code: '15', departament: '23'},
	{name: 'GRAMALOTE', code: '16', departament: '23'},
	{name: 'HACARI', code: '17', departament: '23'},
	{name: 'HERRAN', code: '18', departament: '23'},
	{name: 'LABATECA', code: '19', departament: '23'},
	{name: 'LA ESPERANZA', code: '20', departament: '23'},
	{name: 'LA PLAYA', code: '21', departament: '23'},
	{name: 'LOS PATIOS', code: '22', departament: '23'},
	{name: 'LOURDES', code: '23', departament: '23'},
	{name: 'MUTISCUA', code: '24', departament: '23'},
	{name: 'OCANA', code: '25', departament: '23'},
	{name: 'PAMPLONA', code: '26', departament: '23'},
	{name: 'PAMPLONITA', code: '27', departament: '23'},
	{name: 'PUERTO SANTANDER', code: '28', departament: '23'},
	{name: 'RAGONVALIA', code: '29', departament: '23'},
	{name: 'SALAZAR', code: '30', departament: '23'},
	{name: 'SAN CALIXTO', code: '31', departament: '23'},
	{name: 'SAN CAYETANO', code: '32', departament: '23'},
	{name: 'SANTIAGO', code: '33', departament: '23'},
	{name: 'SARDINATA', code: '34', departament: '23'},
	{name: 'SILOS', code: '35', departament: '23'},
	{name: 'TEORAMA', code: '36', departament: '23'},
	{name: 'TIBU', code: '37', departament: '23'},
	{name: 'TOLEDO', code: '38', departament: '23'},
	{name: 'VILLA CARO', code: '39', departament: '23'},
	{name: 'VILLA DEL ROSARIO', code: '40', departament: '23'},
	{name: 'MOCOA', code: '01', departament: '24'},
	{name: 'COLON', code: '02', departament: '24'},
	{name: 'ORITO', code: '03', departament: '24'},
	{name: 'PUERTO ASIS', code: '04', departament: '24'},
	{name: 'PUERTO CAICEDO', code: '05', departament: '24'},
	{name: 'PUERTO GUZMAN', code: '06', departament: '24'},
	{name: 'PUERTO LEGUIZAMO', code: '07', departament: '24'},
	{name: 'SIBUNDOY', code: '08', departament: '24'},
	{name: 'SAN FRANCISCO', code: '09', departament: '24'},
	{name: 'SAN MIGUEL', code: '10', departament: '24'},
	{name: 'SANTIAGO', code: '11', departament: '24'},
	{name: 'VALLE DEL GUAMUEZ', code: '12', departament: '24'},
	{name: 'VILLAGARZON', code: '13', departament: '24'},
	{name: 'ARMENIA', code: '01', departament: '25'},
	{name: 'BUENAVISTA', code: '02', departament: '25'},
	{name: 'CALARCA', code: '03', departament: '25'},
	{name: 'CIRCASIA', code: '04', departament: '25'},
	{name: 'CORDOBA', code: '05', departament: '25'},
	{name: 'FILANDIA', code: '06', departament: '25'},
	{name: 'GENOVA', code: '07', departament: '25'},
	{name: 'LA TEBAIDA', code: '08', departament: '25'},
	{name: 'MONTENEGRO', code: '09', departament: '25'},
	{name: 'PIJAO', code: '10', departament: '25'},
	{name: 'QUIMBAYA', code: '11', departament: '25'},
	{name: 'SALENTO', code: '12', departament: '25'},
	{name: 'PEREIRA', code: '01', departament: '26'},
	{name: 'APIA', code: '02', departament: '26'},
	{name: 'BALBOA', code: '03', departament: '26'},
	{name: 'BELEN DE UMBRIA', code: '04', departament: '26'},
	{name: 'DOSQUEBRADAS', code: '05', departament: '26'},
	{name: 'GUATICA', code: '06', departament: '26'},
	{name: 'LA CELIA', code: '07', departament: '26'},
	{name: 'LA VIRGINIA', code: '08', departament: '26'},
	{name: 'MARSELLA', code: '09', departament: '26'},
	{name: 'MISTRATO', code: '10', departament: '26'},
	{name: 'PUEBLO RICO', code: '11', departament: '26'},
	{name: 'QUINCHIA', code: '12', departament: '26'},
	{name: 'SANTA ROSA DE CABAL', code: '13', departament: '26'},
	{name: 'SANTUARIO', code: '14', departament: '26'},
	{name: 'SAN ANDRES', code: '01', departament: '27'},
	{name: 'PROVIDENCIA', code: '02', departament: '27'},
	{name: 'SANTA CATALINA', code: '03', departament: '27'},
	{name: 'BUCARAMANGA', code: '01', departament: '28'},
	{name: 'AGUADA', code: '02', departament: '28'},
	{name: 'ALBANIA', code: '03', departament: '28'},
	{name: 'ARATOCA', code: '04', departament: '28'},
	{name: 'BARBOSA', code: '05', departament: '28'},
	{name: 'BARICHARA', code: '06', departament: '28'},
	{name: 'BARRANCABERMEJA', code: '07', departament: '28'},
	{name: 'BETULIA', code: '08', departament: '28'},
	{name: 'BOLIVAR', code: '09', departament: '28'},
	{name: 'CABRERA', code: '10', departament: '28'},
	{name: 'CALIFORNIA', code: '11', departament: '28'},
	{name: 'CAPITANEJO', code: '12', departament: '28'},
	{name: 'CARCASI', code: '13', departament: '28'},
	{name: 'CEPITA', code: '14', departament: '28'},
	{name: 'CERRITO', code: '15', departament: '28'},
	{name: 'CHARALA', code: '16', departament: '28'},
	{name: 'CHARTA', code: '17', departament: '28'},
	{name: 'CHIMA', code: '18', departament: '28'},
	{name: 'CHIPATA', code: '19', departament: '28'},
	{name: 'CIMITARRA', code: '20', departament: '28'},
	{name: 'CONCEPCION', code: '21', departament: '28'},
	{name: 'CONFINES', code: '22', departament: '28'},
	{name: 'CONTRATACION', code: '23', departament: '28'},
	{name: 'COROMORO', code: '24', departament: '28'},
	{name: 'CURITI', code: '25', departament: '28'},
	{name: 'EL CARMEN DE CHUCURI', code: '26', departament: '28'},
	{name: 'EL GUACAMAYO', code: '27', departament: '28'},
	{name: 'EL PENON', code: '28', departament: '28'},
	{name: 'EL PLAYON', code: '29', departament: '28'},
	{name: 'ENCINO', code: '30', departament: '28'},
	{name: 'ENCISO', code: '31', departament: '28'},
	{name: 'FLORIAN', code: '32', departament: '28'},
	{name: 'FLORIDABLANCA', code: '33', departament: '28'},
	{name: 'GALAN', code: '34', departament: '28'},
	{name: 'GAMBITA', code: '35', departament: '28'},
	{name: 'GIRON', code: '36', departament: '28'},
	{name: 'GUACA', code: '37', departament: '28'},
	{name: 'GUADALUPE', code: '38', departament: '28'},
	{name: 'GUAPOTA', code: '39', departament: '28'},
	{name: 'GUAVATA', code: '40', departament: '28'},
	{name: 'GUEPSA', code: '41', departament: '28'},
	{name: 'HATO', code: '42', departament: '28'},
	{name: 'JESUS MARIA', code: '43', departament: '28'},
	{name: 'JORDAN', code: '44', departament: '28'},
	{name: 'LA BELLEZA', code: '45', departament: '28'},
	{name: 'LANDAZURI', code: '46', departament: '28'},
	{name: 'LA PAZ', code: '47', departament: '28'},
	{name: 'LEBRIJA', code: '48', departament: '28'},
	{name: 'LOS SANTOS', code: '49', departament: '28'},
	{name: 'MACARAVITA', code: '50', departament: '28'},
	{name: 'MALAGA', code: '51', departament: '28'},
	{name: 'MATANZA', code: '52', departament: '28'},
	{name: 'MOGOTES', code: '53', departament: '28'},
	{name: 'MOLAGAVITA', code: '54', departament: '28'},
	{name: 'OCAMONTE', code: '55', departament: '28'},
	{name: 'OIBA', code: '56', departament: '28'},
	{name: 'ONZAGA', code: '57', departament: '28'},
	{name: 'PALMAR', code: '58', departament: '28'},
	{name: 'PALMAS DEL SOCORRO', code: '59', departament: '28'},
	{name: 'PARAMO', code: '60', departament: '28'},
	{name: 'PIEDECUESTA', code: '61', departament: '28'},
	{name: 'PINCHOTE', code: '62', departament: '28'},
	{name: 'PUENTE NACIONAL', code: '63', departament: '28'},
	{name: 'PUERTO PARRA', code: '64', departament: '28'},
	{name: 'PUERTO WILCHES', code: '65', departament: '28'},
	{name: 'RIONEGRO', code: '66', departament: '28'},
	{name: 'SABANA DE TORRES', code: '67', departament: '28'},
	{name: 'SAN ANDRES', code: '68', departament: '28'},
	{name: 'SAN BENITO', code: '69', departament: '28'},
	{name: 'SAN GIL', code: '70', departament: '28'},
	{name: 'SAN JOAQUIN', code: '71', departament: '28'},
	{name: 'SAN JOSE DE MIRANDA', code: '72', departament: '28'},
	{name: 'SAN MIGUEL', code: '73', departament: '28'},
	{name: 'SAN VICENTE DE CHUCURI', code: '74', departament: '28'},
	{name: 'SANTA BARBARA', code: '75', departament: '28'},
	{name: 'SANTA HELENA DEL OPON', code: '76', departament: '28'},
	{name: 'SIMACOTA', code: '77', departament: '28'},
	{name: 'SOCORRO', code: '78', departament: '28'},
	{name: 'SUAITA', code: '79', departament: '28'},
	{name: 'SUCRE', code: '80', departament: '28'},
	{name: 'SURATA', code: '81', departament: '28'},
	{name: 'TONA', code: '82', departament: '28'},
	{name: 'VALLE DE SAN JOSE', code: '83', departament: '28'},
	{name: 'VELEZ', code: '84', departament: '28'},
	{name: 'VETAS', code: '85', departament: '28'},
	{name: 'VILLANUEVA', code: '86', departament: '28'},
	{name: 'ZAPATOCA', code: '87', departament: '28'},
	{name: 'SINCELEJO', code: '01', departament: '29'},
	{name: 'BUENAVISTA', code: '02', departament: '29'},
	{name: 'CAIMITO', code: '03', departament: '29'},
	{name: 'COLOSO', code: '04', departament: '29'},
	{name: 'COROZAL', code: '05', departament: '29'},
	{name: 'COVENAS', code: '06', departament: '29'},
	{name: 'CHALAN', code: '07', departament: '29'},
	{name: 'EL ROBLE', code: '08', departament: '29'},
	{name: 'GALERAS', code: '09', departament: '29'},
	{name: 'GUARANDA', code: '10', departament: '29'},
	{name: 'LA UNION', code: '11', departament: '29'},
	{name: 'LOS PALMITOS', code: '12', departament: '29'},
	{name: 'MAJAGUAL', code: '13', departament: '29'},
	{name: 'MORROA', code: '14', departament: '29'},
	{name: 'OVEJAS', code: '15', departament: '29'},
	{name: 'PALMITO', code: '16', departament: '29'},
	{name: 'SAMPUES', code: '17', departament: '29'},
	{name: 'SAN BENITO ABAD', code: '18', departament: '29'},
	{name: 'SAN JUAN DE BETULIA', code: '19', departament: '29'},
	{name: 'SAN MARCOS', code: '20', departament: '29'},
	{name: 'SAN ONOFRE', code: '21', departament: '29'},
	{name: 'SAN PEDRO', code: '22', departament: '29'},
	{name: 'SAN LUIS DE SINCE', code: '23', departament: '29'},
	{name: 'SUCRE', code: '24', departament: '29'},
	{name: 'SANTIAGO DE TOLU', code: '25', departament: '29'},
	{name: 'TOLU VIEJO', code: '26', departament: '29'},
	{name: 'IBAGUE', code: '01', departament: '30'},
	{name: 'ALPUJARRA', code: '02', departament: '30'},
	{name: 'ALVARADO', code: '03', departament: '30'},
	{name: 'AMBALEMA', code: '04', departament: '30'},
	{name: 'ANZOATEGUI', code: '05', departament: '30'},
	{name: 'ARMERO GUAYABAL', code: '06', departament: '30'},
	{name: 'ATACO', code: '07', departament: '30'},
	{name: 'CAJAMARCA', code: '08', departament: '30'},
	{name: 'CARMEN DE APICALA', code: '09', departament: '30'},
	{name: 'CASABIANCA', code: '10', departament: '30'},
	{name: 'CHAPARRAL', code: '11', departament: '30'},
	{name: 'COELLO', code: '12', departament: '30'},
	{name: 'COYAIMA', code: '13', departament: '30'},
	{name: 'CUNDAY', code: '14', departament: '30'},
	{name: 'DOLORES', code: '15', departament: '30'},
	{name: 'ESPINAL', code: '16', departament: '30'},
	{name: 'FALAN', code: '17', departament: '30'},
	{name: 'FLANDES', code: '18', departament: '30'},
	{name: 'FRESNO', code: '19', departament: '30'},
	{name: 'GUAMO', code: '20', departament: '30'},
	{name: 'HERVEO', code: '21', departament: '30'},
	{name: 'HONDA', code: '22', departament: '30'},
	{name: 'ICONONZO', code: '23', departament: '30'},
	{name: 'LERIDA', code: '24', departament: '30'},
	{name: 'LIBANO', code: '25', departament: '30'},
	{name: 'SAN SEBASTIAN DE MARIQUITA', code: '26', departament: '30'},
	{name: 'MELGAR', code: '27', departament: '30'},
	{name: 'MURILLO', code: '28', departament: '30'},
	{name: 'NATAGAIMA', code: '29', departament: '30'},
	{name: 'ORTEGA', code: '30', departament: '30'},
	{name: 'PALOCABILDO', code: '31', departament: '30'},
	{name: 'PIEDRAS', code: '32', departament: '30'},
	{name: 'PLANADAS', code: '33', departament: '30'},
	{name: 'PRADO', code: '34', departament: '30'},
	{name: 'PURIFICACION', code: '35', departament: '30'},
	{name: 'RIOBLANCO', code: '36', departament: '30'},
	{name: 'RONCESVALLES', code: '37', departament: '30'},
	{name: 'ROVIRA', code: '38', departament: '30'},
	{name: 'SALDANA', code: '39', departament: '30'},
	{name: 'SAN ANTONIO', code: '40', departament: '30'},
	{name: 'SAN LUIS', code: '41', departament: '30'},
	{name: 'SANTA ISABEL', code: '42', departament: '30'},
	{name: 'SUAREZ', code: '43', departament: '30'},
	{name: 'VALLE DE SAN JUAN', code: '44', departament: '30'},
	{name: 'VENADILLO', code: '45', departament: '30'},
	{name: 'VILLAHERMOSA', code: '46', departament: '30'},
	{name: 'VILLARRICA', code: '47', departament: '30'},
	{name: 'CALI', code: '01', departament: '31'},
	{name: 'ALCALA', code: '02', departament: '31'},
	{name: 'ANDALUCIA', code: '03', departament: '31'},
	{name: 'ANSERMANUEVO', code: '04', departament: '31'},
	{name: 'ARGELIA', code: '05', departament: '31'},
	{name: 'BOLIVAR', code: '06', departament: '31'},
	{name: 'BUENAVENTURA', code: '07', departament: '31'},
	{name: 'GUADALAJARA DE BUGA', code: '08', departament: '31'},
	{name: 'BUGALAGRANDE', code: '09', departament: '31'},
	{name: 'CAICEDONIA', code: '10', departament: '31'},
	{name: 'CALIMA', code: '11', departament: '31'},
	{name: 'CANDELARIA', code: '12', departament: '31'},
	{name: 'CARTAGO', code: '13', departament: '31'},
	{name: 'DAGUA', code: '14', departament: '31'},
	{name: 'EL AGUILA', code: '15', departament: '31'},
	{name: 'EL CAIRO', code: '16', departament: '31'},
	{name: 'EL CERRITO', code: '17', departament: '31'},
	{name: 'EL DOVIO', code: '18', departament: '31'},
	{name: 'FLORIDA', code: '19', departament: '31'},
	{name: 'GINEBRA', code: '20', departament: '31'},
	{name: 'GUACARI', code: '21', departament: '31'},
	{name: 'JAMUNDI', code: '22', departament: '31'},
	{name: 'LA CUMBRE', code: '23', departament: '31'},
	{name: 'LA UNION', code: '24', departament: '31'},
	{name: 'LA VICTORIA', code: '25', departament: '31'},
	{name: 'OBANDO', code: '26', departament: '31'},
	{name: 'PALMIRA', code: '27', departament: '31'},
	{name: 'PRADERA', code: '28', departament: '31'},
	{name: 'RESTREPO', code: '29', departament: '31'},
	{name: 'RIOFRIO', code: '30', departament: '31'},
	{name: 'ROLDANILLO', code: '31', departament: '31'},
	{name: 'SAN PEDRO', code: '32', departament: '31'},
	{name: 'SEVILLA', code: '33', departament: '31'},
	{name: 'TORO', code: '34', departament: '31'},
	{name: 'TRUJILLO', code: '35', departament: '31'},
	{name: 'TULUA', code: '36', departament: '31'},
	{name: 'ULLOA', code: '37', departament: '31'},
	{name: 'VERSALLES', code: '38', departament: '31'},
	{name: 'VIJES', code: '39', departament: '31'},
	{name: 'YOTOCO', code: '40', departament: '31'},
	{name: 'YUMBO', code: '41', departament: '31'},
	{name: 'ZARZAL', code: '42', departament: '31'},
	{name: 'MITU', code: '01', departament: '32'},
	{name: 'CARURU', code: '02', departament: '32'},
	{name: 'PACOA', code: '03', departament: '32'},
	{name: 'TARAIRA', code: '04', departament: '32'},
	{name: 'PAPUNAUA', code: '05', departament: '32'},
	{name: 'YAVARATE', code: '06', departament: '32'},
	{name: 'PUERTO CARRENO', code: '01', departament: '33'},
	{name: 'LA PRIMAVERA', code: '02', departament: '33'},
	{name: 'SANTA ROSALIA', code: '03', departament: '33'},
	{name: 'CUMARIBO', code: '04', departament: '33'},
])

OfficeName.create([
  {name: 'OTRO'},
  {name: 'OTROS ORGANISMOS DE CONTROL'}
])
