User.create([
  {document: "12345678", name: "USUARIO MIGRACION", charge: 'MIGRACION', password: "Previsora2018", password_confirmation: "Previsora2018", role: 1},
  {document: "1032459412", name: "JONATHAN GRANADOS", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 1},
  {document: "1", name: "COORDINADOR OPERATIVO", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 2},
  {document: "2", name: "COORDINADOR LEGAL", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 3},
  {document: "3", name: "ADMINISTRADOR", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 4},
  {document: "1033773336", name: "GABRIELA SUAREZ", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 1},
  {document: "1234", name: "JONATHAN PRIETO", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 1},
  {document: "5678", name: "PAULA TORRES", charge: 'INGENIERO PYO', password: "Previsora2018", password_confirmation: "Previsora2018", role: 1},
  {document: '1020729468', name: 'NATALIA ALEJANDRA  MONCAYO RODRIGUEZ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '49797396', name: 'BETSABE  MANTILLA DIAZ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1010169121', name: 'ANGELA LILIANA LOPEZ ALVAREZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1031138340', name: 'LUIS EDUARDO LOPEZ  MORA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1026252607', name: 'LUZ ANDREA JIMENEZ MUÑOZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '52780795', name: 'CRYSTHEL EMANUELLA GUTIERREZ RAMIREZ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '39567180', name: 'LIDA MORELIA CALDERON RODRIGUEZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1026570699', name: 'CHRISTIAN CAMILO  HERNANDEZ VEGA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '7181859', name: 'DANNY FABIAN GUIO MUÑOZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '80525785', name: 'FREDDY LEONEL ROJAS RIOS', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '40216726', name: 'FLOR ANGELA TORRES HUERTAS', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1015441384', name: 'DANIEL ALEJANDRO PALACIOS BALLEN', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '79828072', name: 'LEONARDO FABIO CALDERON GALLEGO', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '51779870', name: 'ANA PATRICIA MOLANO GACHANCIPA', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1018469232', name: 'AURA JESSICA MEDINA FANDIÑO', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '79993930', name: 'EMIRO ANTONIO VAGAS ', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '71683546', name: 'FABIAN DE JESUS PASADA VELEZ', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1118532099', name: 'MAYRA  MORENO ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1016039726', name: 'MARIA ALEJANDRA  GUTIERREZ BECERRA', charge: 'PROFESIONAL GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '52976920', name: 'EDITH JOHANNA VELASQUEZ GONZALEZ', charge: 'TECNICO CONTRATISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '63358777', name: 'DALILA CRISTINA TAPIAS ACEVEDO', charge: 'ESPECIALISTA DE LA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '37901644', name: 'LUISA FERNANDA ORTEGA SOLANO', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '72272660', name: 'ARON JOSE ORTIZ ', charge: 'PROFESIONAL SUBGERENCIA DE LITIGIOS', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1018442399', name: 'YURANY HASLEYDI NORE ORTEGA', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1018407179', name: 'IVAN  ORDOÑEZ ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '80212112', name: 'JUAN MANUEL PEÑA TORRES', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1022372499', name: 'DAYANE ACOSTA AVILA ', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '20370708', name: 'SANDRA MILENA SANCHEZ RUIZ', charge: 'CONTADOR PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '28554902', name: 'CLAUDIA  RODRIGUEZ PATRON', charge: 'ABOGADO ESPECIALISTA CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1047404034', name: 'CRISTIAN D POMARES ', charge: 'CONTADOR PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '1012329910', name: 'INDIRA ALEXANDRA BEJARANO RAMIREZ', charge: 'ABOGADO PROFESIONAL CONTRATISTA GERENCIA DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '80110210', name: 'VICTOR ANDRES GOMEZ HENAO', charge: 'GERENTE DE PROCESOS JUDICIALES', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1},
  {document: '51575744', name: 'NOHORA MARLENI BOJACA MARTIN', charge: 'SUBGERENTE DE LITIGIOS', password: 'Previsora2018', password_confirmation: 'Previsora2018', role: 1}
])

ProcessClass.create([
  {name: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO', n_type:	2},
  {name: 'JURISDICCION CIVIL', n_type: 2},
  {name: 'JURISDICCION PENAL', n_type: 2},
  {name: 'JURISDICCION LABORAL', n_type: 2},
  {name: 'RESPONSABILIDAD FISCAL', n_type: 3},
  {name: 'TUTELA', n_type: 5},
  {name: "PROCESO ARBITRAL", n_type: 2},
  {name: "PREJUDICIAL REQUISITO DE PROCEDIBILIDAD", n_type: 1},
  {name: "PROCEDIMIENTO ADMINISTRATIVO" , n_type: 4},
  {name: 'PENDIENTE', n_type: 0}
])

SubprocessClass.create([
  {name: 'PROCESOS ADMINISTRATIVOS', n_type: -1},
  {name: 'JURISDICCION CIVIL', n_type: -1},
  {name: 'OTRAS ENTIDADES', n_type: -1},
  {name: 'COLJUEGOS', n_type: -1},
  {name: 'POLIZAS VIDA GRUPO', n_type: -1},
  {name: 'REPARACION DIRECTA', n_type: -1},
  {name: 'NULIDAD Y RESTABLECIMIENTO', n_type: -1},
  {name: 'EJECUTIVO', n_type: -1},
  {name: 'ACCION POPULAR', n_type: -1},
  {name: 'ACCION DE GRUPO', n_type: -1},
  {name: 'ACCION DE NULIDAD', n_type: -1},
  {name: 'ACCIO DE REPETICION', n_type: -1},
  {name: 'ACCION CONTRA ACTUAL', n_type: -1},
  {name: 'COACTIVO', n_type: -1},
  {name: 'FAMILIA', n_type: -1},
  {name: 'DISCIPLINARIO', n_type: -1},
  {name: 'ACCION DE CUMPLIMIENTO', n_type: -1},
  {name: 'ARBITRAMIENTO', n_type: -1},
  {name: 'POR PRIMAS', n_type: -1},
  {name: 'HIPOTECARIOS', n_type: -1},
  {name: 'DIRECTOS', n_type: -1},
  {name: 'ART. 86 -1437', n_type: -1},
  {name: 'LEY 1437', n_type: -1},
  {name: 'RESPONSABILIDAD FISCAL', n_type: -1},
  {name: 'ORDINARIO', n_type: -1},
  {name: 'ESPECIAL', n_type: -1},
  {name: 'VERBAL', n_type: 3},
  {name: 'ORDINARIO', n_type: 3},
  {name: 'ORDINARIO', n_type: 4},
  {name: 'COLJUEGOS', n_type: 4},
  {name: 'JUNTA DE CALIFICACION', n_type: 5},
  {name: 'CONTRA PROVIDENCIA JUDICIAL', n_type: 5},
  {name: 'CONTRA PROVIDENCIA (PROCESO FISCAL)', n_type: 5},
  {name: 'CONTRATO DE SEGUROS', n_type: 5},
  {name: 'DERECHO DE PETICION', n_type: 5},
  {name: 'EXPEDICION POLIZAS (PRESUNCION DE RIESGOS)', n_type: 5},
  {name: 'FALTA DE LEGITIMACION', n_type: 5},
  {name: 'INCAPACIDAD TEMPORAL', n_type: 5},
  {name: 'POLIZA VIDA GRUPO', n_type: 5},
  {name: 'ACCIDENTES PERSONALES', n_type: 5},
  {name: 'SOAT - AUTORIZACIONES EPS', n_type: 5},
  {name: 'SOAT - PAGO INDEMNIZACIONES', n_type: 5},
  {name: 'EXPEDICION DE POLIZAS DE SERIDAD CANDIDATURA NO ASEGURABLE', n_type: 5},
  {name: 'ACTUACION TEMERARIA', n_type: 5},
  {name: 'PROCESOS PENALES', n_type: 21},
  {name: 'NULIDAD POR INCONSTITUCIONALIDAD', n_type: 22},
  {name: 'CONTROL INMEDIATO DE LEGALIDAD', n_type: 22},
  {name: 'NULIDAD', n_type: 22},
  {name: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO', n_type: 22},
  {name: 'NULIDAD ELECTORAL', n_type: 22},
  {name: 'REPARACION DIRECTA', n_type: 22},
  {name: 'CONTROVERSIAS CONTRACTUALES', n_type: 22},
  {name: 'REPETICION', n_type: 22},
  {name: 'PERDIDA DE INVESTIDURA', n_type: 22},
  {name: 'ACCION POPULAR', n_type: 22},
  {name: 'ACCION DE GRUPO', n_type: 22},
  {name: 'CUMPLIMIENTO DE NORMAS CON FUERZA MATERIAL DE LEY O DE ACTOS ADMINISTRATIVOS', n_type: 22},
  {name: 'NULIDAD DE LAS CARTAS DE NATURALEZA Y DE LAS RESOLUCIONES DE AUTORIZACION DE INSCRIPCION', n_type: 23},
  {name: 'CONTROL POR VIA DE EXCEPCION', n_type: 23},
  {name: 'PROCESO VERBAL', n_type: 23},
  {name: 'PROCESO VERBAL SUMARIO', n_type: 23},
  {name: 'PROCESOS DECLARATIVOS ESPECIALES', n_type: 23},
  {name: 'PROCESO EJECUTIVO', n_type: 23},
  {name: 'PROCESO DE SUCESION', n_type: 23},
  {name: 'PROCESO DE LIQUIDACION DE SOCIEDADES CONYUGALES O PATRIMONIALES POR CAUSA DISTINTA DE LA MUERTE DE LOS CONYUGES O COMPANEROS PERMANENTES', n_type: 23},
  {name: 'DISOLUCION, NULIDAD Y LIQUIDACION DE SOCIEDADES', n_type: 23},
  {name: 'INSOLVENCIA DE LA PERSONA NATURAL NO COMERCIANTE', n_type: 23},
  {name: 'PROCESO ORDINARIO', n_type: 23},
  {name: 'PROCESO ARBITRAL', n_type: 24},
  {name: 'ESPECIAL', n_type: 25},
  {name: 'ORDINARIO', n_type: 25}
])

LinkType.create([
  {name: 'PENDIENTE', n_type: 0},
  {name: 'GARANTE', n_type: 4},
  {name: 'CONVOCANTE', n_type: 1},
  {name: 'DEMANDANTE', n_type: 2},
  {name: 'TERCERO CIVILMENTE RESPONSABLE', n_type: 2},
  {name: 'LLAMADA EN GARANTIA', n_type: 2},
  {name: 'DEMANDADO', n_type: 3},
  {name: 'TERCERO CIVILMENTE RESPONSABLE', n_type: 1},
  {name: 'LLAMADA EN GARANTIA', n_type: 1},
  {name: 'ACCIONANTE', n_type: 1},
  {name: 'ACCIONADO', n_type: 5},
  {name: 'VINCULADO', n_type: 5},
  {name: 'TERCERO CIVILMENTE RESPONSABLE', n_type: 6},
  {name: 'ACCIONADO', n_type: 6},
  {name: 'CONVOCADO', n_type: 6}
])

BranchPolicy.create([
  {name: 'PENDIENTE', num: 0},
  {name: 'ARMENIA', num: 1},
  {name: 'BARRANQUILLA', num: 2},
  {name: 'BUCARAMANGA', num: 3},
  {name: 'CALI', num: 4},
  {name: 'CARTAGENA', num: 5},
  {name: 'CUCUTA', num: 6},
  {name: 'FLORENCIA', num: 7},
  {name: 'IBAGUE', num: 8},
  {name: 'MANIZALES', num: 9},
  {name: 'MEDELLIN', num: 10},
  {name: 'MOCOA', num: 11},
  {name: 'MONTERIA', num: 12},
  {name: 'NEIVA', num: 13},
  {name: 'PASTO', num: 14},
  {name: 'PEREIRA', num: 15},
  {name: 'POPAYAN', num: 16},
  {name: 'QUIBDO', num: 17},
  {name: 'RIOHACHA', num: 18},
  {name: 'SAN ANDRES', num: 19},
  {name: 'SANTA MARTA', num: 20},
  {name: 'SINCELEJO', num: 21},
  {name: 'TUNJA', num: 23},
  {name: 'VALLEDUPAR', num: 24},
  {name: 'VILLAVICENCIO', num: 25},
  {name: 'YOPAL', num: 26},
  {name: 'BUENAVENTURA', num: 27},
  {name: 'ARAUCA', num: 28},
  {name: 'CENTRO EMPRESARIAL CORPORATIVO', num: 32},
  {name: 'CENTRO DE SERVICIOS MASIVOS', num: 33},
  {name: 'VIRTUAL BARRANQUILLA', num: 35},
  {name: 'REGIONAL ESTATAL', num: 70},
  {name: 'CASA MATRIZ', num: 80},
  {name: 'BOGOTA', num: 90}
])

BranchCommercial.create([
  {name: 'PENDIENTE', num: 0},
  {name: 'MANEJO', num: 1},
  {name: 'CUMPLIMIENTO', num: 2},
  {name: 'INCENDIO', num: 3},
  {name: 'SUSTRACCION', num: 4},
  {name: 'TRANSPORTES', num: 5},
  {name: 'CASCO BARCO', num: 6},
  {name: 'AUTOMOVILES', num: 7},
  {name: 'SOAT', num: 8},
  {name: 'VIDRIOS PLANOS', num: 9},
  {name: 'CASCO AVIACION', num: 10},
  {name: 'TERREMOTO (AMP. INCENDIO)', num: 11},
  {name: 'TERREMOTO (AMP. CORRIENTE DEBIL)', num: 12},
  {name: 'RESPONSABILIDAD CIVIL', num: 13},
  {name: 'SEGURO AGRICOLA', num: 14},
  {name: 'INFIDELIDAD DE RIESGOS FINANCIEROS', num: 15},
  {name: 'VIDA COLECTIVO', num: 16},
  {name: 'VIDA GRUPO', num: 17},
  {name: 'VIDA GRUPO DEUDORES', num: 18},
  {name: 'ACCIDENTES PERSONALES', num: 19},
  {name: 'ESTABILIDAD Y CALIDAD DE VIVIENDA', num: 20},
  {name: 'OBRAS CIVILES', num: 21},
  {name: 'SALUD', num: 22},
  {name: 'DESEMPLEO', num: 23},
  {name: 'ADMINIST. RIESGOS PROFESIONALES', num: 24},
  {name: 'VIDA INDIVIDUAL', num: 25},
  {name: 'CAUCION JUDICIAL', num: 29},
  {name: 'ROTURA DE MAQUINARIA', num: 81},
  {name: 'MONTAJE DE MAQUINARIA', num: 82},
  {name: 'CORRIENTE DEBIL', num: 83},
  {name: 'TODO RIESGO CONTRATISTA', num: 84},
  {name: 'MINAS Y PETROLEOS', num: 85},
  {name: 'PREVIHOSPITAL', num: 86},
  {name: 'PREVIALCALDIAS', num: 87},
  {name: 'PREVIPYME', num: 88},
  {name: 'PREVIHOGAR', num: 89},
  {name: 'AREAS COMUNES', num: 90},
  {name: 'PREVITURISMO', num: 91},
  {name: 'PREVIQUIMICOS', num: 92},
  {name: 'PREVIEDUCATIVO', num: 93},
  {name: 'TODO RIESGO EMPRESARIAL', num: 94},
  {name: 'PREVICAMPO', num: 95},
  {name: 'DANOS MATERIALES', num: 98}
])

LitigationSource.create([
  {name: 'PENDIENTE', n_type: 0},
  {name: 'SINIESTRO', n_type: 1},
  {name: 'PROVISION', n_type: 1},
  {name: 'ESTIMACION RECOBRO', n_type: 1},
  {name: 'VINCULACION ERRADA', n_type: 1},
  {name: 'CONTRATO LABORAL', n_type: 1},
  {name: 'CREDITO HIPOTECARIO', n_type: 1},
  {name: 'DOLO O CULPA GRAVE', n_type: 1},
  {name: 'PRIMAS', n_type: 1}
])

Protection.create([
  {name: 'PENDIENTE', n_type: 0},
  {name: 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL', n_type: 1},
  {name: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA', n_type: 1},
  {name: 'DANOS EXTRAPATRIMONIALES', n_type: 1},
  {name: 'ERRORES U OMISIONES PROFESIONALES', n_type: 1},
  {name: 'COBERTURA R.C CLINICAS Y HOSPITALES', n_type: 1},
  {name: 'FALLOS CON RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'RENDICION Y RECONSTRUCCION DE CUENTAS', n_type: 1},
  {name: 'PREDIOS LABORES Y OPERACIONES', n_type: 1},
  {name: 'EMPLEADOS NO IDENTIFICADOS ( CLAUSULA)', n_type: 1},
  {name: 'ACTOS INCORRECTOS', n_type: 1},
  {name: 'INCAPACIDAD PERMANENTE', n_type: 1},
  {name: 'RC. PATRONAL', n_type: 1},
  {name: 'ABUSO DE CONFIANZA', n_type: 1},
  {name: 'ASISTENCIA JURIDICA PENAL', n_type: 1},
  {name: 'ASISTENCIA JURIDICA CIVIL', n_type: 1},
  {name: 'HONORARIOS PROFESIONALES', n_type: 1},
  {name: 'PAGO DE SALARIOS PRESTACIONES SOCIALES E INDEMNIZACIONES', n_type: 1},
  {name: 'HURTO CALIFICADO', n_type: 1},
  {name: 'BUEN MANEJO DEL ANTICIPO', n_type: 1},
  {name: 'ACTOS QUE GENEREN JUICIOS DE RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'PERJUICIOS MODALIDAD DANO EMERGENTE', n_type: 1},
  {name: 'RESPONSABILIDAD CIVIL CRUZADA', n_type: 1},
  {name: 'CONVERSION', n_type: 1},
  {name: 'CUMPLIMIENTO DE CONTRATO', n_type: 1},
  {name: 'INFIDELIDAD DE EMPLEADOS', n_type: 1},
  {name: 'AVERIAS', n_type: 1},
  {name: 'EXTENDED COVERAGE (OTROS AMPAROS ADICIONALES)', n_type: 1},
  {name: 'PERDIDA PARCIAL DANOS', n_type: 1},
  {name: 'FALTA DE ENTREGA', n_type: 1},
  {name: 'ENFERMEDADES DE ALTO COSTO SUBSIDIADO', n_type: 1},
  {name: 'COBERTURA OBRAS CIVILES ( CONSTRUCCION)', n_type: 1},
  {name: 'COBERTURA R.C EXTRACONTRACTUAL', n_type: 1},
  {name: 'PERDIDA SEVERA POR HURTO', n_type: 1},
  {name: 'TERAPEUTICOS', n_type: 1},
  {name: 'CUMPLIMIENTO', n_type: 41},
  {name: 'INCUMPLIMIENTO', n_type: 42},
  {name: 'ESTABILIDAD LABORAL', n_type: 42},
  {name: 'SALARIOS Y PRESTACIONES E INDEMNIZACIONES', n_type: 42},
  {name: 'BUEN MANEJO DEL ANTICIPO', n_type: 42},
  {name: 'COBERTURA GLOBAL DEL MANEJO', n_type: 1},
  {name: 'OTRO', n_type: 1}
])

ScoreContingency.create([
  {name: 'PENDIENTE'},
  {name: 'EVENTUAL'},
  {name: 'REMOTA'},
  {name: 'PROBABLE'}
])

CurrentStage.create([
  {name: 'PENDIENTE', n_type: 0},
  {name: 'AUTO DE APERTURA', n_type: 1},
  {name: 'AUTO DE IMPUTACION', n_type: 1},
  {name: 'ARGUMENTOS DE DEFENSA', n_type: 1},
  {name: 'ALEGATOS DE CONCLUSION', n_type: 1},
  {name: 'FALLO CON RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'RECURSO DE REPOSICION', n_type: 1},
  {name: 'AUTO QUE RESUELVE LA REPOSICION', n_type: 1},
  {name: 'RECURSO DE APELACION', n_type: 1},
  {name: 'AUTO QUE RESUELVE APELACION', n_type: 1},
  {name: 'FALLO SIN RESPONSABILIDAD FISCAL', n_type: 1},
  {name: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA', n_type: 1},
  {name: 'AUTO DE APERTURA E IMPUTACION', n_type: 2},
  {name: 'AUDIENCIA DE DESCARGOS', n_type: 2},
  {name: 'AUDIENCIA DE DECISION', n_type: 2},
  {name: 'FALLO CON RESPONSABILIDAD FISCAL', n_type: 2},
  {name: 'RECURSO DE REPOSICION', n_type: 2},
  {name: 'AUTO QUE RESUELVE LA REPOSICION', n_type: 2},
  {name: 'RECURSO DE APELACION', n_type: 2},
  {name: 'AUTO QUE RESUELVE APELACION', n_type: 2},
  {name: 'FALLO SIN RESPONSABILIDAD FISCAL', n_type: 2},
  {name: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA', n_type: 2},
  {name: 'INDAGACION', n_type: 5},
  {name: 'INVESTIGACION', n_type: 5},
  {name: 'ETAPA DE JUZGAMIENTO', n_type: 5},
  {name: 'AUDIENCIA DE ACUSACION', n_type: 5},
  {name: 'AUDIENCIA PREPARATORIA', n_type: 5},
  {name: 'AUDIENCIA DE JUICIO ORAL', n_type: 5},
  {name: 'AUDIENCIA DE INCIDENTE DE REPARACION INTEGRAL', n_type: 5},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 5},
  {name: 'AUDIENCIA DE PRUEBAS Y ALEGACIONES', n_type: 5},
  {name: 'SENTENCIA DE INCIDENTE DE REPARACION INTEGRAL', n_type: 5},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 3},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 3},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 3},
  {name: 'DEMANDA DE RECONVENCION', n_type: 3},
  {name: 'PRUEBAS', n_type: 3},
  {name: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA', n_type: 3},
  {name: 'SENTENCIA DE PRIMERA INSTANCIA', n_type: 3},
  {name: 'APELACION', n_type: 3},
  {name: 'AUDIENCIA DE CONCILIACION (ART 70)', n_type: 3},
  {name: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA', n_type: 3},
  {name: 'SENTENCIA SEGUNDA INSTANCIA', n_type: 3},
  {name: 'RECURSO EXTRAORDINARIO DE UNIFICACION DE JURISPRUDENCIA', n_type: 3},
  {name: 'RECURSO DE REVISION', n_type: 3},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 4},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 4},
  {name: 'DEMANDA DE RECONVENCION', n_type: 4},
  {name: 'AUDIENCIA Y FALLO', n_type: 4},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 4},
  {name: 'AUDIENCIA PUBLICA', n_type: 4},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 4},
  {name: 'AUDIENCIA DE TRAMITE O PRUEBA', n_type: 4},
  {name: 'AUDIENCIA DE JUZGAMIENTO', n_type: 4},
  {name: 'APELACION', n_type: 4},
  {name: 'AUDIENCIA DE ALEGACIONES Y FALLO', n_type: 4},
  {name: 'AUDIENCIA DE ALEGACIONES', n_type: 4},
  {name: 'AUDIENCIA DE FALLO', n_type: 4},
  {name: 'DEMANDA DE CASACION', n_type: 4},
  {name: 'ADMISION DEMANDA DE CASACION', n_type: 4},
  {name: 'OPOSICION DEMANDA DE CASACION', n_type: 4},
  {name: 'SENTENCIA DE CASACION', n_type: 4},
  {name: 'INTEGRACION DEL TRIBUNAL ARBITRAL', n_type: 6},
  {name: 'IMPEDIMENTOS Y RECUSACIONES ', n_type: 6},
  {name: 'INSTALACION DEL TRIBUNAL ARBITRAL', n_type: 6},
  {name: 'ADMISION DE LA DEMANDA', n_type: 6},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 6},
  {name: 'AUDIENCIA DE CONCILIACION', n_type: 6},
  {name: 'ACTA DE FIJACION DE HONORARIOS Y GASTOS DEL TRIBUNAL', n_type: 6},
  {name: 'PRIMERA AUDIENCIA DE TRAMITE', n_type: 6},
  {name: 'AUDIENCIAS Y PRUEBAS', n_type: 6},
  {name: 'AUDIENCIA DE ALEGATOS Y FALLO', n_type: 6},
  {name: 'LAUDO ARBITRAL', n_type: 6},
  {name: 'RECURSO EXTRAORDINARIO DE ANULACION', n_type: 6},
  {name: 'SENTENCIA SOBRE ANULACION', n_type: 6},
  {name: 'RECURSO DE REVISION', n_type: 6},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 7},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 7},
  {name: 'DEMANDA DE RECONVENCION', n_type: 7},
  {name: 'AUDIENCIA INICIAL', n_type: 7},
  {name: 'PRUEBAS PRIMERA INSTANCIA', n_type: 7},
  {name: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO', n_type: 7},
  {name: 'APELACION', n_type: 7},
  {name: 'AUDIENCIA DE SUSTENTACION Y FALLO', n_type: 7},
  {name: 'DEMANDA DE CASACION', n_type: 7},
  {name: 'ADMISION DEMANDA DE CASACION', n_type: 7},
  {name: 'OPOSICION DEMANDA DE CASACION', n_type: 7},
  {name: 'SENTENCIA DE CASACION', n_type: 7},
  {name: 'RECURSO DE QUEJA', n_type: 7},
  {name: 'RECURSO DE REVISION', n_type: 7},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 8},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 8},
  {name: 'DEMANDA DE RECONVENCION', n_type: 8},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 8},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 9},
  {name: 'AUTO ADMISORIO DE LA DEMANDA', n_type: 9},
  {name: 'CONTESTACION DE LA DEMANDA', n_type: 9},
  {name: 'SENTENCIA DE UNICA INSTANCIA', n_type: 9},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 9},
  {name: 'PRESENTACION DE LA DEMANDA', n_type: 10},
  {name: 'MANDAMIENTO EJECUTIVO', n_type: 10},
  {name: 'PRESENTACION DE EXCEPCIONES Y/O RECURSO DE REPOSICION', n_type: 10},
  {name: 'PRUEBAS', n_type: 10},
  {name: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)', n_type: 10},
  {name: 'AUDIENCIA INICIAL', n_type: 10},
  {name: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO', n_type: 10},
  {name: 'AUTO ORDENA SEGUIR ADELANTE LA EJECUCION', n_type: 10},
  {name: 'LIQUIDACION DEL CREDITO POR LAS PARTES', n_type: 10},
  {name: 'AUTO QUE APRUEBA O MODIFICA LIQUIDACION DEL CREDITO', n_type: 10},
  {name: 'REMATE DE BIENES', n_type: 10},
  {name: 'DILIGENCIA DE DESLINDE', n_type: 11},
  {name: 'SOLICITUD DE LICENCIA PREVIA', n_type: 11},
  {name: 'AUTODECRETA DIVISION', n_type: 11},
  {name: 'INSCRIPCION DE LA PARTICION', n_type: 11},
  {name: 'ENTREGA DE PARTE ADJUDICADA', n_type: 11},
  {name: 'REMATE', n_type: 11},
  {name: 'APERTURA', n_type: 12},
  {name: 'POR NOTARIO O JUZGADO', n_type: 12},
  {name: 'PUBLICACION JUDICIAL DEL TESTAMENTO CERRADO', n_type: 12},
  {name: 'PRESENTACION DE OPOSICION', n_type: 12},
  {name: 'RECHAZO DE OPOSICION', n_type: 12},
  {name: 'AUDIENCIA DE PRUEBAS', n_type: 12},
  {name: 'PUBLICACION DEL TESTAMENTO ANTE CINCO TESTIGOS', n_type: 12},
  {name: 'TESTAMENTO VERBAL', n_type: 12},
  {name: 'EMBARGO Y SECUESTRO', n_type: 12},
  {name: 'TERMINACION DE SECUESTRO', n_type: 12},
  {name: 'HERENCIA YACENTE', n_type: 12},
  {name: 'RECONOCIMIENTO DE INTERESADOS', n_type: 12},
  {name: 'REQUERIMIENTO PARA EJERCER DERECHO DE OPCION', n_type: 12},
  {name: 'ACEPTACION DE ACREEDORES DEL ASIGNATARIO', n_type: 12},
  {name: 'REPUDIACION DE ASIGNACIONES A FAVOR DE INCAPACES', n_type: 12},
  {name: 'ADMINISTRACION DE HERENCIA', n_type: 12},
  {name: 'RESTITUCION DE BIENES', n_type: 12},
  {name: 'PAGO DE DEUDAS', n_type: 12},
  {name: 'DECRETO DE PARTICION Y DESIGANCION DE PARTIDOR', n_type: 12},
  {name: 'ENTREGA DE BIENES A ADJUDICATARIOS', n_type: 12},
  {name: 'DEMANDA', n_type: 13},
  {name: 'ADMISION DEMANDA', n_type: 13},
  {name: 'POTESTACION DEMANDA', n_type: 13},
  {name: 'EMPLAZAMIENTO DE ACREEDORES DE LA SOCIEDAD', n_type: 13},
  {name: 'AUDIENCIA INICIAL', n_type: 13},
  {name: 'SENTENCIA', n_type: 13},
  {name: 'LIQUIDACION', n_type: 13},
  {name: 'SOLICITUD DE NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'DESIGNACION CONCILIADOR', n_type: 14},
  {name: 'ACEPTACION SOLICITUD DE NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'COMUNICACION DE LA ACEPTACION', n_type: 14},
  {name: 'AUDIENCIA NEGOCIACION DE DEUDAS', n_type: 14},
  {name: 'ACUERDO DE PAGO', n_type: 14},
  {name: 'IMPUGNACION DEL ACUERDO', n_type: 14},
  {name: 'CUMPLIMIENTO DEL ACUERDO', n_type: 14},
  {name: 'FRACASO DE NEGOCIACION', n_type: 14},
  {name: 'INCUMPLIMIENTO DE ACUERDO', n_type: 14},
  {name: 'APERTURA DE LIQUIDACION PATRIMONIAL', n_type: 14},
  {name: 'PRESENTACION DE OBJECIONES POR ACREEDORES', n_type: 14},
  {name: 'RESOLUCION DE OBJECIONES', n_type: 14},
  {name: 'ACUERDO RESOLUTORIO DENTRO DE LIQUIDACION PATRIMONIAL', n_type: 14},
  {name: 'AUDIENCIA DE ADJUTICACION', n_type: 14},
  {name: 'DEMANDA ', n_type: 15},
  {name: 'PRUEBAS', n_type: 15},
  {name: 'SENTENCIA', n_type: 15},
  {name: 'DEMANDA', n_type: 17},
  {name: 'ADMISION DEMANDA', n_type: 17},
  {name: 'CONTESTACION DEMANDA', n_type: 17},
  {name: 'AUTO ORDENA AVALUO DE BIEN COMUN', n_type: 17},
  {name: 'OBJECIONES AL AVALUO', n_type: 17},
  {name: 'DESIGNACION PARTIDOR', n_type: 17},
  {name: 'POSESION PARTIDOR', n_type: 17},
  {name: 'ENTREGA DE LO ADJUDICADO', n_type: 17},
  {name: 'AUTO DECRETA VENTA DE COSA COMUN', n_type: 17},
  {name: 'REMATE', n_type: 17},
  {name: 'DEMANDA', n_type: 16},
  {name: 'ADMISION DEMANDA', n_type: 16},
  {name: 'CONTESTACION DEMANDA', n_type: 16},
  {name: 'AUDIENCIA CONCILIACION', n_type: 16},
  {name: 'PRUEBAS - ALEGATOS CONCLUSION', n_type: 16},
  {name: 'SENTENCIA PRIMERA INSTANCIA', n_type: 16},
  {name: 'ALEGATOS SEGUNDA INSTANCIA', n_type: 16},
  {name: 'SENTENCIA SEGUNDA INSTANCIA', n_type: 16},
  {name: 'DEMANDA CASACION - ADMINISION DEMANDA CASACION', n_type: 16},
  {name: 'OPOSICION DEMANDA CASACION', n_type: 16},
  {name: 'SENTENCIA CASACION', n_type: 16},
  {name: 'RECURSO SUPLICA', n_type: 16},
  {name: 'RECURSO QUEJA', n_type: 16},
  {name: 'RECURSO REVISION', n_type: 16},
  {name: 'EN TERMINOS PARA RESOLVER RECURSOS DE REPOSICION', n_type: 18},
  {name: 'AUDIENCIA SUSPENDIDA', n_type: 18},
  {name: 'AUDIENCIA QUE RESUELVE', n_type: 18},
  {name: 'SANCION EN FIRME', n_type: 18},
  {name: 'PREJUDICIAL', n_type: 19},
])

JoinCommittee.create([
  {name: 'PENDIENTE'},
  {name: 'SI'},
  {name: 'NO'}
])

Committee.create([
  {name: 'PENDIENTE'},
  {name: 'CONCILIA'},
  {name: 'NO CONCILIA'},
  {name: 'INVIABLE'}
])

Instance.create([
  {name: 'PENDIENTE'},
  {name: 'PRIMERA'},
  {name: 'SEGUNDA'},
  {name: 'UNICA'},
  {name: 'GRADO DE CONSULTA'},
  {name: 'RECURSO EXTRAORDINARIO'},
  {name: 'PREJUDICIAL'},
  {name: 'RECOBRO'},
  {name: 'NO APLICA'}
])

CaseTermination.create([
  {name: 'PENDIENTE', n_type: 0},
  {name: 'TERMINADO CON PAGO: EN CONTRA', n_type: 1},
  {name: 'TERMINADO SIN PAGO: A FAVOR', n_type: 1},
  {name: 'TERMINADO SIN PAGO: EN CONTRA', n_type: 1},
  {name: 'FAVORABLE', n_type: 2},
  {name: 'DESFAVORABLE', n_type: 2}
])

GubernatorialWay.create([
  {name: 'PENDIENTE', n_type: 1},
  {name: 'CONEXION', n_type: 1},
  {name: 'SIPLAFT', n_type: 1},
  {name: 'ESTADOS FINANCIEROS', n_type: 1},
  {name: 'MORA', n_type: 1},
  {name: 'POLIZA', n_type: 1},
  {name: 'VISITA FISCALIZACION', n_type: 1},
  {name: 'INEXACTITUD', n_type: 1},
  {name: 'NO APLICA', n_type: 2}
])

ReinsuranceType.create([
  {name: 'NO SE PRESENTO'},
  {name: 'FACULTATIVO'},
  {name: 'CUOTA PARTE'}
])

MoneyType.create([
  {name: 'PESOS'},
  {name: 'DOLAR'}
])

ReservedReleased.create([
  {name: 'PENDIENTE'},
  {name: 'NO'},
  {name: 'SI'}
])

CoensuranceType.create([
  {name: 'NO SE PRESENTO'},
  {name: 'CEDIDO'},
  {name: 'ACEPTADO'}
])

CaseState.create([
  {name: 'EN CURSO'},
  {name: 'TERMINADO'}
])

LastPerformance.create([
  {name: 'PENDIENTE'},
  {name: 'OTRO'},
  {name: 'ALEGATOS'},
  {name: 'AUTO QUE TERMINA PROCESO POR CONCILIACION'},
  {name: 'AUTO QUE TERMINA PROCESO POR TRANSACCION'},
  {name: 'DESCARGOS'},
  {name: 'GRADO DE CONSULTA'},
  {name: 'RECURSO DE REPOSICION'},
  {name: 'RECURSO DE APELACION'},
  {name: 'SENTENCIA Y AUTOS GENERALES'}
])

OfficeName.create([
  {name: 'OTRO'},
  {name: 'OTROS ORGANISMOS DE CONTROL'},
  {name: 'ALCALDIA'},
  {name: 'ALCALDIA BOGOTA'},
  {name: 'AUDITORIA FISCAL ANTE LA CONTRALORIA DE BOGOTA D.C.'},
  {name: 'AUDITORIA GENERAL DE LA REPUBLICA'},
  {name: 'AUDITORIA GENERAL DE LA REPUBLICA'},
  {name: 'CAMARA COMERCIO'},
  {name: 'CENTRO CONCILIACION Y ARBITRAJE'},
  {name: 'COLJUEGOS'},
  {name: 'CONSEJO DE ESTADO'},
  {name: 'CONSEJO SECCIONAL JUDICATURA'},
  {name: 'CONSEJO SUPERIOR DE LA JUDICATURA'},
  {name: 'CONTRALORIA DE BOGOTA D.C.'},
  {name: 'CONTRALORIA DE CUNDINAMARCA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE AMAZONAS'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE ARAUCA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE CORDOBA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE LA GUAJIRA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE NARINO'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DE VAUPES'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL CAQUETA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL CAUCA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL GUAINIA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL GUAVIARE'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL META'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL VALLE DEL CAUCA'},
  {name: 'CONTRALORIA DEPARTAMENTAL DEL VICHADA'},
  {name: 'CONTRALORIA DISTRITAL DE BUENAVENTURA'},
  {name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS'},
  {name: 'CONTRALORIA DISTRITAL DE SANTA MARTA'},
  {name: 'CONTRALORIA GENERAL DE ANTIOQUIA'},
  {name: 'CONTRALORIA GENERAL DE BOYACA'},
  {name: 'CONTRALORIA GENERAL DE CALDAS'},
  {name: 'CONTRALORIA GENERAL DE L A REPUBLICA GERENCIA DEPARTAMENTAL ARAUCA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL AMAZONAS'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL ANTIOQUIA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL ATLANTICO'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CALDAS'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAQUETA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CESAR'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CHOCO'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CORDOBA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL GUAINIA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL GUAJIRA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL GUAVIARE'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL MAGDALENA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL META'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL NARINO'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL NORTE DE SANTANDER'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL PUTUMAYO'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL QUINDIO'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL RISARALDA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL SAN ANDRES, PROVIDENCIA Y SANTA CATALINA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL SANTANDER'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL SUCRE'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL VALLE DEL CAUCA'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL VAUPES'},
  {name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL VICHADA'},
  {name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR'},
  {name: 'CONTRALORIA GENERAL DE MEDELLIN'},
  {name: 'CONTRALORIA GENERAL DE SANTIAGO DE CALI'},
  {name: 'CONTRALORIA GENERAL DEL BOYACA'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO DE SANTANDER'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO DE SUCRE'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO DEL MAGDALENA'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO DEL PUTUMAYO'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO DEL QUINDIO'},
  {name: 'CONTRALORIA GENERAL DEL DEPARTAMENTO NORTE DE SANTANDER'},
  {name: 'CONTRALORIA GENERAL DEL MUNICIPIO DE MANIZALES'},
  {name: 'CONTRALORIA GENERAL DEL RISARALDA'},
  {name: 'CONTRALORIA GENERAL DEPARTAMENTO DEL ATLANTICO'},
  {name: 'CONTRALORIA GENERAL DEPARTAMENTO DEL CHOCO'},
  {name: 'CONTRALORIA MUNICIPAL DE ARMENIA'},
  {name: 'CONTRALORIA MUNICIPAL DE BARRANCABERMEJA'},
  {name: 'CONTRALORIA MUNICIPAL DE BELLO'},
  {name: 'CONTRALORIA MUNICIPAL DE CUCUTA'},
  {name: 'CONTRALORIA MUNICIPAL DE DOSQUEBRADAS'},
  {name: 'CONTRALORIA MUNICIPAL DE ENVIGADO'},
  {name: 'CONTRALORIA MUNICIPAL DE FLORIDABLANCA'},
  {name: 'CONTRALORIA MUNICIPAL DE IBAGUE'},
  {name: 'CONTRALORIA MUNICIPAL DE MONTERIA'},
  {name: 'CONTRALORIA MUNICIPAL DE NEIVA'},
  {name: 'CONTRALORIA MUNICIPAL DE PASTO'},
  {name: 'CONTRALORIA MUNICIPAL DE PEREIRA'},
  {name: 'CONTRALORIA MUNICIPAL DE POPAYAN'},
  {name: 'CONTRALORIA MUNICIPAL DE SINCELEJO'},
  {name: 'CONTRALORIA MUNICIPAL DE SOACHA'},
  {name: 'CONTRALORIA MUNICIPAL DE SOLEDAD'},
  {name: 'CONTRALORIA MUNICIPAL DE TULUA'},
  {name: 'CONTRALORIA MUNICIPAL DE TUNJA'},
  {name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR'},
  {name: 'CONTRALORIA MUNICIPAL DE VILLAVICENCIO'},
  {name: 'ENTES JURISDICCION COACTIVA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE BUCARAMANGA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE TURBO'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE MOCOA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE PROVIDENCIA.'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE SAN ANDRES'},
  {name: 'JUZGADO 0 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE ACACIAS'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE CAUCASIA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE DESCONGESTION DE COROZAL'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE GIRARDOTA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE LERIDA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE LORICA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE MARINILLA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE MONTELIBANO'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE MONTERREY'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE PLANETA RICA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE PUERTO BOYACA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE ROLDANILLO'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE SAHAGUN'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE SANTA BARBARA'},
  {name: 'JUZGADO 0 CIVIL CIRCUITO DE SANTA ROSA DE CABAL'},
  {name: 'JUZGADO 0 CIVIL DESCONGESTION DE BOGOTA'},
  {name: 'JUZGADO 0 CIVIL MUNICIPAL DE PAJARITO'},
  {name: 'JUZGADO 0 CIVIL MUNICIPAL DE YOPAL'},
  {name: 'JUZGADO 0 CIVIL ORALES DE BOGOTA'},
  {name: 'JUZGADO 0 CIVIL PROMISCUO DE MAJAGUAL'},
  {name: 'JUZGADO 0 CIVIL PROMISCUO DE MEDELLIN'},
  {name: 'JUZGADO 0 CIVIL PROMISCUO DE TAME'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE CALOTO'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE ESPINAL'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE HONDA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE LA CEJA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE MONTELIBANO'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE PLANETA RICA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE PROVIDENCIA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE PUERTO BERRIO'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE ROLDANILLO'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE SAN JUAN DEL CESAR'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 0 LABORAL CIRCUITO DE YARUMAL'},
  {name: 'JUZGADO 0 PENAL CIRCUITO DE CAQUEZA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE ARAUCA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BARRANCABERMEJA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BOYACA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE BUGA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE CARTAGO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE BUCARAMANGA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE MONTERIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE PEREIRA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE FACATATIVA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE GIRARDOT'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE MOCOA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE PROVIDENCIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE QUIBDO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE SAN ANDRES'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE SAN GIL'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE TURBO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO CIRCUITO DE YOPAL'},
  {name: 'JUZGADO 1 ADMINISTRATIVO DESCONGESTION DE MANIZALES'},
  {name: 'JUZGADO 1 ADMINISTRATIVO DESCONGESTION DE MEDELLIN'},
  {name: 'JUZGADO 1 ADMINISTRATIVO DESCONGESTION DE PEREIRA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE ARMENIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE BUGA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE CARTAGO'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE FLORENCIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE GIRARDOT'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE MANIZALES'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE MOCOA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE MONTERIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE PEREIRA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE PROVIDENCIA'},
  {name: 'JUZGADO 1 ADMINISTRATIVO ORALES DE SAN GIL'},
  {name: 'JUZGADO 1 ADMINIStypeTRATIVO ORALES DE PASTO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE APARTADO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BARRANCABERMEJA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BELLO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE BUGA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE FACATATIVA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE IPIALES'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE ITSMINA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE LA DORADA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE LA UNION'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE MAGANGUE'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE MOCOA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE PALMIRA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE PASTO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE PLANETA RICA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE QUIBDO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE SAHAGUN'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE SANTA BARBARA'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 1 CIVIL CIRCUITO DE YOPAL'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE ACACIAS'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE APARTADO'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE BARRANCABERMEJA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE CARTAGENA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE PASTO'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE PURIFICACION'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE SABANALARGA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE SANTA MARTA'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE VALLEDUPAR'},
  {name: 'JUZGADO 1 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 1 CIVIL PEQUENAS CAUSAS DE MONTERIA'},
  {name: 'JUZGADO 1 CIVIL PEQUENAS CAUSAS DE VILLAVICENCIO'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE AGUACHICA'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE BOGOTA'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE CHINCHINA'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE LERIDA'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE ORTEGA'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE SAHAGUN'},
  {name: 'JUZGADO 1 CIVIL PROMISCUO DE SAN VICENTE'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE CALI'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE CHAPARRAL'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE LORICA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 1 LABORAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 1 LABORAL PEQUENAS CAUSAS DE BOGOTA'},
  {name: 'JUZGADO 1 PENAL CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 1 PENAL CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 1 PENAL MUNICIPAL DE BELLO'},
  {name: 'JUZGADO 1 PENAL MUNICIPAL DE CALI'},
  {name: 'JUZGADO 1 PENAL MUNICIPAL DE SANTAFE DE BOGOTA DC'},
  {name: 'JUZGADO 1 PENAL PROMISCUO DE ANSERMA'},
  {name: 'JUZGADO 1 PENAL PROMISCUO DE PLATO'},
  {name: 'JUZGADO 1 PENAL PROMISCUO DE SASAIMA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 10 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO MUNICIPAL DE BARRANQUILLA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 10 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 10 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 10 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 10 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 10 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 10 CIVIL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 10 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 10 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 10 LABORAL PEQUENAS CAUSAS DE BOGOTA'},
  {name: 'JUZGADO 101 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 11 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 11 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 11 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 11 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 11 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 11 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 11 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 11 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 11 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 11 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 11 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 11 LABORAL CIRCUITO DE CALI'},
  {name: 'JUZGADO 11 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE BUGA'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE IBAGUE'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE SAN GIL'},
  {name: 'JUZGADO 12 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 12 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 12 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 12 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 12 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 12 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 12 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 12 CIVIL MUNICIPAL DE CARTAGENA'},
  {name: 'JUZGADO 12 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 12 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 12 LABORAL CIRCUITO DE SANTAFE DE BOGOTA DC'},
  {name: 'JUZGADO 13 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 13 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 13 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 13 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 13 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 13 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 13 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 13 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 13 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 13 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 13 CIVIL MUNICIPAL DE IBAGUE'},
  {name: 'JUZGADO 13 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 133 PENAL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE ENVIGADO'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 14 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 14 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 14 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 14 ADMINISTRATIVO ORALES DE TUNJA'},
  {name: 'JUZGADO 14 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 14 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 14 CIVIL MUNICIPAL DE BARRANQUILLA'},
  {name: 'JUZGADO 14 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 14 LABORAL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 14 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 14 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 15 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 15 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 15 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 15 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 15 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 15 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 15 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 15 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 15 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 15 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 15 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 15 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 15 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 15 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 15 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 15 CIVIL ORALES DE CALI'},
  {name: 'JUZGADO 15 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 15 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 16 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 16 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 16 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 16 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 16 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 16 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 16 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 16 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 16 PENAL CIRCUITO DE CALI'},
  {name: 'JUZGADO 17 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 17 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 17 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 17 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 17 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 17 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 17 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 18 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 18 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 18 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 18 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 18 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 18 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 18 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 18 LABORAL CIRCUITO DE CALI'},
  {name: 'JUZGADO 18 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 19 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 19 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 19 ADMINISTRATIVO ORALES DE BOGOTA'},
  {name: 'JUZGADO 19 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 19 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 19 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE ARAUCA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE BUGA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE CARTAGO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE MEDELLIN'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE FACATATIVA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE GIRARDOT'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE MOCOA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE QUIBDO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE RIOSUCIO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE SAN GIL'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE SOGAMOSO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE TURBO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE YOPAL'},
  {name: 'JUZGADO 2 ADMINISTRATIVO CIRCUITO DE ZIPAQUIRA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO MUNICIPAL DE CALDAS'},
  {name: 'JUZGADO 2 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE ARAUCA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE ARMENIA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE GIRARDOT'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 2 ADMINISTRATIVO ORALES DE VILLAVICENCIO'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE CERETE'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE COROZAL'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE GARZON'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE IPIALES'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE ITAGUI'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE LA PLATA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE MELGAR'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE OCA¥A'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE PALMIRA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE PITALITO'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE SANTANDER DE QUILICH'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE SOGAMOSO'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE TULUA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE TUMACO'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE TURBACO'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 2 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE IBAGUE'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE MOCOA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE NEIVA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE PALMIRA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE PASTO'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE PEREIRA'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE SINCELEJO'},
  {name: 'JUZGADO 2 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 2 CIVIL ORALES DE ENVIGADO'},
  {name: 'JUZGADO 2 CIVIL ORALES DE ITAGUI'},
  {name: 'JUZGADO 2 CIVIL PEQUENAS CAUSAS DE SANTA MARTA'},
  {name: 'JUZGADO 2 CIVIL PEQUENAS CAUSAS DE SOLEDAD'},
  {name: 'JUZGADO 2 CIVIL PROMISCUO DE CARMEN DE VIBORAL'},
  {name: 'JUZGADO 2 CIVItypeL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE PASTO'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 2 LABORAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 2 LABORAL PEQUENAS CAUSAS DE CUCUTA'},
  {name: 'JUZGADO 2 PENAL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 2 PENAL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 2 PENAL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 2 PENAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 2 PENAL MUNICIPAL DE LOS PATIOS'},
  {name: 'JUZGADO 2 PENAL MUNICIPAL DE NEIVA'},
  {name: 'JUZGADO 2 PENAL PROMISCUO DE SALAMINA'},
  {name: 'JUZGADO 20 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 20 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 20 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 20 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 20 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 20 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 20 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 21 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 21 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 21 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 21 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 21 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 21 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 21 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 21 CIVIL CIRCUITO DE SOACHA'},
  {name: 'JUZGADO 21 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 21 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 22 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 22 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 22 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 22 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 22 CIVIL MUNICIPAL DE CALI'},
  {name: 'JUZGADO 22 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 23 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 23 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 23 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 23 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 24 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 24 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 24 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 24 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 24 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 24 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 25 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 25 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 25 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 25 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 25 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 26 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 26 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 26 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 26 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 26 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 26 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 27 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 27 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 27 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 28 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 28 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 28 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 28 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 28 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 29 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 29 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 29 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 29 ADMINtypeISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 29 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 29 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 29 CIVIL MUNICIPAL DE CALI'},
  {name: 'JUZGADO 29 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE BUGA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE FACATATIVA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE GIRARDOT'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE MONTELIBANO'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE QUIBDO'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE RIOHACHA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE SAN GIL'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 3 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE ARMENIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE CARTAGENA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE FLORENCIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE MONTERIA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE SAN GIL'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE SANTA MARTA'},
  {name: 'JUZGADO 3 ADMINISTRATIVO ORALES DE VILLAVICENCIO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE DUITAMA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE ENVIGADO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE MONTELIBANO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE PALMIRA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE PASTO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE TULUA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 3 CIVIL CIRCUITO DE YOPAL'},
  {name: 'JUZGADO 3 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 3 CIVIL MUNICIPAL DE MONTERIA'},
  {name: 'JUZGADO 3 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 3 CIVIL ORALES DE ARMENIA'},
  {name: 'JUZGADO 3 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE BUENAVENTURA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE PASTO'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 3 LABORAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 3 PENAL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 30 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 30 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 30 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 30 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 31 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 31 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 31 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 31 CIVIL MUNICIPAL DE CALI'},
  {name: 'JUZGADO 31 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 32 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 32 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 32 CIVIL MUNICIPAL DE CALI'},
  {name: 'JUZGADO 32 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 33 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 33 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 33 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 34 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 34 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 34 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 34 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 34 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 35 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 35 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 35 ADMINISTRATIVO ORALES DE BOGOTA'},
  {name: 'JUZGADO 35 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 36 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 36 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 36 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 36 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 37 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 37 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 37 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 38 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 38 ADMINISTRATIVO ORALES DE BOGOTA'},
  {name: 'JUZGADO 38 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 39 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 39 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE FLORENCIA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 4 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 4 ADMINISTRATIVO MUNICIPAL DE PEREIRA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE ARMENIA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE CARTAGENA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE SINCELEJO'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE VALLEDUPAR'},
  {name: 'JUZGADO 4 ADMINISTRATIVO ORALES DE VILLAVICENCIO'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE MONTELIBANO'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE PALMIRA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE PUERTO SANTANDER'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE SINCE'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 4 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 4 CIVIL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 4 CIVIL MUNICIPAL DE FLORIDABLANCA'},
  {name: 'JUZGADO 4 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 4 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 4 CIVIL ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 4 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 4 DE FAMILIA CIRCUITO DE PASTO'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 4 LABORAL CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 4 LABORAL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 4 PENAL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 4 PENAL MUNICIPAL DE BUCARAMANGA'},
  {name: 'JUZGADO 40 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 42 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 42 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 44 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 45 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 45 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 46 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 46 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 47 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 47 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 48 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 49 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 49 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE ARMENIA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 5 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 5 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE PEREIRA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE TUNJA'},
  {name: 'JUZGADO 5 ADMINISTRATIVO ORALES DE VALLEDUPAR'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 5 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 5 CIVIL MUNICIPAL DE PEREIRA'},
  {name: 'JUZGADO 5 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 5 LABORAL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 5 LABORAL CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 5 PENAL MUNICIPAL DE PALMIRA'},
  {name: 'JUZGADO 50 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 51 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 52 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 58 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 59 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE ARMENIA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE PEREIRA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE SANTA MARTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE SINCE'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 6 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 6 ADMINISTRATIVO MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE BOGOTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE MANIZALES'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE NEIVA'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE VALLEDUPAR'},
  {name: 'JUZGADO 6 ADMINISTRATIVO ORALES DE VILLAVICENCIO'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 6 CIVIL CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 6 CIVIL MUNICIPAL DE PALMIRA'},
  {name: 'JUZGADO 6 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 6 CIVIL ORALES DE SINCELEJO'},
  {name: 'JUZGADO 6 CIVIL typeCIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 6 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 6 LABORAL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 6 LABORAL CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 60 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 61 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 61 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 61 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 615 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 62 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 63 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 63 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 64 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 64 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 64 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE MONTERIA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE CUCUTA'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 7 ADMINISTRATIVO ORALES DE VILLAVICENCIO'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 7 CIVIL CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 7 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 7 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 7 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 7 LABORAL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 702 ADMINISTRATIVO DESCONGESTION DE IBAGUE'},
  {name: 'JUZGADO 73 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 751 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE SAN GIL'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE CUCUTA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE MANIZALES'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE POPAYAN'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE SINCELEJO'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE VALLEDUPAR'},
  {name: 'JUZGADO 8 ADMINISTRATIVO CIRCUITO DE VILLAVICENCIO'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE BARRANQUILLA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE BUCARAMANGA'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE IBAGUE'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE POPAYAN'},
  {name: 'JUZGADO 8 ADMINISTRATIVO ORALES DE SINCELEJO'},
  {name: 'JUZGADO 8 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 8 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 8 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 8 CIVIL CIRCUITO DE CARTAGENA'},
  {name: 'JUZGADO 8 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 8 CIVIL MUNICIPAL DE MEDELLIN'},
  {name: 'JUZGADO 8 CIVIL MUNICIPAL DE PEREIRA'},
  {name: 'JUZGADO 8 CIVIL MUNICIPAL DE VILLAVICENCIO'},
  {name: 'JUZGADO 8 CIVIL ORALES DE CALI'},
  {name: 'JUZGADO 8 LABORAL CIRCUITO DE CALI'},
  {name: 'JUZGADO 80 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE CALI'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE IBAGUE'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE NEIVA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE PASTO'},
  {name: 'JUZGADO 9 ADMINISTRATIVO CIRCUITO DE TUNJA'},
  {name: 'JUZGADO 9 ADMINISTRATIVO ORALES DE CALI'},
  {name: 'JUZGADO 9 ADMINISTRATIVO ORALES DE MEDELLIN'},
  {name: 'JUZGADO 9 ADMINISTRATIVO ORALES DE SINCELEJO'},
  {name: 'JUZGADO 9 CIVIL CIRCUITO DE BARRANQUILLA'},
  {name: 'JUZGADO 9 CIVIL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 9 CIVIL CIRCUITO DE BUCARAMANGA'},
  {name: 'JUZGADO 9 CIVIL CIRCUITO DE CALI'},
  {name: 'JUZGADO 9 CIVIL CIRCUITO DE MEDELLIN'},
  {name: 'JUZGADO 9 CIVIL MUNICIPAL DE BOGOTA'},
  {name: 'JUZGADO 9 CIVIL MUNICIPAL DE SANTAFE DE BOGOTA DC'},
  {name: 'JUZGADO 9 CIVIL ORALES DE MEDELLIN'},
  {name: 'JUZGADO 9 LABORAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 9 PENAL CIRCUITO DE BOGOTA'},
  {name: 'JUZGADO 903 ADMINISTRATIVO CIRCUITO DE DESCONGESTION DE FLORENCIA'},
  {name: 'JUZGADO CIVIL CIRCUITO'},
  {name: 'MINISTERIO'},
  {name: 'MINISTERIO INTERIOR'},
  {name: 'SUPERINTENDENCIA FINANCIERA'},
  {name: 'TRIBUNAL ADMINISTRATIVO'},
  {name: 'TRIBUNAL SUPERIOR'}
])
