class Aleja44 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(5652).update(id: 5652,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(20740).update(id: 20740,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(5486).update(id: 5486,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(5587).update(id: 5587,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(5546).update(id: 5546,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(5903).update(id: 5903,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(5780).update(id: 5780,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(20335).update(id: 20335,protection: ['', 'OTRO'])
    puts TypeProcess.find(20339).update(id: 20339,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(5862).update(id: 5862,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(5533).update(id: 5533,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(18023).update(id: 18023,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(5932).update(id: 5932,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(5329).update(id: 5329,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(18404).update(id: 18404,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(5445).update(id: 5445,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(11339).update(id: 11339,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(2991).update(id: 2991,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2908).update(id: 2908,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3717).update(id: 3717,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2937).update(id: 2937,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3118).update(id: 3118,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2921).update(id: 2921,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3220).update(id: 3220,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3072).update(id: 3072,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3312).update(id: 3312,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2700).update(id: 2700,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3272).update(id: 3272,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2981).update(id: 2981,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2949).update(id: 2949,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2945).update(id: 2945,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3245).update(id: 3245,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2721).update(id: 2721,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3475).update(id: 3475,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3307).update(id: 3307,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3074).update(id: 3074,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3544).update(id: 3544,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3490).update(id: 3490,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2883).update(id: 2883,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2976).update(id: 2976,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(3489).update(id: 3489,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(20846).update(id: 20846,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
  end
end
