class Aleja18 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'DEMANDADO')
    puts TypeProcess.find(18914).update(id: 18914,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18898).update(id: 18898,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18714).update(id: 18714,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18666).update(id: 18666,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18662).update(id: 18662,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18556).update(id: 18556,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18555).update(id: 18555,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18553).update(id: 18553,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18552).update(id: 18552,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18551).update(id: 18551,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18238).update(id: 18238,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18237).update(id: 18237,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18236).update(id: 18236,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18235).update(id: 18235,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(18078).update(id: 18078,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17866).update(id: 17866,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17642).update(id: 17642,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17641).update(id: 17641,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14900).update(id: 14900,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(9889).update(id: 9889,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'DEMANDADO')
    puts TypeProcess.find(9722).update(id: 9722,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9515).update(id: 9515,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9395).update(id: 9395,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8805).update(id: 8805,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8116).update(id: 8116,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'DEMANDADO')
    puts TypeProcess.find(7996).update(id: 7996,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7970).update(id: 7970,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7876).update(id: 7876,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'DEMANDADO')
    puts TypeProcess.find(7789).update(id: 7789,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(7311).update(id: 7311,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7222).update(id: 7222,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7199).update(id: 7199,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7162).update(id: 7162,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7058).update(id: 7058,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6751).update(id: 6751,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'DEMANDADO')
    puts TypeProcess.find(6514).update(id: 6514,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(286).update(id: 286,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(19750).update(id: 19750,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(19735).update(id: 19735,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(19287).update(id: 19287,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17480).update(id: 17480,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17441).update(id: 17441,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17218).update(id: 17218,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17146).update(id: 17146,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(17000).update(id: 17000,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16946).update(id: 16946,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16906).update(id: 16906,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16832).update(id: 16832,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16759).update(id: 16759,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16710).update(id: 16710,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16700).update(id: 16700,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16514).update(id: 16514,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16510).update(id: 16510,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16410).update(id: 16410,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16367).update(id: 16367,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16359).update(id: 16359,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16262).update(id: 16262,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(16254).update(id: 16254,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(15354).update(id: 15354,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(15339).update(id: 15339,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(15011).update(id: 15011,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14987).update(id: 14987,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14986).update(id: 14986,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14985).update(id: 14985,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14983).update(id: 14983,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14982).update(id: 14982,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14981).update(id: 14981,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14980).update(id: 14980,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14977).update(id: 14977,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14976).update(id: 14976,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14973).update(id: 14973,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14972).update(id: 14972,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14936).update(id: 14936,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14821).update(id: 14821,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14791).update(id: 14791,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14790).update(id: 14790,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14788).update(id: 14788,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(14663).update(id: 14663,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13938).update(id: 13938,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13912).update(id: 13912,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13907).update(id: 13907,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13906).update(id: 13906,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13860).update(id: 13860,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13807).update(id: 13807,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13806).update(id: 13806,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13799).update(id: 13799,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13798).update(id: 13798,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13797).update(id: 13797,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13796).update(id: 13796,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13795).update(id: 13795,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13794).update(id: 13794,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13793).update(id: 13793,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13777).update(id: 13777,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13716).update(id: 13716,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13702).update(id: 13702,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13701).update(id: 13701,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13696).update(id: 13696,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13636).update(id: 13636,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13629).update(id: 13629,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13617).update(id: 13617,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13616).update(id: 13616,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13605).update(id: 13605,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13587).update(id: 13587,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13569).update(id: 13569,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13561).update(id: 13561,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13556).update(id: 13556,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13534).update(id: 13534,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13530).update(id: 13530,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13524).update(id: 13524,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13523).update(id: 13523,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13504).update(id: 13504,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13503).update(id: 13503,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13500).update(id: 13500,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13490).update(id: 13490,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13423).update(id: 13423,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13422).update(id: 13422,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13412).update(id: 13412,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13389).update(id: 13389,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13387).update(id: 13387,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13386).update(id: 13386,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13385).update(id: 13385,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13381).update(id: 13381,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13378).update(id: 13378,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13375).update(id: 13375,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13374).update(id: 13374,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13370).update(id: 13370,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13337).update(id: 13337,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13333).update(id: 13333,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13304).update(id: 13304,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13296).update(id: 13296,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13289).update(id: 13289,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13280).update(id: 13280,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13256).update(id: 13256,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13225).update(id: 13225,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13222).update(id: 13222,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13202).update(id: 13202,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13191).update(id: 13191,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13168).update(id: 13168,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13134).update(id: 13134,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13133).update(id: 13133,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13129).update(id: 13129,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13120).update(id: 13120,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13108).update(id: 13108,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13107).update(id: 13107,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13106).update(id: 13106,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13101).update(id: 13101,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13097).update(id: 13097,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13096).update(id: 13096,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13064).update(id: 13064,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(13052).update(id: 13052,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'VERBAL',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12988).update(id: 12988,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12932).update(id: 12932,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12834).update(id: 12834,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12671).update(id: 12671,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12429).update(id: 12429,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12424).update(id: 12424,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12421).update(id: 12421,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12417).update(id: 12417,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12401).update(id: 12401,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12399).update(id: 12399,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12396).update(id: 12396,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12392).update(id: 12392,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12391).update(id: 12391,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12388).update(id: 12388,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12384).update(id: 12384,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12375).update(id: 12375,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12373).update(id: 12373,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12363).update(id: 12363,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12362).update(id: 12362,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12359).update(id: 12359,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12358).update(id: 12358,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12357).update(id: 12357,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12356).update(id: 12356,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12353).update(id: 12353,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12349).update(id: 12349,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12343).update(id: 12343,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12342).update(id: 12342,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12329).update(id: 12329,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(12328).update(id: 12328,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10729).update(id: 10729,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10706).update(id: 10706,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10693).update(id: 10693,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10689).update(id: 10689,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10664).update(id: 10664,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10612).update(id: 10612,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10569).update(id: 10569,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10518).update(id: 10518,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10516).update(id: 10516,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10510).update(id: 10510,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10506).update(id: 10506,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10505).update(id: 10505,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10504).update(id: 10504,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10503).update(id: 10503,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10502).update(id: 10502,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10501).update(id: 10501,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10500).update(id: 10500,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10499).update(id: 10499,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10494).update(id: 10494,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(10230).update(id: 10230,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(9609).update(id: 9609,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9602).update(id: 9602,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9600).update(id: 9600,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9598).update(id: 9598,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9570).update(id: 9570,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9502).update(id: 9502,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9474).update(id: 9474,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9448).update(id: 9448,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9438).update(id: 9438,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9437).update(id: 9437,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9436).update(id: 9436,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9435).update(id: 9435,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9433).update(id: 9433,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9398).update(id: 9398,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9347).update(id: 9347,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9262).update(id: 9262,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9244).update(id: 9244,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'DEMANDADO')
    puts TypeProcess.find(9240).update(id: 9240,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9236).update(id: 9236,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9203).update(id: 9203,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9199).update(id: 9199,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9195).update(id: 9195,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9191).update(id: 9191,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9190).update(id: 9190,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9182).update(id: 9182,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9181).update(id: 9181,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9172).update(id: 9172,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9170).update(id: 9170,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9111).update(id: 9111,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9096).update(id: 9096,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9033).update(id: 9033,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9010).update(id: 9010,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8846).update(id: 8846,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8837).update(id: 8837,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8683).update(id: 8683,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8682).update(id: 8682,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'NO PRESENTA')
    puts TypeProcess.find(8660).update(id: 8660,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8549).update(id: 8549,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8375).update(id: 8375,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8362).update(id: 8362,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8350).update(id: 8350,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8336).update(id: 8336,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8332).update(id: 8332,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8286).update(id: 8286,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8285).update(id: 8285,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8151).update(id: 8151,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(8117).update(id: 8117,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'DEMANDADO')
    puts TypeProcess.find(7960).update(id: 7960,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7930).update(id: 7930,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPETICION',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7894).update(id: 7894,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7893).update(id: 7893,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7890).update(id: 7890,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'DEMANDADO')
    puts TypeProcess.find(7784).update(id: 7784,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7688).update(id: 7688,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7687).update(id: 7687,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7643).update(id: 7643,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7642).update(id: 7642,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7641).update(id: 7641,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7640).update(id: 7640,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7639).update(id: 7639,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7588).update(id: 7588,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7425).update(id: 7425,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'DEMANDADO')
    puts TypeProcess.find(7181).update(id: 7181,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7142).update(id: 7142,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7109).update(id: 7109,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(7031).update(id: 7031,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6953).update(id: 6953,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6828).update(id: 6828,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6827).update(id: 6827,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6801).update(id: 6801,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPETICION',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6715).update(id: 6715,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6607).update(id: 6607,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6555).update(id: 6555,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6439).update(id: 6439,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO',link_type: 'DEMANDADO')
    puts TypeProcess.find(6438).update(id: 6438,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6388).update(id: 6388,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6284).update(id: 6284,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6283).update(id: 6283,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6282).update(id: 6282,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6270).update(id: 6270,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6251).update(id: 6251,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6204).update(id: 6204,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6116).update(id: 6116,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6102).update(id: 6102,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6090).update(id: 6090,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDADO')
    puts TypeProcess.find(6087).update(id: 6087,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6058).update(id: 6058,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6054).update(id: 6054,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6053).update(id: 6053,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6052).update(id: 6052,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(6051).update(id: 6051,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5223).update(id: 5223,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5193).update(id: 5193,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5122).update(id: 5122,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5093).update(id: 5093,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5037).update(id: 5037,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'DEMANDADO')
    puts TypeProcess.find(4207).update(id: 4207,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4201).update(id: 4201,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4199).update(id: 4199,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4198).update(id: 4198,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO',link_type: 'DEMANDADO')
    puts TypeProcess.find(4197).update(id: 4197,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4196).update(id: 4196,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4192).update(id: 4192,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4183).update(id: 4183,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4179).update(id: 4179,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4178).update(id: 4178,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4161).update(id: 4161,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4157).update(id: 4157,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4155).update(id: 4155,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4138).update(id: 4138,process_class: 'JURISDICCION LABORAL',subprocess_class: 'ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4121).update(id: 4121,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4119).update(id: 4119,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4103).update(id: 4103,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'NULIDAD Y RESTABLECIMIENTO DEL DERECHO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4096).update(id: 4096,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(4082).update(id: 4082,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4075).update(id: 4075,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4073).update(id: 4073,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4072).update(id: 4072,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDANTE')
    puts TypeProcess.find(4067).update(id: 4067,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'CONTROVERSIAS CONTRACTUALES',link_type: 'DEMANDANTE')
    puts TypeProcess.find(2548).update(id: 2548,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2544).update(id: 2544,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2531).update(id: 2531,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2530).update(id: 2530,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2520).update(id: 2520,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2515).update(id: 2515,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2513).update(id: 2513,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2507).update(id: 2507,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2504).update(id: 2504,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2496).update(id: 2496,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2490).update(id: 2490,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2474).update(id: 2474,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2469).update(id: 2469,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2466).update(id: 2466,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2464).update(id: 2464,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2456).update(id: 2456,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2452).update(id: 2452,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2442).update(id: 2442,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2428).update(id: 2428,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2423).update(id: 2423,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2421).update(id: 2421,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2418).update(id: 2418,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2415).update(id: 2415,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2408).update(id: 2408,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2383).update(id: 2383,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2372).update(id: 2372,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(390).update(id: 390,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(290).update(id: 290,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(122).update(id: 122,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDADO')
    puts TypeProcess.find(95).update(id: 95,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
  end
end
