class Al05 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(95).update(id: 95,office_name: 'JUZGADO 001 ADMINISTRATIVO DE PEREIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(286).update(id: 286,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2408).update(id: 2408,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2423).update(id: 2423,office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO DE PEREIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2452).update(id: 2452,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2464).update(id: 2464,office_name: 'JUZGADO 001 ADMINISTRATIVO DE CARTAGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2469).update(id: 2469,office_name: 'JUZGADO 001 ADMINISTRATIVO DE PEREIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2515).update(id: 2515,office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO DE PEREIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2548).update(id: 2548,office_name: 'JUZGADO 001 ADMINISTRATIVO DE CARTAGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4067).update(id: 4067,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4072).update(id: 4072,office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE AIPE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4073).update(id: 4073,office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE IQUIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4082).update(id: 4082,office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE GUADALUPE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4096).update(id: 4096,office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE PALERMO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4103).update(id: 4103,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4119).update(id: 4119,office_name: 'JUZGADO 001 CIVIL MUNICIPAL DE GARZON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4157).update(id: 4157,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4161).update(id: 4161,office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE IQUIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4197).update(id: 4197,office_name: 'JUZGADO 001 ADMINISTRATIVO DE NEIVA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5037).update(id: 5037,office_name: 'DESPACHO 001 DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE MANIZALES ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5093).update(id: 5093,office_name: 'DESPACHO 001 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE IBAGUE ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5122).update(id: 5122,office_name: 'DESPACHO 001 DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE IBAGUE ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5223).update(id: 5223,office_name: 'DESPACHO 001 DE LA SALA DE CASACION LABORAL DE LA CORTE SUPREMA DE JUSTICIA   ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5901).update(id: 5901,office_name: 'FISCALIA SECCIONAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6270).update(id: 6270,office_name: 'JUZGADO 001 ADMINISTRATIVO DE NEIVA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6284).update(id: 6284,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6514).update(id: 6514,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6715).update(id: 6715,office_name: 'DESPACHO 001  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6751).update(id: 6751,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6801).update(id: 6801,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7058).update(id: 7058,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7109).update(id: 7109,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7162).update(id: 7162,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7222).update(id: 7222,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7311).update(id: 7311,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7588).update(id: 7588,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7639).update(id: 7639,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7687).update(id: 7687,office_name: 'JUZGADO 001 ADMINISTRATIVO DE FLORENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7688).update(id: 7688,office_name: 'JUZGADO 001 ADMINISTRATIVO DE FLORENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7876).update(id: 7876,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7890).update(id: 7890,office_name: 'JUZGADO 001 ADMINISTRATIVO DE FLORENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7930).update(id: 7930,office_name: 'JUZGADO 001 ADMINISTRATIVO DE FLORENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7960).update(id: 7960,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7996).update(id: 7996,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8116).update(id: 8116,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8151).update(id: 8151,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8682).update(id: 8682,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9096).update(id: 9096,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9172).update(id: 9172,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9181).update(id: 9181,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9203).update(id: 9203,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9240).update(id: 9240,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9347).update(id: 9347,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9435).update(id: 9435,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9438).update(id: 9438,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9515).update(id: 9515,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9570).update(id: 9570,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9722).update(id: 9722,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,office_name: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16478).update(id: 16478,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19102).update(id: 19102,office_name: '001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20462).update(id: 20462,office_name: 'JUZGADO 011 ADMINISTRATIVO DE MEDELLIN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,office_name: 'JUZGADO 003 ADMINISTRATIVO DE QUIBDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,office_name: 'JUZGADO 001 ADMINISTRATIVO DE QUIBDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO ESPECIALIZADO EN RESTITUCION DE TIERRAS DE QUIBDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO DE QUIBDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,office_name: 'JUZGADO 001 CIVIL MUNICIPAL DE QUIBDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
