class Aleja39 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(5652).update(id: 5652,passive_part: 'CONCESION TUNEL ABURRA-ORIENTE S-A')
    puts TypeProcess.find(20740).update(id: 20740,passive_part: 'DEPARTAMENTO DE CAQUETA')
    puts TypeProcess.find(5486).update(id: 5486,passive_part: 'ESE HOSPITAL DEL SUR GABRIEL JARAMILLO PIEDRAHITA')
    puts TypeProcess.find(5587).update(id: 5587,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO-INPEC-')
    puts TypeProcess.find(20127).update(id: 20127,passive_part: 'HOSPITAL EL TUNAL')
    puts TypeProcess.find(5546).update(id: 5546,passive_part: 'ESE HOSPITAL MARCO FIDEL SUAREZ DE BELLO')
    puts TypeProcess.find(5903).update(id: 5903,passive_part: 'ESE HOSPITAL LA INMACULADA DE GUATAPE Y ESE HOSPITAL SAN JUAN DE DIOS DE RIONEGRO')
    puts TypeProcess.find(5780).update(id: 5780,passive_part: 'COMFENALCO')
    puts TypeProcess.find(20193).update(id: 20193,passive_part: 'EMCALI')
    puts TypeProcess.find(20194).update(id: 20194,passive_part: 'MUNICPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(20335).update(id: 20335,passive_part: 'LA PREVISORA S A ')
    puts TypeProcess.find(20339).update(id: 20339,passive_part: 'TRANSMAMONAL SAS')
    puts TypeProcess.find(2852).update(id: 2852,passive_part: 'NACION MINISTERIO DE AGRICULTURA')
    puts TypeProcess.find(5862).update(id: 5862,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO-INPEC-')
    puts TypeProcess.find(5533).update(id: 5533,passive_part: 'JHON JAIRO FLOREZ SERNA')
    puts TypeProcess.find(18023).update(id: 18023,passive_part: 'RAMIRO ANTONIO NAVIA DIAZ - JOSE FERNEY PEREZ - ESTEFANIA DEL PILAR SANCHEZ CANAS - CARLOS ALBERTO S')
    puts TypeProcess.find(5932).update(id: 5932,passive_part: 'ESE HOSPITAL SAN JOSE DE SALGAR Y OTROS')
    puts TypeProcess.find(21142).update(id: 21142,passive_part: 'PREVISORA SA ')
    puts TypeProcess.find(5329).update(id: 5329,passive_part: 'ESE HOSPITAL GENERAL DE MEDELLIN')
    puts TypeProcess.find(18404).update(id: 18404,passive_part: 'HERMEREGILDO BENACHI BELLO - JUAN MANUEL CHAVES MARTINEZ')
    puts TypeProcess.find(5445).update(id: 5445,passive_part: 'ESE HOSPITAL MARCO FIDEL SUAREZ DE BELLO')
    puts TypeProcess.find(11339).update(id: 11339,passive_part: 'JESUS HERNAN GUEVARA  - LUIS ALBEIRO VILLAQUIRAN BURBANO')
    puts TypeProcess.find(2991).update(id: 2991,passive_part: 'EMCALI')
    puts TypeProcess.find(2908).update(id: 2908,passive_part: 'INPEC')
    puts TypeProcess.find(3717).update(id: 3717,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(2937).update(id: 2937,passive_part: 'LUIS FELIPE MUNOS REINOSA')
    puts TypeProcess.find(3118).update(id: 3118,passive_part: 'INPEC')
    puts TypeProcess.find(2921).update(id: 2921,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3220).update(id: 3220,passive_part: 'DEPARTAMENTO DEL VALLE DEL CAUCA')
    puts TypeProcess.find(9230).update(id: 9230,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3072).update(id: 3072,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3312).update(id: 3312,passive_part: 'HOSPITAL DIVINO NINO DE BUGA')
    puts TypeProcess.find(2700).update(id: 2700,passive_part: 'HOSPITAL SUSANA LOPEZ DE VALENCIA Y OTROS')
    puts TypeProcess.find(3272).update(id: 3272,passive_part: 'MUNICIPIO DE YUMBO')
    puts TypeProcess.find(2981).update(id: 2981,passive_part: ' MUNICIPIO DE CALI')
    puts TypeProcess.find(2949).update(id: 2949,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(2945).update(id: 2945,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3245).update(id: 3245,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(2721).update(id: 2721,passive_part: 'ESE NORTE TRES DEL CAUCA Y IPS')
    puts TypeProcess.find(3475).update(id: 3475,passive_part: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE')
    puts TypeProcess.find(3307).update(id: 3307,passive_part: 'INPEC')
    puts TypeProcess.find(3074).update(id: 3074,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3544).update(id: 3544,passive_part: 'HOSPITAL UNIVERSITARIO DEL VALLE')
    puts TypeProcess.find(3490).update(id: 3490,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(2883).update(id: 2883,passive_part: 'EMCALI')
    puts TypeProcess.find(2976).update(id: 2976,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI')
    puts TypeProcess.find(3489).update(id: 3489,passive_part: 'NACION Y OTROS')
    puts TypeProcess.find(20846).update(id: 20846,passive_part: 'RED DE SALUD DE ORIENTE ESE Y OTROS')
  end
end
