class Aleja56 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(5265).update(id: 5265,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9524).update(id: 9524,passive_part: 'DIRECCION TERRITORIAL DE SALUD DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9837).update(id: 9837,passive_part: 'MUNICIPIO DE MANIZALES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5639).update(id: 5639,passive_part: 'ESE HOSPITAL MANUEL URIBE ANGEL DE ENVIGADO Y OTRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5460).update(id: 5460,passive_part: 'HOSPITAL MARCO FIDEL SUAREZ DE BELLO Y OTRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5929).update(id: 5929,passive_part: 'ESE HOSPITAL MANUEL URIBE ANGEL DE ENVIGADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11250).update(id: 11250,passive_part: 'AMIN CASTRO IBANEZ ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11225).update(id: 11225,passive_part: 'ELKIN EMILIO MARTINEZ MESA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11254).update(id: 11254,passive_part: 'IRMA LOPEZ HENAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10794).update(id: 10794,passive_part: 'GUSTAVO FRANCISCO PETRO URREGO-DIEGO FERNANDO BRAVO BORDA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20372).update(id: 20372,passive_part: 'ALFONSO MARIA LIBORIO ALVARADO LOPEZ-HECTOR RAUL FRANCO ROA-HECTOR MANUEL CAMANO CHACON',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20370).update(id: 20370,passive_part: 'NELSON VIVAS MORA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11673).update(id: 11673,passive_part: 'MARIA INES OSORIO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9981).update(id: 9981,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20169).update(id: 20169,passive_part: 'LEONARDO CRUZ GARCIA CAMILO ANDRES GARZON CONSORCIO JULIO FLOREZ JULIAN DANIEL MOLANO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20163).update(id: 20163,passive_part: 'WILAMAR ROA MALAGON OMAR MAURICIO CARDENAS COLORADO CARLOS ENRIQUE CARVAJALINO MARIAM ALEJANDRA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20071).update(id: 20071,passive_part: 'CARLOS EDUARDO CAICEDO-PABLO JOSE LACOUTUR-RAFAEL ALEJANDRO MARTINEZ-SANDER ALONSO RODRIGUEZ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(366).update(id: 366,passive_part: 'ALAN EDMUNDO JARA-CLAUDIA MARCELA AMAYA-RICARDO RODRIGUEZ HENAO-IVAN CORTES LOSADA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20067).update(id: 20067,passive_part: 'SONIA BETTY RINCON-PATRICIA GOMEZ CUERVO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14621).update(id: 14621,passive_part: 'ALAN EDMUNDO JARA URZOLA - LUZ STELLA CASASFRANCO VANEGAS - HERNANDO MARTINEZ AGUILERA-JAIRO CARRENO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13668).update(id: 13668,passive_part: 'JAIME GUZMAN ROJAS-JHON JADER ROMERO RIVERA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20274).update(id: 20274,passive_part: 'ESE HOSPITAL SAN VICENTE DE PAUL DE LORICA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20172).update(id: 20172,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI - FRANKLIN CAICEDO BONILLA Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20044).update(id: 20044,passive_part: 'HOSPITAL UNIVERSITARIO DEL VALLE - EVARISTO GARCIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12005).update(id: 12005,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10570).update(id: 10570,passive_part: 'VIRGILIO GUTIERREZ - JUAN DE JESUS BABATIVA - CARLOS ANDRES CARDENAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10636).update(id: 10636,passive_part: 'JAIME ALBORNOZ RIVAS - FREDDY MENA CORDOBA - BARTOLO VALENCIA RAMOS - JOSE OCORO - CARLOS MORENO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10596).update(id: 10596,passive_part: 'NESTOR GARCIA BUITRAGO - SANDRA JABER MARTINEZ - CAMILO QUIROGA MORA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20125).update(id: 20125,passive_part: 'ESE SAN JUAN DE DIOS DE YARUMAL ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9458).update(id: 9458,passive_part: 'COSMITET LTDA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20042).update(id: 20042,passive_part: 'EMCALI Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20200).update(id: 20200,passive_part: 'EMCALI Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20196).update(id: 20196,passive_part: 'HOSPITAL CARLOS HOLMES TRUJILLO ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8401).update(id: 8401,passive_part: 'IPS UNIVERSITARIA SERVICIOS DE SALUD UNIVERSIDAD DE ANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20199).update(id: 20199,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(35).update(id: 35,passive_part: 'MUNICIPIO DE MANIZALES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(124).update(id: 124,passive_part: 'HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOFIA DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20173).update(id: 20173,passive_part: ' LA PREVISORA SA COMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7874).update(id: 7874,passive_part: 'ESE HOSPITAL SAN RAFAEL DE ITAGUI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20309).update(id: 20309,passive_part: 'CEDENAR ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20244).update(id: 20244,passive_part: 'DEPARTAMENTO DE PUTUMAYO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11326).update(id: 11326,passive_part: 'ENELIA SALINAS CHIVATA -  XIOMARA YAMILE CHANTRE-TELESFORO CAMPO CUETIA-INVERSIONES CIPE COLOMBIA SA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20345).update(id: 20345,passive_part: 'CORPORACION AUTONOMA REGIONAL DE RISARALDA CARDER',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20189).update(id: 20189,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(1717).update(id: 1717,passive_part: 'HOSPITAL ENGATIVA II NIVEL ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20406).update(id: 20406,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8239).update(id: 8239,passive_part: 'FUNDACION HOSPITAL SAN PEDRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20281).update(id: 20281,passive_part: 'COMFAMILIAR DE NARINO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8241).update(id: 8241,passive_part: 'PASTO SALUD ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8130).update(id: 8130,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(32).update(id: 32,passive_part: 'HOSPITAL UNIVERSITARIO DEPARTAMENTAL DE NARINO ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8083).update(id: 8083,passive_part: 'HOSPITAL UNIVERSITARIO DEPARTAMENTAL DE NARINO ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8403).update(id: 8403,passive_part: 'CENTRALES ELECTRICAS DE NARINO SA ESP',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8142).update(id: 8142,passive_part: 'HOSPITAL EDUARDO SANTOS DE LA UNION ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8250).update(id: 8250,passive_part: 'FUNDACION HOSPITAL SAN PEDRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(16067).update(id: 16067,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14798).update(id: 14798,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(15794).update(id: 15794,passive_part: 'MUNICIPIO DE ALBANIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11436).update(id: 11436,passive_part: 'MUNICIPIO DE BARRANCAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14160).update(id: 14160,passive_part: 'MUNICIPIO DE HATONUEVO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14346).update(id: 14346,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14878).update(id: 14878,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13428).update(id: 13428,passive_part: 'MUNICIPIO DE URIBIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13147).update(id: 13147,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13208).update(id: 13208,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(16150).update(id: 16150,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12989).update(id: 12989,passive_part: 'MUNICIPIO DE URIBIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(15814).update(id: 15814,passive_part: 'DISTRITO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14880).update(id: 14880,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14879).update(id: 14879,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(16115).update(id: 16115,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(15775).update(id: 15775,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(15750).update(id: 15750,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(14789).update(id: 14789,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(15287).update(id: 15287,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11429).update(id: 11429,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11427).update(id: 11427,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11432).update(id: 11432,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11431).update(id: 11431,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11430).update(id: 11430,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11470).update(id: 11470,passive_part: 'MUNICIPIO DE ALBANIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11480).update(id: 11480,passive_part: 'DEPARTAMENTO DE LA GUAJIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11451).update(id: 11451,passive_part: 'MUNICIPIO DE HATONUEVO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11479).update(id: 11479,passive_part: 'MUNICIPIO DE URIBIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11465).update(id: 11465,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11466).update(id: 11466,passive_part: 'MUNICIPIO DE URIBIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11469).update(id: 11469,passive_part: 'MUNICIPIO DE URIBIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11447).update(id: 11447,passive_part: 'MUNICIPIO DE BARRANCAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11435).update(id: 11435,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11449).update(id: 11449,passive_part: 'MUNICIPIO DE SAN JUAN DEL CESAR',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11444).update(id: 11444,passive_part: 'MUNICIPIO DE RIOHACHA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11439).update(id: 11439,passive_part: 'MUNICIPIO DE MAICAO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11460).update(id: 11460,passive_part: 'MUNICIPIO DE BARRANCAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12626).update(id: 12626,passive_part: 'IE PLAYA RICA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12459).update(id: 12459,passive_part: 'IE PLAYA RICA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12707).update(id: 12707,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12477).update(id: 12477,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12715).update(id: 12715,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12722).update(id: 12722,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12580).update(id: 12580,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12495).update(id: 12495,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12496).update(id: 12496,passive_part: 'MUNICIPIO DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(11468).update(id: 11468,passive_part: 'EMPRESA DE DESARROLLO URBANO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12456).update(id: 12456,passive_part: 'DEPARTAMENTO ADMINISTRATIVO DE PLANEACION DE MEDELLIN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12732).update(id: 12732,passive_part: 'MUNICIPIO DE SANTA ROSA DE OSOS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12593).update(id: 12593,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12446).update(id: 12446,passive_part: 'MUNICIPIO DE TARAZA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12741).update(id: 12741,passive_part: 'CORANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12583).update(id: 12583,passive_part: 'MUNICIPIO DE YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12558).update(id: 12558,passive_part: 'MUNICIPIO DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12582).update(id: 12582,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(332).update(id: 332,passive_part: 'MUNICIPIO DE NECOCLI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(336).update(id: 336,passive_part: 'MUNICIPIO DE YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(348).update(id: 348,passive_part: 'DIAN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12591).update(id: 12591,passive_part: 'MUNICIPIO DE CHIGORODO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12441).update(id: 12441,passive_part: 'MUNICIPIO DE DABEIBA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12740).update(id: 12740,passive_part: 'CORANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12469).update(id: 12469,passive_part: 'MUNICIPIO DE ENVIGADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12573).update(id: 12573,passive_part: 'MUNICIPIO DE OLAYA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12692).update(id: 12692,passive_part: 'CORPOURABA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12485).update(id: 12485,passive_part: 'MUNICIPIO DE ENVIGADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12541).update(id: 12541,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12638).update(id: 12638,passive_part: 'MUNICIPIO DE ENVIGADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12555).update(id: 12555,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12783).update(id: 12783,passive_part: 'CORNARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12550).update(id: 12550,passive_part: 'MUNICIPIO DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12542).update(id: 12542,passive_part: 'MUNICIPIO DE VEGACHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12518).update(id: 12518,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12452).update(id: 12452,passive_part: 'MUNICIPIO DE SABANALARGA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12772).update(id: 12772,passive_part: 'MUNICIPIO DE YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13466).update(id: 13466,passive_part: 'MUNICIPIO DE CONCORDIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12662).update(id: 12662,passive_part: 'ESE HOSPITAL LA MISERICORDIA DE NECHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12760).update(id: 12760,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12618).update(id: 12618,passive_part: 'ESE HOSPITAL LA ESTRELLA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12605).update(id: 12605,passive_part: 'ESE HOSPITAL SAN SEBASTIAN DE URABA DE NECOCLI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12719).update(id: 12719,passive_part: 'ESE HOSPITAL FRANCISCO VALDERRAMA DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12726).update(id: 12726,passive_part: 'MUNICIPIO DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12468).update(id: 12468,passive_part: 'MUNICIPIO DE COPACABANA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12464).update(id: 12464,passive_part: 'MUNICIPIO DE LA ESTRELLA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12701).update(id: 12701,passive_part: 'ESE HOSPITAL SAN MARTIN DE PORRES DEL MUNICIPIO DE ARMENIA MANTEQUILLA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12494).update(id: 12494,passive_part: 'MUNICIPIO DE VIGIA DEL FUERTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12508).update(id: 12508,passive_part: 'MUNICIPIO DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12796).update(id: 12796,passive_part: 'ESE DEL MUNICIPIO DE ARBOLETES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12759).update(id: 12759,passive_part: 'MUNICIPIO DE CONCEPCION',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12523).update(id: 12523,passive_part: 'MUNICIPIO DE HISPANIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12729).update(id: 12729,passive_part: 'MUNICIPIO DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12570).update(id: 12570,passive_part: 'MUNICIPIO OLAYA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12486).update(id: 12486,passive_part: 'EMPRESA AUTONOMA DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12487).update(id: 12487,passive_part: 'EMPRESA AUTONOMA DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12503).update(id: 12503,passive_part: 'MUNICIPIO DE VEGACHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12747).update(id: 12747,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12669).update(id: 12669,passive_part: 'MUNICIPIO DE OLAYA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12761).update(id: 12761,passive_part: 'ESE HOSPITAL DEL MUNCIPIO DE SAN ROQUE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12595).update(id: 12595,passive_part: 'MUNICIPIO DE CARACOLI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12540).update(id: 12540,passive_part: 'MUNICIPIO DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12475).update(id: 12475,passive_part: 'MUNICIPIO DE CAMPAMENTO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12721).update(id: 12721,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10950).update(id: 10950,passive_part: 'MUNICIPIO DE DABEIBA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12575).update(id: 12575,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12455).update(id: 12455,passive_part: 'MUNICIPIO DE PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12604).update(id: 12604,passive_part: 'MUNICIPIO DE CONCEPCION',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12525).update(id: 12525,passive_part: 'MUNICIPIO DE SAN ANDRES DE CUERQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12735).update(id: 12735,passive_part: 'MUNICIPIO DE GIRARDOTA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12597).update(id: 12597,passive_part: 'MUNICIPIO DE SAN ROQUE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12665).update(id: 12665,passive_part: 'ESP DEL MUNICIPIO DE LA CEJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12517).update(id: 12517,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12549).update(id: 12549,passive_part: 'MUNICIPIO DE SOPETRAN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(347).update(id: 347,passive_part: 'MUNICIPIO DE JERICO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13936).update(id: 13936,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13424).update(id: 13424,passive_part: 'ESE HOSPITAL LA MISERICORDIA DE NECHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12585).update(id: 12585,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12526).update(id: 12526,passive_part: 'EMPRESA DE VIVIENDA DE ANTIOQUIA - VIVA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12532).update(id: 12532,passive_part: 'MUNICIPIO DE AMALFI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12720).update(id: 12720,passive_part: 'AREA METROPOLITANA DEL VALLE DE ABURRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12672).update(id: 12672,passive_part: 'ESE HOSPITAL SAN VICENTE DE PAUL DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12524).update(id: 12524,passive_part: 'MUNICIPIO DE SOPETRAN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12531).update(id: 12531,passive_part: 'MUNICIPIO DE SOPETRAN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12622).update(id: 12622,passive_part: 'ESE HOSPITAL SAN FRANCISCO DE ASIS DE ANZA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12589).update(id: 12589,passive_part: 'MUNICIPIO DE VEGACHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12599).update(id: 12599,passive_part: 'SAN FRANCISCO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12630).update(id: 12630,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12764).update(id: 12764,passive_part: 'YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12556).update(id: 12556,passive_part: 'TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12670).update(id: 12670,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE SANTA FE DE ANTIOQUIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12449).update(id: 12449,passive_part: 'TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12563).update(id: 12563,passive_part: 'TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12572).update(id: 12572,passive_part: 'TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12655).update(id: 12655,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE SANTA FE DE ANTIOQUIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12635).update(id: 12635,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE NECHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12621).update(id: 12621,passive_part: 'ESE HOSPITAL DE ABEJORRAL',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12581).update(id: 12581,passive_part: 'ESE HOSPITAL DE PUERTO TRIUNFO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12686).update(id: 12686,passive_part: 'TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12734).update(id: 12734,passive_part: 'CONCORDIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12565).update(id: 12565,passive_part: 'MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12793).update(id: 12793,passive_part: 'CAROLINA DEL PRINCIPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12724).update(id: 12724,passive_part: 'MONTEBELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12617).update(id: 12617,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE PEQUE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12789).update(id: 12789,passive_part: 'ESE HOSPITAL SAN VICENTE DE PAUL',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12610).update(id: 12610,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12611).update(id: 12611,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12612).update(id: 12612,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12620).update(id: 12620,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12694).update(id: 12694,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12601).update(id: 12601,passive_part: 'PUERTO NARE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12462).update(id: 12462,passive_part: 'ESP DEL MUNICIPIO DE REMEDIOS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12699).update(id: 12699,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12627).update(id: 12627,passive_part: 'MUNICIPIO DE CIUDAD BOLIVAR',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12482).update(id: 12482,passive_part: 'MUNICIPIO DE REMEDIOS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12490).update(id: 12490,passive_part: 'MUNICIPIO DE REMEDIOS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12649).update(id: 12649,passive_part: 'ESP DEL MUNICIPIO DE CARACOLI ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12714).update(id: 12714,passive_part: 'MUNICIPIO DE REMEDIOS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12710).update(id: 12710,passive_part: 'MUNICIPIO DE REMEDIOS ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12678).update(id: 12678,passive_part: 'MUNICIPIO DE SANTA FE DE ANTIOQUIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12461).update(id: 12461,passive_part: 'MUNICIPIO DE DABEIBA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12561).update(id: 12561,passive_part: 'MUNICIPIO DE SANTA FE DE ANTIOQUIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12613).update(id: 12613,passive_part: 'MUNICIPIO DE SAN PEDRO DE URABA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12507).update(id: 12507,passive_part: 'ESE HOSPITAL SAN ANTONIO DEL MUNICIPIO DE BETANIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12467).update(id: 12467,passive_part: 'MUNICIPIO DE FRONTINO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12636).update(id: 12636,passive_part: 'MUNICIPIO DE FRONTINO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12473).update(id: 12473,passive_part: 'MUNICIPIO DE LA CEJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12474).update(id: 12474,passive_part: 'MUNICIPIO DE LA CEJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12684).update(id: 12684,passive_part: 'INDEPORTES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12628).update(id: 12628,passive_part: 'MUNICIPIO DE GUARNE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12650).update(id: 12650,passive_part: 'ESP DEL MUNICIPIO DE GUATAPE ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12680).update(id: 12680,passive_part: 'ESE HOSPITAL MARCO A CARDONA DEL MUNICIPIO DE MACEO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12769).update(id: 12769,passive_part: 'ESE HOSPITAL SAN ANTONIO DEL MUNICIPIO DE CISNEROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12731).update(id: 12731,passive_part: 'MUNICIPIO DE SOPETRAN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12753).update(id: 12753,passive_part: 'MUNICIPIO DE CARACOLI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12744).update(id: 12744,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12660).update(id: 12660,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12676).update(id: 12676,passive_part: 'MUNICIPIO DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12756).update(id: 12756,passive_part: 'MUNICIPIO DE YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12763).update(id: 12763,passive_part: 'MUNICIPIO DE YONDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12675).update(id: 12675,passive_part: 'MUNICIPIO DE NECHI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12785).update(id: 12785,passive_part: 'MUNICIPIO DE SAN FRANCISCO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12632).update(id: 12632,passive_part: 'MUNICIPIO DE CAUCASIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12771).update(id: 12771,passive_part: 'MUNICIPIO DE SAN PEDRO DE URABA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12569).update(id: 12569,passive_part: 'MUNICIPIO DE SAN JUAN DE URABA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12647).update(id: 12647,passive_part: 'MUNICIPIO DE CAMPAMENTO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12812).update(id: 12812,passive_part: 'MUNICIPIO DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12805).update(id: 12805,passive_part: 'MUNICIPIO DE GUATAPE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12695).update(id: 12695,passive_part: 'MUNICIPIO DE SAN LUIS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12516).update(id: 12516,passive_part: 'MUNICIPIO DE LA CEJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12640).update(id: 12640,passive_part: 'MUNICIPIO DE SANTA ROSA DE OSOS ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12778).update(id: 12778,passive_part: 'ESE HOSPITAL FRANCISCO VALDERRAMA DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12639).update(id: 12639,passive_part: 'MUNICIPIO DE GIRARDOTA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12733).update(id: 12733,passive_part: 'MUNICIPIO DE CONCORDIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12590).update(id: 12590,passive_part: 'MUNICIPIO DE ARMENIA MANTEQUILLA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12463).update(id: 12463,passive_part: 'INSTITUTO MUNICIPAL D RECREACION Y DEPORTES DE ARBOLETES ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12748).update(id: 12748,passive_part: 'ESE HOSPITAL NUEVO HORIZONTE DE ABRIAQUI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12654).update(id: 12654,passive_part: 'ESE HOSPITAL FRANCISCO VALDERRAMA DE TURBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12579).update(id: 12579,passive_part: 'MUNICIPIO DE SAN PEDRO DE URABA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12603).update(id: 12603,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS DEL MUNICIPIO DE MARINILLA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6799).update(id: 6799,passive_part: 'CAPRECOM EPS  GAVAVISION',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7782).update(id: 7782,passive_part: 'JOSE ERLIN MURILLO SEGUROS GENERALES SURAMERICANA  LA PREVISORA SACOMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8040).update(id: 8040,passive_part: 'FONDO PRESTACIONES SOCIALES DEL MAGISTERIO Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9258).update(id: 9258,passive_part: 'CAPRECOM EPS CAPRECOM IPS CLINICA QUIBDO ESEHOSPITAL ISMAEL ROLDAN DE QUIBDO ESEHOSPITAL GENERAL DE MEDELLIN HOSPITAL UNIVERSITARIO SAN VICENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7849).update(id: 7849,passive_part: 'MUNICIPO ALTO BAUDO FUNDACION SOLIDARIA DE SALUD DEL BAJO BAUDO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7706).update(id: 7706,passive_part: 'GAVAVISION UNIDAD DE ESPECIALISTAS SASCAPRECOM EPSCAPRECOM IPSNACION MINISTERIO DE SALUD Y PROTECCION SOCIAL ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7095).update(id: 7095,passive_part: 'HOSPITAL PABLO TOBON URIBE-MINISTERIO DE DEFENSA NACIONAL',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9750).update(id: 9750,passive_part: 'INPEC MUNICIPIO DE QUIBDO MINISTERIO DE JUSTICIA Y DEL DERECHO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9556).update(id: 9556,passive_part: 'ESEHOSPITAL SAN FRANCISCO DE ASIS ESEHOSPITAL SAN JOSE DE TADO LA PREVISORA SA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9538).update(id: 9538,passive_part: 'INPEC NACION - RAMA JUDICIAL CAPRECOM EPS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9359).update(id: 9359,passive_part: 'NACION- HOSPITAL SAN ROQUE CARMEN DE ATRATO Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9112).update(id: 9112,passive_part: 'INPEC MINISTRO DE JUSTICIA Y DEL DERECHO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8902).update(id: 8902,passive_part: 'ICBF FUSI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8854).update(id: 8854,passive_part: 'TRANSPORTES PROGRESO DEL CHOCO Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5576).update(id: 5576,passive_part: 'DISTRIBUIDORA DEL PACIFICO SA ESP  ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9178).update(id: 9178,passive_part: 'ESE HOSPITAL DE MAICAO - NACION - MINISTERIO DE SALUD - GOBERNACION DEL DEPARTAMENTO DE LA GUAJIRA -',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8092).update(id: 8092,passive_part: 'RAFAEL ADOLFO AREVALO AROCA - ITAU CORPBANCA COLOMBIA SA- INVERSIONES AVANADE Y CIA SAS - LA PREVISO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5682).update(id: 5682,passive_part: 'ESE HOSPITAL FRANCISCO LUIS JIMENEZ MARTINEZ DE CAREPA ESE ARBDE APARTADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8390).update(id: 8390,passive_part: 'SANDRA JANNET MEDINA PIEROTTI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7356).update(id: 7356,passive_part: 'SINDICATO DE TRABAJADORES DEL SECTOR DE LA SALUD Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9017).update(id: 9017,passive_part: 'COOTRANSVALLE SAMACA ARISTOBULO GIL TURCA LA PREVISORA SACOMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9745).update(id: 9745,passive_part: 'LIBARDO ANTONIO SALAZAR SEPULVEDA LYSICAR Y OTROS HERNAN DARIO OCAMPO SALAZAR BERNARDO LOPEZ ALZATE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8770).update(id: 8770,passive_part: 'EMPRESAS VARIAS DE MEDELLIN ESP Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7601).update(id: 7601,passive_part: 'ISAGEN SA GRUPO ICT II SAS ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8746).update(id: 8746,passive_part: 'CARLOS ACTAVIO ESCOBAR LOPEZ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6093).update(id: 6093,passive_part: 'NUEVA EPS IPS UNIVERSITARIA CLINICA LEON XIII',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(434).update(id: 434,passive_part: 'EPS Y MEDICINA PREPAGADA SURAMERICANA SAEPSSURA HOSPITAL PABLO TOBON URIBE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7026).update(id: 7026,passive_part: 'LA PREVISORA SA NAVITRANS SA OLEOTANQUES SAS EN LIQUIDACION',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8205).update(id: 8205,passive_part: 'IPS COMFAMA EPS Y MEDICINA PREPAGADA SURAMERICANA SA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9357).update(id: 9357,passive_part: 'SALUD TOTAL EPS-S SA HOSPITAL PABLO TOBON URIBE JUAN CARLOS CASTANO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6741).update(id: 6741,passive_part: 'ESE HOSPITAL PEDRO CLAVER AGUIRRE Y DE TOLEDO HOSPITAL GENERAL DE MEDELLIN LUZ CASTRO DE GUTIERREZ ESE HOSPITAL SAN VICENTE DE PAUL DE CALDAS CAPRECOM EPS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7838).update(id: 7838,passive_part: 'MUNICIPIO DE MEDELLIN EMPRESA DE TRANSPORTE MASIVO DEL VALLE DEL ABURRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7693).update(id: 7693,passive_part: 'EMPRESA DE TRANSPORTE MASIVO DEL VALLE DE ABURRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9048).update(id: 9048,passive_part: 'IVAN DARIO ROJAS LOPEZ LA PREVISORA SA ESE HOSPITAL SAN RAFAEL DE SAN LUIS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6068).update(id: 6068,passive_part: 'ESEHOSPITAL SAN ANTONIO DE CISNEROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7073).update(id: 7073,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS DE RIONEGRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6480).update(id: 6480,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS DE RIONEGRO ESE HOSPITAL SAN JUAN DE DIOS DE COCORNA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9619).update(id: 9619,passive_part: 'NACION-MINDEFENSA-POLICIA BELLO SALUD MAYOR SEGURIDAD LTDA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8213).update(id: 8213,passive_part: 'VERONICA JOHANA CARDONA VASQUEZ DEPARTAMENTO DE ANTIOQUIA MUNICIPIO DE COPACABANA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7880).update(id: 7880,passive_part: 'ESEMETROSALUD  ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7953).update(id: 7953,passive_part: 'LA PREVISORA SA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9585).update(id: 9585,passive_part: 'ESE HOSPITAL SAN RAFAEL DE SAN LUIS FUNDACION CLINICA DEL NORTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9457).update(id: 9457,passive_part: 'INVIAS CORANTIOQUIA DEVIMED SA DEPARTAMENTO DE ANTIOQUIA MUNICIPIO DE COPACABANA INCO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7616).update(id: 7616,passive_part: 'YULIANA ALEXANDRA GIRALDO MARTINEZ JHON JAIRO REYES RODRIGUEZ HOSPITAL SAN VICENTE DE PAUL DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5262).update(id: 5262,passive_part: 'ACUARELA CDO SAS MUNICIPIO DE COPACABANA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7742).update(id: 7742,passive_part: 'MUNICIPIO DE SANTA FE DE ANTIOQUIA ESE HOSPITAL SAN JUAN DE DIOS SANTA FE DE ANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8927).update(id: 8927,passive_part: 'EMPRESA DE TRASPORTE MASIVO DE VALLE DE ABURRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9549).update(id: 9549,passive_part: 'UNIDAD HOSPITALARIA SAN ANTONONIO DE PRADO MEDELLIN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9597).update(id: 9597,passive_part: 'INPEC CAPRECOM',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7124).update(id: 7124,passive_part: 'MUNICIPIO DE MEDELLIN INSTITUCION UNIVERSITARIA TECNOLOGICO PASCUAL BRAVO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9935).update(id: 9935,passive_part: 'ESEHOSPITAL SAN JUAN DE DIOS DE SANTA FE DE ANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7088).update(id: 7088,passive_part: 'HOSPITAL GENERAL DE MEDELLIN LUZ CASTRO DE GUTIERREZ ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8631).update(id: 8631,passive_part: 'ESE METRO SALUD HOSPITAL GENERAL DE MEDELLIN LUZ CASTRO DE GUTIERREZ ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(5).update(id: 5,passive_part: 'ESE METROSALUD SALUD TOTAL SA CLINICA ANTIOQUIA SAVIA SALUD EPS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6791).update(id: 6791,passive_part: 'HOSPITAL MENTAL DE ANTIOQUIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6390).update(id: 6390,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS SANTA FE DE ANTIOQUIA FUNDACION CLINICA DEL NORTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7975).update(id: 7975,passive_part: 'MUNICIPIO DE PUERTO BERRIO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7653).update(id: 7653,passive_part: 'ESE METROSALUD',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6620).update(id: 6620,passive_part: 'ESEHOSPITAL ANTONIO ROLDAN BETANCUR DE LA PINTADA COORPORACION CLINICA SALUDCOOP',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6074).update(id: 6074,passive_part: 'RAMA JUDICIAL-CONSEJO SUPERIOR DE LA JUDICATURA FISCALIA GENERAL DE LA NACION INPEC NACION - MINISTERIO DE DEFENSA - POLICIA NACIONAL',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7107).update(id: 7107,passive_part: 'ESEHOSPITAL SAN RAFAEL DE VENECIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6634).update(id: 6634,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS SANTA FE DE ANTIOQUIASAVIA SALUD EPS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8378).update(id: 8378,passive_part: 'INVIAS CORANTIOQUIA DEPARTAMENTO DE ANTIOQUIA MUNICIPIO DE COPACABANA DEVIMED ANI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8991).update(id: 8991,passive_part: 'ESE METROSALUD NACION-MINDEFENSA-POLICIA MUNICIPIO DE MEDELLIN UNIDAD HOSPITALARIA DE MANRIQUE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9045).update(id: 9045,passive_part: 'MUNICIPIO DE ENVIGADO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9916).update(id: 9916,passive_part: 'MUNICIPIO DE ENVIGADO SECRETARIA DE TRANSITO Y TRANSPORTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8848).update(id: 8848,passive_part: 'HOSPITAL NUESTRA SENORA DEL ROSARIO DE BELMIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6781).update(id: 6781,passive_part: 'HOSPITAL SAN VICENTE DE PAUL DE CALDAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8206).update(id: 8206,passive_part: 'ESE METROSALUD',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9885).update(id: 9885,passive_part: 'CLINICA DE URABA SA COOMEVA HOSPITAL LA MARIA ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9180).update(id: 9180,passive_part: 'ESE HOSPITAL MARCO FIDEL SUAREZ DE BELLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8840).update(id: 8840,passive_part: 'MUNICIPIO DE ANDES ESE HOSPITAL SAN RAFAEL DE ANDES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8432).update(id: 8432,passive_part: 'INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6454).update(id: 6454,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS YARUMAL ALVARO AALARCON BADILLO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7626).update(id: 7626,passive_part: 'ESE METROSALUD',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(427).update(id: 427,passive_part: 'FUNDACION HOSPITALARIA SAN VICENTE DE PAUL SOCIEDAD MEDICA RIONEGRO SA ESE HOSPITAL NUESTRA SENORA DE LA CANDELARIA DE GUARNE MINISTERIO DE SALUD Y DE LA PROTECCION SOCIAL',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9422).update(id: 9422,passive_part: 'LA PREVISORA SA MUNICIPIO DE ITAGUI OSCAR DARIO PIEDRAHITA PAREJO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9002).update(id: 9002,passive_part: 'ESEHOSPITAL SAN RAFAEL DE ITAGUI',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9046).update(id: 9046,passive_part: 'HOSPITAL GENERAL DE MEDELLIN LUZ CASTRO DE GUTIERREZ ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9034).update(id: 9034,passive_part: 'MUNICIPIO DE ENVIGADO LA PREVISORA SA COMPANIA DE SEGUROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9143).update(id: 9143,passive_part: 'INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7973).update(id: 7973,passive_part: 'HOSPITAL GENERAL DE MEDELLIN LUZ CASTRO DE GUTIERREZ ESE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9092).update(id: 9092,passive_part: 'INPEC EPS CAPRECOM',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7704).update(id: 7704,passive_part: 'CONTRALORIA GENERAL DE MEDELLIN',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9155).update(id: 9155,passive_part: 'MUNICIPIO DE MEDELLIN -SECRETARIA DE MOVILIDAD',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8208).update(id: 8208,passive_part: 'FUNDACION HOSPITAL INFANTIL LOS ANGELES',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(4704).update(id: 4704,passive_part: 'ESE HOSPITAL UNIVERSITARIO DE SANTANDER',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10954).update(id: 10954,passive_part: 'MUNICIPIO DE ARMENIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7156).update(id: 7156,passive_part: 'HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8523).update(id: 8523,passive_part: 'ESE HOSPITAL UNIVERSITARIO DE SANTANDER-INSTITUTO NACIONAL PENITENCIARIO INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20219).update(id: 20219,passive_part: 'NEXARTE SA Y SURGAS SA ESP',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7638).update(id: 7638,passive_part: 'HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO - INSTITUTO NACIONAL DE CANCEROLOGIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8426).update(id: 8426,passive_part: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PITALITO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8277).update(id: 8277,passive_part: 'ESE NORTE 3',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2497).update(id: 2497,passive_part: 'MUNICIPIO DE DOSQUEBRADAS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20320).update(id: 20320,passive_part: 'ESE SAN JUAN DE DIOS MUNICIPIO DE RIONEGRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2497).update(id: 2497,passive_part: 'ESE SALUD PEREIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20138).update(id: 20138,passive_part: 'MUNICIPIO DE MURINDO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(10957).update(id: 10957,passive_part: 'MUNICIPIO DE ARMENIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20134).update(id: 20134,passive_part: 'EMPRESA DE VIVIENDA DE ANTIOQUIA VIVA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20159).update(id: 20159,passive_part: 'EMPRESA DE VIVIENDA DE ANTIOQUIA VIVA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20232).update(id: 20232,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS DE RIONEGRO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20161).update(id: 20161,passive_part: 'ESP SANTA FE DE ANTIOQUIA OCCIDENTE LIMPIO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20293).update(id: 20293,passive_part: 'MUNICIPIO DE MUTATAT',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(377).update(id: 377,passive_part: 'COOTRADEMACOC Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(6978).update(id: 6978,passive_part: 'MUNICIPIO DE PEREIRA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(12858).update(id: 12858,passive_part: 'PENDIENTE',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9467).update(id: 9467,passive_part: 'HOSPITAL DE MONTENEGRO ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9374).update(id: 9374,passive_part: 'ASMET SALUD',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8614).update(id: 8614,passive_part: 'ESPECIALISTAS ASOCIADOS Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9372).update(id: 9372,passive_part: 'INVIAS ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2473).update(id: 2473,passive_part: 'COMFAMILIAR RISARALDA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2153).update(id: 2153,passive_part: 'HOSPITAL SAN JUAN DE DIOS DE ARMENIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2076).update(id: 2076,passive_part: 'EMPRESAS PUBLICAS DE ARMENIA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9093).update(id: 9093,passive_part: 'HOSPITAL PIO X DE LA TEBAIDA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(82).update(id: 82,passive_part: 'INVERSIONES GLP SAS ESP Y OTROS',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(2392).update(id: 2392,passive_part: 'DEPARTAMENTO DE RISARALDA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9530).update(id: 9530,passive_part: 'MUNICIPIO DE ARMENIA ',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9409).update(id: 9409,passive_part: 'HOSPITAL SAN JUAN DE DIOS LA CEJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(7395).update(id: 7395,passive_part: 'JONATHAN STEVEN GONZALEZ PANTOJA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13695).update(id: 13695,passive_part: 'INSTITUCIONEDUCATIVAMONGAMBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9414).update(id: 9414,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(13695).update(id: 13695,passive_part: 'INSTITUCION EDUCATIVA MOGAMBO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8002).update(id: 8002,passive_part: 'CENTRALES ELECTRICAS DE NARINO SA ESP',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(8820).update(id: 8820,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9423).update(id: 9423,passive_part: 'ESE HOSPITAL SAN NICOLAS DE PLANETA RICA',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(9146).update(id: 9146,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(20011).update(id: 20011,passive_part: 'MUNICIPIO DE ENVIGADO',state: 'REGISTRO NUEVO ACTUALIZADO')
    puts TypeProcess.find(72).update(id: 72,passive_part: 'HOSPITAL MILITAR CENTRAL ',state: 'REGISTRO NUEVO ACTUALIZADO')
  end
end
