class Aleja73 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9837).update(id: 9837,reason_conc: 'SOLICITAN 20 MILLLONES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9981).update(id: 9981,reason_conc: 'NO CONCILIAR LAS PRETENSIONES DE LA PARTE ACTIVA TENIENDO EN CUENTA QUE LOS ELEMENTOS NO SE ENCUENTRAN ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20309).update(id: 20309,reason_conc: 'AUN NO SE REALIZA AUDIENCIA INICIAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20281).update(id: 20281,reason_conc: 'AUSENCIA DE COBERTURA DE LA POLIZA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4704).update(id: 4704,reason_conc: 'QUE UNA VEZ VERIFICADOS LOS HECHOS Y ANTECEDENTES DEL CASO SE LOGRO EVIDENCIAR QUE HA OPERADO EL TERMINO DE LA CADUCIDAD DE LA ACCION AUNADO A LA AUSENCIA DE COBERTURA DENTRO DEL CONTRATO DE SEGUROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8523).update(id: 8523,reason_conc: 'NO SE ESTABLECIERON ELEMENTOS PROBATORIOS Y DE JUICIO QUE INDIQUEN RESPONSABILIDAD DE NUESTRO ASEGURADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(72).update(id: 72,reason_conc: 'LA SOLICITUD DE CONCILIACION EXTRAJUDICIAL SE HIZO POR FUERA DE LA VIGENCIA DE LA POLIZA ANADIENDO ADEMAS QUE LO ANTERIOR SE CONFIGURA COMO UNA EXCLUSION AL TENOR LITERAL DE LA POLIZA',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
