class Aleja55 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(2991).update(id: 2991,reason_inv: 'ESPERAR EL FALLO ')
    puts TypeProcess.find(2908).update(id: 2908,reason_inv: 'ESPERAR EL FALLO DEL CONSEJO DE ESTADO ')
    puts TypeProcess.find(3717).update(id: 3717,reason_inv: 'ESPERAR EL FALLO')
    puts TypeProcess.find(2937).update(id: 2937,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3118).update(id: 3118,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(2921).update(id: 2921,reason_inv: 'SE RECOMIENDA ESPERAR EL DESARROLLO DEL DEBATE PROBATORIO')
    puts TypeProcess.find(3220).update(id: 3220,reason_inv: 'ESPERAR EL DESARROLLO DEL DEBATE PROBATORIO')
    puts TypeProcess.find(9230).update(id: 9230,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3072).update(id: 3072,reason_inv: 'SE RECOMIENDA EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3312).update(id: 3312,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(2700).update(id: 2700,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3272).update(id: 3272,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(2981).update(id: 2981,reason_inv: 'ESPERAR EL FALLO')
    puts TypeProcess.find(2949).update(id: 2949,reason_inv: 'ESPERAR EL FALLO DE SEGUNDA INSTANCIA')
    puts TypeProcess.find(2945).update(id: 2945,reason_inv: 'SE RECOMIENDA ESPERAR EL DESARROLLO DEL DEBATE PROBATORIO')
    puts TypeProcess.find(3245).update(id: 3245,reason_inv: 'ESPERAR EL FALLO DE SEGUNDA INSTANCIA')
    puts TypeProcess.find(2721).update(id: 2721,reason_inv: 'ESPERAR EL FALLO')
    puts TypeProcess.find(3475).update(id: 3475,reason_inv: 'ESPERAR EL FALLO')
    puts TypeProcess.find(3307).update(id: 3307,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3074).update(id: 3074,reason_inv: 'ESPERAR EL FALLO DE SEGUNDA INSTANCIA')
    puts TypeProcess.find(3544).update(id: 3544,reason_inv: 'ESPERAR EL FALLO')
    puts TypeProcess.find(3490).update(id: 3490,reason_inv: 'SE RECOMIENDA ESPERAR EL DESARROLLO DEL DEBATE PROBATORIO')
    puts TypeProcess.find(2883).update(id: 2883,reason_inv: 'ESPERAR EL FALLO ')
    puts TypeProcess.find(2976).update(id: 2976,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
    puts TypeProcess.find(3489).update(id: 3489,reason_inv: 'ESPERAR EL FALLO EN SEGUNDA INSTANCIA')
  end
end
