class Fix27 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(18930).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18929).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18928).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18927).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18242).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18076).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17364).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17363).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17338).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17029).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15634).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14651).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13149).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12193).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12191).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12190).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12189).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12188).update(case_termination: 'Duplicado',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10995).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17386).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17334).update(case_termination: 'TERMINADO-DESVINCULAN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17293).update(case_termination: 'TRMINADO CON PAGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17256).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17253).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17232).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17202).update(case_termination: 'TERMINADO-ARCHIVO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17172).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17039).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16467).update(case_termination: 'TERMINADO CON PAGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11999).update(case_termination: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
