class Al17 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(280).update(id: 280,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1363).update(id: 1363,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1375).update(id: 1375,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1412).update(id: 1412,current_stage: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1553).update(id: 1553,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1733).update(id: 1733,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1776).update(id: 1776,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2358).update(id: 2358,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3866).update(id: 3866,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4167).update(id: 4167,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4208).update(id: 4208,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4210).update(id: 4210,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4212).update(id: 4212,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4219).update(id: 4219,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4227).update(id: 4227,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4228).update(id: 4228,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4229).update(id: 4229,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4231).update(id: 4231,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4233).update(id: 4233,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4241).update(id: 4241,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4242).update(id: 4242,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4394).update(id: 4394,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4436).update(id: 4436,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4451).update(id: 4451,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4452).update(id: 4452,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4453).update(id: 4453,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4456).update(id: 4456,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4459).update(id: 4459,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4460).update(id: 4460,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4462).update(id: 4462,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4463).update(id: 4463,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4464).update(id: 4464,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4465).update(id: 4465,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4466).update(id: 4466,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4467).update(id: 4467,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4468).update(id: 4468,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4469).update(id: 4469,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4470).update(id: 4470,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4471).update(id: 4471,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4472).update(id: 4472,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4473).update(id: 4473,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4474).update(id: 4474,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4475).update(id: 4475,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4476).update(id: 4476,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4477).update(id: 4477,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4478).update(id: 4478,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4479).update(id: 4479,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4480).update(id: 4480,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4481).update(id: 4481,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4482).update(id: 4482,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4483).update(id: 4483,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4484).update(id: 4484,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4485).update(id: 4485,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4486).update(id: 4486,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4489).update(id: 4489,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4490).update(id: 4490,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4491).update(id: 4491,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4494).update(id: 4494,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4495).update(id: 4495,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4496).update(id: 4496,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4497).update(id: 4497,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4499).update(id: 4499,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4502).update(id: 4502,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4503).update(id: 4503,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4504).update(id: 4504,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4723).update(id: 4723,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4907).update(id: 4907,current_stage: 'LIQUIDACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4913).update(id: 4913,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4914).update(id: 4914,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4915).update(id: 4915,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4916).update(id: 4916,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4917).update(id: 4917,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4918).update(id: 4918,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4920).update(id: 4920,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4921).update(id: 4921,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4923).update(id: 4923,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4924).update(id: 4924,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4926).update(id: 4926,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4927).update(id: 4927,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4929).update(id: 4929,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4930).update(id: 4930,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4931).update(id: 4931,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4933).update(id: 4933,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4934).update(id: 4934,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4936).update(id: 4936,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4937).update(id: 4937,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4939).update(id: 4939,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4942).update(id: 4942,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4944).update(id: 4944,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4945).update(id: 4945,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4946).update(id: 4946,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4948).update(id: 4948,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4949).update(id: 4949,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4950).update(id: 4950,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4951).update(id: 4951,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4952).update(id: 4952,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4954).update(id: 4954,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4956).update(id: 4956,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4958).update(id: 4958,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4960).update(id: 4960,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4961).update(id: 4961,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4964).update(id: 4964,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4966).update(id: 4966,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4971).update(id: 4971,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4972).update(id: 4972,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4974).update(id: 4974,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4976).update(id: 4976,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4979).update(id: 4979,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4980).update(id: 4980,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4981).update(id: 4981,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4983).update(id: 4983,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4987).update(id: 4987,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4989).update(id: 4989,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4991).update(id: 4991,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4992).update(id: 4992,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4994).update(id: 4994,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4995).update(id: 4995,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4996).update(id: 4996,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4999).update(id: 4999,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5002).update(id: 5002,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5003).update(id: 5003,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5004).update(id: 5004,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5005).update(id: 5005,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5006).update(id: 5006,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5007).update(id: 5007,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5008).update(id: 5008,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5009).update(id: 5009,current_stage: 'AUDIENCIA DE SUSTENTACION RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5010).update(id: 5010,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5013).update(id: 5013,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5016).update(id: 5016,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5019).update(id: 5019,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5021).update(id: 5021,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5022).update(id: 5022,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5025).update(id: 5025,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5028).update(id: 5028,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5029).update(id: 5029,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5030).update(id: 5030,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5032).update(id: 5032,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5033).update(id: 5033,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5034).update(id: 5034,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5035).update(id: 5035,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5036).update(id: 5036,current_stage: 'AUTO ADMISORIO DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5069).update(id: 5069,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5479).update(id: 5479,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5825).update(id: 5825,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5928).update(id: 5928,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5993).update(id: 5993,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5996).update(id: 5996,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6017).update(id: 6017,current_stage: 'SENTENCIA PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6059).update(id: 6059,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6076).update(id: 6076,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6140).update(id: 6140,current_stage: 'CONTESTACION DE LADEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6249).update(id: 6249,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6295).update(id: 6295,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6297).update(id: 6297,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6310).update(id: 6310,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6426).update(id: 6426,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6457).update(id: 6457,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6499).update(id: 6499,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6507).update(id: 6507,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6637).update(id: 6637,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6669).update(id: 6669,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6820).update(id: 6820,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6852).update(id: 6852,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6961).update(id: 6961,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7085).update(id: 7085,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7112).update(id: 7112,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7125).update(id: 7125,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7166).update(id: 7166,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7381).update(id: 7381,current_stage: 'ADMISION DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7447).update(id: 7447,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7477).update(id: 7477,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7582).update(id: 7582,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7634).update(id: 7634,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7694).update(id: 7694,current_stage: 'AUDIENCIA DE CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7695).update(id: 7695,current_stage: 'AUDIENCIA DE CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7772).update(id: 7772,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7800).update(id: 7800,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7866).update(id: 7866,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7875).update(id: 7875,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7877).update(id: 7877,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7920).update(id: 7920,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7937).update(id: 7937,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7940).update(id: 7940,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8052).update(id: 8052,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8057).update(id: 8057,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8160).update(id: 8160,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8162).update(id: 8162,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8264).update(id: 8264,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8329).update(id: 8329,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8331).update(id: 8331,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8370).update(id: 8370,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8786).update(id: 8786,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8794).update(id: 8794,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8908).update(id: 8908,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8917).update(id: 8917,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9083).update(id: 9083,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9159).update(id: 9159,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9284).update(id: 9284,current_stage: 'CONTESTACION DE LADEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9325).update(id: 9325,current_stage: 'AUDIENCIA DE TRAMITE O PRUEBA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9329).update(id: 9329,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9354).update(id: 9354,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9490).update(id: 9490,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9555).update(id: 9555,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9625).update(id: 9625,current_stage: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9716).update(id: 9716,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9779).update(id: 9779,current_stage: 'AUDIENCIA Y FALLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9813).update(id: 9813,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9822).update(id: 9822,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9857).update(id: 9857,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9858).update(id: 9858,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9881).update(id: 9881,current_stage: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9894).update(id: 9894,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10001).update(id: 10001,current_stage: 'AUDIENCIA DE FALLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10015).update(id: 10015,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10046).update(id: 10046,current_stage: 'AUDIENCIA INICIAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10071).update(id: 10071,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10072).update(id: 10072,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11575).update(id: 11575,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12934).update(id: 12934,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13004).update(id: 13004,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13111).update(id: 13111,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13150).update(id: 13150,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13209).update(id: 13209,current_stage: 'AUTO DE APERTURA E IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13229).update(id: 13229,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13263).update(id: 13263,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13393).update(id: 13393,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13408).update(id: 13408,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13411).update(id: 13411,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13437).update(id: 13437,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13440).update(id: 13440,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13441).update(id: 13441,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13442).update(id: 13442,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13470).update(id: 13470,current_stage: 'AUTO DE APERTURA E IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13570).update(id: 13570,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13873).update(id: 13873,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13876).update(id: 13876,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13879).update(id: 13879,current_stage: 'AUTO DE APERTURA E IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13880).update(id: 13880,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13990).update(id: 13990,current_stage: 'AUTO QUE RESUELVE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14084).update(id: 14084,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14328).update(id: 14328,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14348).update(id: 14348,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14505).update(id: 14505,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14783).update(id: 14783,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14819).update(id: 14819,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15017).update(id: 15017,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15018).update(id: 15018,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15019).update(id: 15019,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15020).update(id: 15020,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15224).update(id: 15224,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16190).update(id: 16190,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16204).update(id: 16204,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16206).update(id: 16206,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16207).update(id: 16207,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16209).update(id: 16209,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16210).update(id: 16210,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16211).update(id: 16211,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16212).update(id: 16212,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16213).update(id: 16213,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16218).update(id: 16218,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16227).update(id: 16227,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16228).update(id: 16228,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16229).update(id: 16229,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16230).update(id: 16230,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16231).update(id: 16231,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16250).update(id: 16250,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16258).update(id: 16258,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16259).update(id: 16259,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16264).update(id: 16264,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16272).update(id: 16272,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16317).update(id: 16317,current_stage: 'RECURSO DE REPOSICION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16318).update(id: 16318,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16411).update(id: 16411,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16468).update(id: 16468,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16478).update(id: 16478,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16501).update(id: 16501,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16578).update(id: 16578,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16654).update(id: 16654,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16737).update(id: 16737,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16749).update(id: 16749,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16795).update(id: 16795,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16799).update(id: 16799,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16827).update(id: 16827,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16888).update(id: 16888,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16921).update(id: 16921,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17012).update(id: 17012,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17013).update(id: 17013,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17014).update(id: 17014,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17027).update(id: 17027,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17028).update(id: 17028,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17030).update(id: 17030,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17046).update(id: 17046,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17048).update(id: 17048,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17049).update(id: 17049,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17095).update(id: 17095,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17096).update(id: 17096,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17098).update(id: 17098,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17099).update(id: 17099,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17103).update(id: 17103,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17106).update(id: 17106,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17113).update(id: 17113,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17114).update(id: 17114,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17117).update(id: 17117,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17123).update(id: 17123,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17127).update(id: 17127,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17128).update(id: 17128,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17129).update(id: 17129,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17142).update(id: 17142,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17149).update(id: 17149,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17164).update(id: 17164,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17166).update(id: 17166,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17173).update(id: 17173,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17176).update(id: 17176,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17189).update(id: 17189,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17199).update(id: 17199,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17288).update(id: 17288,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17292).update(id: 17292,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17329).update(id: 17329,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17332).update(id: 17332,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17339).update(id: 17339,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17340).update(id: 17340,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17350).update(id: 17350,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17367).update(id: 17367,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17371).update(id: 17371,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17382).update(id: 17382,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17399).update(id: 17399,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17401).update(id: 17401,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(id: 17402,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17403).update(id: 17403,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17409).update(id: 17409,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17411).update(id: 17411,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17412).update(id: 17412,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17427).update(id: 17427,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17428).update(id: 17428,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17431).update(id: 17431,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17432).update(id: 17432,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17433).update(id: 17433,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17438).update(id: 17438,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17439).update(id: 17439,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17440).update(id: 17440,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17442).update(id: 17442,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17454).update(id: 17454,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17455).update(id: 17455,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17456).update(id: 17456,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17464).update(id: 17464,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17466).update(id: 17466,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17467).update(id: 17467,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17473).update(id: 17473,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17475).update(id: 17475,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17477).update(id: 17477,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17481).update(id: 17481,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17482).update(id: 17482,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17488).update(id: 17488,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17490).update(id: 17490,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17497).update(id: 17497,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17498).update(id: 17498,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17499).update(id: 17499,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17502).update(id: 17502,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17507).update(id: 17507,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17530).update(id: 17530,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17551).update(id: 17551,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17555).update(id: 17555,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17556).update(id: 17556,current_stage: 'RECURSO DE REPOSICION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17563).update(id: 17563,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17564).update(id: 17564,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17571).update(id: 17571,current_stage: 'RECURSO DE REPOSICION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17572).update(id: 17572,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17576).update(id: 17576,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17589).update(id: 17589,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17599).update(id: 17599,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17600).update(id: 17600,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17602).update(id: 17602,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17603).update(id: 17603,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17615).update(id: 17615,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17620).update(id: 17620,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17628).update(id: 17628,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17634).update(id: 17634,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17650).update(id: 17650,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17654).update(id: 17654,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17655).update(id: 17655,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17658).update(id: 17658,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17665).update(id: 17665,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17667).update(id: 17667,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17670).update(id: 17670,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17672).update(id: 17672,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17673).update(id: 17673,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17675).update(id: 17675,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17677).update(id: 17677,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17678).update(id: 17678,current_stage: 'AUTO DE APERTURA E IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17687).update(id: 17687,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17691).update(id: 17691,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17692).update(id: 17692,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17693).update(id: 17693,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17712).update(id: 17712,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17725).update(id: 17725,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17726).update(id: 17726,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17744).update(id: 17744,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17746).update(id: 17746,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17749).update(id: 17749,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17751).update(id: 17751,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17757).update(id: 17757,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17770).update(id: 17770,current_stage: 'AUTO DE IMPUTACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17775).update(id: 17775,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17778).update(id: 17778,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17779).update(id: 17779,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17780).update(id: 17780,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17786).update(id: 17786,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17787).update(id: 17787,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17795).update(id: 17795,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17797).update(id: 17797,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17798).update(id: 17798,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17801).update(id: 17801,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17802).update(id: 17802,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17803).update(id: 17803,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17804).update(id: 17804,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17805).update(id: 17805,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17813).update(id: 17813,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17815).update(id: 17815,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17816).update(id: 17816,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17821).update(id: 17821,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17829).update(id: 17829,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17844).update(id: 17844,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17853).update(id: 17853,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17859).update(id: 17859,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17865).update(id: 17865,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17874).update(id: 17874,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17879).update(id: 17879,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17884).update(id: 17884,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17885).update(id: 17885,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17886).update(id: 17886,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17887).update(id: 17887,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17888).update(id: 17888,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17889).update(id: 17889,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17890).update(id: 17890,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17891).update(id: 17891,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17892).update(id: 17892,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17894).update(id: 17894,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17901).update(id: 17901,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17918).update(id: 17918,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17923).update(id: 17923,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17926).update(id: 17926,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17931).update(id: 17931,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17936).update(id: 17936,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17942).update(id: 17942,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17943).update(id: 17943,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17952).update(id: 17952,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17953).update(id: 17953,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17954).update(id: 17954,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17975).update(id: 17975,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17978).update(id: 17978,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17983).update(id: 17983,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17984).update(id: 17984,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17985).update(id: 17985,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17988).update(id: 17988,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18005).update(id: 18005,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18008).update(id: 18008,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18010).update(id: 18010,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18011).update(id: 18011,current_stage: 'RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18012).update(id: 18012,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18013).update(id: 18013,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18025).update(id: 18025,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18026).update(id: 18026,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18034).update(id: 18034,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18036).update(id: 18036,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18037).update(id: 18037,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18043).update(id: 18043,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18064).update(id: 18064,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18081).update(id: 18081,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18084).update(id: 18084,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18085).update(id: 18085,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18087).update(id: 18087,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18088).update(id: 18088,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18089).update(id: 18089,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18095).update(id: 18095,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18098).update(id: 18098,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18109).update(id: 18109,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18116).update(id: 18116,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18123).update(id: 18123,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18125).update(id: 18125,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18126).update(id: 18126,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18127).update(id: 18127,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18128).update(id: 18128,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18143).update(id: 18143,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18147).update(id: 18147,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18150).update(id: 18150,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18153).update(id: 18153,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18154).update(id: 18154,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18155).update(id: 18155,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18156).update(id: 18156,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18157).update(id: 18157,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18165).update(id: 18165,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18193).update(id: 18193,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18200).update(id: 18200,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18201).update(id: 18201,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18202).update(id: 18202,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18203).update(id: 18203,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18220).update(id: 18220,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18223).update(id: 18223,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18249).update(id: 18249,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18250).update(id: 18250,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18251).update(id: 18251,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18273).update(id: 18273,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18307).update(id: 18307,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18316).update(id: 18316,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18317).update(id: 18317,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18319).update(id: 18319,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18320).update(id: 18320,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18353).update(id: 18353,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18354).update(id: 18354,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18375).update(id: 18375,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18376).update(id: 18376,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18377).update(id: 18377,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18378).update(id: 18378,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18380).update(id: 18380,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18384).update(id: 18384,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18385).update(id: 18385,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18428).update(id: 18428,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18448).update(id: 18448,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18515).update(id: 18515,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18676).update(id: 18676,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18890).update(id: 18890,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18906).update(id: 18906,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18970).update(id: 18970,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18973).update(id: 18973,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18985).update(id: 18985,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19286).update(id: 19286,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19288).update(id: 19288,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19305).update(id: 19305,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19474).update(id: 19474,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19481).update(id: 19481,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19483).update(id: 19483,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19484).update(id: 19484,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19485).update(id: 19485,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19486).update(id: 19486,current_stage: 'AUDIENCIA DE DECISION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19487).update(id: 19487,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19488).update(id: 19488,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19490).update(id: 19490,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19530).update(id: 19530,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19733).update(id: 19733,current_stage: 'ALEGATOS DE CONCLUSION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19756).update(id: 19756,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19760).update(id: 19760,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20091).update(id: 20091,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20095).update(id: 20095,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20166).update(id: 20166,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20167).update(id: 20167,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20168).update(id: 20168,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20216).update(id: 20216,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20217).update(id: 20217,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20218).update(id: 20218,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20220).update(id: 20220,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20221).update(id: 20221,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20235).update(id: 20235,current_stage: 'SENTENCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20243).update(id: 20243,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20245).update(id: 20245,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20246).update(id: 20246,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20247).update(id: 20247,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20249).update(id: 20249,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20250).update(id: 20250,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20251).update(id: 20251,current_stage: 'DEMANDA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20252).update(id: 20252,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20253).update(id: 20253,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20254).update(id: 20254,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20260).update(id: 20260,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20262).update(id: 20262,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20271).update(id: 20271,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20283).update(id: 20283,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20284).update(id: 20284,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20285).update(id: 20285,current_stage: 'ADMISION DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20286).update(id: 20286,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20290).update(id: 20290,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20291).update(id: 20291,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20301).update(id: 20301,current_stage: 'DEMANDA DE CASACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20302).update(id: 20302,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20303).update(id: 20303,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20304).update(id: 20304,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20315).update(id: 20315,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20317).update(id: 20317,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20334).update(id: 20334,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20354).update(id: 20354,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20380).update(id: 20380,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20381).update(id: 20381,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20382).update(id: 20382,current_stage: 'AUDIENCIA DE DESCARGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20387).update(id: 20387,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20388).update(id: 20388,current_stage: 'PRESENTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20400).update(id: 20400,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20409).update(id: 20409,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20423).update(id: 20423,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20478).update(id: 20478,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20480).update(id: 20480,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20481).update(id: 20481,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20482).update(id: 20482,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,current_stage: 'DEMANDA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,current_stage: 'DEMANDA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,current_stage: 'DEMANDA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20635).update(id: 20635,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20644).update(id: 20644,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20645).update(id: 20645,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20646).update(id: 20646,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20647).update(id: 20647,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20648).update(id: 20648,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20649).update(id: 20649,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20650).update(id: 20650,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20651).update(id: 20651,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20652).update(id: 20652,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20806).update(id: 20806,current_stage: 'AUTO DE APERTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20961).update(id: 20961,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20965).update(id: 20965,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20969).update(id: 20969,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20991).update(id: 20991,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20992).update(id: 20992,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21004).update(id: 21004,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21106).update(id: 21106,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21108).update(id: 21108,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21109).update(id: 21109,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21140).update(id: 21140,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21143).update(id: 21143,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21149).update(id: 21149,current_stage: 'CONTESTACION DE LA DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21241).update(id: 21241,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21288).update(id: 21288,current_stage: 'APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21306).update(id: 21306,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21314).update(id: 21314,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21315).update(id: 21315,current_stage: 'DEMANDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21380).update(id: 21380,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21382).update(id: 21382,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21383).update(id: 21383,current_stage: 'AUDIENCIA DE INSTRUCCION Y JUZGAMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21399).update(id: 21399,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21402).update(id: 21402,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21403).update(id: 21403,current_stage: 'PRUEBAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21408).update(id: 21408,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21430).update(id: 21430,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21434).update(id: 21434,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
