class Aleja02 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(21242).update(id: 21242,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21245).update(id: 21245,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21251).update(id: 21251,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21252).update(id: 21252,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21255).update(id: 21255,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21257).update(id: 21257,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21264).update(id: 21264,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21267).update(id: 21267,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21269).update(id: 21269,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21270).update(id: 21270,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21274).update(id: 21274,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21276).update(id: 21276,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21285).update(id: 21285,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21293).update(id: 21293,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21294).update(id: 21294,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21297).update(id: 21297,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21299).update(id: 21299,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21307).update(id: 21307,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21308).update(id: 21308,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21309).update(id: 21309,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21311).update(id: 21311,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21312).update(id: 21312,case_id_bap: 'PENDIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
