class Aleja10 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(8805).update(case_id_bap: 'GPJ-3767-2016',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20530',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8738).update(case_id_bap: 'GPJ-3518-2016',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20527',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8970).update(case_id_bap: 'GPJ-5473-2016',process_class: 'PENDIENTE',subprocess_class: 'PENDIENTE',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20531',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9078).update(case_id_bap: 'GPJ-6284-2016',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20526',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9110).update(case_id_bap: 'GPJ-6434-2016',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '3',branch_commercial: '13',number: '21130',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9348).update(case_id_bap: 'GPJ-7556-2016',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20528',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6345).update(case_id_bap: 'GPJ-11316-2017',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20546',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6425).update(case_id_bap: 'GPJ-11558-2017',process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20154',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2670).update(case_id_bap: 'GPJ-2068-2016',process_class: 'PENDIENTE',subprocess_class: 'PENDIENTE',case_state: 'EN CURSO',branch_policy: '0',branch_commercial: '0',number: 'NO PRESENTA',exercise: 'NO PRESENTA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9576).update(case_id_bap: 'GPJ-8503-2016',process_class: 'PENDIENTE',subprocess_class: 'PENDIENTE',case_state: 'EN CURSO',branch_policy: '18',branch_commercial: '5',number: '21002',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9060).update(case_id_bap: 'GPJ-6218-2016',process_class: 'PENDIENTE',subprocess_class: 'PENDIENTE',case_state: 'EN CURSO',branch_policy: '35',branch_commercial: '13',number: '20529',exercise: '2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
