class Aleja07 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9918).update(passive_part: 'TRANSPORTES Y SUMINISTROS PETROLEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9899).update(passive_part: 'SUBRED CENTRO ORIENTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9740).update(passive_part: 'HOSPITALES TUNAL Y SIMON BOLIVAR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9545).update(passive_part: 'HOSPITAL DE SUBA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9296).update(passive_part: 'HOSPITAL MILITAR CENTRAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9266).update(passive_part: 'HOSPITAL MILITAR CENTRAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9175).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9031).update(passive_part: 'HOSPITAL SAN CARLOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9027).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9021).update(passive_part: 'EAAB',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8883).update(passive_part: 'HOSPITAL MILITAR CENTRAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8816).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8727).update(passive_part: 'HOSPITAL LA SAMARITANA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8471).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8422).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8268).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8267).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7961).update(passive_part: 'HOSPITAL DE SUBA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7944).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7739).update(passive_part: 'INSTITUTO NACIONAL DE CANCEROLOGIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7714).update(passive_part: 'HOSPITAL LA SAMARITANA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7665).update(passive_part: 'MINISTERIO DEL INTERIOR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7624).update(passive_part: 'ALIANZA FIDUCIARIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7597).update(passive_part: 'HOSPITAL SAN BLAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7579).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7327).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7271).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7127).update(passive_part: 'HOSPITAL INFANTIL DE SAN JOSE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6985).update(passive_part: 'HOSPITAL CLINIICA SAN RAFAEL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6984).update(passive_part: 'SALUD TOTAL EPS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6904).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6542).update(passive_part: 'CAPRECOM',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6511).update(passive_part: 'SALUD TOTAL EPS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6475).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6423).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6418).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6360).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6267).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6153).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6077).update(passive_part: 'EAAB',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6044).update(passive_part: 'HOSPITAL SAN JOSE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1852).update(passive_part: 'HOSPITAL SAN CARLOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1847).update(passive_part: 'FUNDACION MEDICO PREVENTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1843).update(passive_part: 'CONGREGACION DOMINICAS STA CATALINA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1775).update(passive_part: 'FUNDACION CARDIO INFANTIL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1712).update(passive_part: 'EAAB',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1694).update(passive_part: 'MARTHA DOLLY CACERES OVIEDO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1661).update(passive_part: 'HOSPITAL SIMON BOLIVAR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1655).update(passive_part: 'EAAB',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1652).update(passive_part: 'IDU',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1624).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1609).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1602).update(passive_part: 'LA PREVISORA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1596).update(passive_part: 'INVIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1538).update(passive_part: 'PREVISORA  QBE SEGUROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1458).update(passive_part: 'HOSPITAL DE SUBA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1438).update(passive_part: 'SALUD TOTAL EPS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1428).update(passive_part: 'HOSPITALES SAN RAFAEL Y TUNAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1424).update(passive_part: 'IDU',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1423).update(passive_part: 'HOSPITAL DE SUBA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1414).update(passive_part: 'IDU',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1392).update(passive_part: 'HOSPITAL DE KENNEDY',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1326).update(passive_part: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1312).update(passive_part: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(102).update(passive_part: 'CLINICA DEL META',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1834).update(passive_part: 'HOSPITAL DE KENNEDY',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1726).update(passive_part: 'HOSPITAL SIMON BOLIVAR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1717).update(passive_part: 'HOSPITAL ENGATIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1672).update(passive_part: 'ETB',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1591).update(passive_part: 'DAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
