class UpdatingM01 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(22322).update(id: 22322,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22219).update(id: 22219,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22097).update(id: 22097,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22093).update(id: 22093,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22031).update(id: 22031,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21988).update(id: 21988,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21967).update(id: 21967,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21962).update(id: 21962,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21951).update(id: 21951,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21941).update(id: 21941,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21914).update(id: 21914,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21910).update(id: 21910,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21896).update(id: 21896,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21895).update(id: 21895,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21854).update(id: 21854,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21816).update(id: 21816,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21806).update(id: 21806,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21804).update(id: 21804,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21728).update(id: 21728,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21717).update(id: 21717,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21715).update(id: 21715,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21714).update(id: 21714,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21712).update(id: 21712,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21708).update(id: 21708,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21707).update(id: 21707,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21706).update(id: 21706,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21596).update(id: 21596,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21594).update(id: 21594,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20843).update(id: 20843,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20777).update(id: 20777,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20620).update(id: 20620,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20458).update(id: 20458,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20446).update(id: 20446,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20443).update(id: 20443,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(235).update(id: 235,case_state: 'TERMINADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
