class Camilo4 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19).update(more_protections: 'MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(53).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(256).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(305).update(more_protections: 'MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(482).update(more_protections: 'SEGURO OBLITARORIO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1350).update(more_protections: 'RC SERVIDORES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1351).update(more_protections: 'POLIZA MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1473).update(more_protections: 'INFIDELIDAD Y RIESGOS FINANCIEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1638).update(more_protections: 'RCC Y RCE PARA OPERADORES DE TRANSPORTE MULIMODAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1671).update(more_protections: 'CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1680).update(more_protections: 'CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1681).update(more_protections: 'MUERTE O LESIONES A DOS O MAS PERSONAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1739).update(more_protections: 'ERRORES U OMISIONES PROFESIONALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1779).update(more_protections: 'CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1803).update(more_protections: 'RC DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1844).update(more_protections: 'RESPONSABILIDAD CIVIL  SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1856).update(more_protections: 'RC SERVIDORES Y ADMINISTRADORES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1857).update(more_protections: 'RC SERVIDORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2201).update(more_protections: 'TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2207).update(more_protections: 'DANOS CORPORALES CAUSADOS E ACCIDENTE DE TRANSITO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2472).update(more_protections: 'RESPONSABILIDAD CIVIL CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2591).update(more_protections: 'SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2955).update(more_protections: 'VEHICULOS PROPIOS Y NO PROPIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2964).update(more_protections: 'GASTOS MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3302).update(more_protections: 'SEGURO CUMPLIMIENTO POLIZA UNICA A FAVOR DE ENTIDADES ESTATALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3480).update(more_protections: 'RC  CONTRATISTA DEPENDIENTE Y  SUBCONTRATISTAS INDEPENDIENTES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3494).update(more_protections: 'DANOS A BIENES DE TERCEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3563).update(more_protections: 'MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3661).update(more_protections: 'COBERTURA BASICA DE TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3672).update(more_protections: 'RC VEHICULOS PROPIOS Y NO PROPIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4393).update(more_protections: 'SUSTRACCION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4448).update(more_protections: 'FALLAS EN SUMINISTRO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4562).update(more_protections: 'POLIZA DE SEGURO DE ACCIDENTES PERSONALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4621).update(more_protections: 'CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4651).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4653).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5541).update(more_protections: 'RESPONSABILIDAD PARA SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5687).update(more_protections: 'RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5723).update(more_protections: 'DANOS MORALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5756).update(more_protections: 'RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5783).update(more_protections: 'RESPONSABILIDAD CIVIL CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5824).update(more_protections: 'RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5883).update(more_protections: 'RESPONSABILIDAD CIVIL PROFESIONAL MEDICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5942).update(more_protections: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6227).update(more_protections: 'AUTOMOVILES POLIZA INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6230).update(more_protections: 'AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6281).update(more_protections: 'MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6291).update(more_protections: 'RESPONSABILIDAD CIVIL CONTRACTUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6381).update(more_protections: 'RC SERVIDORES PUBLICOS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6473).update(more_protections: 'INEXISTENCIA DE COBERTURA EN RAZON AL OBJETO DE LA POLIZA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6570).update(more_protections: 'PREVIALCALDIAS MULTIRIESGO CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6612).update(more_protections: 'AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6613).update(more_protections: 'PFREVIALCALDIAS MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6661).update(more_protections: 'COBERTURA RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6669).update(more_protections: 'COBERTURA RC DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6740).update(more_protections: 'GASTOS MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6743).update(more_protections: 'COLECTIVA AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6826).update(more_protections: 'EN EL PRESENTE PROCESO NO HAY POLIZA CON LA CUAL SE NOS HAYA VINCULADO SOMOS DEMANDOS DIRECTOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6846).update(more_protections: 'RESPONSABILIDAD CIVIL PROFESIONALES MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6855).update(more_protections: 'PREVIPYME POLIZA MULTIRIESGO RC EXTRACONTRACTUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6865).update(more_protections: 'COLECTIVA AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7013).update(more_protections: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7029).update(more_protections: 'CUMPLIMIENTO Y BUEN MANEJO DE ANTICIPO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7060).update(more_protections: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7121).update(more_protections: 'AUTOMOVILES INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7137).update(more_protections: 'RESPONSABILIDAD CIVIL DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7254).update(more_protections: 'MUERTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7351).update(more_protections: 'SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7366).update(more_protections: 'MULTIRRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7367).update(more_protections: 'ESTUDIANTES INSTITUCIONES EDUCATIVAS MUNICIPIO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7387).update(more_protections: 'AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7391).update(more_protections: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7396).update(more_protections: 'SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7409).update(more_protections: 'AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7462).update(more_protections: 'SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7521).update(more_protections: 'AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7536).update(more_protections: 'RCE NO 3910 BAJO LA MODALIDAD DE COASEGURO EXPEDIDA POR COLSEGUROS SA HOY ALLIANZ SEGUROS SA LIDER EN UN 60 PORCIENTO JUNTO CON LAS COMPANIAS SEGUROS GENERALES SURAMERICANA SA 20 PORCIENTO Y LA PREVISORA SA COMPANIA DE SEGUROS 20 PORCIENTO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7595).update(more_protections: 'POLIZA MULTIRIESGO PREVIALCALDIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7623).update(more_protections: 'AVIACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7658).update(more_protections: 'SEGURO AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7754).update(more_protections: 'SEGURO AUTOMOVILES POLIZA INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7758).update(more_protections: 'DANOS MATERIALES COMBINADOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7794).update(more_protections: 'SEGURO DE VIDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7900).update(more_protections: 'SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7982).update(more_protections: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8005).update(more_protections: 'SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8023).update(more_protections: 'MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8060).update(more_protections: 'POLIZA MULTIRIESGO PREVIALCALDIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8259).update(more_protections: 'SEGURO PREVIALCALDIAS POLIZA MULTIERIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8400).update(more_protections: 'SEGURO DE VIDA GRUPO FUNCIONARIOS CONSEJO SUPERIOR DE LA JUDICATURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8444).update(more_protections: 'RESPONSABILIDAD CIVIL PARA MIEMBROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8711).update(more_protections: 'RESPONSABILIDAD CIVIL SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8858).update(more_protections: 'POLIZA COLECTIVA DE AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8974).update(more_protections: 'RC PROFESIONAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9080).update(more_protections: 'INCENDIO O EXPLOSION ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9293).update(more_protections: 'PERDIDA MENOR POR DANOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9301).update(more_protections: 'SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9592).update(more_protections: 'MUERTE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9615).update(more_protections: 'RESPONSABILIDAD CIVIL  SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9790).update(more_protections: 'TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9970).update(more_protections: 'SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10045).update(more_protections: 'RESPONSABILIDAD CIVIL DE SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11386).update(more_protections: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11408).update(more_protections: 'DELITOS CONTRA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12999).update(more_protections: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13006).update(more_protections: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13017).update(more_protections: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13114).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13250).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13567).update(more_protections: 'COBERTURA GLOBAL DE MANEJO OFICIAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13598).update(more_protections: 'INCENDIO SUSTRACCION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13621).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13622).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13624).update(more_protections: 'INCENDIO  SUSTRACCION  CORRIENTE DEBIL  MANEJO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14386).update(more_protections: 'MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14635).update(more_protections: 'DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14670).update(more_protections: 'MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14691).update(more_protections: 'MANEJO DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14718).update(more_protections: 'COBERTURA RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14887).update(more_protections: 'MANEJO OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15184).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15424).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15426).update(more_protections: 'RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15474).update(more_protections: 'MANEJO SECTOR OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15476).update(more_protections: 'RESPONSABILIDAD CIVIL SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15739).update(more_protections: 'MANEJO OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15741).update(more_protections: 'MANEJO OFICIAL   COBERTURA GLOBAL DE MANEJO OFICIAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18876).update(more_protections: 'PREVIALCALDIAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19385).update(more_protections: 'RESPONSABILIDAD CIVIL DE SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19391).update(more_protections: 'ACTOS INCORRECTOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19694).update(more_protections: 'MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20172).update(more_protections: 'VIDA GRUPO',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
