class Upd12 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(22136).update(reserved_fees_cents: 121600,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21825).update(reserved_fees_cents: 300000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12811).update(reserved_fees_cents: 2000000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12745).update(reserved_fees_cents: 4889220,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12722).update(reserved_fees_cents: 101098,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12721).update(reserved_fees_cents: 95601,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12715).update(reserved_fees_cents: 24937,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12714).update(reserved_fees_cents: 1000000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12699).update(reserved_fees_cents: 576507,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12580).update(reserved_fees_cents: 99417,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12569).update(reserved_fees_cents: 600000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12532).update(reserved_fees_cents: 200000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12496).update(reserved_fees_cents: 88238,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12477).update(reserved_fees_cents: 315601,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12475).update(reserved_fees_cents: 232824,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12455).update(reserved_fees_cents: 600000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12401).update(reserved_fees_cents: 106142,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12396).update(reserved_fees_cents: 93416,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12393).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12392).update(reserved_fees_cents: 200000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12297).update(reserved_fees_cents: 600000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12259).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12206).update(reserved_fees_cents: 340000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12205).update(reserved_fees_cents: 3000000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12203).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12194).update(reserved_fees_cents: 340000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12192).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12191).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11810).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11620).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11619).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11561).update(reserved_fees_cents: 808,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11559).update(reserved_fees_cents: 9515566,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11433).update(reserved_fees_cents: 2200000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11403).update(reserved_fees_cents: 50000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11231).update(reserved_fees_cents: 500000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10913).update(reserved_fees_cents: 79054,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10442).update(reserved_fees_cents: 720000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10273).update(reserved_fees_cents: 149272,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10259).update(reserved_fees_cents: 3000000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5394).update(reserved_fees_cents: 2730000,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3747).update(reserved_fees_cents: 609375,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2843).update(reserved_fees_cents: 804375,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2618).update(reserved_fees_cents: 1613689,state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
