class AddingAttornies < ActiveRecord::Migration[5.1]

  def change

    Attorny.create(code: 0, name: 'MIGRADOR')
    Attorny.create(code: 2, name: 'SERGIO ALEJANDRO VILLEGAS AGUDELO')
    Attorny.create(code: 3, name: 'JUAN FERNANDO ARBELAEZ')
    Attorny.create(code: 4, name: 'MATEO PELAEZ GARCIA')
    Attorny.create(code: 5, name: 'BEATRIZ ELENA ESTRADA TOBON')
    Attorny.create(code: 9, name: 'JUAN CAMILO ARANGO RIOS')
    Attorny.create(code: 21, name: 'MONTANO COVALEDA ANA PIEDAD')
    Attorny.create(code: 26, name: 'BARRIOS VELEZ Y ASOCIADOS - REPRESENTANTE LEGAL RICARDO VELEZ OCHOA')
    Attorny.create(code: 43, name: 'BARON SERNA GLORIA MERCEDES')
    Attorny.create(code: 49, name: 'SUAREZ Y NUNEZ ASOCIADOS LTDA - JOSE ANTONIO CACERES')
    Attorny.create(code: 65, name: 'FORERO GONZALEZ FRANCISCO YESIT')
    Attorny.create(code: 72, name: 'MORA CABRERA MARLIO')
    Attorny.create(code: 76, name: 'CARLOS E QUIJANO R ABOGADOS CONSULTORES SAS')
    Attorny.create(code: 79, name: 'GARCIA HARKER CARLOS FRANCISCO')
    Attorny.create(code: 87, name: 'DIEGO DE JESUS VELEZ ACEVEDO')
    Attorny.create(code: 91, name: 'OSCAR ELIAS BOTERO')
    Attorny.create(code: 94, name: 'MULFORD CARBONELL ROSARIO')
    Attorny.create(code: 99, name: 'SALAZAR AVENIA JORGE ELIECER')
    Attorny.create(code: 102, name: 'OLIVELLA VILORIA HUGUES ALFONSO')
    Attorny.create(code: 103, name: 'ANDRADE DE AVILA ANTONIO')
    Attorny.create(code: 104, name: 'YAMA SANTACRUZ CLAUDIO HENRY')
    Attorny.create(code: 109, name: 'AYCARDY GALEANO LILLI ESTHER')
    Attorny.create(code: 111, name: 'CUELLAR SALAS JOAQUIN')
    Attorny.create(code: 114, name: 'LASPRILLA VASQUEZ ORLANDO')
    Attorny.create(code: 116, name: 'ARISTIZABAL MARIN HAROLD')
    Attorny.create(code: 127, name: 'AREVALO TORRES MARINA')
    Attorny.create(code: 128, name: 'MARIA CAROLINA ECHEVERRI GONZALEZ')
    Attorny.create(code: 157, name: 'ZARATE LOPEZ JUAN DAVID')
    Attorny.create(code: 176, name: 'GOMEZ RODRIGUEZ BELLA SOBEIDA')
    Attorny.create(code: 204, name: 'BURBANO CORTES GUILLERMO ENRIQUE')
    Attorny.create(code: 237, name: 'VELEZ BARRERA JORGE ANTONIO')
    Attorny.create(code: 243, name: 'VILLANUEVA SEPULVEDA OSCAR IVAN')
    Attorny.create(code: 295, name: 'HERRERA AVILA GUSTAVO ALBERTO')
    Attorny.create(code: 298, name: 'JOAQUIN DE JESUS CASTANO')
    Attorny.create(code: 331, name: 'JORGE AUGUSTO FRANCO GIRALDO')
    Attorny.create(code: 333, name: 'NATALIA BOTERO ZAPATA')
    Attorny.create(code: 349, name: 'RIOS SILVA Y CIA SAS - OSCAR ORLANDO RIOS SILVA')
    Attorny.create(code: 353, name: 'NOVOA VILLAMIL MILCIADES')
    Attorny.create(code: 356, name: 'CHAVEZ JIMENEZ DORICELLI')
    Attorny.create(code: 360, name: 'ALVAREZ LOPEZ Y ABOGADOS ASOCIADOS - FABIO ALVAREZ LOPEZ')
    Attorny.create(code: 362, name: 'AREVALO RONCANCIO HERNAN')
    Attorny.create(code: 363, name: 'URIBE DE URBINA LUIS FERNANDO')
    Attorny.create(code: 366, name: 'SENECAR LTDA - SERVIO TULIO CAICEDO')
    Attorny.create(code: 370, name: 'LOPEZ CASTANO ANGELA MARIA')
    Attorny.create(code: 379, name: 'MORENO GARCIA ABOGADOS ASOCIADOS - HUGO MORENO ECHEVERRY')
    Attorny.create(code: 381, name: 'ZARTA ARIZABALETA Y ASOCIADOS LTDA - ZARTA ARIZABALETA JOSE FERNANDO')
    Attorny.create(code: 382, name: 'FABIO PEREZ QUESADA SAS')
    Attorny.create(code: 390, name: 'VARGAS VARGAS CARLOS ANDRES')
    Attorny.create(code: 396, name: 'CIFUENTES NEIRA CARLOS')
    Attorny.create(code: 397, name: 'BERNAL CALVO JOSE DEL CARMEN')
    Attorny.create(code: 400, name: 'PENALOZA PABON GIOVANNY ALBERTO')
    Attorny.create(code: 409, name: 'ALVARO AUGUSTO GOMEZ MONTES')
    Attorny.create(code: 410, name: 'LINA MARIA URIBE ZULUAGA')
    Attorny.create(code: 413, name: 'JURIDICA DE SEGUROS DEL CARIBE SA JURIDICARIBE')
    Attorny.create(code: 415, name: 'WAGENER HOLLMAN MANFRED CARLOS')
    Attorny.create(code: 420, name: 'LUISA VELASQUEZ ABOGADOS SAS - LUISA FERNANDA VELASQUEZ ANGEL')
    Attorny.create(code: 421, name: 'PUENTES DIANA MILENA')
    Attorny.create(code: 423, name: 'I LEX GRUPO CONSULTOR SAS - MARISOL DUQUE OSSA')
    Attorny.create(code: 425, name: 'FIRMA DE ABOGADOS JACQUELINE ROMERO ESTRADA SAS - ROMERO ESTRADA JACQUELINE')
    Attorny.create(code: 426, name: 'MARIA PATRICIA RIOS CORREA')
    Attorny.create(code: 428, name: 'ESCUDERO GIRALDO ASOCIADOS - JUAN PABLO GIRALDO')
    Attorny.create(code: 429, name: 'URRIAGO ZAPATA LUIS HELMER')
    Attorny.create(code: 430, name: 'OLAYA CUERVO MIKY FERNANDO')
    Attorny.create(code: 431, name: 'GALEANO Y ASOCIADOS TECNICOS Y ABOGADOS EN SEGUROS SAS - GALEANO GERMAN RICARDO')
    Attorny.create(code: 432, name: 'GIL ROA ABOGADOS SAS')
    Attorny.create(code: 435, name: 'GOMEZ VELEZ ALBA INES')
    Attorny.create(code: 437, name: 'AMAYA OLARTE ORLANDO JESUS')
    Attorny.create(code: 438, name: 'ARIZA Y GOMEZ ASOCIADOS')
    Attorny.create(code: 442, name: 'BUITRAGO FLOREZ DIEGO')
    Attorny.create(code: 444, name: 'DAVILA Y BERMUDEZ ABOGADOS - ANTONIO LUIS DAVILA')
    Attorny.create(code: 448, name: 'ALVAREZ Y HERNANDEZ ABOGADOS SAS - JHON FREDY ALVAREZ CARMAGO')
    Attorny.create(code: 452, name: 'SANABRIA ARTURO')
    Attorny.create(code: 453, name: 'GOMEZ SALAZAR OLGA LUCIA')
    Attorny.create(code: 454, name: 'LUIS FERNANDO MEJIA SERNA')
    Attorny.create(code: 455, name: 'SANCLEMENTE TORRES DIANA')
    Attorny.create(code: 457, name: 'BERNAL RINCON ABOGADOS SAS')
    Attorny.create(code: 458, name: 'PILONIETA RUEDA MIREYA')
    Attorny.create(code: 459, name: 'JOSE MIGUEL ARANGO ISAZA')
    Attorny.create(code: 461, name: 'JULIO CESAR YEPES')
    Attorny.create(code: 463, name: 'ASTUDILLO ABOGADOS - CLAUDIA PATRICIA ASTUDILLO')
    Attorny.create(code: 464, name: 'DIONISIO ARAUJO ABOGADOS Y CONSULTORES')
    Attorny.create(code: 466, name: 'NANDAR CASTELLANOS ROBERTO')
    Attorny.create(code: 467, name: 'LOPEZ PENA EDMER LEANDRO')
    Attorny.create(code: 666, name: 'YURANY HASBLEIDI  NOPE ORTEGA')
    Attorny.create(code: 999, name: 'GHERRERA Y ASOCIADOS SAS - DUBERNEY RESTREPO VILLADA')
    Attorny.create(code: 233260, name: 'GALEANO Y ASOCIADOSTECNICOS Y ABOGADOS EN SEGUROS SAS - JAVIER LANDINEZ MONTANEZ')
    
  end

end
