class Al03 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(307).update(id: 307,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(368).update(id: 368,passive_part: 'IMPLICADOS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(449).update(id: 449,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(450).update(id: 450,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(452).update(id: 452,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(454).update(id: 454,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1753).update(id: 1753,passive_part: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8063).update(id: 8063,passive_part: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11218).update(id: 11218,passive_part: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12005).update(id: 12005,passive_part: 'MUNICIPIO DE VELEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12858).update(id: 12858,passive_part: 'MUNICIPIO DE SAN JOSE DE URE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12934).update(id: 12934,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12962).update(id: 12962,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13004).update(id: 13004,passive_part: 'CAROLINA SUAREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13053).update(id: 13053,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13111).update(id: 13111,passive_part: 'ANDRES ALBERTO NARVAEZ SANCHEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13192).update(id: 13192,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13302).update(id: 13302,passive_part: 'PENDIENTE AUTO DE APERTURA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13411).update(id: 13411,passive_part: 'ALFREDO VEGA QUINTERO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13437).update(id: 13437,passive_part: 'FRANCO ROMERO RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13440).update(id: 13440,passive_part: 'FRANCO ROMERO RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13441).update(id: 13441,passive_part: 'FRANCO ROMERO RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13442).update(id: 13442,passive_part: 'FRANCO ROMERO RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13570).update(id: 13570,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13574).update(id: 13574,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13819).update(id: 13819,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13826).update(id: 13826,passive_part: 'INTERVINIENTES ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13869).update(id: 13869,passive_part: 'SAULO QUINONES GARCIA EDISON HURTADO VALENCIA Y NAVIA MARIA RIASCOS RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14077).update(id: 14077,passive_part: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14084).update(id: 14084,passive_part: 'MANUEL AGUSTIN CUELLAR ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14179).update(id: 14179,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14245).update(id: 14245,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14397).update(id: 14397,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14431).update(id: 14431,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14441).update(id: 14441,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14505).update(id: 14505,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14524).update(id: 14524,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14602).update(id: 14602,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14644).update(id: 14644,passive_part: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14664).update(id: 14664,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14679).update(id: 14679,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14680).update(id: 14680,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14682).update(id: 14682,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14684).update(id: 14684,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14689).update(id: 14689,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14741).update(id: 14741,passive_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14783).update(id: 14783,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14794).update(id: 14794,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14819).update(id: 14819,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14867).update(id: 14867,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14895).update(id: 14895,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14918).update(id: 14918,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14958).update(id: 14958,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14998).update(id: 14998,passive_part: 'OVIRIS CARABALLO SALGADO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15017).update(id: 15017,passive_part: 'FRANCISCO VEGA ARRAUTH Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15018).update(id: 15018,passive_part: 'JUDITH PINEDO FLOREZ   ALICIA SAENZ DE MARENCO YOTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15019).update(id: 15019,passive_part: 'ALBERTO BERNAL JIMENEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15020).update(id: 15020,passive_part: 'GABRIEL VERGARA LAGO CARLOS BARRERA SANCHEZ  AQUILES RODRIGUEZ RIBON JORGE VASQUEZ PJARO JESUS RADA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15025).update(id: 15025,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15027).update(id: 15027,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15168).update(id: 15168,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15224).update(id: 15224,passive_part: 'ALBERTO BERNAL JIMENEZ  JORGE MENDOZA DIAGO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15507).update(id: 15507,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15772).update(id: 15772,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15911).update(id: 15911,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15912).update(id: 15912,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15991).update(id: 15991,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16003).update(id: 16003,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16007).update(id: 16007,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16021).update(id: 16021,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16024).update(id: 16024,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16048).update(id: 16048,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16049).update(id: 16049,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16052).update(id: 16052,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16141).update(id: 16141,passive_part: 'IMPLIC',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16146).update(id: 16146,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16186).update(id: 16186,passive_part: 'JOSE JOAQUIN MONZO AVEDANO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16190).update(id: 16190,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16204).update(id: 16204,passive_part: 'MUNICIPIO DE OROCUE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16206).update(id: 16206,passive_part: 'JAVIER AUGUSTO ALVAREZ ALFONSO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16207).update(id: 16207,passive_part: 'ANA CONSTANZA HERNANDEZ RODRIGUEZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16209).update(id: 16209,passive_part: 'JAVIER AUGUSTO ALVAREZ ALFONSO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16210).update(id: 16210,passive_part: 'CLAYRE MILENA MORALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16212).update(id: 16212,passive_part: 'CLAYRE MILENA MORALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16213).update(id: 16213,passive_part: 'CLAYRE MILENA MORALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16218).update(id: 16218,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16227).update(id: 16227,passive_part: 'JAVIER AUGUSTO ALVAREZ ALFONSO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16228).update(id: 16228,passive_part: 'CLAYRE MILENA MORALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16229).update(id: 16229,passive_part: 'JOSUE ALEXANDER BOHORQUEZ PENA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16230).update(id: 16230,passive_part: 'JOSUE ALEXANDER BOHORQUEZ PENA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16231).update(id: 16231,passive_part: 'CARMELO MARTINEZ MOTAVITA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,passive_part: 'SERGIO HERNANDEZ GAMARRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16250).update(id: 16250,passive_part: 'CAPRESOCA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16259).update(id: 16259,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16264).update(id: 16264,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16272).update(id: 16272,passive_part: 'LESBIA BELENO PUELLO  MABEL MEZA MARTINEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,passive_part: 'JULIO ALANDETE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16317).update(id: 16317,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16318).update(id: 16318,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,passive_part: 'JOSE MESTRE LOMBANA  ANTONIO APONTE RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16411).update(id: 16411,passive_part: 'DOUGLAS PAEZ SOSA Y MARTA CARVAJAL HERRERA ROBERTO USECHE VIVIAN ELJAIEK Y JUDITH PINEDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,passive_part: 'JOSE SAAVEDRA  RAMIRO PEREIRA  Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16468).update(id: 16468,passive_part: 'CARLOS ZAYAS Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16501).update(id: 16501,passive_part: 'HELI CALA LOPEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,passive_part: 'CARLOS ZAYAS Y LUIS ALVARADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,passive_part: 'FUNDACION MULTIACTIVA AHINCO JOSE SAAVEDRA  ECE HOSPITAL SAN ANTONIO DE PADUA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,passive_part: 'CARLOS ZAYAS Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,passive_part: 'RUBYS MENCO CONTRERAS COOPBRETON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16578).update(id: 16578,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,passive_part: 'JUAN ESCANO RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16654).update(id: 16654,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,passive_part: 'CARLOS ZAYAS ROJAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16737).update(id: 16737,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,passive_part: 'MAGALY DE LA ROSA ESPINOSA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16799).update(id: 16799,passive_part: 'CARLOS ZAYAS  Y LUIS ALVARADO PENA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,passive_part: 'FERNANDO TINOCO TAMARA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16827).update(id: 16827,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16888).update(id: 16888,passive_part: 'CARLOS ZAYAS  Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16921).update(id: 16921,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17012).update(id: 17012,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17013).update(id: 17013,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17014).update(id: 17014,passive_part: 'GEOVALDS GONZALEZ JIMENEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17027).update(id: 17027,passive_part: 'NELSON RICARDO MARINO VELANDIA Y OTRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17028).update(id: 17028,passive_part: 'JUDITH PINEDO FLOREZ  JULIO ALANDETE ARROYO  Y NORMA ROMAN LEYGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17030).update(id: 17030,passive_part: 'MEDIMARKETING LTDA   RAMIRO TURIZO  Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17095).update(id: 17095,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17096).update(id: 17096,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17098).update(id: 17098,passive_part: 'FRANCISCO VEGA ARRAUTH  Y  FABIO SALOM GALVAN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17099).update(id: 17099,passive_part: 'MIGUEL ARNEDO MYRON MARTINEZ RAMOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17103).update(id: 17103,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17113).update(id: 17113,passive_part: 'CLAYRE MILENA MORALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17114).update(id: 17114,passive_part: 'RUBEN DARIO HIGUERA MARQUEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17117).update(id: 17117,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17123).update(id: 17123,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17127).update(id: 17127,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17129).update(id: 17129,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17149).update(id: 17149,passive_part: 'JORGE MENDOZA DIAGO   EMIRO PASCUAL PINTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17164).update(id: 17164,passive_part: 'NELSON BENJAMIN BARRETO VACA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17166).update(id: 17166,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17173).update(id: 17173,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17189).update(id: 17189,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17199).update(id: 17199,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17288).update(id: 17288,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17292).update(id: 17292,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17329).update(id: 17329,passive_part: 'NICOLAS CURI VERGARA  Y  OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17332).update(id: 17332,passive_part: 'AMER BAYUELO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17339).update(id: 17339,passive_part: 'MEDIMARKETING LTDA   RAMIRO CLARET  ANTONIO BARRIOS Y ALBERTO BERNAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17340).update(id: 17340,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17350).update(id: 17350,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17367).update(id: 17367,passive_part: 'JESUS FERNANDO SANDOVAL CHAQUEA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17371).update(id: 17371,passive_part: 'GEOVALDIS GONZALEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17382).update(id: 17382,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17398).update(id: 17398,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17399).update(id: 17399,passive_part: 'CONSTRUCCIONES CIVILES S A   CICON S A   INGECON S A   ENRIQUE CHARTUNI',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17401).update(id: 17401,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(id: 17402,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17403).update(id: 17403,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17409).update(id: 17409,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17411).update(id: 17411,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17412).update(id: 17412,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17421).update(id: 17421,passive_part: 'LEYLA ORTEGA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17427).update(id: 17427,passive_part: 'LUZ NELLY TORRES PEREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17428).update(id: 17428,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17431).update(id: 17431,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17432).update(id: 17432,passive_part: 'RAUL FLOREZ CHAVEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17438).update(id: 17438,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17439).update(id: 17439,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17440).update(id: 17440,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17442).update(id: 17442,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17454).update(id: 17454,passive_part: 'BEATRIZ DE LA PENA   PRODESC Y  ROGELIO PIMIENTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17455).update(id: 17455,passive_part: 'BEATRIZ DE LA PENA CASTRO   BEATRIZ   Y   COOSALUD',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17456).update(id: 17456,passive_part: 'BEATRIZ EUGENIA DE LA PENA CASTRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17464).update(id: 17464,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17467).update(id: 17467,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17473).update(id: 17473,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17475).update(id: 17475,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17477).update(id: 17477,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17481).update(id: 17481,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17482).update(id: 17482,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17487).update(id: 17487,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17488).update(id: 17488,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17490).update(id: 17490,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17497).update(id: 17497,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17498).update(id: 17498,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17499).update(id: 17499,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17502).update(id: 17502,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17507).update(id: 17507,passive_part: 'BEATRIZ DE LA PENA CASTRO   ABEL ORDOSGOITIA MEJIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17508).update(id: 17508,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17531).update(id: 17531,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17555).update(id: 17555,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17556).update(id: 17556,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17559).update(id: 17559,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17563).update(id: 17563,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17564).update(id: 17564,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17571).update(id: 17571,passive_part: 'MYRON MARTINEZ RAMOS  ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17572).update(id: 17572,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17576).update(id: 17576,passive_part: 'HELI CALA LOPEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17589).update(id: 17589,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17599).update(id: 17599,passive_part: 'MARIA DEL ROSARIO URQUIJO DE VASQUEZ   MAYRA ROMERO DE HAYDAR   ANTONIO MORALES CASTILLO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17600).update(id: 17600,passive_part: 'EFRAIN ORTIZ ALCALA   Y  MARIA DEL ROSARIO URQUIJO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17602).update(id: 17602,passive_part: 'EFRAIN ORTIZ ALCALA   MARIA DEL ROSARIO URQUIJO DE VASQUEZ Y RUBEN CARAZO CARRASQUILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17603).update(id: 17603,passive_part: 'MARIA DEL ROSARIO URQUIJO   Y  RODOLFO OSPINO PACHECO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17615).update(id: 17615,passive_part: 'FRANCISCO VEGA ARRAUTH  DANIELLYS PENARANDA  SOLUCIONES INFORMATICAS SAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17620).update(id: 17620,passive_part: 'FREDY TELLO AMADO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17629).update(id: 17629,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17645).update(id: 17645,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17654).update(id: 17654,passive_part: 'JULIO CASTELLON MARTINEZ Y  MELBA MERCADO CERVANTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17655).update(id: 17655,passive_part: 'VERENA POLO  JACQUELINE COHEN COGOLLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17658).update(id: 17658,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17665).update(id: 17665,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17667).update(id: 17667,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17672).update(id: 17672,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17673).update(id: 17673,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17675).update(id: 17675,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17678).update(id: 17678,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17692).update(id: 17692,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17693).update(id: 17693,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17725).update(id: 17725,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17726).update(id: 17726,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17744).update(id: 17744,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17745).update(id: 17745,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17746).update(id: 17746,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17749).update(id: 17749,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17751).update(id: 17751,passive_part: 'FABIO CASTELLANOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17755).update(id: 17755,passive_part: 'JOSE JOAQUIN MONZON ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17757).update(id: 17757,passive_part: 'ZULMA LILIANA GAMEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17775).update(id: 17775,passive_part: 'JUDITH PINEDO FLOREZ   JULIO ALANDETE ARROYO   NORMA ROMAN LEYGUES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17778).update(id: 17778,passive_part: 'INES GONFRIER SARMIENTO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17779).update(id: 17779,passive_part: 'JORGE CAMILO ABRIL TARACHE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17780).update(id: 17780,passive_part: 'MARTHA INES GONFIER SARMIENTO Y OTRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17786).update(id: 17786,passive_part: 'FRANCISCO VEGA ARRAUTH  DANIELLYS PENARANDA   ELMER NAVARRO HERNANDEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17787).update(id: 17787,passive_part: 'FRANCISCO VEGA ARRAUTH   DANIELLYS PENARANDA Y  ELMER NAVARRO HERNANDEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17795).update(id: 17795,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17797).update(id: 17797,passive_part: 'IVONNE ANDREA VELASQUEZ BONILLA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17798).update(id: 17798,passive_part: 'VITELIO VENITEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17801).update(id: 17801,passive_part: 'JOEL OLMOS CORDERO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17802).update(id: 17802,passive_part: 'VITELIO VENITEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17803).update(id: 17803,passive_part: 'JOSE MAURICIO  JIMENEZ PEREZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17804).update(id: 17804,passive_part: 'MARTHA INES GONFIER SARMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17805).update(id: 17805,passive_part: 'VITELIO VENITEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17813).update(id: 17813,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17815).update(id: 17815,passive_part: 'MUNICIPIO DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17816).update(id: 17816,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17821).update(id: 17821,passive_part: 'ALIX MORENO ROMERO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17829).update(id: 17829,passive_part: 'JULIETA GOMEZ DE CORTES Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17844).update(id: 17844,passive_part: 'LEONEL BOHORQUEZ BOHORQUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17853).update(id: 17853,passive_part: 'ALBERTO BERNAL JIMENEZ CIP CONSTRUCTORES LTDA GERMAN SIERRA ANAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17859).update(id: 17859,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17865).update(id: 17865,passive_part: 'ANTONIO BARRIOS BARRIOS  NESTOR RAMIREZ CAMARGO   MARIA BUELVAS MENDOZA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17871).update(id: 17871,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17874).update(id: 17874,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17879).update(id: 17879,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17884).update(id: 17884,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17885).update(id: 17885,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17886).update(id: 17886,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17887).update(id: 17887,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17888).update(id: 17888,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17889).update(id: 17889,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17890).update(id: 17890,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17891).update(id: 17891,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17892).update(id: 17892,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17894).update(id: 17894,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17901).update(id: 17901,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17918).update(id: 17918,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17926).update(id: 17926,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17931).update(id: 17931,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17942).update(id: 17942,passive_part: 'REINALDO GUIO CISNEROS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17943).update(id: 17943,passive_part: 'REINALDO GUIO CISNEROS Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17952).update(id: 17952,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17953).update(id: 17953,passive_part: 'ALBERTO BERNAL JIMENEZ  CORPORACION VIDA   GERMAN SIERRA ANAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17954).update(id: 17954,passive_part: 'ELSY ESPERANZA MADRID RIANO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17975).update(id: 17975,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17978).update(id: 17978,passive_part: 'LYDA MARCELA PEREZ RAMIREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17982).update(id: 17982,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17983).update(id: 17983,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17984).update(id: 17984,passive_part: 'LILIAN FERNANDA SALCEDO RESTREPO Y RAFAEL NAYIB FONSECA SAAD',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17985).update(id: 17985,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17988).update(id: 17988,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18005).update(id: 18005,passive_part: 'JAVIER MONTOYA SALCEDO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18008).update(id: 18008,passive_part: 'ANTONIO FLOREZ GARIZABAL  WALTER ARELLANO LACHARME',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18010).update(id: 18010,passive_part: 'ROBERTO USECHE VIVERO     ELIANA SERGE BOLANOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18011).update(id: 18011,passive_part: 'JUDITH PINEDO FLOREZ  ALEJANDRA ESPINOSA  JUDITH PEREZ RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18012).update(id: 18012,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18013).update(id: 18013,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18025).update(id: 18025,passive_part: 'ALGEMIRO PEREZ MORERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18026).update(id: 18026,passive_part: 'LEONEL BOHORQUEZ BOHORQUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18036).update(id: 18036,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18037).update(id: 18037,passive_part: 'JORGE CAMILO ABRIL TARACHE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18043).update(id: 18043,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18064).update(id: 18064,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18070).update(id: 18070,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18081).update(id: 18081,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18084).update(id: 18084,passive_part: 'LUIS BENEDETTI RACINES   SERGIO SUAREZ NIEVES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18085).update(id: 18085,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18087).update(id: 18087,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18088).update(id: 18088,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18089).update(id: 18089,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18095).update(id: 18095,passive_part: 'NANCY RINCON PAYARES   CONSTRUAMBIENTE LTDA   ELIO ANGEL MARRUGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18098).update(id: 18098,passive_part: 'JAVIER MONTOYA SALCEDO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18109).update(id: 18109,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18116).update(id: 18116,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18123).update(id: 18123,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18125).update(id: 18125,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18126).update(id: 18126,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18127).update(id: 18127,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18128).update(id: 18128,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18143).update(id: 18143,passive_part: 'ROBERTO USECHE VIVERO   CARLOS RODRIGUEZ CRISMATT  SERVITRUST GNB SUDAMERIS S A ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18147).update(id: 18147,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18150).update(id: 18150,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18153).update(id: 18153,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18155).update(id: 18155,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18156).update(id: 18156,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18157).update(id: 18157,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18180).update(id: 18180,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18181).update(id: 18181,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18183).update(id: 18183,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18184).update(id: 18184,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18187).update(id: 18187,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18188).update(id: 18188,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18189).update(id: 18189,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18192).update(id: 18192,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18200).update(id: 18200,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18201).update(id: 18201,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18202).update(id: 18202,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18203).update(id: 18203,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18224).update(id: 18224,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18227).update(id: 18227,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18249).update(id: 18249,passive_part: 'EDGAR ARRIETA CARABALLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18250).update(id: 18250,passive_part: 'TOMAS RODRIGUEZ MANOTAS   JORGE LUIS MORELOS  JUAN APARICIO MONCAYO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18251).update(id: 18251,passive_part: 'RAMON LEON HERNANDEZ   ANTONIO FLOREZ GARIZABAL  AUGUSTO MAINERO ROMAN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18268).update(id: 18268,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18273).update(id: 18273,passive_part: 'CARLOS GIRALDO GOMEZ  ORLANDO CARVAJAL  MARIO URAN Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18289).update(id: 18289,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18293).update(id: 18293,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18296).update(id: 18296,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18303).update(id: 18303,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18307).update(id: 18307,passive_part: 'GUSTAVO RAFAEL BUENDIA ELLES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18308).update(id: 18308,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18309).update(id: 18309,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18311).update(id: 18311,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18312).update(id: 18312,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18314).update(id: 18314,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18315).update(id: 18315,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18316).update(id: 18316,passive_part: 'JUDITH PINEDO FLOREZ  CAPRECOM   MEDISALUD CONSULTING Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18317).update(id: 18317,passive_part: 'JUDITH PINEDO FLOREZ  COOSALUD EPS S Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18319).update(id: 18319,passive_part: 'LUIS FERNANDO BENEDETTI RACINES  ISIS DUQUE PUPO  REMBERTO QUINTANA ESPINOSA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18320).update(id: 18320,passive_part: 'LUIS FERNANDO BENEDETTI RACINES SERGIO SUAREZ NIEVES  ANGELIS BARRIOS PADILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18321).update(id: 18321,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18340).update(id: 18340,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18344).update(id: 18344,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18346).update(id: 18346,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18347).update(id: 18347,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18349).update(id: 18349,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18350).update(id: 18350,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18353).update(id: 18353,passive_part: 'LUIS FERNANDO BENEDETTI RACINES  SERGIO SUAREZ NIEVES  ANGELIS BARRIOS PADILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18354).update(id: 18354,passive_part: 'EMIRO URUETA PADILLA   RAMON PEREZ YEPES  FERNANDO CUETO RIVERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18366).update(id: 18366,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18368).update(id: 18368,passive_part: 'IIMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18369).update(id: 18369,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18375).update(id: 18375,passive_part: 'TOMAS RODRIGUEZ   MARTA RODRIGUEZ   CLINICA BLAS DE LEZO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18376).update(id: 18376,passive_part: 'TOMAS RODRIGUEZ  MARTA RODRIGUEZ FUNDACION UNIDAD DE CUIDADOS INTENSIVOS DONA PILAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18377).update(id: 18377,passive_part: 'TOMAS RODIRGUEZ MARTA RODRIGUEZ   CLINICA GENERAL DEL CARIBE S A',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18378).update(id: 18378,passive_part: 'TOMAS RODRIGUEZ   MARTA RODRIGUEZ   CLINICA SOL DE LAS AMERICAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18379).update(id: 18379,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18380).update(id: 18380,passive_part: 'NERLIDES HERNANDEZFRANCO   Y   PATRICIA HERNANDEZ SANCHEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18382).update(id: 18382,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18384).update(id: 18384,passive_part: 'JORGE LEQUERICA ARAUJO   Y    GABRIEL JOSE BARRIOS BUSTILLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18385).update(id: 18385,passive_part: 'JORGE LEQUERICA ARAUJO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18398).update(id: 18398,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18425).update(id: 18425,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18428).update(id: 18428,passive_part: 'MARTHA INES GONFIER SARMIENTO Y OTRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18434).update(id: 18434,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18435).update(id: 18435,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18439).update(id: 18439,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18440).update(id: 18440,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18441).update(id: 18441,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18442).update(id: 18442,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18448).update(id: 18448,passive_part: 'ELSY ESPERANZA MADRID RIANO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18458).update(id: 18458,passive_part: 'MUNICIPIO DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18469).update(id: 18469,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18478).update(id: 18478,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18482).update(id: 18482,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18495).update(id: 18495,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18496).update(id: 18496,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18502).update(id: 18502,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18515).update(id: 18515,passive_part: 'ROLIN ALEXANDER ALARCON GARCIA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18517).update(id: 18517,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18518).update(id: 18518,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18520).update(id: 18520,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18524).update(id: 18524,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18525).update(id: 18525,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18527).update(id: 18527,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18535).update(id: 18535,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18604).update(id: 18604,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18609).update(id: 18609,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18621).update(id: 18621,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18624).update(id: 18624,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18625).update(id: 18625,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18632).update(id: 18632,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18639).update(id: 18639,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18640).update(id: 18640,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18646).update(id: 18646,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18676).update(id: 18676,passive_part: 'MUNICIPIO YOPAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18682).update(id: 18682,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18711).update(id: 18711,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18717).update(id: 18717,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18745).update(id: 18745,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18748).update(id: 18748,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18751).update(id: 18751,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18778).update(id: 18778,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18793).update(id: 18793,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18806).update(id: 18806,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18830).update(id: 18830,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18839).update(id: 18839,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18851).update(id: 18851,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18854).update(id: 18854,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18856).update(id: 18856,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18873).update(id: 18873,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18874).update(id: 18874,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18880).update(id: 18880,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18890).update(id: 18890,passive_part: 'DIRECCION DEL SECTOR EDUCACION CULTURA RECREACION Y DEPORTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18906).update(id: 18906,passive_part: 'EMPRESA DE ACUEDUCTOALCANTARILLADO Y ASEO DE BOGOTA ESP',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18943).update(id: 18943,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18953).update(id: 18953,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18970).update(id: 18970,passive_part: 'ARMANDO ADOLFO SEGURA EVAN Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18973).update(id: 18973,passive_part: 'MUNICIPIO DE VISTA HERMOSA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18985).update(id: 18985,passive_part: 'HOSPITAL DE YOPAL ESE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19055).update(id: 19055,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19063).update(id: 19063,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19110).update(id: 19110,passive_part: 'WILSON JAMES CASTANO  LUIS ORTIZ HERRERA MARLY JEREZ ARIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19288).update(id: 19288,passive_part: 'CARLOS BARRIOS GOMEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19305).update(id: 19305,passive_part: 'CARLOS BARRIOS GOMEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19474).update(id: 19474,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19481).update(id: 19481,passive_part: 'LUIS ALBERTO MONSALVO GNECCO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19483).update(id: 19483,passive_part: 'LEONARDO JOSE MAYA AMAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19484).update(id: 19484,passive_part: 'FREDYS MIGUEL SOCARRAS REALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19485).update(id: 19485,passive_part: 'LEONARDO JOSE MAYA AMAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19486).update(id: 19486,passive_part: 'LUIS FABIAN FERNANDEZ MAESTRE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19487).update(id: 19487,passive_part: 'LEONARDO JOSE MAYA AMAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19488).update(id: 19488,passive_part: 'LEONARDO JOSE MAYA AMAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19490).update(id: 19490,passive_part: 'LEONARDO JOSE MAYA AMAYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19615).update(id: 19615,passive_part: 'PENDIENTE AUTO DE APERTURA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19618).update(id: 19618,passive_part: 'PENDIENTE AUTO DE APERTURA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19668).update(id: 19668,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19672).update(id: 19672,passive_part: 'IMPLICADOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19733).update(id: 19733,passive_part: 'WILLIAM RODOLFO MARTINEZ SANTAMARIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19760).update(id: 19760,passive_part: 'INTERVINIENTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20175).update(id: 20175,passive_part: 'BARTOLO VALENCIA RAMOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20176).update(id: 20176,passive_part: 'BARTOLO VALENCIA RAMOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20177).update(id: 20177,passive_part: 'BARTOLO VALENCIA RAMOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20330).update(id: 20330,passive_part: 'MUNICIPIO DE ARMENIA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20382).update(id: 20382,passive_part: 'MUNICIPIO DE ARMENIA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20400).update(id: 20400,passive_part: 'MUNICIPIO DE MONTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20409).update(id: 20409,passive_part: 'MUNICIPIO DE MONITOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20462).update(id: 20462,passive_part: 'ESE HOSPITAL MARCO FIDEL SUAREZ DE BELLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,passive_part: 'GAVAVISION UNIDAD DE ESPECIALISTAS IPS NACION - MINISTERIO DE DEFENSA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,passive_part: 'DISPAC SA ESP',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,passive_part: 'TRANSPORTES PROGRESO DEL CHOCO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,passive_part: 'TRANSPORTE RAPIDO OCHOA SA Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,passive_part: 'JOSE ERLIN MURILLO SEGUROS GENERALES SURAMERICANA  LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20601).update(id: 20601,passive_part: 'ESE HOSPITAL SAN JUAN DE DIOS DEL MUNICIPIO DE MARINILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20602).update(id: 20602,passive_part: 'MUNICIPIO DE SAN PEDRO DE URABA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20603).update(id: 20603,passive_part: 'MUNICIPIO DE SAN PEDRO DE URABA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20604).update(id: 20604,passive_part: 'ESE HOSPITAL FRANCISCO VALDERRAMA DE TURBO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20605).update(id: 20605,passive_part: 'ESE HOSPITAL NUEVO HORIZONTE DE ABRIAQUI',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20635).update(id: 20635,passive_part: 'MUNICIPIO DE LA CEJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20644).update(id: 20644,passive_part: 'MUNICIPIO DE SANTA FE DE ANTIOQUIA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20645).update(id: 20645,passive_part: 'ESE HOSPITAL LA MERCED DEL MUNICIPIO DE CIUDAD BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20646).update(id: 20646,passive_part: 'MUNICIPIO DE REMEDIOS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20647).update(id: 20647,passive_part: 'MUNICIPIO DE REMEDIOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20648).update(id: 20648,passive_part: 'ESP DEL MUNICIPIO DE CARACOLI ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20649).update(id: 20649,passive_part: 'MUNICIPIO DE REMEDIOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20650).update(id: 20650,passive_part: 'MUNICIPIO DE REMEDIOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20651).update(id: 20651,passive_part: 'MUNICIPIO DE CIUDAD BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20658).update(id: 20658,passive_part: 'PUERTO NARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20661).update(id: 20661,passive_part: 'ESE HOSPITAL DEL MUNICIPIO DE PEQUE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20761).update(id: 20761,passive_part: 'MUNICIPIO DE GUARNE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20769).update(id: 20769,passive_part: 'MUNICIPIO DE SABANALARGA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20770).update(id: 20770,passive_part: 'MUNICIPIO DE TURBO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20787).update(id: 20787,passive_part: 'INPEC',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20956).update(id: 20956,passive_part: 'MUNICIPIO DE SANTIAGO DE CALI ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20988).update(id: 20988,passive_part: 'ESE SALUD PEREIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21024).update(id: 21024,passive_part: 'ESE HOSPITAL LA MARIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21138).update(id: 21138,passive_part: 'SECRETARIA DE SALUD DISTRITAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21173).update(id: 21173,passive_part: 'CARLOS EDUARDO CAICEDO-PABLO JOSE LACOUTUR-RAFAEL ALEJANDRO MARTINEZ-SANDER ALONSO RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21174).update(id: 21174,passive_part: 'HUGO ALBERTO CARRILLO-ARTURO ARIAS VILLA-LIDERTUR SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21175).update(id: 21175,passive_part: 'NESTOR GARCIA BUITRAGO-MARIA SUSANA MUHAMAD-SANDRA JABER MARTINEZ-SANDRA YOLIMA SGUERRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21176).update(id: 21176,passive_part: 'WILAMAR ROA MALAGON OMAR MAURICIO CARDENAS COLORADO CARLOS ENRIQUE CARVAJALINO MARIAM ALEJANDRA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
