class AddingAttornies < ActiveRecord::Migration[5.1]

  def change

    Attorny.create(name:'ALBA INES GOMEZ VELEZ', code:'00001')
    Attorny.create(name:'ALEX FONTALVO VELASQUEZ', code:'00002')
    Attorny.create(name:'ALEXANDRA PATRICIA TORRES HERRERA', code:'00003')
    Attorny.create(name:'ALMA ROCIO ARIZA FORTICH', code:'00004')
    Attorny.create(name:'ALVARO AUGUSTO GOMEZ MONTES', code:'00005')
    Attorny.create(name:'ANA INES GOMEZ CALDERON', code:'00006')
    Attorny.create(name:'ANA INES URIBE OSORIO', code:'00007')
    Attorny.create(name:'ANA MILENA VELASCO MUNOZ', code:'00008')
    Attorny.create(name:'ANA PIEDAD MONTANO COVALEDA', code:'00009')
    Attorny.create(name:'ANDRES ORION ALVAREZ PEREZ', code:'00010')
    Attorny.create(name:'ANGELA LOPEZ', code:'00011')
    Attorny.create(name:'ANGELA MARIA LOPEZ CASTANO', code:'00012')
    Attorny.create(name:'ANTONIO ANDRADE DE AVILA', code:'00013')
    Attorny.create(name:'ANTONIO LUIS DAVILA GARCIA', code:'00014')
    Attorny.create(name:'ARTURO SANABRIA GOMEZ', code:'00015')
    Attorny.create(name:'BEATRIZ ELENA ESTRADA TOBON', code:'00016')
    Attorny.create(name:'BELLA SOBEIDA GOMEZ RODRIGUEZ', code:'00017')
    Attorny.create(name:'BLANCA STELLA OROZCO RAMIREZ', code:'00018')
    Attorny.create(name:'CARLOS ALFONSO CIFUENTES NEIRA', code:'00019')
    Attorny.create(name:'CARLOS ANDRES VARGAS VARGAS', code:'00020')
    Attorny.create(name:'CARLOS EDUARDO GOMEZ GUTIERREZ', code:'00021')
    Attorny.create(name:'CARLOS ENRIQUE QUIJANO RUEDA', code:'00022')
    Attorny.create(name:'CARLOS FRANCISCO GARCIA HARKER', code:'00023')
    Attorny.create(name:'CHARLES CHAPMAN', code:'00024')
    Attorny.create(name:'CLARA PATRICIA RUBIANO ZALAMEA', code:'00025')
    Attorny.create(name:'CLARA SONIA PEREZ LOPEZ', code:'00026')
    Attorny.create(name:'CLAUDIA PATRICIA ASTUDILLO TIGREROS', code:'00027')
    Attorny.create(name:'CLAUDIA SOFIA FLOREZ MAHECHA', code:'00028')
    Attorny.create(name:'CLAUDIO HENRY YAMA SANTACRUZ', code:'00029')
    Attorny.create(name:'DANIEL ALEJANDRO PALACIOS BALLEN', code:'00030')
    Attorny.create(name:'DIANA LESLIE BLANCO ARENAS', code:'00031')
    Attorny.create(name:'DIANA MILENA PUENTES', code:'00032')
    Attorny.create(name:'DIANA SANCLEMENTE TORRES', code:'00033')
    Attorny.create(name:'DIEGO BUITRAGO FLOREZ', code:'00034')
    Attorny.create(name:'DIEGO DE JESUS VELEZ ACEVEDO', code:'00035')
    Attorny.create(name:'DILSON JAVIER RAMIREZ DEL TORO', code:'00036')
    Attorny.create(name:'DIONISIO ARAUJO', code:'00037')
    Attorny.create(name:'DORICELLI CHAVEZ JIMENEZ', code:'00038')
    Attorny.create(name:'EDMER LEANDRO LOPEZ PENA', code:'00039')
    Attorny.create(name:'EIDELMAN JAVIER GONZALEZ SANCHEZ', code:'00040')
    Attorny.create(name:'ESPERANZA PARRA MARTINEZ', code:'00041')
    Attorny.create(name:'ESTEBAN PARDO LANZETTA', code:'00042')
    Attorny.create(name:'FABIO ALVAREZ LOPEZ', code:'00043')
    Attorny.create(name:'FABIO BERMUDEZ SUAREZ', code:'00044')
    Attorny.create(name:'FABIO PEREZ QUESADA', code:'00045')
    Attorny.create(name:'FERNANDO AUGUSTO GARCIA MATAMOROS', code:'00046')
    Attorny.create(name:'FRANCISCO YESIT FORERO GONZALEZ', code:'00047')
    Attorny.create(name:'FREDY ALVAREZ CAMARGO', code:'00048')
    Attorny.create(name:'GERMAN EDUARDO PALACIO ZUNIGA', code:'00049')
    Attorny.create(name:'GERMAN MAURICIO OSPINA MUNOZ', code:'00050')
    Attorny.create(name:'GERMAN RICARDO GALEANO SOTOMAYOR', code:'00051')
    Attorny.create(name:'GERMAN VALDES', code:'00052')
    Attorny.create(name:'GINNY DAYANE ACOSTA AVILA', code:'00053')
    Attorny.create(name:'GIOVANNY ALBERTO PENALOZA PABON', code:'00054')
    Attorny.create(name:'GLORIA BARON LEMUS', code:'00055')
    Attorny.create(name:'GLORIA MERCEDES BARON SERNA', code:'00056')
    Attorny.create(name:'GLORIA SARMIENTO LOBO GUERRERO', code:'00057')
    Attorny.create(name:'GUILLERMO ENRIQUE BURBANO CORTES', code:'00058')
    Attorny.create(name:'GUSTAVO ALBERTO HERRERA AVILA', code:'00059')
    Attorny.create(name:'HAROLD ARISTIZABAL MARIN', code:'00060')
    Attorny.create(name:'HERNAN AREVALO RONCANCIO ', code:'00061')
    Attorny.create(name:'HUGO HERNANDO MORENO ECHEVERRY', code:'00062')
    Attorny.create(name:'HUGUES ALFONSO OLIVELLA VILORIA', code:'00063')
    Attorny.create(name:'JACQUELINE ROMERO ESTRADA', code:'00064')
    Attorny.create(name:'JAIME ANDRES VELASCO MUNOZ', code:'00065')
    Attorny.create(name:'JAIRO CABEZAS LEON', code:'00066')
    Attorny.create(name:'JAVIER LANDINEZ MONTANEZ', code:'00067')
    Attorny.create(name:'JAVIER REALES ESPANA', code:'00068')
    Attorny.create(name:'JAVIER VASQUEZ NEIRA', code:'00069')
    Attorny.create(name:'JHON FREDY ALVAREZ CARMAGO', code:'00070')
    Attorny.create(name:'JOAQUIN ANDRES CUELLAR SALAS', code:'00071')
    Attorny.create(name:'JOAQUIN ANDRES SALAZAR CUELLAR', code:'00072')
    Attorny.create(name:'JOAQUIN DE JESUS CASTANO RAMIREZ', code:'00073')
    Attorny.create(name:'JOHN JAIRO CORREA ESCOBAR', code:'00074')
    Attorny.create(name:'JORGE ANDRES TABORDA JIMENEZ', code:'00075')
    Attorny.create(name:'JORGE ANTONIO VELEZ BARRERA', code:'00076')
    Attorny.create(name:'JORGE AUGUSTO FRANCO GIRALDO', code:'00077')
    Attorny.create(name:'JORGE ELIECER SALAZAR AVENIA', code:'00078')
    Attorny.create(name:'JORGE LUIS SABOGAL SABOGAL', code:'00079')
    Attorny.create(name:'JORGE MAURICIO BARRERA TAPIAS', code:'00080')
    Attorny.create(name:'JORGE TABORDA', code:'00081')
    Attorny.create(name:'JORGE VELEZ', code:'00082')
    Attorny.create(name:'JOSE ANTONIO CACERES NINO', code:'00083')
    Attorny.create(name:'JOSE DEL CARMEN BERNAL CALVO', code:'00084')
    Attorny.create(name:'JOSE DEL CARMEN MUNOZ CRUZ', code:'00085')
    Attorny.create(name:'JOSE FERNANDO TORRES FERNANDEZ DE CASTRO ', code:'00086')
    Attorny.create(name:'JOSE FERNANDO ZARTA ARIZABALETA ', code:'00087')
    Attorny.create(name:'JOSE HERNAN AREVALO RONCANCIO', code:'00088')
    Attorny.create(name:'JOSE RIOS ALZATE', code:'00089')
    Attorny.create(name:'JUAN CAMILO ARANGO RIOS', code:'00090')
    Attorny.create(name:'JUAN CARLOS HURTADO RESTREPO', code:'00091')
    Attorny.create(name:'JUAN DAVID ZARATE LOPEZ', code:'00092')
    Attorny.create(name:'JUAN FERNANDO ARBELAEZ VILLADA', code:'00093')
    Attorny.create(name:'JUAN MANUEL DIAZ GRANADOS ORTIZ', code:'00094')
    Attorny.create(name:'JUAN PABLO ARAUJO', code:'00095')
    Attorny.create(name:'JUAN PABLO GIRALDO PUERTA', code:'00096')
    Attorny.create(name:'JUAN RICARDO PRIETO PELAEZ', code:'00097')
    Attorny.create(name:'JULIO CESAR YEPES RESTREPO', code:'00098')
    Attorny.create(name:'JULIO MAURICIO LOPEZ CIUFFETELLI', code:'00099')
    Attorny.create(name:'JULY ALEXANDRA CIRO HIGUITA', code:'00100')
    Attorny.create(name:'LIBARDO ANGEL GONZALEZ', code:'00101')
    Attorny.create(name:'LIDIA MIREYA PILONIETA RUEDA', code:'00102')
    Attorny.create(name:'LILLY ESTHER AYCARDI GALEANO', code:'00103')
    Attorny.create(name:'LINA MARCELA GABELO VELASQUEZ', code:'00104')
    Attorny.create(name:'LINA MARIA URIBE ZULUAGA', code:'00105')
    Attorny.create(name:'LUIS ALBERTO GOMEZ BETANCURT', code:'00106')
    Attorny.create(name:'LUIS FERNANDO MEJIA SERNA', code:'00107')
    Attorny.create(name:'LUIS FERNANDO NOVOA VILLAMIL', code:'00108')
    Attorny.create(name:'LUIS FERNANDO URIBE DE URBINA', code:'00109')
    Attorny.create(name:'LUIS HELMER URRIAGO ZAPATA', code:'00110')
    Attorny.create(name:'LUISA FERNANDA VELASQUEZ ANGEL', code:'00111')
    Attorny.create(name:'LUZ ANGELA MILLAN CRUZ', code:'00112')
    Attorny.create(name:'MANFRED CARLOS WAGENER HOLLMANN', code:'00113')
    Attorny.create(name:'MARIA CAROLINA ECHEVERRI GONZALEZ', code:'00114')
    Attorny.create(name:'MARIA CLAUDIA ROMERO', code:'00115')
    Attorny.create(name:'MARIA DEL PILAR GALVIS SEGURA', code:'00116')
    Attorny.create(name:'MARIA ELVIRA BOSSA MADRID', code:'00117')
    Attorny.create(name:'MARIA PATRICIA RIOS CORREA ', code:'00118')
    Attorny.create(name:'MARIA PILIONETA ', code:'00119')
    Attorny.create(name:'MARINA AREVALO TORRES', code:'00120')
    Attorny.create(name:'MARISOL DUQUE', code:'00121')
    Attorny.create(name:'MARLIO MORA CABRERA', code:'00122')
    Attorny.create(name:'MARTHA LUCIA GARCIA TAVERA', code:'00123')
    Attorny.create(name:'MATEO PELAEZ GARCIA', code:'00124')
    Attorny.create(name:'MAURICIO PAVA LUGO', code:'00125')
    Attorny.create(name:'MIGUEL ANGEL MARQUEZ SERRANO', code:'00126')
    Attorny.create(name:'MIKY FERNANDO OLAYA CUERVO', code:'00127')
    Attorny.create(name:'MILCIADES ALBERTO NOVOA VILLAMIL', code:'00128')
    Attorny.create(name:'MIREYA PILONIETA RUEDA', code:'00129')
    Attorny.create(name:'MIRNA PATRICIA WILCHES NAVARRO', code:'00130')
    Attorny.create(name:'MYRIAM DE JESUS DONADO DONADO ', code:'00131')
    Attorny.create(name:'NATALIA BOTERO ZAPATA', code:'00132')
    Attorny.create(name:'NELSON ROA REYES', code:'00133')
    Attorny.create(name:'NOPE ORTEGA YURANY HASBLEIDI', code:'00134')
    Attorny.create(name:'ODILA BARRERA BOHORQUEZ', code:'00135')
    Attorny.create(name:'OLFA MARIA PEREZ', code:'00136')
    Attorny.create(name:'OLGA LUCIA GOMEZ PINEDA', code:'00137')
    Attorny.create(name:'OLGA LUCIA GOMEZ SALAZAR', code:'00138')
    Attorny.create(name:'ORDONEZ ORDONEZ ANDRES E', code:'00139')
    Attorny.create(name:'ORLANDO JESUS AMAYA OLARTE', code:'00140')
    Attorny.create(name:'ORLANDO LASPRILLA VASQUEZ', code:'00141')
    Attorny.create(name:'OSCAR ELIAS BOTERO CHALARCA', code:'00142')
    Attorny.create(name:'OSCAR IVAN VILLANUEVA SEPULVEDA', code:'00143')
    Attorny.create(name:'OSCAR ORLANDO RIOS SILVA', code:'00144')
    Attorny.create(name:'PABLO ARTETA MANRIQUE', code:'00145')
    Attorny.create(name:'PEDRO MARTIN QUINONES MACHLER', code:'00146')
    Attorny.create(name:'PENDIENTE HOMOLOGACIÓN', code:'00147')
    Attorny.create(name:'RAFAEL ALBERTO ARIZA GOMEZ', code:'00148')
    Attorny.create(name:'RAFAEL ENRIQUE SEVILLA AGUILAR', code:'00149')
    Attorny.create(name:'RICARDO VELEZ OCHOA', code:'00150')
    Attorny.create(name:'ROBERTO CARMELO NANDAR CASTELLANOS', code:'00151')
    Attorny.create(name:'ROSARIO MULFORD CARBONELL', code:'00152')
    Attorny.create(name:'SAUL GIRALDO GARCIA', code:'00153')
    Attorny.create(name:'SERGIO ALEJANDRO VILLEGAS AGUDELO', code:'00154')
    Attorny.create(name:'SERVIO TULIO CAICEDO VELASCO', code:'00155')
    Attorny.create(name:'SIGIFREDO WILCHES BORNACELLI', code:'00156')
    Attorny.create(name:'WILLIAM ADAN RODRIGUEZ CASTILLO', code:'00157')
    Attorny.create(name:'WINSTON HERMINSUL RUBIO SEGURA', code:'00158')
    Attorny.create(name:'YEZID GARCIA ARENAS', code:'00159')

  end
  
end
