class Aleja09 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(18104).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'GENNER CABALLERO MADARIAGA Y OTROS',process_radicate: '21-05-994',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 20000000,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10539).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'GENNER CABALLERO MADARIAGA Y OTROS',process_radicate: '21-05-1004',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 1977527,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10496).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'MUNICIPIO DE VALLEDUPAR SECRETARIA DE TRANSITO Y TRANSPORTE MUNICIPAL',process_radicate: '123-2014',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 170000000,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10538).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'MUNICIPIO DE VALLEDUPAR',process_radicate: '124-2014',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 87971898,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10601).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'MUNICIPIO TERMINAL DE TRANSPORTES DE VALLEDUPAR',process_radicate: '130-2014',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 5511500,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11499).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'MUNICIPIO DE PAILITAS CESAR',process_radicate: '21-05-1005',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 13981973,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13150).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR Y MUNICIPIO DE MANAURE',process_radicate: '21-04-1101',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 400000000,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13393).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR ',process_radicate: 'PRF- 21-04-1114',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 226096475,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13408).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR',process_radicate: '21-04-1116',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 109278743,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13880).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'GOBERNACION DEPARTAMENTO DEL CESAR',process_radicate: '21-04-1132',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 51959600,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13209).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'MUNICIPIO DE VALLEDUPAR',process_radicate: '168-2017',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 45000000,reserved_fees_cents: 2500000,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13263).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'MUNICIPIO DE VALLEDUPAR',process_radicate: '170-2017',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 17656324,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13229).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',process_radicate: '169-2017',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 11310349,reserved_fees_cents: 1200000,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13470).update(active_part: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',passive_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',process_radicate: '174-2017',office_name: 'CONTRALORIA MUNICIPAL DE VALLEDUPAR',litigation_source: 'SINIESTRO',provision_cents: 20201369,reserved_fees_cents: 2500000,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13876).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR',process_radicate: '21-05-1130',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 17693557,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13873).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'MUNICIPIO DE VALLEDUPAR',process_radicate: '21-05-1134',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 315000000,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13879).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR',process_radicate: '21-04-1133',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 6031514,reserved_fees_cents: 600000,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14348).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR',process_radicate: '21-04-1146',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 111821608,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13990).update(active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA',passive_part: 'DEPARTAMENTO DEL CESAR',process_radicate: '21-05-1099',office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA',litigation_source: 'SINIESTRO',provision_cents: 400000000,reserved_fees_cents: 0,case_state: 'EN CURSO',branch_policy: '35',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
