class Fix07 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(22169).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22168).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22167).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22166).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22165).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22164).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22163).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22162).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22161).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22160).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22159).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22158).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22157).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22156).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22155).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22154).update(protection: ['', 'PENDIENTE'],reinsurance_type: 'PENDIENTE',reserved_released: 'PENDIENTE',money_type: 'PENDIENTE',join_committee: 'PENDIENTE',committee: 'PENDIENTE',coensurance_type: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14222).update(join_committee: 'PENDIENTE',committee: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
