class Al05 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(872).update(id: 872,active_part: 'COLJUEGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19105).update(id: 19105,active_part: 'DIRECCION DE IMPUESTOS Y ADUANAS NACIONALES DIAN.',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1136).update(id: 1136,active_part: 'CARMEN LILIANA CAPERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21587).update(id: 21587,active_part: 'ANGELICA ISABEL CARDENAS MARTINEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21853).update(id: 21853,active_part: 'COLJUEGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22109).update(id: 22109,active_part: 'COLJUEGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22112).update(id: 22112,active_part: 'COLJUEGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19911).update(id: 19911,active_part: 'GERMAN DE AQUINO RIVAS ASPRILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22).update(id: 22,active_part: 'ESE HOSPITAL SAN JUAN DE DIOS DE PAMPLONA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(295).update(id: 295,active_part: 'HOSPITAL DEPARTAMENTAL CENTENARIO DE SEVILLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20094).update(id: 20094,active_part: 'E.S.E. HOSPITAL SAN RAFAEL DE GIRARDOTA ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20384).update(id: 20384,active_part: 'PEDRO LUIS ALVAREZ FLOREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21640).update(id: 21640,active_part: 'E. S. E. HOSPITAL SANTA MARGARITA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20195).update(id: 20195,active_part: 'BOLIVAR RIALPE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4865).update(id: 4865,active_part: 'ESCAMILLA GOMEZ BLANCA ELVIRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4888).update(id: 4888,active_part: 'ANDRES AVELINO GOMEZ GOMEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4730).update(id: 4730,active_part: 'BOTELLO BARRIENTOS MILENA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4837).update(id: 4837,active_part: 'CARLOS MARIO CAMARON VANEGAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4772).update(id: 4772,active_part: 'ZABALA SANGUINO ALVARO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4787).update(id: 4787,active_part: 'DELGADO ASCANIO YANETH',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4780).update(id: 4780,active_part: 'SANCHEZ  EDITH JOHANA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4847).update(id: 4847,active_part: 'LAGUADO PABON MAYRA ALEJANDRA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2185).update(id: 2185,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2182).update(id: 2182,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5254).update(id: 5254,active_part: 'GABRIEL JAIME AGUDELO CADAVID',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1907).update(id: 1907,active_part: 'CLAUDIA MARCELA HERRERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21255).update(id: 21255,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5078).update(id: 5078,active_part: 'BUITRAGO NAVARRO ROCIO AIDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1766).update(id: 1766,active_part: 'FRANCENID APONTE PRADA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2871).update(id: 2871,active_part: 'ADOLFO LEON LOZANO CAICEDO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5288).update(id: 5288,active_part: 'LILIA INES GOMEZ GOMEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21259).update(id: 21259,active_part: 'KETY QUINTANA MEDINA  JUANA QUINTANA MEJIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7316).update(id: 7316,active_part: 'Martha Cecilia Noruega Sánchez',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3736).update(id: 3736,active_part: 'JOSE GABRIEL CASTANO ROJAS   ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3492).update(id: 3492,active_part: 'MARTHA CECILIA GARCIA CALDERON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3296).update(id: 3296,active_part: 'GUTIERREZ CASTANO FERNEY ANIBAL',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2880).update(id: 2880,active_part: 'ALBA YANETH PALACIOS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2521).update(id: 2521,active_part: 'ANA MARIA AGUDELO RAMIREZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2647).update(id: 2647,active_part: 'ALBA NELLY VENTURA MOSQUERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2648).update(id: 2648,active_part: 'DIANA PATRICIA RAMIREZ GOMEZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2150).update(id: 2150,active_part: 'LUISA FERNANDA GARZON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2380).update(id: 2380,active_part: 'JOSE OSPENHAIMER VARGAS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21387).update(id: 21387,active_part: 'GLORIA PATRICIA RESTREPO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3194).update(id: 3194,active_part: 'AMARILES MARLENI ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4283).update(id: 4283,active_part: 'MARIA LUISA CRUZ NINO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2179).update(id: 2179,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4917).update(id: 4917,active_part: 'LONDONO PARRA MARY LUZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4913).update(id: 4913,active_part: 'LAURA PERALTA MARTINEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4944).update(id: 4944,active_part: 'NELCY ANDRADE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4453).update(id: 4453,active_part: 'MOISES REUTO MATIZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4482).update(id: 4482,active_part: 'CABALLERO JAIMES VICTOR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4494).update(id: 4494,active_part: 'ARENIZ PABON PEDRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4497).update(id: 4497,active_part: 'FIDEL ALBERTO MORALES ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3439).update(id: 3439,active_part: 'GLORIA ESPERANZA MORALES CABRERA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3273).update(id: 3273,active_part: 'LINA MARCELA PARRA GUTIERREZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3206).update(id: 3206,active_part: 'YAN SCARLO PARRA BELALCAZAR ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2890).update(id: 2890,active_part: 'ANCISAR MOLINA MANOSCA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3663).update(id: 3663,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3057).update(id: 3057,active_part: 'MARIA DEISY TORRES VARGAS ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2893).update(id: 2893,active_part: 'EDY ALFRAY DIAZ MARMOLEJO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3621).update(id: 3621,active_part: 'JUAN FRANCISCO RUIZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3609).update(id: 3609,active_part: 'BBRENDA ASTAIZA MOPAN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3115).update(id: 3115,active_part: 'NANCY MATAMOROS GUZMAN ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3603).update(id: 3603,active_part: 'ADRIANA MARIA MANZANO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3467).update(id: 3467,active_part: 'MARLIN CARABALI RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2324).update(id: 2324,active_part: 'MARIO ANDRES GORDON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7649).update(id: 7649,active_part: 'LA PREVISORA SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7651).update(id: 7651,active_part: 'LA PREVISORA SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4400).update(id: 4400,active_part: 'VILLAMIL  YULY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21470).update(id: 21470,active_part: 'MARIBEL COLORADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21418).update(id: 21418,active_part: 'MARIA YAMILET MOLINA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21469).update(id: 21469,active_part: 'GLORIA INES FONSECA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20214).update(id: 20214,active_part: 'CALOS JULIO SANDOVAL ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21462).update(id: 21462,active_part: 'MARIA YOLANDA BUITRAGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21404).update(id: 21404,active_part: 'VICTOR ALFONSO SARMIENTO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21478).update(id: 21478,active_part: 'MARIA INES MORALES ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21401).update(id: 21401,active_part: 'ROELFIL DUQUE ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4710).update(id: 4710,active_part: 'WILSON CARVAJAL CONTRERAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(85).update(id: 85,active_part: 'WESLY NOOSLY KELLY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(47).update(id: 47,active_part: 'BLANCA PARDO SUAREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(73).update(id: 73,active_part: 'LUZ ESPERANZA MONDRAGON AREVALO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(100).update(id: 100,active_part: 'OLGA RODRIGUEZ GONZALEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(101).update(id: 101,active_part: 'MARIA EDID ARIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20001).update(id: 20001,active_part: 'LOTERIA DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21517).update(id: 21517,active_part: 'EDGAR JAVIER HUERTAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5251).update(id: 5251,active_part: 'WILLIAN DAVID CUARTAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20423).update(id: 20423,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5419).update(id: 5419,active_part: 'CLAUDIA PATRICIA GONZALEZ GONZALEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5804).update(id: 5804,active_part: 'DIANA CRISTINA HERRERA RAMIREZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5704).update(id: 5704,active_part: 'HECTOR FABIO SANTAMARIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21829).update(id: 21829,active_part: 'OMAIDE ACOSTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5456).update(id: 5456,active_part: 'MARIA ORVILLA GARCES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21460).update(id: 21460,active_part: 'MUÑOZ ESCOBAR LUZ MYRIAM',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5963).update(id: 5963,active_part: 'UPEGUI BETANCUR JOSE GUILLERMO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1456).update(id: 1456,active_part: 'LA PREVISORA  COMPA¥IA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21529).update(id: 21529,active_part: 'SAYIRA SABRINA SALGADO PATERNINA Y OTRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21531).update(id: 21531,active_part: 'ELVIRA ROSA DIAZ BORJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5974).update(id: 5974,active_part: 'PALENCIA LLORENTE BERNEDIS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1782).update(id: 1782,active_part: 'SANCHEZ  LEONOR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1883).update(id: 1883,active_part: 'JHON JAIRO ORTIZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1809).update(id: 1809,active_part: 'LETICIA ESCARRGA JAIRO BUSTOS PABON',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1634).update(id: 1634,active_part: 'ELISEO MURILLO CRIOLLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3946).update(id: 3946,active_part: 'LUDIS MARIA BANDERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3928).update(id: 3928,active_part: 'NAVIS MORA SAURTIH ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21281).update(id: 21281,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5404).update(id: 5404,active_part: 'SEBASTIAN MARTINEZ GUILLEN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2607).update(id: 2607,active_part: 'AYALA MOSQUERA MARYURY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4114).update(id: 4114,active_part: 'AURORA ROJAS ALBARRACIN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1801).update(id: 1801,active_part: 'NORMA CONSTANZA RAMIREZ QUINONEZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3901).update(id: 3901,active_part: 'MIRIAM NOBLE MEDINA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4900).update(id: 4900,active_part: 'SANDRA MILEENA ORTEGA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3941).update(id: 3941,active_part: 'LUZ MARINA CUBIDES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2060).update(id: 2060,active_part: 'SANDRA PATRICIA ESCOBAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1921).update(id: 1921,active_part: 'JORGE NEVER BEDOYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2886).update(id: 2886,active_part: 'REYES HOYOS YANCY FERNANDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2858).update(id: 2858,active_part: 'VALENCIA AVILA YURANY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3473).update(id: 3473,active_part: 'FLORALBA PALACIOS SANCHEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3217).update(id: 3217,active_part: 'CECILIA TORRES PECHENE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3427).update(id: 3427,active_part: 'FERNANDO SALAZAR CAMACHO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5755).update(id: 5755,active_part: 'LOPEZ CABRERA YOLIMA AYDE Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5672).update(id: 5672,active_part: 'MESA JENNY JOHANA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5858).update(id: 5858,active_part: 'FELIPE MAURICIO HERRERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5418).update(id: 5418,active_part: 'EUCLIDES MONTES REY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3871).update(id: 3871,active_part: 'SILVIA AMARIS ECHAVEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5912).update(id: 5912,active_part: 'ELKIN EMILIO LOZANO MOSQUERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5838).update(id: 5838,active_part: 'RAUL ANTONIO URIBE CIFUENTES Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5746).update(id: 5746,active_part: 'PORRAS BLANDON MARIA MERCEDES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5897).update(id: 5897,active_part: 'CARTAGENA MARIA DE LA CRUZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5392).update(id: 5392,active_part: 'ARISTIDES MORENO RENTERIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3973).update(id: 3973,active_part: 'ABILIO ARAUJO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5700).update(id: 5700,active_part: 'SANCHEZ BUSTAMENTE DORA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5540).update(id: 5540,active_part: 'TOBON AGUDELO JAIME',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5580).update(id: 5580,active_part: 'GUERRA ORTEGA LINA MARCELA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5741).update(id: 5741,active_part: 'BLANDON MENA JESUS A ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1423).update(id: 1423,active_part: 'LUZ ANGELICA LARGO LAGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5605).update(id: 5605,active_part: 'ISAURA DEL SOCORRO ARROYAVE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4638).update(id: 4638,active_part: 'RODRIGUEZ TORRES CARLOS ENRIQUE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4578).update(id: 4578,active_part: 'RESTREPO ALVAREZ FRANCISCO JAVIER',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4649).update(id: 4649,active_part: 'MARIELA LLANOS CUADROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4691).update(id: 4691,active_part: 'YULI MARITZA GELVEZ RAMIREZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4602).update(id: 4602,active_part: 'NUBIA STELLA MALDONADO  PINEDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2469).update(id: 2469,active_part: 'MARIA LIBIA SUAREZ TREJOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5408).update(id: 5408,active_part: 'ADRIANA PATRICIA TUBEQUIA MONROY',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5908).update(id: 5908,active_part: 'CASTRILLON ZAPATA MARIA LILIAM',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9337).update(id: 9337,active_part: 'OBANDO GALINDO LYDA FABIOLA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3287).update(id: 3287,active_part: 'LEYDI VIVIANA LOPEZ RUA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2175).update(id: 2175,active_part: 'DILIA TIRZA NARVAEZ HERNANDEZ Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5898).update(id: 5898,active_part: 'GALLEGO ESTRADA LUIS FERNANDO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5552).update(id: 5552,active_part: 'ROSA JULIA RODRIGUEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4801).update(id: 4801,active_part: 'GARCIA SOTO NELSON EMILIO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4380).update(id: 4380,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2174).update(id: 2174,active_part: 'LIGIA MONTENEGRO DELGADO Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1799).update(id: 1799,active_part: 'CARRILLO GALINDO SILVIO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21452).update(id: 21452,active_part: 'HERNADO DE JESUS GONZALEZ MONTOYA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5442).update(id: 5442,active_part: 'VELEZ CARLOS ARTURO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5437).update(id: 5437,active_part: 'DIAZ MUNOZ DIANA PATRICIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20615).update(id: 20615,active_part: 'RODRIGUEZ GUERRERO DANNY ALEXANDER',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20609).update(id: 20609,active_part: 'LANDAZABAL MENDEZ TERESA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20614).update(id: 20614,active_part: 'CASTAÑO GARCIA ALEXANDER',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,active_part: 'JUAN FERNANDO DAVILA DENIS YUNNIER DAVILA CUESTA JHOSETH OWEN DAVILA PANESSO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(70).update(id: 70,active_part: 'LA PREVISORA S A  COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1605).update(id: 1605,active_part: 'LA PREVISORA SA COMPA¥IA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1649).update(id: 1649,active_part: 'LA PREVISORA S.A. COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2724).update(id: 2724,active_part: 'LA PREVISORA S.A. COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2866).update(id: 2866,active_part: 'LA PREVISORA S A  COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3358).update(id: 3358,active_part: 'LA PREVISORA S A  COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3974).update(id: 3974,active_part: 'LA PREVISORA SA COMPA¥IA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4353).update(id: 4353,active_part: 'LA PREVISORA SA CIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4444).update(id: 4444,active_part: 'LA PREVISORA  COMPA¥IA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5292).update(id: 5292,active_part: 'LA PREVISORA  COMPA¥IA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5768).update(id: 5768,active_part: 'LA PREVISORA S.A. COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5851).update(id: 5851,active_part: 'LA PREVISORA S.A. COMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21252).update(id: 21252,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21269).update(id: 21269,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21270).update(id: 21270,active_part: 'LA PREVISORA SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21285).update(id: 21285,active_part: 'LA PREVISORA SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21308).update(id: 21308,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21309).update(id: 21309,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21312).update(id: 21312,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS  AXA COLPATRIA SEGUROS SA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22154).update(id: 22154,active_part: 'LA PREVISORA S.A. CIA. DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18727).update(id: 18727,active_part: 'ALVARO FERNANDO GRIJALBA FUERTES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
