class Aleja68 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(5265).update(id: 5265,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9524).update(id: 9524,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9837).update(id: 9837,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5639).update(id: 5639,current_stage: 'SENTENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5460).update(id: 5460,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5929).update(id: 5929,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11250).update(id: 11250,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11225).update(id: 11225,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11254).update(id: 11254,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10794).update(id: 10794,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20372).update(id: 20372,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20370).update(id: 20370,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11673).update(id: 11673,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9981).update(id: 9981,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20169).update(id: 20169,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20163).update(id: 20163,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20071).update(id: 20071,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(366).update(id: 366,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20067).update(id: 20067,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14621).update(id: 14621,current_stage: 'AUDIENCIA DE DECISION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13668).update(id: 13668,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20274).update(id: 20274,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20172).update(id: 20172,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20044).update(id: 20044,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12005).update(id: 12005,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10570).update(id: 10570,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10636).update(id: 10636,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10596).update(id: 10596,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20125).update(id: 20125,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20042).update(id: 20042,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20200).update(id: 20200,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8401).update(id: 8401,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20199).update(id: 20199,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(35).update(id: 35,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(124).update(id: 124,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7874).update(id: 7874,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20309).update(id: 20309,current_stage: 'PRESENTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20244).update(id: 20244,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11326).update(id: 11326,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20345).update(id: 20345,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20189).update(id: 20189,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1717).update(id: 1717,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20406).update(id: 20406,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8239).update(id: 8239,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20281).update(id: 20281,current_stage: 'SENTENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8241).update(id: 8241,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8130).update(id: 8130,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(32).update(id: 32,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8083).update(id: 8083,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8403).update(id: 8403,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8142).update(id: 8142,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8250).update(id: 8250,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16067).update(id: 16067,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14798).update(id: 14798,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15794).update(id: 15794,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11436).update(id: 11436,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14160).update(id: 14160,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14346).update(id: 14346,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14878).update(id: 14878,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13428).update(id: 13428,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13147).update(id: 13147,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13208).update(id: 13208,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16150).update(id: 16150,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12989).update(id: 12989,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15814).update(id: 15814,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14880).update(id: 14880,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14879).update(id: 14879,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16115).update(id: 16115,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15775).update(id: 15775,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15750).update(id: 15750,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14789).update(id: 14789,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15287).update(id: 15287,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11429).update(id: 11429,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11427).update(id: 11427,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11432).update(id: 11432,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11431).update(id: 11431,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11430).update(id: 11430,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11470).update(id: 11470,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11480).update(id: 11480,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11451).update(id: 11451,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11479).update(id: 11479,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11465).update(id: 11465,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11466).update(id: 11466,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11469).update(id: 11469,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11447).update(id: 11447,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11435).update(id: 11435,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11449).update(id: 11449,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11444).update(id: 11444,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11439).update(id: 11439,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11460).update(id: 11460,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12626).update(id: 12626,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12459).update(id: 12459,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12707).update(id: 12707,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12477).update(id: 12477,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12715).update(id: 12715,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12722).update(id: 12722,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12580).update(id: 12580,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12495).update(id: 12495,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12496).update(id: 12496,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11468).update(id: 11468,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12456).update(id: 12456,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12732).update(id: 12732,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12593).update(id: 12593,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12446).update(id: 12446,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12741).update(id: 12741,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12583).update(id: 12583,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12558).update(id: 12558,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12582).update(id: 12582,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(332).update(id: 332,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(336).update(id: 336,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(348).update(id: 348,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12591).update(id: 12591,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12441).update(id: 12441,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12740).update(id: 12740,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12469).update(id: 12469,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12573).update(id: 12573,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12692).update(id: 12692,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12485).update(id: 12485,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12541).update(id: 12541,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12638).update(id: 12638,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12555).update(id: 12555,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12783).update(id: 12783,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12550).update(id: 12550,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12542).update(id: 12542,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12518).update(id: 12518,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12452).update(id: 12452,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12772).update(id: 12772,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13466).update(id: 13466,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12662).update(id: 12662,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12760).update(id: 12760,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12618).update(id: 12618,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12605).update(id: 12605,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12719).update(id: 12719,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12726).update(id: 12726,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12468).update(id: 12468,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12464).update(id: 12464,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12701).update(id: 12701,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12494).update(id: 12494,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12508).update(id: 12508,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12796).update(id: 12796,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12759).update(id: 12759,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12523).update(id: 12523,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12729).update(id: 12729,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12570).update(id: 12570,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12486).update(id: 12486,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12487).update(id: 12487,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12503).update(id: 12503,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12747).update(id: 12747,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12669).update(id: 12669,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12761).update(id: 12761,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12595).update(id: 12595,current_stage: 'AUTO QUE RESUELVE APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12540).update(id: 12540,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12475).update(id: 12475,current_stage: 'AUTO QUE RESUELVE LA REPOSICION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12721).update(id: 12721,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10950).update(id: 10950,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12575).update(id: 12575,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12455).update(id: 12455,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12604).update(id: 12604,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12525).update(id: 12525,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12735).update(id: 12735,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12597).update(id: 12597,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12665).update(id: 12665,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12517).update(id: 12517,current_stage: 'AUTO DE IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12549).update(id: 12549,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(347).update(id: 347,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13936).update(id: 13936,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13424).update(id: 13424,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12585).update(id: 12585,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12526).update(id: 12526,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12532).update(id: 12532,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12720).update(id: 12720,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12672).update(id: 12672,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12524).update(id: 12524,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12531).update(id: 12531,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12622).update(id: 12622,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12589).update(id: 12589,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12599).update(id: 12599,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12630).update(id: 12630,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12764).update(id: 12764,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12556).update(id: 12556,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12670).update(id: 12670,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12449).update(id: 12449,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12563).update(id: 12563,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12572).update(id: 12572,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12655).update(id: 12655,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12635).update(id: 12635,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12621).update(id: 12621,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12581).update(id: 12581,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12686).update(id: 12686,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12734).update(id: 12734,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12565).update(id: 12565,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12793).update(id: 12793,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12724).update(id: 12724,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12617).update(id: 12617,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12789).update(id: 12789,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12610).update(id: 12610,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12611).update(id: 12611,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12612).update(id: 12612,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12620).update(id: 12620,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12694).update(id: 12694,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12601).update(id: 12601,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12462).update(id: 12462,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12699).update(id: 12699,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12627).update(id: 12627,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12482).update(id: 12482,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12490).update(id: 12490,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12649).update(id: 12649,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12714).update(id: 12714,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12710).update(id: 12710,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12678).update(id: 12678,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12461).update(id: 12461,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12561).update(id: 12561,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12613).update(id: 12613,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12507).update(id: 12507,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12467).update(id: 12467,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12636).update(id: 12636,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12473).update(id: 12473,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12474).update(id: 12474,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12684).update(id: 12684,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12628).update(id: 12628,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12650).update(id: 12650,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12680).update(id: 12680,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12769).update(id: 12769,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12731).update(id: 12731,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12753).update(id: 12753,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12744).update(id: 12744,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12660).update(id: 12660,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12676).update(id: 12676,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12756).update(id: 12756,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12763).update(id: 12763,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12675).update(id: 12675,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12785).update(id: 12785,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12632).update(id: 12632,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12771).update(id: 12771,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12569).update(id: 12569,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12647).update(id: 12647,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12812).update(id: 12812,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12805).update(id: 12805,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12695).update(id: 12695,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12516).update(id: 12516,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12640).update(id: 12640,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12778).update(id: 12778,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12639).update(id: 12639,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12733).update(id: 12733,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12590).update(id: 12590,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12463).update(id: 12463,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12748).update(id: 12748,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12654).update(id: 12654,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12579).update(id: 12579,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12603).update(id: 12603,current_stage: 'AUTO DE APERTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6799).update(id: 6799,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7782).update(id: 7782,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8040).update(id: 8040,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9258).update(id: 9258,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7849).update(id: 7849,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7706).update(id: 7706,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7095).update(id: 7095,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9750).update(id: 9750,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9556).update(id: 9556,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9538).update(id: 9538,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9359).update(id: 9359,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9112).update(id: 9112,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8902).update(id: 8902,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8854).update(id: 8854,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5576).update(id: 5576,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9178).update(id: 9178,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5682).update(id: 5682,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7356).update(id: 7356,current_stage: 'AUDIENCIA DE CONCILIACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9017).update(id: 9017,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9745).update(id: 9745,current_stage: 'SENTENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8770).update(id: 8770,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7601).update(id: 7601,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8746).update(id: 8746,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6093).update(id: 6093,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(434).update(id: 434,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7026).update(id: 7026,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8205).update(id: 8205,current_stage: 'DEMANDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9357).update(id: 9357,current_stage: 'SENTENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6741).update(id: 6741,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7838).update(id: 7838,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7693).update(id: 7693,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9048).update(id: 9048,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6068).update(id: 6068,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7073).update(id: 7073,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6480).update(id: 6480,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9619).update(id: 9619,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8213).update(id: 8213,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7880).update(id: 7880,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7953).update(id: 7953,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9585).update(id: 9585,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9457).update(id: 9457,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7616).update(id: 7616,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5262).update(id: 5262,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7742).update(id: 7742,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9549).update(id: 9549,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9597).update(id: 9597,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7124).update(id: 7124,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9935).update(id: 9935,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7088).update(id: 7088,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8631).update(id: 8631,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5).update(id: 5,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6791).update(id: 6791,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6390).update(id: 6390,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7975).update(id: 7975,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7653).update(id: 7653,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6620).update(id: 6620,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6074).update(id: 6074,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7107).update(id: 7107,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6634).update(id: 6634,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8378).update(id: 8378,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8991).update(id: 8991,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9045).update(id: 9045,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9916).update(id: 9916,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8848).update(id: 8848,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6781).update(id: 6781,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8206).update(id: 8206,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9885).update(id: 9885,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9180).update(id: 9180,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8840).update(id: 8840,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8432).update(id: 8432,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6454).update(id: 6454,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7626).update(id: 7626,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(427).update(id: 427,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9422).update(id: 9422,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9002).update(id: 9002,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9046).update(id: 9046,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9034).update(id: 9034,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9143).update(id: 9143,current_stage: 'SENTENCIA SEGUNDA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7973).update(id: 7973,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9092).update(id: 9092,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7704).update(id: 7704,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8208).update(id: 8208,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4704).update(id: 4704,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10954).update(id: 10954,current_stage: 'AUDIENCIA DE DESCARGOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7156).update(id: 7156,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8523).update(id: 8523,current_stage: 'APELACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20219).update(id: 20219,current_stage: 'AUDIENCIA DE CONCILIACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7638).update(id: 7638,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8426).update(id: 8426,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2497).update(id: 2497,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20320).update(id: 20320,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2497).update(id: 2497,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20138).update(id: 20138,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10957).update(id: 10957,current_stage: 'ARGUMENTOS DE DEFENSA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20134).update(id: 20134,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20159).update(id: 20159,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20232).update(id: 20232,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20161).update(id: 20161,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20293).update(id: 20293,current_stage: 'AUTO DE APERTURA E IMPUTACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(377).update(id: 377,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6978).update(id: 6978,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12858).update(id: 12858,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9467).update(id: 9467,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9374).update(id: 9374,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8614).update(id: 8614,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9372).update(id: 9372,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2473).update(id: 2473,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2153).update(id: 2153,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2076).update(id: 2076,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9093).update(id: 9093,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(82).update(id: 82,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2392).update(id: 2392,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9530).update(id: 9530,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13695).update(id: 13695,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9414).update(id: 9414,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13695).update(id: 13695,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8002).update(id: 8002,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8820).update(id: 8820,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9423).update(id: 9423,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9146).update(id: 9146,current_stage: 'PRUEBAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20011).update(id: 20011,current_stage: 'CONTESTACION DE LA DEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(72).update(id: 72,current_stage: 'CONTESTACION DE LADEMANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
