class Al02 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(4453).update(id: 4453,active_part: 'MOISES REUTO MATIZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4497).update(id: 4497,active_part: 'FIDEL ALBERTO MORALES ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4723).update(id: 4723,active_part: 'ROQUE SARRIAS ERASO ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4913).update(id: 4913,active_part: 'LAURA PERALTA MARTINEZ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4944).update(id: 4944,active_part: 'NELCY ANDRADE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4974).update(id: 4974,active_part: 'ALFONSO ENRIQUE GONZALEZ ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5035).update(id: 5035,active_part: 'LEIDY VIVIANA ROA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13004).update(id: 13004,active_part: 'CONTRALORIA GENERAL DE SANTIAGO DE CALI',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13111).update(id: 13111,active_part: 'CONTRALORIA MUNICIPAL DE POPAYAN',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13411).update(id: 13411,active_part: 'MUNICIPIO DE AGUACHICA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13437).update(id: 13437,active_part: 'CONTRALORIA DISTRITAL DE BUENAVENTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13440).update(id: 13440,active_part: 'CONTRALORIA DISTRITAL DE BUENAVENTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13441).update(id: 13441,active_part: 'CONTRALORIA DISTRITAL DE BUENAVENTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13442).update(id: 13442,active_part: 'CONTRALORIA DISTRITAL DE BUENAVENTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13869).update(id: 13869,active_part: 'CONTRALORIA DISTRITAL DE BUENAVENTURA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14084).update(id: 14084,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14998).update(id: 14998,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15017).update(id: 15017,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15018).update(id: 15018,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15019).update(id: 15019,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15020).update(id: 15020,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15224).update(id: 15224,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16186).update(id: 16186,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16204).update(id: 16204,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16206).update(id: 16206,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16207).update(id: 16207,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16209).update(id: 16209,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16210).update(id: 16210,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16211).update(id: 16211,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16212).update(id: 16212,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16213).update(id: 16213,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16227).update(id: 16227,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16228).update(id: 16228,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16229).update(id: 16229,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16230).update(id: 16230,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16231).update(id: 16231,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16250).update(id: 16250,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16258).update(id: 16258,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16272).update(id: 16272,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16411).update(id: 16411,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16468).update(id: 16468,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16478).update(id: 16478,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16501).update(id: 16501,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16578).update(id: 16578,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16654).update(id: 16654,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16737).update(id: 16737,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16749).update(id: 16749,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16795).update(id: 16795,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16799).update(id: 16799,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16827).update(id: 16827,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16888).update(id: 16888,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16921).update(id: 16921,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17012).update(id: 17012,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17013).update(id: 17013,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17014).update(id: 17014,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17027).update(id: 17027,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17028).update(id: 17028,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17030).update(id: 17030,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17046).update(id: 17046,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17048).update(id: 17048,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17049).update(id: 17049,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17095).update(id: 17095,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17096).update(id: 17096,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17098).update(id: 17098,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17099).update(id: 17099,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17103).update(id: 17103,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17106).update(id: 17106,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17113).update(id: 17113,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17114).update(id: 17114,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17117).update(id: 17117,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17123).update(id: 17123,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17127).update(id: 17127,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17128).update(id: 17128,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17129).update(id: 17129,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17142).update(id: 17142,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17149).update(id: 17149,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17164).update(id: 17164,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17166).update(id: 17166,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17173).update(id: 17173,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17176).update(id: 17176,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17189).update(id: 17189,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17199).update(id: 17199,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17288).update(id: 17288,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17292).update(id: 17292,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17329).update(id: 17329,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17332).update(id: 17332,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17339).update(id: 17339,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17340).update(id: 17340,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17350).update(id: 17350,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17367).update(id: 17367,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17371).update(id: 17371,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17382).update(id: 17382,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17399).update(id: 17399,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17401).update(id: 17401,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL ATLANTICO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(id: 17402,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17403).update(id: 17403,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17409).update(id: 17409,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17411).update(id: 17411,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17412).update(id: 17412,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17421).update(id: 17421,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17427).update(id: 17427,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17428).update(id: 17428,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17431).update(id: 17431,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17432).update(id: 17432,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17438).update(id: 17438,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17439).update(id: 17439,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17440).update(id: 17440,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17442).update(id: 17442,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17454).update(id: 17454,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17455).update(id: 17455,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17456).update(id: 17456,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17464).update(id: 17464,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17466).update(id: 17466,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17467).update(id: 17467,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17473).update(id: 17473,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17475).update(id: 17475,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17477).update(id: 17477,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17481).update(id: 17481,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17482).update(id: 17482,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17488).update(id: 17488,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17490).update(id: 17490,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17497).update(id: 17497,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17498).update(id: 17498,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17499).update(id: 17499,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17502).update(id: 17502,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17507).update(id: 17507,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17530).update(id: 17530,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17551).update(id: 17551,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17555).update(id: 17555,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17556).update(id: 17556,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17563).update(id: 17563,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17564).update(id: 17564,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17571).update(id: 17571,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17572).update(id: 17572,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17576).update(id: 17576,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17589).update(id: 17589,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17599).update(id: 17599,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17600).update(id: 17600,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17602).update(id: 17602,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17603).update(id: 17603,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17615).update(id: 17615,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17620).update(id: 17620,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17628).update(id: 17628,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17634).update(id: 17634,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17650).update(id: 17650,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17654).update(id: 17654,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17655).update(id: 17655,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17658).update(id: 17658,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17665).update(id: 17665,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17667).update(id: 17667,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17670).update(id: 17670,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17672).update(id: 17672,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17673).update(id: 17673,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17675).update(id: 17675,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17677).update(id: 17677,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17678).update(id: 17678,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17687).update(id: 17687,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17691).update(id: 17691,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17692).update(id: 17692,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17693).update(id: 17693,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17712).update(id: 17712,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17725).update(id: 17725,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17726).update(id: 17726,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17744).update(id: 17744,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17746).update(id: 17746,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17749).update(id: 17749,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17751).update(id: 17751,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17755).update(id: 17755,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17757).update(id: 17757,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17770).update(id: 17770,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17775).update(id: 17775,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17778).update(id: 17778,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17779).update(id: 17779,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17780).update(id: 17780,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17786).update(id: 17786,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17787).update(id: 17787,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17795).update(id: 17795,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17797).update(id: 17797,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17798).update(id: 17798,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17801).update(id: 17801,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17802).update(id: 17802,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17803).update(id: 17803,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17804).update(id: 17804,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17805).update(id: 17805,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17813).update(id: 17813,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17815).update(id: 17815,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17816).update(id: 17816,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17821).update(id: 17821,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17829).update(id: 17829,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17844).update(id: 17844,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17853).update(id: 17853,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17859).update(id: 17859,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17865).update(id: 17865,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17874).update(id: 17874,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17879).update(id: 17879,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17884).update(id: 17884,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17885).update(id: 17885,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17886).update(id: 17886,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17887).update(id: 17887,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17888).update(id: 17888,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17889).update(id: 17889,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17890).update(id: 17890,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17891).update(id: 17891,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17892).update(id: 17892,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17894).update(id: 17894,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17901).update(id: 17901,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17918).update(id: 17918,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17923).update(id: 17923,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17926).update(id: 17926,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17931).update(id: 17931,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17936).update(id: 17936,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17942).update(id: 17942,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17943).update(id: 17943,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17952).update(id: 17952,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17953).update(id: 17953,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17954).update(id: 17954,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17975).update(id: 17975,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17978).update(id: 17978,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17983).update(id: 17983,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17984).update(id: 17984,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17985).update(id: 17985,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17988).update(id: 17988,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18005).update(id: 18005,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18008).update(id: 18008,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18010).update(id: 18010,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18011).update(id: 18011,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18012).update(id: 18012,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18013).update(id: 18013,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18025).update(id: 18025,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18026).update(id: 18026,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18034).update(id: 18034,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18036).update(id: 18036,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18037).update(id: 18037,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18043).update(id: 18043,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18064).update(id: 18064,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18081).update(id: 18081,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18084).update(id: 18084,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18085).update(id: 18085,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18087).update(id: 18087,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18088).update(id: 18088,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18089).update(id: 18089,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18095).update(id: 18095,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18098).update(id: 18098,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18109).update(id: 18109,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18116).update(id: 18116,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18123).update(id: 18123,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18125).update(id: 18125,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18126).update(id: 18126,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18127).update(id: 18127,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18128).update(id: 18128,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18143).update(id: 18143,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18147).update(id: 18147,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18150).update(id: 18150,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18153).update(id: 18153,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18154).update(id: 18154,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18155).update(id: 18155,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18156).update(id: 18156,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18157).update(id: 18157,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18165).update(id: 18165,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18180).update(id: 18180,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18184).update(id: 18184,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18187).update(id: 18187,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18188).update(id: 18188,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18189).update(id: 18189,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18192).update(id: 18192,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18193).update(id: 18193,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18200).update(id: 18200,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18201).update(id: 18201,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18202).update(id: 18202,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18203).update(id: 18203,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18223).update(id: 18223,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18249).update(id: 18249,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18250).update(id: 18250,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18251).update(id: 18251,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18268).update(id: 18268,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18273).update(id: 18273,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18289).update(id: 18289,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18293).update(id: 18293,active_part: 'CONTRALORIA GENERAL DE BOYACA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18296).update(id: 18296,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18303).update(id: 18303,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18307).update(id: 18307,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18309).update(id: 18309,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTA BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18315).update(id: 18315,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18316).update(id: 18316,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18317).update(id: 18317,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18319).update(id: 18319,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18320).update(id: 18320,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18321).update(id: 18321,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18340).update(id: 18340,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18344).update(id: 18344,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18346).update(id: 18346,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18350).update(id: 18350,active_part: 'CONTRALORIA GENERAL DE BOYACA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18353).update(id: 18353,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18354).update(id: 18354,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18375).update(id: 18375,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18376).update(id: 18376,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18377).update(id: 18377,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18378).update(id: 18378,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18379).update(id: 18379,active_part: 'CONTRALORIA GENERAL DE BOYACA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18380).update(id: 18380,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18384).update(id: 18384,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18385).update(id: 18385,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18398).update(id: 18398,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18425).update(id: 18425,active_part: 'CONTRALORIA GENERAL DEL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18428).update(id: 18428,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18434).update(id: 18434,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18435).update(id: 18435,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18439).update(id: 18439,active_part: 'CONTRALORIA GENERAL DE BOYACA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18441).update(id: 18441,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18442).update(id: 18442,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18448).update(id: 18448,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18469).update(id: 18469,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18478).update(id: 18478,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18502).update(id: 18502,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18515).update(id: 18515,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18524).update(id: 18524,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18525).update(id: 18525,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18527).update(id: 18527,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18535).update(id: 18535,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18604).update(id: 18604,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18621).update(id: 18621,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18624).update(id: 18624,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18625).update(id: 18625,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18639).update(id: 18639,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18676).update(id: 18676,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18711).update(id: 18711,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18717).update(id: 18717,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18748).update(id: 18748,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18793).update(id: 18793,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18806).update(id: 18806,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18873).update(id: 18873,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18874).update(id: 18874,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18880).update(id: 18880,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18890).update(id: 18890,active_part: 'CONTRALORIA DE BOGOTA DC',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18906).update(id: 18906,active_part: 'CONTRALORIA DE BOGOTA DC',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18943).update(id: 18943,active_part: 'CONTRALORIA GENERAL LA REPUBLICA GERENCIA DEPARTAMENTAL DE BOYACA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18953).update(id: 18953,active_part: 'CONTRALORIA MUNICIPAL DE TUNJA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18970).update(id: 18970,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18973).update(id: 18973,active_part: 'CONTRALORIA DEPARTAMENTAL DEL META',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18985).update(id: 18985,active_part: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19043).update(id: 19043,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19055).update(id: 19055,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19286).update(id: 19286,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19288).update(id: 19288,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19305).update(id: 19305,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19474).update(id: 19474,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19481).update(id: 19481,active_part: 'DEPARTAMENTO DEL CESAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19483).update(id: 19483,active_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19484).update(id: 19484,active_part: 'MUNICIPIO DE VALLEDUPAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19485).update(id: 19485,active_part: 'HOSPITAL EDUARDO ARREDONDO DAZA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19486).update(id: 19486,active_part: 'MUNICIPIO DE VALLEDUPAR',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19487).update(id: 19487,active_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19488).update(id: 19488,active_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19490).update(id: 19490,active_part: 'HOSPITAL EDUARDO ARREDONDO DAZA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19530).update(id: 19530,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19756).update(id: 19756,active_part: 'CONTRALORIA GENERAL DE BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19760).update(id: 19760,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL BOYACA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20170).update(id: 20170,active_part: 'DANIELA MARISOL FIERRO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20382).update(id: 20382,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL QUINDIO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20400).update(id: 20400,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CORDOBA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20409).update(id: 20409,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CORDOBA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20423).update(id: 20423,active_part: 'LA PREVISORA SACOMPANIA DE SEGUROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20462).update(id: 20462,active_part: 'JUAN PABLO CASTRO TORO ALICIA DEL SOCORRO TORO GONZALEZ SANDRA CATALINA ATEHORTUA SANGUINO BAYRON DE JESUS CASTRO ARANGO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,active_part: 'MARIA GEMINIS PENA COPETE CARLOS ALBERTO ROJAS TORRES LUDYTH ALEXA ROJAS PENA CARLOS ALEXANDER ROJAS PENA RUBIELA PENA COPETE ELPIDIO ANTONIO PENA COPETE EDINSON PENA PEREA JEYSON PENA PALACIOS OSCAR ANTONIO PENA COPETE LUIS EMIRO PENA PEREA YEISA ROJAS MURILLO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,active_part: 'JUAN FERNANDO DAVILA DENIS YUNNIER DAVILA CUESTA JHOSETH OWEN DAVILA PANESSO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,active_part: 'ALONSO MORENO MORENO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,active_part: 'ESNEYDA MOSQUERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,active_part: 'ROGELINA MOSQUERA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20635).update(id: 20635,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20644).update(id: 20644,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20645).update(id: 20645,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20646).update(id: 20646,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20647).update(id: 20647,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20648).update(id: 20648,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20649).update(id: 20649,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20650).update(id: 20650,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20651).update(id: 20651,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20652).update(id: 20652,active_part: 'CONTRALORIA GENERAL DE ANTIOQUIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20956).update(id: 20956,active_part: 'ELIANA ARANGO KURATOMI',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21138).update(id: 21138,active_part: 'FLOR ELVIRA SANCHEZ CORTES Y OTROS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
