class AddingAttornies < ActiveRecord::Migration[5.1]

  def change

    Attorny.create(id: 0, name: 'NO APLICA', code: '00000')
    Attorny.create(id: 1, name: 'AESCA SAS', code: '00001')
    Attorny.create(id: 2, name: 'ALBA INES GOMEZ VELEZ', code: '00002')
    Attorny.create(id: 3, name: 'ALEX FONTALVO VELASQUEZ', code: '00003')
    Attorny.create(id: 4, name: 'ALEXANDRA PATRICIA TORRES HERRERA', code: '00004')
    Attorny.create(id: 5, name: 'ALMA ROCIO ARIZA FORTICH', code: '00005')
    Attorny.create(id: 6, name: 'ALVARO ANDRES DIAZ PALACIOS', code: '00006')
    Attorny.create(id: 7, name: 'ALVARO AUGUSTO GOMEZ MONTES', code: '00007')
    Attorny.create(id: 8, name: 'ANA INES GOMEZ CALDERON', code: '00008')
    Attorny.create(id: 9, name: 'ANA INES URIBE OSORIO', code: '00009')
    Attorny.create(id: 10, name: 'ANA MARIA MUNOZ - GERENTE SUCURSAL POPAYAN', code: '00010')
    Attorny.create(id: 11, name: 'ANA MILENA VELASCO MUNOZ', code: '00011')
    Attorny.create(id: 12, name: 'ANA PIEDAD MONTANO COVALEDA', code: '00012')
    Attorny.create(id: 13, name: 'ANDRES ORION ALVAREZ PEREZ', code: '00013')
    Attorny.create(id: 14, name: 'ANGELA MARIA LOPEZ CASTANO', code: '00014')
    Attorny.create(id: 15, name: 'ANTONIO ANDRADE DE AVILA', code: '00015')
    Attorny.create(id: 16, name: 'ANTONIO LUIS DAVILA GARCIA', code: '00016')
    Attorny.create(id: 17, name: 'APODERADO DE PREVISORA', code: '00017')
    Attorny.create(id: 18, name: 'ARTURO SANABRIA GOMEZ', code: '00018')
    Attorny.create(id: 19, name: 'BEATRIZ ELENA ESTRADA TOBON', code: '00019')
    Attorny.create(id: 20, name: 'BELLA SOBEIDA GOMEZ RODRIGUEZ', code: '00020')
    Attorny.create(id: 21, name: 'BLANCA STELLA OROZCO RAMIREZ', code: '00021')
    Attorny.create(id: 22, name: 'CARLOS ALFONSO CIFUENTES NEIRA', code: '00022')
    Attorny.create(id: 23, name: 'CARLOS ANDRES VARGAS VARGAS', code: '00023')
    Attorny.create(id: 24, name: 'CARLOS EDUARDO GOMEZ GUTIERREZ', code: '00024')
    Attorny.create(id: 25, name: 'CARLOS ENRIQUE QUIJANO RUEDA', code: '00025')
    Attorny.create(id: 26, name: 'CARLOS FRANCISCO GARCIA HARKER', code: '00026')
    Attorny.create(id: 27, name: 'CATALINA BERNAL RINCON', code: '00027')
    Attorny.create(id: 28, name: 'CHARLES CHAPMAN', code: '00028')
    Attorny.create(id: 29, name: 'CLARA PATRICIA RUBIANO ZALAMEA', code: '00029')
    Attorny.create(id: 30, name: 'CLARA SONIA PEREZ LOPEZ', code: '00030')
    Attorny.create(id: 31, name: 'CLAUDIA PATRICIA ASTUDILLO TIGREROS', code: '00031')
    Attorny.create(id: 32, name: 'CLAUDIA SOFIA FLOREZ MAHECHA', code: '00032')
    Attorny.create(id: 33, name: 'CLAUDIO HENRY YAMA SANTACRUZ', code: '00033')
    Attorny.create(id: 34, name: 'DANIEL ALEJANDRO PALACIOS BALLEN', code: '00034')
    Attorny.create(id: 35, name: 'DIANA LESLIE BLANCO ARENAS', code: '00035')
    Attorny.create(id: 36, name: 'DIANA MILENA PUENTES', code: '00036')
    Attorny.create(id: 37, name: 'DIANA SANCLEMENTE TORRES', code: '00037')
    Attorny.create(id: 38, name: 'DIEGO BUITRAGO FLOREZ', code: '00038')
    Attorny.create(id: 39, name: 'DIEGO DE JESUS VELEZ ACEVEDO', code: '00039')
    Attorny.create(id: 40, name: 'DILSON JAVIER RAMIREZ DEL TORO', code: '00040')
    Attorny.create(id: 41, name: 'DIONISIO ARAUJO', code: '00041')
    Attorny.create(id: 42, name: 'DORICELLI CHAVEZ JIMENEZ', code: '00042')
    Attorny.create(id: 43, name: 'EDMER LEANDRO LOPEZ PENA', code: '00043')
    Attorny.create(id: 44, name: 'EIDELMAN JAVIER GONZALEZ SANCHEZ', code: '00044')
    Attorny.create(id: 45, name: 'ESPERANZA PARRA MARTINEZ', code: '00045')
    Attorny.create(id: 46, name: 'ESTEBAN PARDO LANZETTA', code: '00046')
    Attorny.create(id: 47, name: 'FABIO ALVAREZ LOPEZ', code: '00047')
    Attorny.create(id: 48, name: 'FABIO BERMUDEZ SUAREZ', code: '00048')
    Attorny.create(id: 49, name: 'FABIO PEREZ QUESADA', code: '00049')
    Attorny.create(id: 50, name: 'FERNANDO AUGUSTO GARCIA MATAMOROS', code: '00050')
    Attorny.create(id: 51, name: 'FRANCISCO YESIT FORERO GONZALEZ', code: '00051')
    Attorny.create(id: 52, name: 'GERMAN EDUARDO PALACIO ZUNIGA', code: '00052')
    Attorny.create(id: 53, name: 'GERMAN GONZALO VALDEZ SANCHEZ ', code: '00053')
    Attorny.create(id: 54, name: 'GERMAN MAURICIO OSPINA MUNOZ', code: '00054')
    Attorny.create(id: 55, name: 'GERMAN RICARDO GALEANO SOTOMAYOR', code: '00055')
    Attorny.create(id: 56, name: 'GERMAN VALDES', code: '00056')
    Attorny.create(id: 57, name: 'GINNY DAYANE ACOSTA AVILA', code: '00057')
    Attorny.create(id: 58, name: 'GIOVANNY ALBERTO PENALOZA PABON', code: '00058')
    Attorny.create(id: 59, name: 'GLORIA BARON LEMUS', code: '00059')
    Attorny.create(id: 60, name: 'GLORIA MERCEDES BARON SERNA', code: '00060')
    Attorny.create(id: 61, name: 'GLORIA SARMIENTO LOBO GUERRERO', code: '00061')
    Attorny.create(id: 62, name: 'GUILLERMO ENRIQUE BURBANO CORTES', code: '00062')
    Attorny.create(id: 63, name: 'GUSTAVO ALBERTO HERRERA AVILA', code: '00063')
    Attorny.create(id: 64, name: 'HAROLD ARISTIZABAL MARIN', code: '00064')
    Attorny.create(id: 65, name: 'HERNAN AREVALO RONCANCIO ', code: '00065')
    Attorny.create(id: 66, name: 'HUGO HERNANDO MORENO ECHEVERRY', code: '00066')
    Attorny.create(id: 67, name: 'HUGUES ALFONSO OLIVELLA VILORIA', code: '00067')
    Attorny.create(id: 68, name: 'JACQUELINE ROMERO ESTRADA', code: '00068')
    Attorny.create(id: 69, name: 'JAIME ANDRES VELASCO MUNOZ', code: '00069')
    Attorny.create(id: 70, name: 'JAIRO CABEZAS LEON', code: '00070')
    Attorny.create(id: 71, name: 'JAVIER LANDINEZ MONTANEZ', code: '00071')
    Attorny.create(id: 72, name: 'JAVIER REALES ESPANA', code: '00072')
    Attorny.create(id: 73, name: 'JAVIER VASQUEZ NEIRA', code: '00073')
    Attorny.create(id: 74, name: 'JHON FREDY ALVAREZ CARMAGO', code: '00074')
    Attorny.create(id: 75, name: 'JOAQUIN ANDRES CUELLAR SALAS', code: '00075')
    Attorny.create(id: 76, name: 'JOAQUIN ANDRES SALAZAR CUELLAR', code: '00076')
    Attorny.create(id: 77, name: 'JOAQUIN DE JESUS CASTANO RAMIREZ', code: '00077')
    Attorny.create(id: 78, name: 'JOHN JAIRO CORREA ESCOBAR', code: '00078')
    Attorny.create(id: 79, name: 'JORGE ANDRES TABORDA JIMENEZ', code: '00079')
    Attorny.create(id: 80, name: 'JORGE ANTONIO VELEZ BARRERA', code: '00080')
    Attorny.create(id: 81, name: 'JORGE AUGUSTO FRANCO GIRALDO', code: '00081')
    Attorny.create(id: 82, name: 'JORGE ELIECER SALAZAR AVENIA', code: '00082')
    Attorny.create(id: 83, name: 'JORGE LUIS SABOGAL SABOGAL', code: '00083')
    Attorny.create(id: 84, name: 'JORGE MAURICIO BARRERA TAPIAS', code: '00084')
    Attorny.create(id: 85, name: 'JORGE VELEZ', code: '00085')
    Attorny.create(id: 86, name: 'JOSE ANTONIO CACERES NINO', code: '00086')
    Attorny.create(id: 87, name: 'JOSE DEL CARMEN BERNAL CALVO', code: '00087')
    Attorny.create(id: 88, name: 'JOSE DEL CARMEN MUNOZ CRUZ', code: '00088')
    Attorny.create(id: 89, name: 'JOSE FERNANDO TORRES FERNANDEZ DE CASTRO ', code: '00089')
    Attorny.create(id: 90, name: 'JOSE FERNANDO ZARTA ARIZABALETA ', code: '00090')
    Attorny.create(id: 91, name: 'JOSE HERNAN AREVALO RONCANCIO', code: '00091')
    Attorny.create(id: 92, name: 'JOSE RIOS ALZATE', code: '00092')
    Attorny.create(id: 93, name: 'JUAN CAMILO ARANGO RIOS', code: '00093')
    Attorny.create(id: 94, name: 'JUAN CARLOS HURTADO RESTREPO', code: '00094')
    Attorny.create(id: 95, name: 'JUAN DAVID ZARATE LOPEZ', code: '00095')
    Attorny.create(id: 96, name: 'JUAN FERNANDO ARBELAEZ VILLADA', code: '00096')
    Attorny.create(id: 97, name: 'JUAN MANUEL DIAZ GRANADOS ORTIZ', code: '00097')
    Attorny.create(id: 98, name: 'JUAN PABLO ARAUJO', code: '00098')
    Attorny.create(id: 99, name: 'JUAN PABLO GIRALDO PUERTA', code: '00099')
    Attorny.create(id: 100, name: 'JUAN RICARDO PRIETO PELAEZ', code: '00100')
    Attorny.create(id: 101, name: 'JULIO CESAR YEPES RESTREPO', code: '00101')
    Attorny.create(id: 102, name: 'JULIO MAURICIO LOPEZ CIUFFETELLI', code: '00102')
    Attorny.create(id: 103, name: 'JULY ALEXANDRA CIRO HIGUITA', code: '00103')
    Attorny.create(id: 104, name: 'LIBARDO ANGEL GONZALEZ', code: '00104')
    Attorny.create(id: 105, name: 'LIDIA MIREYA PILONIETA RUEDA', code: '00105')
    Attorny.create(id: 106, name: 'LILLY ESTHER AYCARDI GALEANO', code: '00106')
    Attorny.create(id: 107, name: 'LINA MARCELA GABELO VELASQUEZ', code: '00107')
    Attorny.create(id: 108, name: 'LINA MARIA URIBE ZULUAGA', code: '00108')
    Attorny.create(id: 109, name: 'LUIS ALBERTO GOMEZ BETANCURT', code: '00109')
    Attorny.create(id: 110, name: 'LUIS FERNANDO MEJIA SERNA', code: '00110')
    Attorny.create(id: 111, name: 'LUIS FERNANDO NOVOA VILLAMIL', code: '00111')
    Attorny.create(id: 112, name: 'LUIS FERNANDO URIBE DE URBINA', code: '00112')
    Attorny.create(id: 113, name: 'LUIS HELMER URRIAGO ZAPATA', code: '00113')
    Attorny.create(id: 114, name: 'LUISA FERNANDA VELASQUEZ ANGEL', code: '00114')
    Attorny.create(id: 115, name: 'LUZ ANGELA MILLAN CRUZ', code: '00115')
    Attorny.create(id: 116, name: 'MANFRED CARLOS WAGENER HOLLMANN', code: '00116')
    Attorny.create(id: 117, name: 'MARIA CAROLINA ECHEVERRI GONZALEZ', code: '00117')
    Attorny.create(id: 118, name: 'MARIA CLAUDIA ROMERO', code: '00118')
    Attorny.create(id: 119, name: 'MARIA DEL PILAR GALVIS SEGURA', code: '00119')
    Attorny.create(id: 120, name: 'MARIA ELVIRA BOSSA MADRID', code: '00120')
    Attorny.create(id: 121, name: 'MARIA PATRICIA RIOS CORREA ', code: '00121')
    Attorny.create(id: 122, name: 'MARIA PILIONETA ', code: '00122')
    Attorny.create(id: 123, name: 'MARINA AREVALO TORRES', code: '00123')
    Attorny.create(id: 124, name: 'MARISOL DUQUE OSSA', code: '00124')
    Attorny.create(id: 125, name: 'MARLIO MORA CABRERA', code: '00125')
    Attorny.create(id: 126, name: 'MARTHA LUCIA GARCIA TAVERA', code: '00126')
    Attorny.create(id: 127, name: 'MATEO PELAEZ GARCIA', code: '00127')
    Attorny.create(id: 128, name: 'MAURICIO PAVA LUGO', code: '00128')
    Attorny.create(id: 129, name: 'MIGUEL ANGEL MARQUEZ SERRANO', code: '00129')
    Attorny.create(id: 130, name: 'MIKY FERNANDO OLAYA CUERVO', code: '00130')
    Attorny.create(id: 131, name: 'MILCIADES ALBERTO NOVOA VILLAMIL', code: '00131')
    Attorny.create(id: 132, name: 'MIREYA PILONIETA RUEDA', code: '00132')
    Attorny.create(id: 133, name: 'MIRNA PATRICIA WILCHES NAVARRO', code: '00133')
    Attorny.create(id: 134, name: 'MYRIAM DE JESUS DONADO DONADO ', code: '00134')
    Attorny.create(id: 135, name: 'NATALIA BOTERO ZAPATA', code: '00135')
    Attorny.create(id: 136, name: 'NELSON ROA REYES', code: '00136')
    Attorny.create(id: 137, name: 'NOPE ORTEGA YURANY HASBLEIDI', code: '00137')
    Attorny.create(id: 138, name: 'ODILA BARRERA BOHORQUEZ', code: '00138')
    Attorny.create(id: 139, name: 'OLFA MARIA PEREZ', code: '00139')
    Attorny.create(id: 140, name: 'OLGA LUCIA GOMEZ PINEDA', code: '00140')
    Attorny.create(id: 141, name: 'OLGA LUCIA GOMEZ SALAZAR', code: '00141')
    Attorny.create(id: 142, name: 'ORDONEZ ORDONEZ ANDRES E', code: '00142')
    Attorny.create(id: 143, name: 'ORLANDO JESUS AMAYA OLARTE', code: '00143')
    Attorny.create(id: 144, name: 'ORLANDO LASPRILLA VASQUEZ', code: '00144')
    Attorny.create(id: 145, name: 'OSCAR ELIAS BOTERO CHALARCA', code: '00145')
    Attorny.create(id: 146, name: 'OSCAR IVAN VILLANUEVA SEPULVEDA', code: '00146')
    Attorny.create(id: 147, name: 'OSCAR ORLANDO RIOS SILVA', code: '00147')
    Attorny.create(id: 148, name: 'PABLO ARTETA MANRIQUE', code: '00148')
    Attorny.create(id: 149, name: 'PEDRO MARTIN QUINONES MACHLER', code: '00149')
    Attorny.create(id: 150, name: 'RAFAEL ALBERTO ARIZA GOMEZ', code: '00150')
    Attorny.create(id: 151, name: 'RAFAEL ENRIQUE SEVILLA AGUILAR', code: '00151')
    Attorny.create(id: 152, name: 'RICARDO VELEZ OCHOA', code: '00152')
    Attorny.create(id: 153, name: 'ROBERTO CARMELO NANDAR CASTELLANOS', code: '00153')
    Attorny.create(id: 154, name: 'ROSARIO MULFORD CARBONELL', code: '00154')
    Attorny.create(id: 155, name: 'SALAZAR ASOCIADOS ABOGADOS LTDA', code: '00155')
    Attorny.create(id: 156, name: 'SAUL GIRALDO GARCIA', code: '00156')
    Attorny.create(id: 157, name: 'SERGIO ALEJANDRO VILLEGAS AGUDELO', code: '00157')
    Attorny.create(id: 158, name: 'SERVIO TULIO CAICEDO VELASCO', code: '00158')
    Attorny.create(id: 159, name: 'SIGIFREDO WILCHES BORNACELLI', code: '00159')
    Attorny.create(id: 160, name: 'WILLIAM ADAN RODRIGUEZ CASTILLO', code: '00160')
    Attorny.create(id: 161, name: 'WINSTON HERMINSUL RUBIO SEGURA', code: '00161')
    Attorny.create(id: 162, name: 'YEZID GARCIA ARENAS', code: '00162')
    Attorny.create(id: 163, name: 'CARLOS VARGAS', code: '00163')

  end

end
