class AddingDepartamentsCities < ActiveRecord::Migration[5.1]

  def change

    Departament.create(name: 'NO PRESENTA', code: '00')
    Departament.create(name:'AMAZONAS', code: '91')
    Departament.create(name:'ANTIOQUIA', code: '05')
    Departament.create(name:'ARAUCA', code: '81')
    Departament.create(name:'ATLANTICO', code: '08')
    Departament.create(name:'BOGOTA', code: '11')
    Departament.create(name:'BOLIVAR', code: '13')
    Departament.create(name:'BOYACA', code: '15')
    Departament.create(name:'CALDAS', code: '17')
    Departament.create(name:'CAQUETA', code: '18')
    Departament.create(name:'CASANARE', code: '85')
    Departament.create(name:'CAUCA', code: '19')
    Departament.create(name:'CESAR', code: '20')
    Departament.create(name:'CHOCO', code: '27')
    Departament.create(name:'CORDOBA', code: '23')
    Departament.create(name:'CUNDINAMARCA', code: '25')
    Departament.create(name:'GUAINIA', code: '94')
    Departament.create(name:'GUAVIARE', code: '95')
    Departament.create(name:'HUILA', code: '41')
    Departament.create(name:'LA GUAJIRA', code: '44')
    Departament.create(name:'MAGDALENA', code: '47')
    Departament.create(name:'META', code: '50')
    Departament.create(name:'NARINO', code: '52')
    Departament.create(name:'NORTE DE SANTANDER', code: '54')
    Departament.create(name:'PUTUMAYO', code: '86')
    Departament.create(name:'QUINDIO', code: '63')
    Departament.create(name:'RISARALDA', code: '66')
    Departament.create(name:'SAN ANDRES', code: '88')
    Departament.create(name:'SANTANDER', code: '68')
    Departament.create(name:'SUCRE', code: '70')
    Departament.create(name:'TOLIMA', code: '73')
    Departament.create(name:'VALLE', code: '76')
    Departament.create(name:'VAUPES', code: '97')
    Departament.create(name:'VICHADA', code: '99')

    CityCase.create(name:'NO PRESENTA', code: '000', departament: '00')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '05')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '91')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '81')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '08')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '11')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '13')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '15')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '17')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '18')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '85')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '19')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '20')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '27')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '23')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '25')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '94')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '95')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '41')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '44')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '47')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '50')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '52')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '54')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '86')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '63')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '66')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '88')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '68')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '70')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '73')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '76')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '97')
    CityCase.create(name:'NO PRESENTA', code: '000', departament: '99')

    CityCase.create(name:'PUERTO SANTANDER', code: '669', departament: '91')
    CityCase.create(name:'PUERTO ALEGRIA', code: '530', departament: '91')
    CityCase.create(name:'EL ENCANTO', code: '263', departament: '91')
    CityCase.create(name:'LA CHORRERA', code: '405', departament: '91')
    CityCase.create(name:'TARAPACA', code: '798', departament: '91')
    CityCase.create(name:'PUERTO NARINO', code: '540', departament: '91')
    CityCase.create(name:'LETICIA', code: '001', departament: '91')
    CityCase.create(name:'LA VICTORIA', code: '430', departament: '91')
    CityCase.create(name:'MIRITI - PARANA', code: '460', departament: '91')
    CityCase.create(name:'LA PEDRERA', code: '407', departament: '91')
    CityCase.create(name:'PUERTO ARICA', code: '536', departament: '91')
    CityCase.create(name:'SAN CARLOS', code: '649', departament: '05')
    CityCase.create(name:'BETULIA', code: '093', departament: '05')
    CityCase.create(name:'ANGOSTURA', code: '038', departament: '05')
    CityCase.create(name:'SAN JOSE DE LA MONTANA', code: '658', departament: '05')
    CityCase.create(name:'VALPARAISO', code: '856', departament: '05')
    CityCase.create(name:'BELLO', code: '088', departament: '05')
    CityCase.create(name:'GUATAPE', code: '321', departament: '05')
    CityCase.create(name:'CANASGORDAS', code: '138', departament: '05')
    CityCase.create(name:'CARACOLI', code: '142', departament: '05')
    CityCase.create(name:'BARBOSA', code: '079', departament: '05')
    CityCase.create(name:'SAN VICENTE', code: '674', departament: '05')
    CityCase.create(name:'EBEJICO', code: '240', departament: '05')
    CityCase.create(name:'SAN ANDRES DE CUERQUIA', code: '647', departament: '05')
    CityCase.create(name:'TAMESIS', code: '789', departament: '05')
    CityCase.create(name:'COCORNA', code: '197', departament: '05')
    CityCase.create(name:'CONCORDIA', code: '209', departament: '05')
    CityCase.create(name:'GIRARDOTA', code: '308', departament: '05')
    CityCase.create(name:'CONCEPCION', code: '206', departament: '05')
    CityCase.create(name:'SAN ROQUE', code: '670', departament: '05')
    CityCase.create(name:'LA UNION', code: '400', departament: '05')
    CityCase.create(name:'SANTA BARBARA', code: '679', departament: '05')
    CityCase.create(name:'SABANALARGA', code: '628', departament: '05')
    CityCase.create(name:'MUTATA', code: '480', departament: '05')
    CityCase.create(name:'LA CEJA', code: '376', departament: '05')
    CityCase.create(name:'SAN JUAN DE URABA', code: '659', departament: '05')
    CityCase.create(name:'HISPANIA', code: '353', departament: '05')
    CityCase.create(name:'SALGAR', code: '642', departament: '05')
    CityCase.create(name:'SONSON', code: '756', departament: '05')
    CityCase.create(name:'GIRALDO', code: '306', departament: '05')
    CityCase.create(name:'ANGELOPOLIS', code: '036', departament: '05')
    CityCase.create(name:'CIUDAD BOLIVAR', code: '101', departament: '05')
    CityCase.create(name:'VIGIA DEL FUERTE', code: '873', departament: '05')
    CityCase.create(name:'CISNEROS', code: '190', departament: '05')
    CityCase.create(name:'SANTA ROSA DE OSOS', code: '686', departament: '05')
    CityCase.create(name:'AMALFI', code: '031', departament: '05')
    CityCase.create(name:'ANZA', code: '044', departament: '05')
    CityCase.create(name:'TARSO', code: '792', departament: '05')
    CityCase.create(name:'ARMENIA', code: '059', departament: '05')
    CityCase.create(name:'TOLEDO', code: '819', departament: '05')
    CityCase.create(name:'CAICEDO', code: '125', departament: '05')
    CityCase.create(name:'BRICENO', code: '107', departament: '05')
    CityCase.create(name:'JERICO', code: '368', departament: '05')
    CityCase.create(name:'ZARAGOZA', code: '895', departament: '05')
    CityCase.create(name:'HELICONIA', code: '347', departament: '05')
    CityCase.create(name:'RIONEGRO', code: '615', departament: '05')
    CityCase.create(name:'REMEDIOS', code: '604', departament: '05')
    CityCase.create(name:'NECOCLI', code: '490', departament: '05')
    CityCase.create(name:'TURBO', code: '837', departament: '05')
    CityCase.create(name:'PUERTO TRIUNFO', code: '591', departament: '05')
    CityCase.create(name:'URRAO', code: '847', departament: '05')
    CityCase.create(name:'SAN LUIS', code: '660', departament: '05')
    CityCase.create(name:'OLAYA', code: '501', departament: '05')
    CityCase.create(name:'SAN JERONIMO', code: '656', departament: '05')
    CityCase.create(name:'URAMITA', code: '842', departament: '05')
    CityCase.create(name:'SABANETA', code: '631', departament: '05')
    CityCase.create(name:'ANDES', code: '034', departament: '05')
    CityCase.create(name:'NARINO', code: '483', departament: '05')
    CityCase.create(name:'JARDIN', code: '364', departament: '05')
    CityCase.create(name:'EL SANTUARIO', code: '697', departament: '05')
    CityCase.create(name:'SAN PEDRO DE LOS MILAGROS', code: '664', departament: '05')
    CityCase.create(name:'PUERTO BERRIO', code: '579', departament: '05')
    CityCase.create(name:'CACERES', code: '120', departament: '05')
    CityCase.create(name:'BELMIRA', code: '086', departament: '05')
    CityCase.create(name:'PEQUE', code: '543', departament: '05')
    CityCase.create(name:'COPACABANA', code: '212', departament: '05')
    CityCase.create(name:'ABRIAQUI', code: '004', departament: '05')
    CityCase.create(name:'BETANIA', code: '091', departament: '05')
    CityCase.create(name:'LIBORINA', code: '411', departament: '05')
    CityCase.create(name:'MEDELLIN', code: '001', departament: '05')
    CityCase.create(name:'PUERTO NARE', code: '585', departament: '05')
    CityCase.create(name:'YOLOMBO', code: '890', departament: '05')
    CityCase.create(name:'CAMPAMENTO', code: '134', departament: '05')
    CityCase.create(name:'DABEIBA', code: '234', departament: '05')
    CityCase.create(name:'GUARNE', code: '318', departament: '05')
    CityCase.create(name:'SOPETRAN', code: '761', departament: '05')
    CityCase.create(name:'ITUANGO', code: '361', departament: '05')
    CityCase.create(name:'RETIRO', code: '607', departament: '05')
    CityCase.create(name:'FREDONIA', code: '282', departament: '05')
    CityCase.create(name:'MACEO', code: '425', departament: '05')
    CityCase.create(name:'YONDO', code: '893', departament: '05')
    CityCase.create(name:'ARBOLETES', code: '051', departament: '05')
    CityCase.create(name:'SAN RAFAEL', code: '667', departament: '05')
    CityCase.create(name:'GUADALUPE', code: '315', departament: '05')
    CityCase.create(name:'AMAGA', code: '030', departament: '05')
    CityCase.create(name:'ENTRERRIOS', code: '264', departament: '05')
    CityCase.create(name:'SEGOVIA', code: '736', departament: '05')
    CityCase.create(name:'GOMEZ PLATA', code: '310', departament: '05')
    CityCase.create(name:'YALI', code: '885', departament: '05')
    CityCase.create(name:'SAN PEDRO DE URABA', code: '665', departament: '05')
    CityCase.create(name:'NECHI', code: '495', departament: '05')
    CityCase.create(name:'CALDAS', code: '129', departament: '05')
    CityCase.create(name:'ANORI', code: '040', departament: '05')
    CityCase.create(name:'TITIRIBI', code: '809', departament: '05')
    CityCase.create(name:'TARAZA', code: '790', departament: '05')
    CityCase.create(name:'ABEJORRAL', code: '002', departament: '05')
    CityCase.create(name:'MARINILLA', code: '440', departament: '05')
    CityCase.create(name:'EL CARMEN DE VIBORAL', code: '148', departament: '05')
    CityCase.create(name:'LA ESTRELLA', code: '380', departament: '05')
    CityCase.create(name:'VALDIVIA', code: '854', departament: '05')
    CityCase.create(name:'CARAMANTA', code: '145', departament: '05')
    CityCase.create(name:'PENOL', code: '541', departament: '05')
    CityCase.create(name:'CAREPA', code: '147', departament: '05')
    CityCase.create(name:'GRANADA', code: '313', departament: '05')
    CityCase.create(name:'VENECIA', code: '861', departament: '05')
    CityCase.create(name:'FRONTINO', code: '284', departament: '05')
    CityCase.create(name:'APARTADO', code: '045', departament: '05')
    CityCase.create(name:'DONMATIAS', code: '237', departament: '05')
    CityCase.create(name:'ITAGUI', code: '360', departament: '05')
    CityCase.create(name:'SANTAFE DE ANTIOQUIA', code: '042', departament: '05')
    CityCase.create(name:'MONTEBELLO', code: '467', departament: '05')
    CityCase.create(name:'CHIGORODO', code: '172', departament: '05')
    CityCase.create(name:'BURITICA', code: '113', departament: '05')
    CityCase.create(name:'ARGELIA', code: '055', departament: '05')
    CityCase.create(name:'CAUCASIA', code: '154', departament: '05')
    CityCase.create(name:'SAN FRANCISCO', code: '652', departament: '05')
    CityCase.create(name:'YARUMAL', code: '887', departament: '05')
    CityCase.create(name:'MURINDO', code: '475', departament: '05')
    CityCase.create(name:'VEGACHI', code: '858', departament: '05')
    CityCase.create(name:'PUEBLORRICO', code: '576', departament: '05')
    CityCase.create(name:'LA PINTADA', code: '390', departament: '05')
    CityCase.create(name:'EL BAGRE', code: '250', departament: '05')
    CityCase.create(name:'ENVIGADO', code: '266', departament: '05')
    CityCase.create(name:'SANTO DOMINGO', code: '690', departament: '05')
    CityCase.create(name:'ALEJANDRIA', code: '021', departament: '05')
    CityCase.create(name:'CAROLINA', code: '150', departament: '05')
    CityCase.create(name:'ARAUQUITA', code: '065', departament: '81')
    CityCase.create(name:'FORTUL', code: '300', departament: '81')
    CityCase.create(name:'PUERTO RONDON', code: '591', departament: '81')
    CityCase.create(name:'TAME', code: '794', departament: '81')
    CityCase.create(name:'ARAUCA', code: '001', departament: '81')
    CityCase.create(name:'CRAVO NORTE', code: '220', departament: '81')
    CityCase.create(name:'SARAVENA', code: '736', departament: '81')
    CityCase.create(name:'USIACURI', code: '849', departament: '08')
    CityCase.create(name:'TUBARA', code: '832', departament: '08')
    CityCase.create(name:'SUAN', code: '770', departament: '08')
    CityCase.create(name:'GALAPA', code: '296', departament: '08')
    CityCase.create(name:'BARRANQUILLA', code: '001', departament: '08')
    CityCase.create(name:'JUAN DE ACOSTA', code: '372', departament: '08')
    CityCase.create(name:'MALAMBO', code: '433', departament: '08')
    CityCase.create(name:'MANATI', code: '436', departament: '08')
    CityCase.create(name:'SABANAGRANDE', code: '634', departament: '08')
    CityCase.create(name:'PIOJO', code: '549', departament: '08')
    CityCase.create(name:'CAMPO DE LA CRUZ', code: '137', departament: '08')
    CityCase.create(name:'SABANALARGA', code: '638', departament: '08')
    CityCase.create(name:'BARANOA', code: '078', departament: '08')
    CityCase.create(name:'POLONUEVO', code: '558', departament: '08')
    CityCase.create(name:'LURUACO', code: '421', departament: '08')
    CityCase.create(name:'REPELON', code: '606', departament: '08')
    CityCase.create(name:'CANDELARIA', code: '141', departament: '08')
    CityCase.create(name:'SANTO TOMAS', code: '685', departament: '08')
    CityCase.create(name:'SANTA LUCIA', code: '675', departament: '08')
    CityCase.create(name:'PUERTO COLOMBIA', code: '573', departament: '08')
    CityCase.create(name:'SOLEDAD', code: '758', departament: '08')
    CityCase.create(name:'PONEDERA', code: '560', departament: '08')
    CityCase.create(name:'PALMAR DE VARELA', code: '520', departament: '08')
    CityCase.create(name:'BOGOTA DC', code: '001', departament: '11')
    CityCase.create(name:'SANTA CATALINA', code: '673', departament: '13')
    CityCase.create(name:'ZAMBRANO', code: '894', departament: '13')
    CityCase.create(name:'SAN PABLO', code: '670', departament: '13')
    CityCase.create(name:'SAN MARTIN DE LOBA', code: '667', departament: '13')
    CityCase.create(name:'EL CARMEN DE BOLIVAR', code: '244', departament: '13')
    CityCase.create(name:'BARRANCO DE LOBA', code: '074', departament: '13')
    CityCase.create(name:'SIMITI', code: '744', departament: '13')
    CityCase.create(name:'TIQUISIO', code: '810', departament: '13')
    CityCase.create(name:'SAN JUAN NEPOMUCENO', code: '657', departament: '13')
    CityCase.create(name:'SANTA ROSA DEL SUR', code: '688', departament: '13')
    CityCase.create(name:'NOROSI', code: '490', departament: '13')
    CityCase.create(name:'CARTAGENA', code: '001', departament: '13')
    CityCase.create(name:'CICUCO', code: '188', departament: '13')
    CityCase.create(name:'MONTECRISTO', code: '458', departament: '13')
    CityCase.create(name:'VILLANUEVA', code: '873', departament: '13')
    CityCase.create(name:'ACHI', code: '006', departament: '13')
    CityCase.create(name:'MORALES', code: '473', departament: '13')
    CityCase.create(name:'PINILLOS', code: '549', departament: '13')
    CityCase.create(name:'HATILLO DE LOBA', code: '300', departament: '13')
    CityCase.create(name:'RIO VIEJO', code: '600', departament: '13')
    CityCase.create(name:'MOMPOS', code: '468', departament: '13')
    CityCase.create(name:'MAHATES', code: '433', departament: '13')
    CityCase.create(name:'SANTA ROSA', code: '683', departament: '13')
    CityCase.create(name:'TALAIGUA NUEVO', code: '780', departament: '13')
    CityCase.create(name:'ARROYOHONDO', code: '062', departament: '13')
    CityCase.create(name:'SAN JACINTO DEL CAUCA', code: '655', departament: '13')
    CityCase.create(name:'SAN CRISTOBAL', code: '620', departament: '13')
    CityCase.create(name:'CALAMAR', code: '140', departament: '13')
    CityCase.create(name:'SAN JACINTO', code: '654', departament: '13')
    CityCase.create(name:'MARIA LA BAJA', code: '442', departament: '13')
    CityCase.create(name:'MAGANGUE', code: '430', departament: '13')
    CityCase.create(name:'CORDOBA', code: '212', departament: '13')
    CityCase.create(name:'SOPLAVIENTO', code: '760', departament: '13')
    CityCase.create(name:'TURBACO', code: '836', departament: '13')
    CityCase.create(name:'CANTAGALLO', code: '160', departament: '13')
    CityCase.create(name:'ARENAL', code: '042', departament: '13')
    CityCase.create(name:'EL GUAMO', code: '248', departament: '13')
    CityCase.create(name:'SAN FERNANDO', code: '650', departament: '13')
    CityCase.create(name:'ALTOS DEL ROSARIO', code: '030', departament: '13')
    CityCase.create(name:'TURBANA', code: '838', departament: '13')
    CityCase.create(name:'EL PENON', code: '268', departament: '13')
    CityCase.create(name:'ARJONA', code: '052', departament: '13')
    CityCase.create(name:'CLEMENCIA', code: '222', departament: '13')
    CityCase.create(name:'SAN ESTANISLAO', code: '647', departament: '13')
    CityCase.create(name:'REGIDOR', code: '580', departament: '13')
    CityCase.create(name:'MARGARITA', code: '440', departament: '13')
    CityCase.create(name:'VENTAQUEMADA', code: '861', departament: '15')
    CityCase.create(name:'ZETAQUIRA', code: '897', departament: '15')
    CityCase.create(name:'TOPAGA', code: '820', departament: '15')
    CityCase.create(name:'CORRALES', code: '215', departament: '15')
    CityCase.create(name:'TENZA', code: '798', departament: '15')
    CityCase.create(name:'TURMEQUE', code: '835', departament: '15')
    CityCase.create(name:'MONGUA', code: '464', departament: '15')
    CityCase.create(name:'FIRAVITOBA', code: '272', departament: '15')
    CityCase.create(name:'GUAYATA', code: '325', departament: '15')
    CityCase.create(name:'MACANAL', code: '425', departament: '15')
    CityCase.create(name:'EL COCUY', code: '244', departament: '15')
    CityCase.create(name:'SANTA SOFIA', code: '696', departament: '15')
    CityCase.create(name:'VILLA DE LEYVA', code: '407', departament: '15')
    CityCase.create(name:'CUITIVA', code: '226', departament: '15')
    CityCase.create(name:'TUTA', code: '837', departament: '15')
    CityCase.create(name:'SOGAMOSO', code: '759', departament: '15')
    CityCase.create(name:'BELEN', code: '087', departament: '15')
    CityCase.create(name:'OICATA', code: '500', departament: '15')
    CityCase.create(name:'CHIVATA', code: '187', departament: '15')
    CityCase.create(name:'COPER', code: '212', departament: '15')
    CityCase.create(name:'LA VICTORIA', code: '401', departament: '15')
    CityCase.create(name:'MUZO', code: '480', departament: '15')
    CityCase.create(name:'TIBASOSA', code: '806', departament: '15')
    CityCase.create(name:'JENESANO', code: '367', departament: '15')
    CityCase.create(name:'BRICENO', code: '106', departament: '15')
    CityCase.create(name:'JERICO', code: '368', departament: '15')
    CityCase.create(name:'QUIPAMA', code: '580', departament: '15')
    CityCase.create(name:'LABRANZAGRANDE', code: '377', departament: '15')
    CityCase.create(name:'SORACA', code: '764', departament: '15')
    CityCase.create(name:'CHISCAS', code: '180', departament: '15')
    CityCase.create(name:'TUNUNGUA', code: '832', departament: '15')
    CityCase.create(name:'PANQUEBA', code: '522', departament: '15')
    CityCase.create(name:'TIBANA', code: '804', departament: '15')
    CityCase.create(name:'PAJARITO', code: '518', departament: '15')
    CityCase.create(name:'PUERTO BOYACA', code: '572', departament: '15')
    CityCase.create(name:'SOTAQUIRA', code: '763', departament: '15')
    CityCase.create(name:'PESCA', code: '542', departament: '15')
    CityCase.create(name:'BOYACA', code: '104', departament: '15')
    CityCase.create(name:'MONGUI', code: '466', departament: '15')
    CityCase.create(name:'CAMPOHERMOSO', code: '135', departament: '15')
    CityCase.create(name:'COVARACHIA', code: '218', departament: '15')
    CityCase.create(name:'SUTAMARCHAN', code: '776', departament: '15')
    CityCase.create(name:'SAN MIGUEL DE SEMA', code: '676', departament: '15')
    CityCase.create(name:'AQUITANIA', code: '047', departament: '15')
    CityCase.create(name:'PAUNA', code: '531', departament: '15')
    CityCase.create(name:'TIPACOQUE', code: '810', departament: '15')
    CityCase.create(name:'LA CAPILLA', code: '380', departament: '15')
    CityCase.create(name:'SABOYA', code: '632', departament: '15')
    CityCase.create(name:'PAYA', code: '533', departament: '15')
    CityCase.create(name:'ALMEIDA', code: '022', departament: '15')
    CityCase.create(name:'CHITARAQUE', code: '185', departament: '15')
    CityCase.create(name:'TUNJA', code: '001', departament: '15')
    CityCase.create(name:'TUTAZA', code: '839', departament: '15')
    CityCase.create(name:'SAN JOSE DE PARE', code: '664', departament: '15')
    CityCase.create(name:'MOTAVITA', code: '476', departament: '15')
    CityCase.create(name:'BUENAVISTA', code: '109', departament: '15')
    CityCase.create(name:'TASCO', code: '790', departament: '15')
    CityCase.create(name:'TOCA', code: '814', departament: '15')
    CityCase.create(name:'MARIPI', code: '442', departament: '15')
    CityCase.create(name:'OTANCHE', code: '507', departament: '15')
    CityCase.create(name:'CUCAITA', code: '224', departament: '15')
    CityCase.create(name:'SAMACA', code: '646', departament: '15')
    CityCase.create(name:'SATIVANORTE', code: '720', departament: '15')
    CityCase.create(name:'PAIPA', code: '516', departament: '15')
    CityCase.create(name:'RONDON', code: '621', departament: '15')
    CityCase.create(name:'BUSBANZA', code: '114', departament: '15')
    CityCase.create(name:'SAN EDUARDO', code: '660', departament: '15')
    CityCase.create(name:'BERBEO', code: '090', departament: '15')
    CityCase.create(name:'SANTA ROSA DE VITERBO', code: '693', departament: '15')
    CityCase.create(name:'SANTANA', code: '686', departament: '15')
    CityCase.create(name:'GACHANTIVA', code: '293', departament: '15')
    CityCase.create(name:'SOCHA', code: '757', departament: '15')
    CityCase.create(name:'PAZ DE RIO', code: '537', departament: '15')
    CityCase.create(name:'SIACHOQUE', code: '740', departament: '15')
    CityCase.create(name:'BETEITIVA', code: '092', departament: '15')
    CityCase.create(name:'SORA', code: '762', departament: '15')
    CityCase.create(name:'SACHICA', code: '638', departament: '15')
    CityCase.create(name:'CHINAVITA', code: '172', departament: '15')
    CityCase.create(name:'CERINZA', code: '162', departament: '15')
    CityCase.create(name:'UMBITA', code: '842', departament: '15')
    CityCase.create(name:'NUEVO COLON', code: '494', departament: '15')
    CityCase.create(name:'CALDAS', code: '131', departament: '15')
    CityCase.create(name:'GARAGOA', code: '299', departament: '15')
    CityCase.create(name:'PACHAVITA', code: '511', departament: '15')
    CityCase.create(name:'SOATA', code: '753', departament: '15')
    CityCase.create(name:'SOCOTA', code: '755', departament: '15')
    CityCase.create(name:'CIENEGA', code: '189', departament: '15')
    CityCase.create(name:'PISBA', code: '550', departament: '15')
    CityCase.create(name:'GUACAMAYAS', code: '317', departament: '15')
    CityCase.create(name:'EL ESPINO', code: '248', departament: '15')
    CityCase.create(name:'MIRAFLORES', code: '455', departament: '15')
    CityCase.create(name:'GAMEZA', code: '296', departament: '15')
    CityCase.create(name:'SAN PABLO DE BORBUR', code: '681', departament: '15')
    CityCase.create(name:'CHIVOR', code: '236', departament: '15')
    CityCase.create(name:'GUICAN', code: '332', departament: '15')
    CityCase.create(name:'CUBARA', code: '223', departament: '15')
    CityCase.create(name:'SAN LUIS DE GACENO', code: '667', departament: '15')
    CityCase.create(name:'PAEZ', code: '514', departament: '15')
    CityCase.create(name:'SAN MATEO', code: '673', departament: '15')
    CityCase.create(name:'TOGUI', code: '816', departament: '15')
    CityCase.create(name:'CHIQUIZA', code: '232', departament: '15')
    CityCase.create(name:'RAMIRIQUI', code: '599', departament: '15')
    CityCase.create(name:'RAQUIRA', code: '600', departament: '15')
    CityCase.create(name:'LA UVITA', code: '403', departament: '15')
    CityCase.create(name:'SUSACON', code: '774', departament: '15')
    CityCase.create(name:'TINJACA', code: '808', departament: '15')
    CityCase.create(name:'NOBSA', code: '491', departament: '15')
    CityCase.create(name:'GUATEQUE', code: '322', departament: '15')
    CityCase.create(name:'IZA', code: '362', departament: '15')
    CityCase.create(name:'BOAVITA', code: '097', departament: '15')
    CityCase.create(name:'SOMONDOCO', code: '761', departament: '15')
    CityCase.create(name:'FLORESTA', code: '276', departament: '15')
    CityCase.create(name:'TOTA', code: '822', departament: '15')
    CityCase.create(name:'CHITA', code: '183', departament: '15')
    CityCase.create(name:'SUTATENZA', code: '778', departament: '15')
    CityCase.create(name:'SATIVASUR', code: '723', departament: '15')
    CityCase.create(name:'VIRACACHA', code: '879', departament: '15')
    CityCase.create(name:'CHIQUINQUIRA', code: '176', departament: '15')
    CityCase.create(name:'MONIQUIRA', code: '469', departament: '15')
    CityCase.create(name:'SANTA MARIA', code: '690', departament: '15')
    CityCase.create(name:'ARCABUCO', code: '051', departament: '15')
    CityCase.create(name:'DUITAMA', code: '238', departament: '15')
    CityCase.create(name:'COMBITA', code: '204', departament: '15')
    CityCase.create(name:'NORCASIA', code: '495', departament: '17')
    CityCase.create(name:'MANIZALES', code: '001', departament: '17')
    CityCase.create(name:'RIOSUCIO', code: '614', departament: '17')
    CityCase.create(name:'MARQUETALIA', code: '444', departament: '17')
    CityCase.create(name:'SUPIA', code: '777', departament: '17')
    CityCase.create(name:'CHINCHINA', code: '174', departament: '17')
    CityCase.create(name:'MANZANARES', code: '433', departament: '17')
    CityCase.create(name:'AGUADAS', code: '013', departament: '17')
    CityCase.create(name:'PACORA', code: '513', departament: '17')
    CityCase.create(name:'LA MERCED', code: '388', departament: '17')
    CityCase.create(name:'LA DORADA', code: '380', departament: '17')
    CityCase.create(name:'VITERBO', code: '877', departament: '17')
    CityCase.create(name:'SAMANA', code: '662', departament: '17')
    CityCase.create(name:'VICTORIA', code: '867', departament: '17')
    CityCase.create(name:'RISARALDA', code: '616', departament: '17')
    CityCase.create(name:'FILADELFIA', code: '272', departament: '17')
    CityCase.create(name:'ANSERMA', code: '042', departament: '17')
    CityCase.create(name:'BELALCAZAR', code: '088', departament: '17')
    CityCase.create(name:'MARMATO', code: '442', departament: '17')
    CityCase.create(name:'PENSILVANIA', code: '541', departament: '17')
    CityCase.create(name:'PALESTINA', code: '524', departament: '17')
    CityCase.create(name:'NEIRA', code: '486', departament: '17')
    CityCase.create(name:'ARANZAZU', code: '050', departament: '17')
    CityCase.create(name:'VILLAMARIA', code: '873', departament: '17')
    CityCase.create(name:'MARULANDA', code: '446', departament: '17')
    CityCase.create(name:'SAN JOSE', code: '665', departament: '17')
    CityCase.create(name:'SALAMINA', code: '653', departament: '17')
    CityCase.create(name:'FLORENCIA', code: '001', departament: '18')
    CityCase.create(name:'EL DONCELLO', code: '247', departament: '18')
    CityCase.create(name:'SAN VICENTE DEL CAGUAN', code: '753', departament: '18')
    CityCase.create(name:'ALBANIA', code: '029', departament: '18')
    CityCase.create(name:'SOLANO', code: '756', departament: '18')
    CityCase.create(name:'EL PAUJIL', code: '256', departament: '18')
    CityCase.create(name:'CARTAGENA DEL CHAIRA', code: '150', departament: '18')
    CityCase.create(name:'VALPARAISO', code: '860', departament: '18')
    CityCase.create(name:'BELEN DE LOS ANDAQUIES', code: '094', departament: '18')
    CityCase.create(name:'SOLITA', code: '785', departament: '18')
    CityCase.create(name:'MILAN', code: '460', departament: '18')
    CityCase.create(name:'LA MONTANITA', code: '410', departament: '18')
    CityCase.create(name:'PUERTO RICO', code: '592', departament: '18')
    CityCase.create(name:'CURILLO', code: '205', departament: '18')
    CityCase.create(name:'MORELIA', code: '479', departament: '18')
    CityCase.create(name:'SAN JOSE DEL FRAGUA', code: '610', departament: '18')
    CityCase.create(name:'AGUAZUL', code: '010', departament: '85')
    CityCase.create(name:'MONTERREY', code: '162', departament: '85')
    CityCase.create(name:'HATO COROZAL', code: '125', departament: '85')
    CityCase.create(name:'CHAMEZA', code: '015', departament: '85')
    CityCase.create(name:'RECETOR', code: '279', departament: '85')
    CityCase.create(name:'PORE', code: '263', departament: '85')
    CityCase.create(name:'SABANALARGA', code: '300', departament: '85')
    CityCase.create(name:'SAN LUIS DE PALENQUE', code: '325', departament: '85')
    CityCase.create(name:'VILLANUEVA', code: '440', departament: '85')
    CityCase.create(name:'LA SALINA', code: '136', departament: '85')
    CityCase.create(name:'MANI', code: '139', departament: '85')
    CityCase.create(name:'YOPAL', code: '001', departament: '85')
    CityCase.create(name:'NUNCHIA', code: '225', departament: '85')
    CityCase.create(name:'SACAMA', code: '315', departament: '85')
    CityCase.create(name:'TAMARA', code: '400', departament: '85')
    CityCase.create(name:'TRINIDAD', code: '430', departament: '85')
    CityCase.create(name:'PAZ DE ARIPORO', code: '250', departament: '85')
    CityCase.create(name:'OROCUE', code: '230', departament: '85')
    CityCase.create(name:'TAURAMENA', code: '410', departament: '85')
    CityCase.create(name:'FLORENCIA', code: '290', departament: '19')
    CityCase.create(name:'TIMBIO', code: '807', departament: '19')
    CityCase.create(name:'GUACHENE', code: '300', departament: '19')
    CityCase.create(name:'LA SIERRA', code: '392', departament: '19')
    CityCase.create(name:'CORINTO', code: '212', departament: '19')
    CityCase.create(name:'TOTORO', code: '824', departament: '19')
    CityCase.create(name:'BUENOS AIRES', code: '110', departament: '19')
    CityCase.create(name:'SANTA ROSA', code: '701', departament: '19')
    CityCase.create(name:'POPAYAN', code: '001', departament: '19')
    CityCase.create(name:'SANTANDER DE QUILICHAO', code: '698', departament: '19')
    CityCase.create(name:'ARGELIA', code: '050', departament: '19')
    CityCase.create(name:'JAMBALO', code: '364', departament: '19')
    CityCase.create(name:'CAJIBIO', code: '130', departament: '19')
    CityCase.create(name:'SUCRE', code: '785', departament: '19')
    CityCase.create(name:'MORALES', code: '473', departament: '19')
    CityCase.create(name:'LA VEGA', code: '397', departament: '19')
    CityCase.create(name:'PADILLA', code: '513', departament: '19')
    CityCase.create(name:'LOPEZ', code: '418', departament: '19')
    CityCase.create(name:'PAEZ', code: '517', departament: '19')
    CityCase.create(name:'PIAMONTE', code: '533', departament: '19')
    CityCase.create(name:'SUAREZ', code: '780', departament: '19')
    CityCase.create(name:'PURACE', code: '585', departament: '19')
    CityCase.create(name:'BOLIVAR', code: '100', departament: '19')
    CityCase.create(name:'PUERTO TEJADA', code: '573', departament: '19')
    CityCase.create(name:'ALMAGUER', code: '022', departament: '19')
    CityCase.create(name:'PIENDAMO', code: '548', departament: '19')
    CityCase.create(name:'TIMBIQUI', code: '809', departament: '19')
    CityCase.create(name:'INZA', code: '355', departament: '19')
    CityCase.create(name:'EL TAMBO', code: '256', departament: '19')
    CityCase.create(name:'ROSAS', code: '622', departament: '19')
    CityCase.create(name:'CALOTO', code: '142', departament: '19')
    CityCase.create(name:'SAN SEBASTIAN', code: '693', departament: '19')
    CityCase.create(name:'VILLA RICA', code: '845', departament: '19')
    CityCase.create(name:'PATIA', code: '532', departament: '19')
    CityCase.create(name:'SILVIA', code: '743', departament: '19')
    CityCase.create(name:'GUAPI', code: '318', departament: '19')
    CityCase.create(name:'SOTARA', code: '760', departament: '19')
    CityCase.create(name:'MIRANDA', code: '455', departament: '19')
    CityCase.create(name:'CALDONO', code: '137', departament: '19')
    CityCase.create(name:'BALBOA', code: '075', departament: '19')
    CityCase.create(name:'TORIBIO', code: '821', departament: '19')
    CityCase.create(name:'MERCADERES', code: '450', departament: '19')
    CityCase.create(name:'LA GLORIA', code: '383', departament: '20')
    CityCase.create(name:'SAN ALBERTO', code: '710', departament: '20')
    CityCase.create(name:'AGUSTIN CODAZZI', code: '013', departament: '20')
    CityCase.create(name:'CHIRIGUANA', code: '178', departament: '20')
    CityCase.create(name:'MANAURE', code: '443', departament: '20')
    CityCase.create(name:'TAMALAMEQUE', code: '787', departament: '20')
    CityCase.create(name:'SAN DIEGO', code: '750', departament: '20')
    CityCase.create(name:'EL COPEY', code: '238', departament: '20')
    CityCase.create(name:'EL PASO', code: '250', departament: '20')
    CityCase.create(name:'LA JAGUA DE IBIRICO', code: '400', departament: '20')
    CityCase.create(name:'RIO DE ORO', code: '614', departament: '20')
    CityCase.create(name:'GAMARRA', code: '295', departament: '20')
    CityCase.create(name:'CURUMANI', code: '228', departament: '20')
    CityCase.create(name:'PUEBLO BELLO', code: '570', departament: '20')
    CityCase.create(name:'BECERRIL', code: '045', departament: '20')
    CityCase.create(name:'PELAYA', code: '550', departament: '20')
    CityCase.create(name:'BOSCONIA', code: '060', departament: '20')
    CityCase.create(name:'CHIMICHAGUA', code: '175', departament: '20')
    CityCase.create(name:'VALLEDUPAR', code: '001', departament: '20')
    CityCase.create(name:'GONZALEZ', code: '310', departament: '20')
    CityCase.create(name:'PAILITAS', code: '517', departament: '20')
    CityCase.create(name:'AGUACHICA', code: '011', departament: '20')
    CityCase.create(name:'SAN MARTIN', code: '770', departament: '20')
    CityCase.create(name:'ASTREA', code: '032', departament: '20')
    CityCase.create(name:'LA PAZ', code: '621', departament: '20')
    CityCase.create(name:'ATRATO', code: '050', departament: '27')
    CityCase.create(name:'CERTEGUI', code: '160', departament: '27')
    CityCase.create(name:'RIOSUCIO', code: '615', departament: '27')
    CityCase.create(name:'NOVITA', code: '491', departament: '27')
    CityCase.create(name:'TADO', code: '787', departament: '27')
    CityCase.create(name:'EL CARMEN DE ATRATO', code: '245', departament: '27')
    CityCase.create(name:'EL CANTON DEL SAN PABLO', code: '135', departament: '27')
    CityCase.create(name:'QUIBDO', code: '001', departament: '27')
    CityCase.create(name:'CARMEN DEL DARIEN', code: '150', departament: '27')
    CityCase.create(name:'MEDIO ATRATO', code: '425', departament: '27')
    CityCase.create(name:'BAGADO', code: '073', departament: '27')
    CityCase.create(name:'LLORO', code: '413', departament: '27')
    CityCase.create(name:'CONDOTO', code: '205', departament: '27')
    CityCase.create(name:'RIO QUITO', code: '600', departament: '27')
    CityCase.create(name:'SIPI', code: '745', departament: '27')
    CityCase.create(name:'ISTMINA', code: '361', departament: '27')
    CityCase.create(name:'UNION PANAMERICANA', code: '810', departament: '27')
    CityCase.create(name:'BAJO BAUDO', code: '077', departament: '27')
    CityCase.create(name:'SAN JOSE DEL PALMAR', code: '660', departament: '27')
    CityCase.create(name:'ALTO BAUDO', code: '025', departament: '27')
    CityCase.create(name:'MEDIO BAUDO', code: '430', departament: '27')
    CityCase.create(name:'ACANDI', code: '006', departament: '27')
    CityCase.create(name:'UNGUIA', code: '800', departament: '27')
    CityCase.create(name:'MEDIO SAN JUAN', code: '450', departament: '27')
    CityCase.create(name:'BOJAYA', code: '099', departament: '27')
    CityCase.create(name:'JURADO', code: '372', departament: '27')
    CityCase.create(name:'EL LITORAL DEL SAN JUAN', code: '250', departament: '27')
    CityCase.create(name:'RIO IRO', code: '580', departament: '27')
    CityCase.create(name:'BAHIA SOLANO', code: '075', departament: '27')
    CityCase.create(name:'NUQUI', code: '495', departament: '27')
    CityCase.create(name:'SAN CARLOS', code: '678', departament: '23')
    CityCase.create(name:'SAN BERNARDO DEL VIENTO', code: '675', departament: '23')
    CityCase.create(name:'BUENAVISTA', code: '079', departament: '23')
    CityCase.create(name:'LOS CORDOBAS', code: '419', departament: '23')
    CityCase.create(name:'CIENAGA DE ORO', code: '189', departament: '23')
    CityCase.create(name:'PUERTO ESCONDIDO', code: '574', departament: '23')
    CityCase.create(name:'PLANETA RICA', code: '555', departament: '23')
    CityCase.create(name:'CANALETE', code: '090', departament: '23')
    CityCase.create(name:'AYAPEL', code: '068', departament: '23')
    CityCase.create(name:'MONTELIBANO', code: '466', departament: '23')
    CityCase.create(name:'SAN PELAYO', code: '686', departament: '23')
    CityCase.create(name:'SAN ANTERO', code: '672', departament: '23')
    CityCase.create(name:'SAN ANDRES SOTAVENTO', code: '670', departament: '23')
    CityCase.create(name:'VALENCIA', code: '855', departament: '23')
    CityCase.create(name:'CHIMA', code: '168', departament: '23')
    CityCase.create(name:'CHINU', code: '182', departament: '23')
    CityCase.create(name:'MONITOS', code: '500', departament: '23')
    CityCase.create(name:'MOMIL', code: '464', departament: '23')
    CityCase.create(name:'COTORRA', code: '300', departament: '23')
    CityCase.create(name:'PUERTO LIBERTADOR', code: '580', departament: '23')
    CityCase.create(name:'PURISIMA', code: '586', departament: '23')
    CityCase.create(name:'CERETE', code: '162', departament: '23')
    CityCase.create(name:'SAHAGUN', code: '660', departament: '23')
    CityCase.create(name:'TIERRALTA', code: '807', departament: '23')
    CityCase.create(name:'MONTERIA', code: '001', departament: '23')
    CityCase.create(name:'TUCHIN', code: '815', departament: '23')
    CityCase.create(name:'SAN JOSE DE URE', code: '682', departament: '23')
    CityCase.create(name:'LA APARTADA', code: '350', departament: '23')
    CityCase.create(name:'PUEBLO NUEVO', code: '570', departament: '23')
    CityCase.create(name:'LORICA', code: '417', departament: '23')
    CityCase.create(name:'SILVANIA', code: '743', departament: '25')
    CityCase.create(name:'NEMOCON', code: '486', departament: '25')
    CityCase.create(name:'TABIO', code: '785', departament: '25')
    CityCase.create(name:'PAIME', code: '518', departament: '25')
    CityCase.create(name:'GUATAVITA', code: '326', departament: '25')
    CityCase.create(name:'ANOLAIMA', code: '040', departament: '25')
    CityCase.create(name:'FUSAGASUGA', code: '290', departament: '25')
    CityCase.create(name:'ANAPOIMA', code: '035', departament: '25')
    CityCase.create(name:'NILO', code: '488', departament: '25')
    CityCase.create(name:'VILLAPINZON', code: '873', departament: '25')
    CityCase.create(name:'SAN BERNARDO', code: '649', departament: '25')
    CityCase.create(name:'VILLETA', code: '875', departament: '25')
    CityCase.create(name:'QUETAME', code: '594', departament: '25')
    CityCase.create(name:'PARATEBUENO', code: '530', departament: '25')
    CityCase.create(name:'GUACHETA', code: '317', departament: '25')
    CityCase.create(name:'AGUA DE DIOS', code: '001', departament: '25')
    CityCase.create(name:'LA PENA', code: '398', departament: '25')
    CityCase.create(name:'APULO', code: '599', departament: '25')
    CityCase.create(name:'SASAIMA', code: '718', departament: '25')
    CityCase.create(name:'UTICA', code: '851', departament: '25')
    CityCase.create(name:'CACHIPAY', code: '123', departament: '25')
    CityCase.create(name:'COGUA', code: '200', departament: '25')
    CityCase.create(name:'TOCAIMA', code: '815', departament: '25')
    CityCase.create(name:'SAN ANTONIO DEL TEQUENDAMA', code: '645', departament: '25')
    CityCase.create(name:'SUTATAUSA', code: '781', departament: '25')
    CityCase.create(name:'PANDI', code: '524', departament: '25')
    CityCase.create(name:'QUEBRADANEGRA', code: '592', departament: '25')
    CityCase.create(name:'JERUSALEN', code: '368', departament: '25')
    CityCase.create(name:'MACHETA', code: '426', departament: '25')
    CityCase.create(name:'CAQUEZA', code: '151', departament: '25')
    CityCase.create(name:'VILLA DE SAN DIEGO DE UBATE', code: '843', departament: '25')
    CityCase.create(name:'GUATAQUI', code: '324', departament: '25')
    CityCase.create(name:'FOMEQUE', code: '279', departament: '25')
    CityCase.create(name:'NOCAIMA', code: '491', departament: '25')
    CityCase.create(name:'CHIA', code: '175', departament: '25')
    CityCase.create(name:'PULI', code: '580', departament: '25')
    CityCase.create(name:'SOACHA', code: '754', departament: '25')
    CityCase.create(name:'FOSCA', code: '281', departament: '25')
    CityCase.create(name:'CAPARRAPI', code: '148', departament: '25')
    CityCase.create(name:'RICAURTE', code: '612', departament: '25')
    CityCase.create(name:'GUAYABAL DE SIQUIMA', code: '328', departament: '25')
    CityCase.create(name:'SAN CAYETANO', code: '653', departament: '25')
    CityCase.create(name:'BITUIMA', code: '095', departament: '25')
    CityCase.create(name:'CAJICA', code: '126', departament: '25')
    CityCase.create(name:'LENGUAZAQUE', code: '407', departament: '25')
    CityCase.create(name:'EL COLEGIO', code: '245', departament: '25')
    CityCase.create(name:'NARINO', code: '483', departament: '25')
    CityCase.create(name:'VILLAGOMEZ', code: '871', departament: '25')
    CityCase.create(name:'CHOCONTA', code: '183', departament: '25')
    CityCase.create(name:'GUTIERREZ', code: '339', departament: '25')
    CityCase.create(name:'TOCANCIPA', code: '817', departament: '25')
    CityCase.create(name:'MANTA', code: '436', departament: '25')
    CityCase.create(name:'TIBACUY', code: '805', departament: '25')
    CityCase.create(name:'CHIPAQUE', code: '178', departament: '25')
    CityCase.create(name:'CABRERA', code: '120', departament: '25')
    CityCase.create(name:'PUERTO SALGAR', code: '572', departament: '25')
    CityCase.create(name:'UBAQUE', code: '841', departament: '25')
    CityCase.create(name:'GUAYABETAL', code: '335', departament: '25')
    CityCase.create(name:'TENA', code: '797', departament: '25')
    CityCase.create(name:'SESQUILE', code: '736', departament: '25')
    CityCase.create(name:'QUIPILE', code: '596', departament: '25')
    CityCase.create(name:'GACHALA', code: '293', departament: '25')
    CityCase.create(name:'YACOPI', code: '885', departament: '25')
    CityCase.create(name:'GACHETA', code: '297', departament: '25')
    CityCase.create(name:'MADRID', code: '430', departament: '25')
    CityCase.create(name:'COTA', code: '214', departament: '25')
    CityCase.create(name:'MOSQUERA', code: '473', departament: '25')
    CityCase.create(name:'GAMA', code: '299', departament: '25')
    CityCase.create(name:'TAUSA', code: '793', departament: '25')
    CityCase.create(name:'LA PALMA', code: '394', departament: '25')
    CityCase.create(name:'VIOTA', code: '878', departament: '25')
    CityCase.create(name:'PACHO', code: '513', departament: '25')
    CityCase.create(name:'SUPATA', code: '777', departament: '25')
    CityCase.create(name:'EL PENON', code: '258', departament: '25')
    CityCase.create(name:'LA MESA', code: '386', departament: '25')
    CityCase.create(name:'GUASCA', code: '322', departament: '25')
    CityCase.create(name:'SUSA', code: '779', departament: '25')
    CityCase.create(name:'MEDINA', code: '438', departament: '25')
    CityCase.create(name:'SIBATE', code: '740', departament: '25')
    CityCase.create(name:'UNE', code: '845', departament: '25')
    CityCase.create(name:'GUADUAS', code: '320', departament: '25')
    CityCase.create(name:'SUESCA', code: '772', departament: '25')
    CityCase.create(name:'SAN JUAN DE RIO SECO', code: '662', departament: '25')
    CityCase.create(name:'FUNZA', code: '286', departament: '25')
    CityCase.create(name:'CHOACHI', code: '181', departament: '25')
    CityCase.create(name:'FUQUENE', code: '288', departament: '25')
    CityCase.create(name:'BOJACA', code: '099', departament: '25')
    CityCase.create(name:'SIMIJACA', code: '745', departament: '25')
    CityCase.create(name:'SUBACHOQUE', code: '769', departament: '25')
    CityCase.create(name:'ZIPAQUIRA', code: '899', departament: '25')
    CityCase.create(name:'EL ROSAL', code: '260', departament: '25')
    CityCase.create(name:'TOPAIPI', code: '823', departament: '25')
    CityCase.create(name:'GRANADA', code: '312', departament: '25')
    CityCase.create(name:'VIANI', code: '867', departament: '25')
    CityCase.create(name:'BELTRAN', code: '086', departament: '25')
    CityCase.create(name:'CHAGUANI', code: '168', departament: '25')
    CityCase.create(name:'ZIPACON', code: '898', departament: '25')
    CityCase.create(name:'LA VEGA', code: '402', departament: '25')
    CityCase.create(name:'VENECIA', code: '506', departament: '25')
    CityCase.create(name:'CARMEN DE CARUPA', code: '154', departament: '25')
    CityCase.create(name:'VERGARA', code: '862', departament: '25')
    CityCase.create(name:'CUCUNUBA', code: '224', departament: '25')
    CityCase.create(name:'TENJO', code: '799', departament: '25')
    CityCase.create(name:'ALBAN', code: '019', departament: '25')
    CityCase.create(name:'NIMAIMA', code: '489', departament: '25')
    CityCase.create(name:'JUNIN', code: '372', departament: '25')
    CityCase.create(name:'PASCA', code: '535', departament: '25')
    CityCase.create(name:'UBALA', code: '839', departament: '25')
    CityCase.create(name:'SAN FRANCISCO', code: '658', departament: '25')
    CityCase.create(name:'GIRARDOT', code: '307', departament: '25')
    CityCase.create(name:'SOPO', code: '758', departament: '25')
    CityCase.create(name:'ARBELAEZ', code: '053', departament: '25')
    CityCase.create(name:'GACHANCIPA', code: '295', departament: '25')
    CityCase.create(name:'FACATATIVA', code: '269', departament: '25')
    CityCase.create(name:'LA CALERA', code: '377', departament: '25')
    CityCase.create(name:'TIBIRITA', code: '807', departament: '25')
    CityCase.create(name:'CACAHUAL', code: '886', departament: '94')
    CityCase.create(name:'PANA PANA', code: '887', departament: '94')
    CityCase.create(name:'MAPIRIPANA', code: '663', departament: '94')
    CityCase.create(name:'MORICHAL', code: '888', departament: '94')
    CityCase.create(name:'BARRANCO MINAS', code: '343', departament: '94')
    CityCase.create(name:'INIRIDA', code: '001', departament: '94')
    CityCase.create(name:'PUERTO COLOMBIA', code: '884', departament: '94')
    CityCase.create(name:'LA GUADALUPE', code: '885', departament: '94')
    CityCase.create(name:'SAN FELIPE', code: '883', departament: '94')
    CityCase.create(name:'CALAMAR', code: '015', departament: '95')
    CityCase.create(name:'EL RETORNO', code: '025', departament: '95')
    CityCase.create(name:'SAN JOSE DEL GUAVIARE', code: '001', departament: '95')
    CityCase.create(name:'MIRAFLORES', code: '200', departament: '95')
    CityCase.create(name:'SAN AGUSTIN', code: '668', departament: '41')
    CityCase.create(name:'PALERMO', code: '524', departament: '41')
    CityCase.create(name:'TARQUI', code: '791', departament: '41')
    CityCase.create(name:'HOBO', code: '349', departament: '41')
    CityCase.create(name:'LA PLATA', code: '396', departament: '41')
    CityCase.create(name:'TIMANA', code: '807', departament: '41')
    CityCase.create(name:'NEIVA', code: '001', departament: '41')
    CityCase.create(name:'CAMPOALEGRE', code: '132', departament: '41')
    CityCase.create(name:'TESALIA', code: '797', departament: '41')
    CityCase.create(name:'YAGUARA', code: '885', departament: '41')
    CityCase.create(name:'OPORAPA', code: '503', departament: '41')
    CityCase.create(name:'SALADOBLANCO', code: '660', departament: '41')
    CityCase.create(name:'ELIAS', code: '244', departament: '41')
    CityCase.create(name:'COLOMBIA', code: '206', departament: '41')
    CityCase.create(name:'VILLAVIEJA', code: '872', departament: '41')
    CityCase.create(name:'NATAGA', code: '483', departament: '41')
    CityCase.create(name:'PALESTINA', code: '530', departament: '41')
    CityCase.create(name:'RIVERA', code: '615', departament: '41')
    CityCase.create(name:'ALGECIRAS', code: '020', departament: '41')
    CityCase.create(name:'TELLO', code: '799', departament: '41')
    CityCase.create(name:'ACEVEDO', code: '006', departament: '41')
    CityCase.create(name:'PITALITO', code: '551', departament: '41')
    CityCase.create(name:'GUADALUPE', code: '319', departament: '41')
    CityCase.create(name:'BARAYA', code: '078', departament: '41')
    CityCase.create(name:'AIPE', code: '016', departament: '41')
    CityCase.create(name:'SANTA MARIA', code: '676', departament: '41')
    CityCase.create(name:'LA ARGENTINA', code: '378', departament: '41')
    CityCase.create(name:'ALTAMIRA', code: '026', departament: '41')
    CityCase.create(name:'GIGANTE', code: '306', departament: '41')
    CityCase.create(name:'ISNOS', code: '359', departament: '41')
    CityCase.create(name:'PAICOL', code: '518', departament: '41')
    CityCase.create(name:'GARZON', code: '298', departament: '41')
    CityCase.create(name:'AGRADO', code: '013', departament: '41')
    CityCase.create(name:'TERUEL', code: '801', departament: '41')
    CityCase.create(name:'IQUIRA', code: '357', departament: '41')
    CityCase.create(name:'SUAZA', code: '770', departament: '41')
    CityCase.create(name:'PITAL', code: '548', departament: '41')
    CityCase.create(name:'DIBULLA', code: '090', departament: '44')
    CityCase.create(name:'DISTRACCION', code: '098', departament: '44')
    CityCase.create(name:'SAN JUAN DEL CESAR', code: '650', departament: '44')
    CityCase.create(name:'MAICAO', code: '430', departament: '44')
    CityCase.create(name:'VILLANUEVA', code: '874', departament: '44')
    CityCase.create(name:'URIBIA', code: '847', departament: '44')
    CityCase.create(name:'BARRANCAS', code: '078', departament: '44')
    CityCase.create(name:'ALBANIA', code: '035', departament: '44')
    CityCase.create(name:'EL MOLINO', code: '110', departament: '44')
    CityCase.create(name:'HATONUEVO', code: '378', departament: '44')
    CityCase.create(name:'MANAURE', code: '560', departament: '44')
    CityCase.create(name:'FONSECA', code: '279', departament: '44')
    CityCase.create(name:'URUMITA', code: '855', departament: '44')
    CityCase.create(name:'RIOHACHA', code: '001', departament: '44')
    CityCase.create(name:'LA JAGUA DEL PILAR', code: '420', departament: '44')
    CityCase.create(name:'PLATO', code: '555', departament: '47')
    CityCase.create(name:'ARIGUANI', code: '058', departament: '47')
    CityCase.create(name:'CHIVOLO', code: '170', departament: '47')
    CityCase.create(name:'SANTA ANA', code: '707', departament: '47')
    CityCase.create(name:'ALGARROBO', code: '030', departament: '47')
    CityCase.create(name:'EL PINON', code: '258', departament: '47')
    CityCase.create(name:'SALAMINA', code: '675', departament: '47')
    CityCase.create(name:'SAN SEBASTIAN DE BUENAVISTA', code: '692', departament: '47')
    CityCase.create(name:'EL RETEN', code: '268', departament: '47')
    CityCase.create(name:'PIVIJAY', code: '551', departament: '47')
    CityCase.create(name:'ARACATACA', code: '053', departament: '47')
    CityCase.create(name:'CONCORDIA', code: '205', departament: '47')
    CityCase.create(name:'EL BANCO', code: '245', departament: '47')
    CityCase.create(name:'PEDRAZA', code: '541', departament: '47')
    CityCase.create(name:'REMOLINO', code: '605', departament: '47')
    CityCase.create(name:'CIENAGA', code: '189', departament: '47')
    CityCase.create(name:'GUAMAL', code: '318', departament: '47')
    CityCase.create(name:'NUEVA GRANADA', code: '460', departament: '47')
    CityCase.create(name:'SANTA MARTA', code: '001', departament: '47')
    CityCase.create(name:'ZAPAYAN', code: '960', departament: '47')
    CityCase.create(name:'CERRO SAN ANTONIO', code: '161', departament: '47')
    CityCase.create(name:'SANTA BARBARA DE PINTO', code: '720', departament: '47')
    CityCase.create(name:'PUEBLOVIEJO', code: '570', departament: '47')
    CityCase.create(name:'TENERIFE', code: '798', departament: '47')
    CityCase.create(name:'SABANAS DE SAN ANGEL', code: '660', departament: '47')
    CityCase.create(name:'PIJINO DEL CARMEN', code: '545', departament: '47')
    CityCase.create(name:'SAN ZENON', code: '703', departament: '47')
    CityCase.create(name:'FUNDACION', code: '288', departament: '47')
    CityCase.create(name:'ZONA BANANERA', code: '980', departament: '47')
    CityCase.create(name:'SITIONUEVO', code: '745', departament: '47')
    CityCase.create(name:'GRANADA', code: '313', departament: '50')
    CityCase.create(name:'PUERTO LOPEZ', code: '573', departament: '50')
    CityCase.create(name:'MAPIRIPAN', code: '325', departament: '50')
    CityCase.create(name:'CABUYARO', code: '124', departament: '50')
    CityCase.create(name:'SAN JUANITO', code: '686', departament: '50')
    CityCase.create(name:'PUERTO LLERAS', code: '577', departament: '50')
    CityCase.create(name:'RESTREPO', code: '606', departament: '50')
    CityCase.create(name:'SAN JUAN DE ARAMA', code: '683', departament: '50')
    CityCase.create(name:'EL CASTILLO', code: '251', departament: '50')
    CityCase.create(name:'PUERTO GAITAN', code: '568', departament: '50')
    CityCase.create(name:'EL DORADO', code: '270', departament: '50')
    CityCase.create(name:'VISTAHERMOSA', code: '711', departament: '50')
    CityCase.create(name:'FUENTE DE ORO', code: '287', departament: '50')
    CityCase.create(name:'PUERTO RICO', code: '590', departament: '50')
    CityCase.create(name:'URIBE', code: '370', departament: '50')
    CityCase.create(name:'SAN CARLOS DE GUAROA', code: '680', departament: '50')
    CityCase.create(name:'GUAMAL', code: '318', departament: '50')
    CityCase.create(name:'CASTILLA LA NUEVA', code: '150', departament: '50')
    CityCase.create(name:'EL CALVARIO', code: '245', departament: '50')
    CityCase.create(name:'MESETAS', code: '330', departament: '50')
    CityCase.create(name:'ACACIAS', code: '006', departament: '50')
    CityCase.create(name:'CUBARRAL', code: '223', departament: '50')
    CityCase.create(name:'VILLAVICENCIO', code: '001', departament: '50')
    CityCase.create(name:'CUMARAL', code: '226', departament: '50')
    CityCase.create(name:'PUERTO CONCORDIA', code: '450', departament: '50')
    CityCase.create(name:'LA MACARENA', code: '350', departament: '50')
    CityCase.create(name:'LEJANIAS', code: '400', departament: '50')
    CityCase.create(name:'SAN MARTIN', code: '689', departament: '50')
    CityCase.create(name:'BARRANCA DE UPIA', code: '110', departament: '50')
    CityCase.create(name:'PUERRES', code: '573', departament: '52')
    CityCase.create(name:'GUACHUCAL', code: '317', departament: '52')
    CityCase.create(name:'GUALMATAN', code: '323', departament: '52')
    CityCase.create(name:'CUMBAL', code: '227', departament: '52')
    CityCase.create(name:'OSPINA', code: '506', departament: '52')
    CityCase.create(name:'SAN BERNARDO', code: '685', departament: '52')
    CityCase.create(name:'EL TAMBO', code: '260', departament: '52')
    CityCase.create(name:'LA CRUZ', code: '378', departament: '52')
    CityCase.create(name:'MOSQUERA', code: '473', departament: '52')
    CityCase.create(name:'GUAITARILLA', code: '320', departament: '52')
    CityCase.create(name:'SANTACRUZ', code: '699', departament: '52')
    CityCase.create(name:'TAMINANGO', code: '786', departament: '52')
    CityCase.create(name:'MAGUI', code: '427', departament: '52')
    CityCase.create(name:'BUESACO', code: '110', departament: '52')
    CityCase.create(name:'ALBAN', code: '019', departament: '52')
    CityCase.create(name:'SAN PEDRO DE CARTAGO', code: '694', departament: '52')
    CityCase.create(name:'ARBOLEDA', code: '051', departament: '52')
    CityCase.create(name:'POTOSI', code: '560', departament: '52')
    CityCase.create(name:'EL ROSARIO', code: '256', departament: '52')
    CityCase.create(name:'LA TOLA', code: '390', departament: '52')
    CityCase.create(name:'CORDOBA', code: '215', departament: '52')
    CityCase.create(name:'CUMBITARA', code: '233', departament: '52')
    CityCase.create(name:'FUNES', code: '287', departament: '52')
    CityCase.create(name:'PROVIDENCIA', code: '565', departament: '52')
    CityCase.create(name:'COLON', code: '203', departament: '52')
    CityCase.create(name:'ROBERTO PAYAN', code: '621', departament: '52')
    CityCase.create(name:'EL CHARCO', code: '250', departament: '52')
    CityCase.create(name:'CUASPUD', code: '224', departament: '52')
    CityCase.create(name:'SAPUYES', code: '720', departament: '52')
    CityCase.create(name:'LA UNION', code: '399', departament: '52')
    CityCase.create(name:'SANTA BARBARA', code: '696', departament: '52')
    CityCase.create(name:'SAN LORENZO', code: '687', departament: '52')
    CityCase.create(name:'ALDANA', code: '022', departament: '52')
    CityCase.create(name:'BARBACOAS', code: '079', departament: '52')
    CityCase.create(name:'CONTADERO', code: '210', departament: '52')
    CityCase.create(name:'IPIALES', code: '356', departament: '52')
    CityCase.create(name:'PASTO', code: '001', departament: '52')
    CityCase.create(name:'RICAURTE', code: '612', departament: '52')
    CityCase.create(name:'SAMANIEGO', code: '678', departament: '52')
    CityCase.create(name:'EL TABLON DE GOMEZ', code: '258', departament: '52')
    CityCase.create(name:'TUQUERRES', code: '838', departament: '52')
    CityCase.create(name:'NARINO', code: '480', departament: '52')
    CityCase.create(name:'BELEN', code: '083', departament: '52')
    CityCase.create(name:'IMUES', code: '354', departament: '52')
    CityCase.create(name:'ILES', code: '352', departament: '52')
    CityCase.create(name:'POLICARPA', code: '540', departament: '52')
    CityCase.create(name:'OLAYA HERRERA', code: '490', departament: '52')
    CityCase.create(name:'SANDONA', code: '683', departament: '52')
    CityCase.create(name:'FRANCISCO PIZARRO', code: '520', departament: '52')
    CityCase.create(name:'EL PENOL', code: '254', departament: '52')
    CityCase.create(name:'YACUANQUER', code: '885', departament: '52')
    CityCase.create(name:'SAN PABLO', code: '693', departament: '52')
    CityCase.create(name:'ANCUYA', code: '036', departament: '52')
    CityCase.create(name:'LA FLORIDA', code: '381', departament: '52')
    CityCase.create(name:'PUPIALES', code: '585', departament: '52')
    CityCase.create(name:'CHACHAGUI', code: '240', departament: '52')
    CityCase.create(name:'LA LLANADA', code: '385', departament: '52')
    CityCase.create(name:'SAN ANDRES DE TUMACO', code: '835', departament: '52')
    CityCase.create(name:'TANGUA', code: '788', departament: '52')
    CityCase.create(name:'LINARES', code: '411', departament: '52')
    CityCase.create(name:'LOS ANDES', code: '418', departament: '52')
    CityCase.create(name:'CONSACA', code: '207', departament: '52')
    CityCase.create(name:'LEIVA', code: '405', departament: '52')
    CityCase.create(name:'MALLAMA', code: '435', departament: '52')
    CityCase.create(name:'EL ZULIA', code: '261', departament: '54')
    CityCase.create(name:'SANTIAGO', code: '680', departament: '54')
    CityCase.create(name:'PUERTO SANTANDER', code: '553', departament: '54')
    CityCase.create(name:'HACARI', code: '344', departament: '54')
    CityCase.create(name:'TIBU', code: '810', departament: '54')
    CityCase.create(name:'SILOS', code: '743', departament: '54')
    CityCase.create(name:'CHITAGA', code: '174', departament: '54')
    CityCase.create(name:'OCANA', code: '498', departament: '54')
    CityCase.create(name:'HERRAN', code: '347', departament: '54')
    CityCase.create(name:'BOCHALEMA', code: '099', departament: '54')
    CityCase.create(name:'CONVENCION', code: '206', departament: '54')
    CityCase.create(name:'CACOTA', code: '125', departament: '54')
    CityCase.create(name:'ABREGO', code: '003', departament: '54')
    CityCase.create(name:'LA PLAYA', code: '398', departament: '54')
    CityCase.create(name:'BUCARASICA', code: '109', departament: '54')
    CityCase.create(name:'SALAZAR', code: '660', departament: '54')
    CityCase.create(name:'EL TARRA', code: '250', departament: '54')
    CityCase.create(name:'LOS PATIOS', code: '405', departament: '54')
    CityCase.create(name:'VILLA CARO', code: '871', departament: '54')
    CityCase.create(name:'LOURDES', code: '418', departament: '54')
    CityCase.create(name:'PAMPLONITA', code: '520', departament: '54')
    CityCase.create(name:'ARBOLEDAS', code: '051', departament: '54')
    CityCase.create(name:'LABATECA', code: '377', departament: '54')
    CityCase.create(name:'VILLA DEL ROSARIO', code: '874', departament: '54')
    CityCase.create(name:'RAGONVALIA', code: '599', departament: '54')
    CityCase.create(name:'CUCUTILLA', code: '223', departament: '54')
    CityCase.create(name:'EL CARMEN', code: '245', departament: '54')
    CityCase.create(name:'PAMPLONA', code: '518', departament: '54')
    CityCase.create(name:'CUCUTA', code: '001', departament: '54')
    CityCase.create(name:'DURANIA', code: '239', departament: '54')
    CityCase.create(name:'CHINACOTA', code: '172', departament: '54')
    CityCase.create(name:'SARDINATA', code: '720', departament: '54')
    CityCase.create(name:'TEORAMA', code: '800', departament: '54')
    CityCase.create(name:'MUTISCUA', code: '480', departament: '54')
    CityCase.create(name:'SAN CAYETANO', code: '673', departament: '54')
    CityCase.create(name:'GRAMALOTE', code: '313', departament: '54')
    CityCase.create(name:'SAN CALIXTO', code: '670', departament: '54')
    CityCase.create(name:'CACHIRA', code: '128', departament: '54')
    CityCase.create(name:'TOLEDO', code: '820', departament: '54')
    CityCase.create(name:'LA ESPERANZA', code: '385', departament: '54')
    CityCase.create(name:'SANTIAGO', code: '760', departament: '86')
    CityCase.create(name:'SIBUNDOY', code: '749', departament: '86')
    CityCase.create(name:'VALLE DEL GUAMUEZ', code: '865', departament: '86')
    CityCase.create(name:'ORITO', code: '320', departament: '86')
    CityCase.create(name:'VILLAGARZON', code: '885', departament: '86')
    CityCase.create(name:'SAN FRANCISCO', code: '755', departament: '86')
    CityCase.create(name:'PUERTO LEGUIZAMO', code: '573', departament: '86')
    CityCase.create(name:'SAN MIGUEL', code: '757', departament: '86')
    CityCase.create(name:'PUERTO GUZMAN', code: '571', departament: '86')
    CityCase.create(name:'PUERTO CAICEDO', code: '569', departament: '86')
    CityCase.create(name:'COLON', code: '219', departament: '86')
    CityCase.create(name:'PUERTO ASIS', code: '568', departament: '86')
    CityCase.create(name:'MOCOA', code: '001', departament: '86')
    CityCase.create(name:'CALARCA', code: '130', departament: '63')
    CityCase.create(name:'BUENAVISTA', code: '111', departament: '63')
    CityCase.create(name:'MONTENEGRO', code: '470', departament: '63')
    CityCase.create(name:'LA TEBAIDA', code: '401', departament: '63')
    CityCase.create(name:'QUIMBAYA', code: '594', departament: '63')
    CityCase.create(name:'GENOVA', code: '302', departament: '63')
    CityCase.create(name:'CORDOBA', code: '212', departament: '63')
    CityCase.create(name:'SALENTO', code: '690', departament: '63')
    CityCase.create(name:'PIJAO', code: '548', departament: '63')
    CityCase.create(name:'FILANDIA', code: '272', departament: '63')
    CityCase.create(name:'ARMENIA', code: '001', departament: '63')
    CityCase.create(name:'CIRCASIA', code: '190', departament: '63')
    CityCase.create(name:'MARSELLA', code: '440', departament: '66')
    CityCase.create(name:'LA VIRGINIA', code: '400', departament: '66')
    CityCase.create(name:'MISTRATO', code: '456', departament: '66')
    CityCase.create(name:'QUINCHIA', code: '594', departament: '66')
    CityCase.create(name:'APIA', code: '045', departament: '66')
    CityCase.create(name:'DOSQUEBRADAS', code: '170', departament: '66')
    CityCase.create(name:'PEREIRA', code: '001', departament: '66')
    CityCase.create(name:'SANTA ROSA DE CABAL', code: '682', departament: '66')
    CityCase.create(name:'SANTUARIO', code: '687', departament: '66')
    CityCase.create(name:'BELEN DE UMBRIA', code: '088', departament: '66')
    CityCase.create(name:'GUATICA', code: '318', departament: '66')
    CityCase.create(name:'LA CELIA', code: '383', departament: '66')
    CityCase.create(name:'BALBOA', code: '075', departament: '66')
    CityCase.create(name:'PUEBLO RICO', code: '572', departament: '66')
    CityCase.create(name:'SAN ANDRES', code: '001', departament: '88')
    CityCase.create(name:'PROVIDENCIA', code: '564', departament: '88')
    CityCase.create(name:'BETULIA', code: '092', departament: '68')
    CityCase.create(name:'OCAMONTE', code: '498', departament: '68')
    CityCase.create(name:'PALMAR', code: '522', departament: '68')
    CityCase.create(name:'AGUADA', code: '013', departament: '68')
    CityCase.create(name:'GUAVATA', code: '324', departament: '68')
    CityCase.create(name:'BARBOSA', code: '077', departament: '68')
    CityCase.create(name:'SAN JOAQUIN', code: '682', departament: '68')
    CityCase.create(name:'SAN ANDRES', code: '669', departament: '68')
    CityCase.create(name:'SANTA HELENA DEL OPON', code: '720', departament: '68')
    CityCase.create(name:'CONCEPCION', code: '207', departament: '68')
    CityCase.create(name:'SANTA BARBARA', code: '705', departament: '68')
    CityCase.create(name:'CURITI', code: '229', departament: '68')
    CityCase.create(name:'ENCISO', code: '266', departament: '68')
    CityCase.create(name:'BARRANCABERMEJA', code: '081', departament: '68')
    CityCase.create(name:'CIMITARRA', code: '190', departament: '68')
    CityCase.create(name:'MOGOTES', code: '464', departament: '68')
    CityCase.create(name:'BOLIVAR', code: '101', departament: '68')
    CityCase.create(name:'PIEDECUESTA', code: '547', departament: '68')
    CityCase.create(name:'CHIMA', code: '176', departament: '68')
    CityCase.create(name:'JESUS MARIA', code: '368', departament: '68')
    CityCase.create(name:'GALAN', code: '296', departament: '68')
    CityCase.create(name:'LA PAZ', code: '397', departament: '68')
    CityCase.create(name:'OIBA', code: '500', departament: '68')
    CityCase.create(name:'RIONEGRO', code: '615', departament: '68')
    CityCase.create(name:'SUAITA', code: '770', departament: '68')
    CityCase.create(name:'HATO', code: '344', departament: '68')
    CityCase.create(name:'SAN BENITO', code: '673', departament: '68')
    CityCase.create(name:'FLORIDABLANCA', code: '276', departament: '68')
    CityCase.create(name:'LA BELLEZA', code: '377', departament: '68')
    CityCase.create(name:'MACARAVITA', code: '425', departament: '68')
    CityCase.create(name:'GUEPSA', code: '327', departament: '68')
    CityCase.create(name:'PUERTO WILCHES', code: '575', departament: '68')
    CityCase.create(name:'TONA', code: '820', departament: '68')
    CityCase.create(name:'GUACA', code: '318', departament: '68')
    CityCase.create(name:'ARATOCA', code: '051', departament: '68')
    CityCase.create(name:'CONFINES', code: '209', departament: '68')
    CityCase.create(name:'LANDAZURI', code: '385', departament: '68')
    CityCase.create(name:'CABRERA', code: '121', departament: '68')
    CityCase.create(name:'PUENTE NACIONAL', code: '572', departament: '68')
    CityCase.create(name:'SAN JOSE DE MIRANDA', code: '684', departament: '68')
    CityCase.create(name:'BUCARAMANGA', code: '001', departament: '68')
    CityCase.create(name:'PINCHOTE', code: '549', departament: '68')
    CityCase.create(name:'CHIPATA', code: '179', departament: '68')
    CityCase.create(name:'ZAPATOCA', code: '895', departament: '68')
    CityCase.create(name:'LOS SANTOS', code: '418', departament: '68')
    CityCase.create(name:'VETAS', code: '867', departament: '68')
    CityCase.create(name:'SUCRE', code: '773', departament: '68')
    CityCase.create(name:'COROMORO', code: '217', departament: '68')
    CityCase.create(name:'ALBANIA', code: '020', departament: '68')
    CityCase.create(name:'ONZAGA', code: '502', departament: '68')
    CityCase.create(name:'EL PLAYON', code: '255', departament: '68')
    CityCase.create(name:'ENCINO', code: '264', departament: '68')
    CityCase.create(name:'PALMAS DEL SOCORRO', code: '524', departament: '68')
    CityCase.create(name:'CAPITANEJO', code: '147', departament: '68')
    CityCase.create(name:'PUERTO PARRA', code: '573', departament: '68')
    CityCase.create(name:'CEPITA', code: '160', departament: '68')
    CityCase.create(name:'LEBRIJA', code: '406', departament: '68')
    CityCase.create(name:'VILLANUEVA', code: '872', departament: '68')
    CityCase.create(name:'SIMACOTA', code: '745', departament: '68')
    CityCase.create(name:'MATANZA', code: '444', departament: '68')
    CityCase.create(name:'SAN MIGUEL', code: '686', departament: '68')
    CityCase.create(name:'CONTRATACION', code: '211', departament: '68')
    CityCase.create(name:'PARAMO', code: '533', departament: '68')
    CityCase.create(name:'EL GUACAMAYO', code: '245', departament: '68')
    CityCase.create(name:'CHARTA', code: '169', departament: '68')
    CityCase.create(name:'SABANA DE TORRES', code: '655', departament: '68')
    CityCase.create(name:'SAN GIL', code: '679', departament: '68')
    CityCase.create(name:'CALIFORNIA', code: '132', departament: '68')
    CityCase.create(name:'CERRITO', code: '162', departament: '68')
    CityCase.create(name:'MOLAGAVITA', code: '468', departament: '68')
    CityCase.create(name:'GUAPOTA', code: '322', departament: '68')
    CityCase.create(name:'GAMBITA', code: '298', departament: '68')
    CityCase.create(name:'EL CARMEN DE CHUCURI', code: '235', departament: '68')
    CityCase.create(name:'CARCASI', code: '152', departament: '68')
    CityCase.create(name:'FLORIAN', code: '271', departament: '68')
    CityCase.create(name:'SAN VICENTE DE CHUCURI', code: '689', departament: '68')
    CityCase.create(name:'SURATA', code: '780', departament: '68')
    CityCase.create(name:'JORDAN', code: '370', departament: '68')
    CityCase.create(name:'GIRON', code: '307', departament: '68')
    CityCase.create(name:'EL PENON', code: '250', departament: '68')
    CityCase.create(name:'MALAGA', code: '432', departament: '68')
    CityCase.create(name:'GUADALUPE', code: '320', departament: '68')
    CityCase.create(name:'BARICHARA', code: '079', departament: '68')
    CityCase.create(name:'VELEZ', code: '861', departament: '68')
    CityCase.create(name:'CHARALA', code: '167', departament: '68')
    CityCase.create(name:'SOCORRO', code: '755', departament: '68')
    CityCase.create(name:'VALLE DE SAN JOSE', code: '855', departament: '68')
    CityCase.create(name:'BUENAVISTA', code: '110', departament: '70')
    CityCase.create(name:'GALERAS', code: '235', departament: '70')
    CityCase.create(name:'SINCELEJO', code: '001', departament: '70')
    CityCase.create(name:'LOS PALMITOS', code: '418', departament: '70')
    CityCase.create(name:'CHALAN', code: '230', departament: '70')
    CityCase.create(name:'CAIMITO', code: '124', departament: '70')
    CityCase.create(name:'OVEJAS', code: '508', departament: '70')
    CityCase.create(name:'TOLU VIEJO', code: '823', departament: '70')
    CityCase.create(name:'MORROA', code: '473', departament: '70')
    CityCase.create(name:'GUARANDA', code: '265', departament: '70')
    CityCase.create(name:'COVENAS', code: '221', departament: '70')
    CityCase.create(name:'PALMITO', code: '523', departament: '70')
    CityCase.create(name:'SAN JUAN DE BETULIA', code: '702', departament: '70')
    CityCase.create(name:'SANTIAGO DE TOLU', code: '820', departament: '70')
    CityCase.create(name:'LA UNION', code: '400', departament: '70')
    CityCase.create(name:'COLOSO', code: '204', departament: '70')
    CityCase.create(name:'EL ROBLE', code: '233', departament: '70')
    CityCase.create(name:'SAN PEDRO', code: '717', departament: '70')
    CityCase.create(name:'SAN MARCOS', code: '708', departament: '70')
    CityCase.create(name:'SAN LUIS DE SINCE', code: '742', departament: '70')
    CityCase.create(name:'MAJAGUAL', code: '429', departament: '70')
    CityCase.create(name:'SAMPUES', code: '670', departament: '70')
    CityCase.create(name:'COROZAL', code: '215', departament: '70')
    CityCase.create(name:'SAN BENITO ABAD', code: '678', departament: '70')
    CityCase.create(name:'SAN ONOFRE', code: '713', departament: '70')
    CityCase.create(name:'SUCRE', code: '771', departament: '70')
    CityCase.create(name:'ARMERO', code: '055', departament: '73')
    CityCase.create(name:'DOLORES', code: '236', departament: '73')
    CityCase.create(name:'LERIDA', code: '408', departament: '73')
    CityCase.create(name:'CHAPARRAL', code: '168', departament: '73')
    CityCase.create(name:'HONDA', code: '349', departament: '73')
    CityCase.create(name:'VILLARRICA', code: '873', departament: '73')
    CityCase.create(name:'CARMEN DE APICALA', code: '148', departament: '73')
    CityCase.create(name:'SAN SEBASTIAN DE MARIQUITA', code: '443', departament: '73')
    CityCase.create(name:'VALLE DE SAN JUAN', code: '854', departament: '73')
    CityCase.create(name:'FRESNO', code: '283', departament: '73')
    CityCase.create(name:'GUAMO', code: '319', departament: '73')
    CityCase.create(name:'SANTA ISABEL', code: '686', departament: '73')
    CityCase.create(name:'SALDANA', code: '671', departament: '73')
    CityCase.create(name:'NATAGAIMA', code: '483', departament: '73')
    CityCase.create(name:'CAJAMARCA', code: '124', departament: '73')
    CityCase.create(name:'ALVARADO', code: '026', departament: '73')
    CityCase.create(name:'SAN ANTONIO', code: '675', departament: '73')
    CityCase.create(name:'ROVIRA', code: '624', departament: '73')
    CityCase.create(name:'COELLO', code: '200', departament: '73')
    CityCase.create(name:'FALAN', code: '270', departament: '73')
    CityCase.create(name:'IBAGUE', code: '001', departament: '73')
    CityCase.create(name:'RIOBLANCO', code: '616', departament: '73')
    CityCase.create(name:'ANZOATEGUI', code: '043', departament: '73')
    CityCase.create(name:'COYAIMA', code: '217', departament: '73')
    CityCase.create(name:'SUAREZ', code: '770', departament: '73')
    CityCase.create(name:'MURILLO', code: '461', departament: '73')
    CityCase.create(name:'PIEDRAS', code: '547', departament: '73')
    CityCase.create(name:'SAN LUIS', code: '678', departament: '73')
    CityCase.create(name:'VENADILLO', code: '861', departament: '73')
    CityCase.create(name:'FLANDES', code: '275', departament: '73')
    CityCase.create(name:'ICONONZO', code: '352', departament: '73')
    CityCase.create(name:'CUNDAY', code: '226', departament: '73')
    CityCase.create(name:'ALPUJARRA', code: '024', departament: '73')
    CityCase.create(name:'RONCESVALLES', code: '622', departament: '73')
    CityCase.create(name:'ESPINAL', code: '268', departament: '73')
    CityCase.create(name:'PRADO', code: '563', departament: '73')
    CityCase.create(name:'AMBALEMA', code: '030', departament: '73')
    CityCase.create(name:'HERVEO', code: '347', departament: '73')
    CityCase.create(name:'LIBANO', code: '411', departament: '73')
    CityCase.create(name:'ATACO', code: '067', departament: '73')
    CityCase.create(name:'MELGAR', code: '449', departament: '73')
    CityCase.create(name:'ORTEGA', code: '504', departament: '73')
    CityCase.create(name:'PURIFICACION', code: '585', departament: '73')
    CityCase.create(name:'VILLAHERMOSA', code: '870', departament: '73')
    CityCase.create(name:'PALOCABILDO', code: '520', departament: '73')
    CityCase.create(name:'CASABIANCA', code: '152', departament: '73')
    CityCase.create(name:'PLANADAS', code: '555', departament: '73')
    CityCase.create(name:'ALCALA', code: '020', departament: '76')
    CityCase.create(name:'LA CUMBRE', code: '377', departament: '76')
    CityCase.create(name:'EL CAIRO', code: '246', departament: '76')
    CityCase.create(name:'RIOFRIO', code: '616', departament: '76')
    CityCase.create(name:'ROLDANILLO', code: '622', departament: '76')
    CityCase.create(name:'EL AGUILA', code: '243', departament: '76')
    CityCase.create(name:'BUGALAGRANDE', code: '113', departament: '76')
    CityCase.create(name:'OBANDO', code: '497', departament: '76')
    CityCase.create(name:'ANDALUCIA', code: '036', departament: '76')
    CityCase.create(name:'BUENAVENTURA', code: '109', departament: '76')
    CityCase.create(name:'GUADALAJARA DE BUGA', code: '111', departament: '76')
    CityCase.create(name:'BOLIVAR', code: '100', departament: '76')
    CityCase.create(name:'ARGELIA', code: '054', departament: '76')
    CityCase.create(name:'CALI', code: '001', departament: '76')
    CityCase.create(name:'TULUA', code: '834', departament: '76')
    CityCase.create(name:'SAN PEDRO', code: '670', departament: '76')
    CityCase.create(name:'ZARZAL', code: '895', departament: '76')
    CityCase.create(name:'VIJES', code: '869', departament: '76')
    CityCase.create(name:'DAGUA', code: '233', departament: '76')
    CityCase.create(name:'CANDELARIA', code: '130', departament: '76')
    CityCase.create(name:'RESTREPO', code: '606', departament: '76')
    CityCase.create(name:'YUMBO', code: '892', departament: '76')
    CityCase.create(name:'TRUJILLO', code: '828', departament: '76')
    CityCase.create(name:'CARTAGO', code: '147', departament: '76')
    CityCase.create(name:'LA VICTORIA', code: '403', departament: '76')
    CityCase.create(name:'YOTOCO', code: '890', departament: '76')
    CityCase.create(name:'EL DOVIO', code: '250', departament: '76')
    CityCase.create(name:'TORO', code: '823', departament: '76')
    CityCase.create(name:'SEVILLA', code: '736', departament: '76')
    CityCase.create(name:'PALMIRA', code: '520', departament: '76')
    CityCase.create(name:'VERSALLES', code: '863', departament: '76')
    CityCase.create(name:'CALIMA', code: '126', departament: '76')
    CityCase.create(name:'FLORIDA', code: '275', departament: '76')
    CityCase.create(name:'CAICEDONIA', code: '122', departament: '76')
    CityCase.create(name:'PRADERA', code: '563', departament: '76')
    CityCase.create(name:'GINEBRA', code: '306', departament: '76')
    CityCase.create(name:'ANSERMANUEVO', code: '041', departament: '76')
    CityCase.create(name:'ULLOA', code: '845', departament: '76')
    CityCase.create(name:'JAMUNDI', code: '364', departament: '76')
    CityCase.create(name:'LA UNION', code: '400', departament: '76')
    CityCase.create(name:'GUACARI', code: '318', departament: '76')
    CityCase.create(name:'EL CERRITO', code: '248', departament: '76')
    CityCase.create(name:'PAPUNAUA', code: '777', departament: '97')
    CityCase.create(name:'CARURU', code: '161', departament: '97')
    CityCase.create(name:'MITU', code: '001', departament: '97')
    CityCase.create(name:'YAVARATE', code: '889', departament: '97')
    CityCase.create(name:'TARAIRA', code: '666', departament: '97')
    CityCase.create(name:'PACOA', code: '511', departament: '97')
    CityCase.create(name:'CUMARIBO', code: '773', departament: '99')
    CityCase.create(name:'PUERTO CARRENO', code: '001', departament: '99')
    CityCase.create(name:'LA PRIMAVERA', code: '524', departament: '99')
    CityCase.create(name:'SANTA ROSALIA', code: '624', departament: '99')

  end
end
