class Aleja49 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(20484).update(id: 20484,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(20485).update(id: 20485,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(5652).update(id: 5652,current_stage: 'SENTENCIA SEGUNDA INSTANCIA')
    puts TypeProcess.find(20063).update(id: 20063,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(20740).update(id: 20740,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(5486).update(id: 5486,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(5587).update(id: 5587,current_stage: 'SENTENCIA SEGUNDA INSTANCIA')
    puts TypeProcess.find(20127).update(id: 20127,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(20068).update(id: 20068,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(5546).update(id: 5546,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(5903).update(id: 5903,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(21020).update(id: 21020,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(20193).update(id: 20193,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(20194).update(id: 20194,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(20335).update(id: 20335,current_stage: 'DEMANDA')
    puts TypeProcess.find(20339).update(id: 20339,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(5862).update(id: 5862,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(5533).update(id: 5533,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(18023).update(id: 18023,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(21142).update(id: 21142,current_stage: 'DEMANDA')
    puts TypeProcess.find(5329).update(id: 5329,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(18404).update(id: 18404,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(5445).update(id: 5445,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(11339).update(id: 11339,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(2991).update(id: 2991,current_stage: 'APELACION')
    puts TypeProcess.find(2908).update(id: 2908,current_stage: 'APELACION')
    puts TypeProcess.find(3717).update(id: 3717,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(2937).update(id: 2937,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)')
    puts TypeProcess.find(3118).update(id: 3118,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(2921).update(id: 2921,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(3220).update(id: 3220,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9230).update(id: 9230,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(3072).update(id: 3072,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(3312).update(id: 3312,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(2700).update(id: 2700,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(3272).update(id: 3272,current_stage: 'APELACION')
    puts TypeProcess.find(2981).update(id: 2981,current_stage: 'APELACION')
    puts TypeProcess.find(2949).update(id: 2949,current_stage: 'APELACION')
    puts TypeProcess.find(2945).update(id: 2945,current_stage: 'PRUEBAS')
    puts TypeProcess.find(3245).update(id: 3245,current_stage: 'APELACION')
    puts TypeProcess.find(2721).update(id: 2721,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(3475).update(id: 3475,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(3307).update(id: 3307,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(3074).update(id: 3074,current_stage: 'APELACION')
    puts TypeProcess.find(3544).update(id: 3544,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(3490).update(id: 3490,current_stage: 'PRUEBAS')
    puts TypeProcess.find(2883).update(id: 2883,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(2976).update(id: 2976,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(3489).update(id: 3489,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(20846).update(id: 20846,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
  end
end
