class CreatingTutelage2 < ActiveRecord::Migration[5.1]
  def change
TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '18/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46816',creation_date: '18/07/2018',link_type: 'ACCIONADO',active_part: 'JUAN CAMILO BELALCAZAR',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 003 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00036',answer_date: '19/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '19/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46839',creation_date: '19/07/2018',link_type: 'ACCIONADO',active_part: 'FREDY SALAZAR VEGA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PENAL DEL CIRCUITO ESPECIALIZADO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00162',answer_date: '23/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '19/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46840',creation_date: '19/07/2018',link_type: 'ACCIONADO',active_part: 'GLORIA HELENA CALLE BERMUDEZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 DE FAMILIA DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00241',answer_date: '23/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '19/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46841',creation_date: '19/07/2018',link_type: 'ACCIONADO',active_part: 'JAIR BELTRAN ENCISO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00216',answer_date: '23/07/2018',desition_date: '26/07/2018',instance: 'UNICA',case_termination: 'DESFAVORABLE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '24/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46910-2018-CR-0172952-0000-01',creation_date: '24/07/2018',link_type: 'ACCIONADO',active_part: 'ADDY TATIANA VICTORIA GONZALEZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 004 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE NEIVA',departament: '41',city_case: '001',process_radicate: '2018-00083',answer_date: '25/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '25/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46911',creation_date: '25/07/2018',link_type: 'ACCIONADO',active_part: 'ANDRES FELIPE HERNANDEZ MOLINA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 004 PENAL DEL CIRCUITO ESPECIALIZADO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00169',answer_date: '25/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '26/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46942',creation_date: '26/07/2018',link_type: 'ACCIONADO',active_part: 'MARLENE MORA DE GARCIA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 004 DE FAMILIA DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00250',answer_date: '27/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '27/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47031-2018-CR-0178669-0000-01',creation_date: '27/07/2018',link_type: 'ACCIONADO',active_part: 'YINA ALEXANDRA PEREZ CARDENAS',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE NEIVA',departament: '41',city_case: '001',process_radicate: '2018-00077',answer_date: '30/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '27/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47032',creation_date: '27/07/2018',link_type: 'ACCIONADO',active_part: 'TRINIDAD ROJAS CARDENAS',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 003 PENAL DEL CIRCUITO ESPECIALIZADO CON FUNCIONES DE CONOCIMIENTO DE NEIVA',departament: '41',city_case: '001',process_radicate: '2018-00123',answer_date: '30/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '27/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47033-2018-CR-0178423-0000-01',creation_date: '27/07/2018',link_type: 'ACCIONADO',active_part: 'EDWARD FERNANDO LOAIZA MUÑOZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 005 PENAL MUNICIPAL CON FUNCIONES DE CONTROL DE GARANTIAS DE ARMENIA',departament: '63',city_case: '001',process_radicate: '2018-00130',answer_date: '30/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '18/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46817',creation_date: '18/07/2018',link_type: 'VINCULADO',active_part: 'JEIKAR ROCHA MYLES',passive_part: 'DEPARTAMENTO ARCHIPIELAGO DE SAN ANDRES Y OTROS',office_name: 'JUZGADO 001 CIVIL MUNICIPAL DE SAN ANDRES',departament: '88',city_case: '001',process_radicate: '2018-00137',answer_date: '19/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'CONTRA SENTENCIA JUDICIAL',notification_date: '19/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46837',creation_date: '19/07/2018',link_type: 'VINCULADO',active_part: 'ELIECER YEPES SANCHEZ Y OTROS',passive_part: 'TRIBUNAL ADMINISTRATIVO DEL VALLE DEL CAUCA',office_name: 'CONSEJO DE ESTADO SALA DE LO CONTENCIOSO ADMINISTRATIVO SECCION QUINTA',departament: '11',city_case: '001',process_radicate: '2018-02032',answer_date: '23/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '23/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46907-2018-CR-0172161-0000-01',creation_date: '23/07/2018',link_type: 'ACCIONADO',active_part: 'CARLOS ARTURO MARULANDA SANCHEZ',passive_part: 'ARL POSITIVA Y LA PREVISORA',office_name: 'JUZGADO 001 PROMISCUO DE FAMILIA DE TULUA',departament: '76',city_case: '834',process_radicate: '2018-00317',answer_date: '25/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '24/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46908',creation_date: '24/07/2018',link_type: 'VINCULADO',active_part: 'KENIA MARCELA ESCOBAR LUCUMI',passive_part: 'CLINICA VALLE SALUD',office_name: 'JUZGADO 001 PENAL MUNICIPAL DE PUERTO TEJADA',departament: '19',city_case: '573',process_radicate: '2018-00070',answer_date: '25/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '24/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46909',creation_date: '24/07/2018',link_type: 'VINCULADO',active_part: 'ROSMIRA RODRIGUEZ GOMEZ',passive_part: 'HOSPITAL SAN ANTONIO DE MITU Y OTROS',office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE MITU',departament: '97',city_case: '001',process_radicate: '2018-00084',answer_date: '25/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '25/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46912',creation_date: '25/07/2018',link_type: 'VINCULADO',active_part: 'HECTOR FABIO DOMINGUEZ',passive_part: 'EMSSANAR EPS',office_name: 'JUZGADO 006 CIVIL MUNICIPAL DE PALMIRA',departament: '76',city_case: '520',process_radicate: '2018-00252',answer_date: '26/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'ACTUACION TEMERARIA',notification_date: '25/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46915',creation_date: '25/07/2018',link_type: 'ACCIONADO',active_part: 'JEYSON ARLEY ROZO OLMOS',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE ACACIAS',departament: '50',city_case: '006',process_radicate: '2018-00410',answer_date: '26/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION',notification_date: '26/07/2018',has_correspondency_radicate: true,correspondency_radicate: '46944-2018-CR-0175990-0000-01',creation_date: '26/07/2018',link_type: 'ACCIONADO',active_part: 'ENEIDER JOSE MENDOZA DIAZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO PROMISCUO MUNICIPAL DE FONSECA',departament: '44',city_case: '279',process_radicate: '2018-00277',answer_date: '30/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'INCAPACIDAD TEMPORAL',notification_date: '26/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47030',creation_date: '26/07/2018',link_type: 'VINCULADO',active_part: 'GERARDO WVEIMAR LOPEZ RAMIREZ',passive_part: 'SERVICIO OCCIDENTAL DE SALUD SOS EPS',office_name: 'JUZGADO 016 CIVIL MUNICIPAL DE ORALIDAD DE CALI',departament: '76',city_case: '001',process_radicate: '2018-00547',answer_date: '30/07/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION',notification_date: '30/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47034',creation_date: '30/07/2018',link_type: 'ACCIONADO',active_part: 'NELSON DE JESUS MONTOYA RAMIREZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO PROMISCUO MUNICIPAL DE ARGELIA',departament: '76',city_case: '054',process_radicate: '2018-00096',answer_date: '01/08/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION',notification_date: '30/07/2018',has_correspondency_radicate: true,correspondency_radicate: '47043-2018-CR-0179133-0000-01',creation_date: '30/07/2018',link_type: 'ACCIONADO',active_part: 'ALVARO DE JESUS SOTO ZAPATA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE ANSERMA',departament: '17',city_case: '042',process_radicate: '2018-00101',answer_date: '01/08/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGURO',notification_date: '31/07/2018',has_correspondency_radicate: false,correspondency_radicate: 'PENDIENTE',creation_date: '31/07/2018',link_type: 'ACCIONADO',active_part: 'CLAUDIA MARCELA TREJOS ROJAS',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 PENAL DEL CIRCUITO PARA ADOLESCENTES CON FUNCION DE CONOCIMIENTO',departament: '66',city_case: '001',process_radicate: '2018-00143',answer_date: '02/08/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '31/07/2018',has_correspondency_radicate: true,correspondency_radicate: '2018-CR-0181029-000-01',creation_date: '31/07/2018',link_type: 'ACCIONADO',active_part: 'LINA MARCELA HINCAPIE MUNOZ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PENAL MUNICIPAL CON FUNCION DE CONTROL DE GARANTIAS',departament: '63',city_case: '001',process_radicate: '2018-00134',answer_date: '02/08/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(p_type: 5,process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION',notification_date: '8/1/2018',has_correspondency_radicate: false,correspondency_radicate: 'PENDIENTE',creation_date: '01/08/2018',link_type: 'ACCIONADO',active_part: 'MARTHA LUCERO BAHAMON MARIN',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 005  PENAL MUNICIPAL',departament: '18',city_case: '001',process_radicate: '2018-00126',answer_date: '02/08/2018',desition_date: 'PENDIENTE',instance: 'PENDIENTE',case_termination: 'PENDIENTE',has_impug: false,imp_date: 'PENDIENTE',tutelage_imp: 'PENDIENTE',objection_date_desition: 'PENDIENTE',date_notification_desition_desacate: 'PENDIENTE',setence_type_second_company: 'PENDIENTE',has_desacate: false,date_notification_desacate: 'PENDIENTE',date_answer_desacate: 'PENDIENTE',objection_date_desition_notification: 'PENDIENTE',sentence_type_desacate: 'PENDIENTE',user_id: 21,state: 'REGISTRO NUEVO')
  end
end
