class Aleja79 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(6154).update(id: 6154,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6506).update(id: 6506,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6539).update(id: 6539,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6547).update(id: 6547,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6602).update(id: 6602,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6604).update(id: 6604,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6671).update(id: 6671,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7722).update(id: 7722,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8591).update(id: 8591,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8649).update(id: 8649,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8829).update(id: 8829,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8896).update(id: 8896,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9001).update(id: 9001,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9196).update(id: 9196,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9292).update(id: 9292,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9724).update(id: 9724,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9775).update(id: 9775,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9942).update(id: 9942,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9987).update(id: 9987,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20034).update(id: 20034,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10090).update(id: 10090,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10193).update(id: 10193,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10194).update(id: 10194,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10195).update(id: 10195,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10196).update(id: 10196,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10198).update(id: 10198,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10199).update(id: 10199,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10218).update(id: 10218,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10275).update(id: 10275,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10283).update(id: 10283,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10287).update(id: 10287,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10290).update(id: 10290,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10293).update(id: 10293,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10294).update(id: 10294,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10297).update(id: 10297,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10310).update(id: 10310,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10315).update(id: 10315,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10317).update(id: 10317,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10322).update(id: 10322,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10325).update(id: 10325,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10333).update(id: 10333,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10415).update(id: 10415,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10796).update(id: 10796,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10988).update(id: 10988,observations: 'Registro Duplicado',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
