class Aleja09 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,passive_part: 'NACION - RAMA JUDICIAL')
    puts TypeProcess.find(18914).update(id: 18914,passive_part: 'MAURICIO DURAN DURAN')
    puts TypeProcess.find(18898).update(id: 18898,passive_part: 'HELBER YESID PINZON SAAVEDRA')
    puts TypeProcess.find(18714).update(id: 18714,passive_part: 'JORGE LUIS LASSO MONTES')
    puts TypeProcess.find(18666).update(id: 18666,passive_part: 'AMIN LOSADA')
    puts TypeProcess.find(18662).update(id: 18662,passive_part: 'ANDRES ESPITIA DUQUE')
    puts TypeProcess.find(18556).update(id: 18556,passive_part: 'SEVERIANA LUGO VARGAS')
    puts TypeProcess.find(18555).update(id: 18555,passive_part: 'JORGE LUIS LASSO')
    puts TypeProcess.find(18553).update(id: 18553,passive_part: 'LUIS ERNESTO ORTIZ CORTES')
    puts TypeProcess.find(18552).update(id: 18552,passive_part: 'ADALBERTO ORTEGA ROJAS')
    puts TypeProcess.find(18551).update(id: 18551,passive_part: 'ROLANDO QUINTERI COLLAZOS')
    puts TypeProcess.find(18238).update(id: 18238,passive_part: 'LUIS FELIPE CONDE LASSO')
    puts TypeProcess.find(18237).update(id: 18237,passive_part: 'ELIZEIN CANO YARA')
    puts TypeProcess.find(18236).update(id: 18236,passive_part: 'JHON ALEXANDER RAMOS ARAUJO')
    puts TypeProcess.find(18235).update(id: 18235,passive_part: 'JORGE LUIS LASSO')
    puts TypeProcess.find(18078).update(id: 18078,passive_part: 'GLORIA ELENA OSPINA')
    puts TypeProcess.find(17866).update(id: 17866,passive_part: 'CHARLES BARRERA ZUNIGA')
    puts TypeProcess.find(17642).update(id: 17642,passive_part: 'CARLOS ANTONIO TOLE CALDERON')
    puts TypeProcess.find(17641).update(id: 17641,passive_part: 'ORLANDO ANDRES RODRIGUEZ ALFARO')
    puts TypeProcess.find(14900).update(id: 14900,passive_part: 'GOLDY DIAZ MINA')
    puts TypeProcess.find(9889).update(id: 9889,passive_part: 'ALCALDIA MAYOR DE BOGOTA')
    puts TypeProcess.find(9722).update(id: 9722,passive_part: 'CONGREGDE HNAS FCANAS MISIONDE MAAUXCLINICA LA ASUNCION')
    puts TypeProcess.find(9515).update(id: 9515,passive_part: 'INSTITUTO UROLOGICO DEL NORTE')
    puts TypeProcess.find(9395).update(id: 9395,passive_part: 'PETROLEUM EXPLORATION INTERNACIONAL SA')
    puts TypeProcess.find(8805).update(id: 8805,passive_part: 'HOSPITAL ROSARIO PUMAREJO DE LOPEZ')
    puts TypeProcess.find(8116).update(id: 8116,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(7996).update(id: 7996,passive_part: 'JORGE ELIECER ROMERO OTALVARO')
    puts TypeProcess.find(7970).update(id: 7970,passive_part: 'ESE CENTRO DE SALUD PALMAR DE VARELA')
    puts TypeProcess.find(7876).update(id: 7876,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(7789).update(id: 7789,passive_part: 'SERTEMCOL LTDA')
    puts TypeProcess.find(7311).update(id: 7311,passive_part: 'CLINICA OFTALMOLOGICA DE SINCELEJO')
    puts TypeProcess.find(7222).update(id: 7222,passive_part: 'HOSPITAL DE SUBA NIVEL II')
    puts TypeProcess.find(7199).update(id: 7199,passive_part: 'ESE HOSPITAL LOCAL DE SANTOS TOMAS')
    puts TypeProcess.find(7162).update(id: 7162,passive_part: 'HOSPITAL UNIVERSITARIO CARI ESE')
    puts TypeProcess.find(7058).update(id: 7058,passive_part: 'VALERIA ATENEA COSTA BARNEY')
    puts TypeProcess.find(6751).update(id: 6751,passive_part: 'GRUAS MANIOBRAS Y MONTAJES SAS')
    puts TypeProcess.find(6514).update(id: 6514,passive_part: 'DISTRITO DE BARRANQUILLA')
    puts TypeProcess.find(286).update(id: 286,passive_part: 'IPS UNIVERSITARIA SEDE BARRANQUILLA')
    puts TypeProcess.find(19750).update(id: 19750,passive_part: 'HELBER YESID PINZON SAAVEDRA')
    puts TypeProcess.find(19735).update(id: 19735,passive_part: 'DARWIN FERNAN LEIVA GAITAN')
    puts TypeProcess.find(19287).update(id: 19287,passive_part: 'PEDRO MUNOZ CLAROS')
    puts TypeProcess.find(17480).update(id: 17480,passive_part: 'MARNIE CONDE QUINTERO')
    puts TypeProcess.find(17441).update(id: 17441,passive_part: 'LIBARDO MUNOZ GOMEZ')
    puts TypeProcess.find(17218).update(id: 17218,passive_part: 'LUIS FELIPE CONDE LASSO')
    puts TypeProcess.find(17146).update(id: 17146,passive_part: 'HUGO FERNANDO CASANOVA NIPI')
    puts TypeProcess.find(17000).update(id: 17000,passive_part: 'ORLANDO ANDRES RODRIGUEZ')
    puts TypeProcess.find(16946).update(id: 16946,passive_part: 'TANIA BEATRIZ PENAFIEL')
    puts TypeProcess.find(16906).update(id: 16906,passive_part: 'ABEL CLAVIJO HERNANDEZ')
    puts TypeProcess.find(16832).update(id: 16832,passive_part: 'TERESA CERON RODRIGUEZ')
    puts TypeProcess.find(16759).update(id: 16759,passive_part: 'RUBEN DARIO MONTES PEREZ')
    puts TypeProcess.find(16710).update(id: 16710,passive_part: 'HERNANDO QUESADA TRUJILLO')
    puts TypeProcess.find(16700).update(id: 16700,passive_part: 'LUIS FELIPE CONDE LASSO')
    puts TypeProcess.find(16514).update(id: 16514,passive_part: 'MARTHA LILIANA QUIMBAYA BAHAMON')
    puts TypeProcess.find(16510).update(id: 16510,passive_part: 'GLORIA ELENA OSPINA')
    puts TypeProcess.find(16410).update(id: 16410,passive_part: 'FERNANDO ARTUNDUAGA')
    puts TypeProcess.find(16359).update(id: 16359,passive_part: 'ADRIANA MARIA GARCIA OROZCO')
    puts TypeProcess.find(16262).update(id: 16262,passive_part: 'FERNELY RAMOS GUTIERREZ')
    puts TypeProcess.find(16254).update(id: 16254,passive_part: 'DARWIN FERNAN LEIVA GAITAN')
    puts TypeProcess.find(15354).update(id: 15354,passive_part: 'TEOFANES VARGAS NASAYO')
    puts TypeProcess.find(15339).update(id: 15339,passive_part: 'RODRIGO GONZALEZ TORO')
    puts TypeProcess.find(15011).update(id: 15011,passive_part: 'CHARLES BARRERA ZUNIGA')
    puts TypeProcess.find(14987).update(id: 14987,passive_part: 'JUAN CARLOS GOSSAIN  ANAMARIA ALVAREZ  BERTA PEREZ  NACHA NEWBALL  OTROS ')
    puts TypeProcess.find(14986).update(id: 14986,passive_part: 'TOMAS RODRIGUEZ MANOTAS  Y LIGIA MARIA CURE RIOS')
    puts TypeProcess.find(14985).update(id: 14985,passive_part: 'TOMAS RODRIGUEZ  NOHORA SERRANO LEONES')
    puts TypeProcess.find(14983).update(id: 14983,passive_part: 'JULIO SALAS BALDOVINO')
    puts TypeProcess.find(14982).update(id: 14982,passive_part: 'RITA ROSA ROMERO SALAS')
    puts TypeProcess.find(14981).update(id: 14981,passive_part: 'JULIO SALAS BALDOVINO')
    puts TypeProcess.find(14980).update(id: 14980,passive_part: 'JULIO SALAS BALDOVINO')
    puts TypeProcess.find(14977).update(id: 14977,passive_part: 'MARIA CRISTINA RODRIGUEZ OTALORA   TOMAS RODRIGUEZ MANOTAS  NORA SERRANO LEONES')
    puts TypeProcess.find(14976).update(id: 14976,passive_part: 'NERLIDES HERNANDEZ FRANCO Y ADIS CABRERA JIMENEZ')
    puts TypeProcess.find(14973).update(id: 14973,passive_part: 'MARTA CRISTINA RODRIGUEZ OTALORA  TOMAS RODRIGUEZ  NOHORA SERRANO LEONES')
    puts TypeProcess.find(14972).update(id: 14972,passive_part: 'TOMAS RODRIGUEZ Y OTROS')
    puts TypeProcess.find(14936).update(id: 14936,passive_part: 'NAUSICRATE PEREZ DAUTT   LUZ CAMACHO ARIZA')
    puts TypeProcess.find(14821).update(id: 14821,passive_part: 'TANIA BEATRIZ PENAFIEL')
    puts TypeProcess.find(14791).update(id: 14791,passive_part: 'CARLOS RAMON ZAYAS Y LUIS MIGUEL ALVARADO ')
    puts TypeProcess.find(14790).update(id: 14790,passive_part: 'CARLOS AMON ZAYAS ROJAS Y LUIS MIGUEL ALVARADO ')
    puts TypeProcess.find(14788).update(id: 14788,passive_part: 'CARLOS RAMON ZAYAS Y LUIS MIGUEL ALVARADO')
    puts TypeProcess.find(14663).update(id: 14663,passive_part: 'JOHNNY MELENDEZ BANQUEZ')
    puts TypeProcess.find(13938).update(id: 13938,passive_part: 'IVAN ESTRADA HERNANDEZ WILSON JAIMES  ANAMARIA BUSTILLO Y OROS')
    puts TypeProcess.find(13912).update(id: 13912,passive_part: 'OSCAR MARIN VILLALBA')
    puts TypeProcess.find(13907).update(id: 13907,passive_part: 'MUNICIPIO DE MELGAR ')
    puts TypeProcess.find(13906).update(id: 13906,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA ')
    puts TypeProcess.find(13807).update(id: 13807,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13806).update(id: 13806,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13799).update(id: 13799,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13798).update(id: 13798,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13797).update(id: 13797,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13796).update(id: 13796,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA')
    puts TypeProcess.find(13795).update(id: 13795,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13794).update(id: 13794,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13793).update(id: 13793,passive_part: 'MUNICIPIO DE VALLE DE SAN JUAN ')
    puts TypeProcess.find(13777).update(id: 13777,passive_part: 'FANCISCO VEGA ARRAUT  ROCIO SIERRA E IDALID CORREA')
    puts TypeProcess.find(13716).update(id: 13716,passive_part: 'MUNICIPIO DE VILLAHERMOSA ')
    puts TypeProcess.find(13702).update(id: 13702,passive_part: 'INCODER ')
    puts TypeProcess.find(13701).update(id: 13701,passive_part: 'WILSON JAMES  LUIS ORTIZ  MARLY JEREZ ARIAS')
    puts TypeProcess.find(13696).update(id: 13696,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13636).update(id: 13636,passive_part: 'ANAMARIA ALVAREZ   BERTA PEREZ  NACHA NEWBALL CANDELARIA VALDELAMAR FUNDACION RENAL DE COLOMBIA')
    puts TypeProcess.find(13629).update(id: 13629,passive_part: 'LUIS BENEDETTI  GUSTAVO MAYO DORIA VEJARANO')
    puts TypeProcess.find(13617).update(id: 13617,passive_part: 'INSTITUCION EDUCATIVA NINO JESUS DE PRAGA ')
    puts TypeProcess.find(13616).update(id: 13616,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13605).update(id: 13605,passive_part: 'MYRON MARTINEZ')
    puts TypeProcess.find(13587).update(id: 13587,passive_part: 'MYRON MARTINEZ RAMOS')
    puts TypeProcess.find(13569).update(id: 13569,passive_part: 'EDAT ESP SA ')
    puts TypeProcess.find(13556).update(id: 13556,passive_part: 'MUNICIPIO DE ORTEGA ')
    puts TypeProcess.find(13530).update(id: 13530,passive_part: 'EDAT ESP SA ')
    puts TypeProcess.find(13524).update(id: 13524,passive_part: 'INSTITUCION EDUCATIVA TECNICA EMPRESARIAL ABERTO CASTILLA ')
    puts TypeProcess.find(13523).update(id: 13523,passive_part: 'MUNICIPIO DE SANTA ISABEL ')
    puts TypeProcess.find(13504).update(id: 13504,passive_part: 'MUNICIPIO DE NATAGAIMA ')
    puts TypeProcess.find(13503).update(id: 13503,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13500).update(id: 13500,passive_part: 'EJERCITO NACIONAL ')
    puts TypeProcess.find(13490).update(id: 13490,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13423).update(id: 13423,passive_part: 'MUNICIPIO DE HERVEO ')
    puts TypeProcess.find(13422).update(id: 13422,passive_part: 'IMDRI')
    puts TypeProcess.find(13412).update(id: 13412,passive_part: 'MUNICIPIO DE ANZOATEGUI ')
    puts TypeProcess.find(13389).update(id: 13389,passive_part: 'JOSE LUIS BAHAMON')
    puts TypeProcess.find(13387).update(id: 13387,passive_part: 'EDAT ESP SA ')
    puts TypeProcess.find(13386).update(id: 13386,passive_part: 'MUNICIPIO DE PURIFICACION')
    puts TypeProcess.find(13385).update(id: 13385,passive_part: 'COLDEPORTES ')
    puts TypeProcess.find(13381).update(id: 13381,passive_part: 'LUIS ENRIQUE PERDOMO CUBIDES')
    puts TypeProcess.find(13378).update(id: 13378,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13375).update(id: 13375,passive_part: 'COLDEPORTES ')
    puts TypeProcess.find(13374).update(id: 13374,passive_part: 'COLDEPORTES ')
    puts TypeProcess.find(13370).update(id: 13370,passive_part: 'DIANA PATRICIA PEREZ')
    puts TypeProcess.find(13337).update(id: 13337,passive_part: 'JESUS ANTONIO CASTRO VARGAS')
    puts TypeProcess.find(13333).update(id: 13333,passive_part: 'INSTITUCION EDUCATIVA TECNICA AGROPECUARIA MARIANO MELENDRO')
    puts TypeProcess.find(13304).update(id: 13304,passive_part: 'IMDRI')
    puts TypeProcess.find(13296).update(id: 13296,passive_part: 'DIANA PATRICIA PEREZ')
    puts TypeProcess.find(13289).update(id: 13289,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13280).update(id: 13280,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(13256).update(id: 13256,passive_part: 'ALBINO CANGRAJO JAVELA')
    puts TypeProcess.find(13225).update(id: 13225,passive_part: 'MUNICIPIO DE SAN ANTONO TOLIMA ')
    puts TypeProcess.find(13222).update(id: 13222,passive_part: 'MIGUEL ANGEL HODWALKER VARGAS')
    puts TypeProcess.find(13202).update(id: 13202,passive_part: 'CIELO GONZALEZ VILLA')
    puts TypeProcess.find(13191).update(id: 13191,passive_part: 'EMPRESA DE ACUEDUCTO  ALCANTARILLADO Y ASEO DEL TOLIMA EDAT EPS S A')
    puts TypeProcess.find(13168).update(id: 13168,passive_part: 'MUNICIPIO DE ORTEGA ')
    puts TypeProcess.find(13134).update(id: 13134,passive_part: 'ADMINISTRACION MUNICPAL DE SAN LUIS TOLIMA ')
    puts TypeProcess.find(13133).update(id: 13133,passive_part: 'CIRO JOSE VEGA ALVAREZ')
    puts TypeProcess.find(13129).update(id: 13129,passive_part: 'MUNICIPIO DE MELGAR')
    puts TypeProcess.find(13120).update(id: 13120,passive_part: 'ARCESIO PEREZ BELLO Y OTROS ')
    puts TypeProcess.find(13108).update(id: 13108,passive_part: 'GOBERNACION DEL TOLIMA ')
    puts TypeProcess.find(13107).update(id: 13107,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(13106).update(id: 13106,passive_part: 'JESUS ELIAS MENESES PERDOMO ')
    puts TypeProcess.find(13101).update(id: 13101,passive_part: 'CHARLES BARRERA ZUNIGA')
    puts TypeProcess.find(13097).update(id: 13097,passive_part: 'EYDER YEAN SUAREZ TOVAR')
    puts TypeProcess.find(13096).update(id: 13096,passive_part: 'BANCO INMOBILIARIO GESTORA URBANA ')
    puts TypeProcess.find(13064).update(id: 13064,passive_part: 'MUNICIPIO DE ATACO ')
    puts TypeProcess.find(13052).update(id: 13052,passive_part: 'BELISARIO MONTEALEGRE CARDENAS')
    puts TypeProcess.find(12988).update(id: 12988,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(12932).update(id: 12932,passive_part: 'JULIO ALBERTO GOMEZ MARTINEZ')
    puts TypeProcess.find(12834).update(id: 12834,passive_part: 'MUNICIPIO DE SAN AGUSTIN')
    puts TypeProcess.find(12671).update(id: 12671,passive_part: 'MUNICIPIO DE AIPE')
    puts TypeProcess.find(12429).update(id: 12429,passive_part: 'INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECREACION DE IBAGU')
    puts TypeProcess.find(12424).update(id: 12424,passive_part: 'NUEVO HOSPITAL LA CANDELARIA DE PURIFICACION TOLIMA')
    puts TypeProcess.find(12421).update(id: 12421,passive_part: 'CORPORACION AUTONOMA REGIONAL DEL TOLIMA CORTOLIMA')
    puts TypeProcess.find(12417).update(id: 12417,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(12401).update(id: 12401,passive_part: 'INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECREACION DE IBAGU')
    puts TypeProcess.find(12399).update(id: 12399,passive_part: 'MUNICIPIO DE VALLE DE SAN JUAN')
    puts TypeProcess.find(12396).update(id: 12396,passive_part: 'INSTITUTO DE FINANCIAMIENTO PROMOCION Y DESARROLLO DE IBAGUE')
    puts TypeProcess.find(12392).update(id: 12392,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(12391).update(id: 12391,passive_part: 'INSTITUTO DE FINANCIAMIENTO PROMOCION Y DESARROLLO DE IBAGUE')
    puts TypeProcess.find(12388).update(id: 12388,passive_part: 'CORPORACION AUTONOMA REGIONAL DEL TOLIMA CORTOLIMA')
    puts TypeProcess.find(12384).update(id: 12384,passive_part: 'MUNICIPIO DEL LIBANO')
    puts TypeProcess.find(12375).update(id: 12375,passive_part: 'HOSPITAL REINA SOFIA DE ESPANA DE LERIDA TOLIMA')
    puts TypeProcess.find(12373).update(id: 12373,passive_part: 'INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECREACION DE IBAGU')
    puts TypeProcess.find(12363).update(id: 12363,passive_part: 'GOBIERNO DEPARTAMENTAL DEL TOLIMA')
    puts TypeProcess.find(12362).update(id: 12362,passive_part: 'HOSPITAL SAN RAFAEL ESPINAL')
    puts TypeProcess.find(12359).update(id: 12359,passive_part: 'HOSPITAL REGIONAL DEL LIBANO TOLIMA')
    puts TypeProcess.find(12358).update(id: 12358,passive_part: 'MUNICIPIO DE ARMERO GUAYABAL')
    puts TypeProcess.find(12357).update(id: 12357,passive_part: 'GOBIERNO DEPARTAMENTAL DEL TOLIMA')
    puts TypeProcess.find(12356).update(id: 12356,passive_part: 'MUNICIPIO SAN SEBASTIAN DE MARIQUITA')
    puts TypeProcess.find(12353).update(id: 12353,passive_part: 'HOSPITAL REGIONAL DEL LIBANO')
    puts TypeProcess.find(12349).update(id: 12349,passive_part: 'HOSPITAL SAN JOSE DE ORTEGA')
    puts TypeProcess.find(12343).update(id: 12343,passive_part: 'MUNICIPIO DE SAN ANTONIO')
    puts TypeProcess.find(12342).update(id: 12342,passive_part: 'ALCALDIA DE IBAGUE')
    puts TypeProcess.find(12329).update(id: 12329,passive_part: 'ALCALDIA DE IBAGUE')
    puts TypeProcess.find(12328).update(id: 12328,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(10729).update(id: 10729,passive_part: 'INSTITUTO MUNICIPAL PARA EL DEPORTE Y LA RECREACION DE IBAGU')
    puts TypeProcess.find(10706).update(id: 10706,passive_part: 'CORPORACION AUTONOMA REGIONAL DEL TOLIMA CORTOLIMA')
    puts TypeProcess.find(10693).update(id: 10693,passive_part: 'CORPORACION AUTONOMA REGIONAL DEL TOLIMA CORTOLIMA')
    puts TypeProcess.find(10689).update(id: 10689,passive_part: 'CORPORACION AUTONOMA REGIONAL DEL TOLIMA CORTOLIMA')
    puts TypeProcess.find(10664).update(id: 10664,passive_part: 'GOBIERNO DEPARTAMENTAL DEL TOLIMA')
    puts TypeProcess.find(10612).update(id: 10612,passive_part: 'MUNICIPIO DE IBAGUE ')
    puts TypeProcess.find(10569).update(id: 10569,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(10518).update(id: 10518,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA EMPRESA SOCIAL DEL ESTADO')
    puts TypeProcess.find(10516).update(id: 10516,passive_part: 'CAJA DE COMPENSACION FAMILIAR DE FENALCO DEL TOLIMA-COMFENAL')
    puts TypeProcess.find(10510).update(id: 10510,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA - IBAGUE')
    puts TypeProcess.find(10506).update(id: 10506,passive_part: 'GOBIERNO DEPARTAMENTAL DEL TOLIMA')
    puts TypeProcess.find(10505).update(id: 10505,passive_part: 'GOBIERNO DEPARTAMENTAL DEL TOLIMA')
    puts TypeProcess.find(10504).update(id: 10504,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA - IBAGUE')
    puts TypeProcess.find(10503).update(id: 10503,passive_part: 'MUNICIPIO DE PIEDRAS')
    puts TypeProcess.find(10502).update(id: 10502,passive_part: 'MUNICIPIO DE VALLE DE SAN JUAN')
    puts TypeProcess.find(10501).update(id: 10501,passive_part: 'ALCALDIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10500).update(id: 10500,passive_part: 'HOSPITAL SAN RAFAEL ESPINAL')
    puts TypeProcess.find(10499).update(id: 10499,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(10494).update(id: 10494,passive_part: 'GESTORA URBANA')
    puts TypeProcess.find(10230).update(id: 10230,passive_part: 'MUNICIPIO DE ATACO')
    puts TypeProcess.find(9609).update(id: 9609,passive_part: 'HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO')
    puts TypeProcess.find(9602).update(id: 9602,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9600).update(id: 9600,passive_part: 'ESE HOSPITAL DEPARTAMENTAL SAN VICENTE DE PAUL')
    puts TypeProcess.find(9598).update(id: 9598,passive_part: 'HOSPITAL SAN VICENTE DE PAUL GARZON HUILA')
    puts TypeProcess.find(9570).update(id: 9570,passive_part: 'MUNICIPIO DE NEIVA')
    puts TypeProcess.find(9502).update(id: 9502,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9474).update(id: 9474,passive_part: 'ESE HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PADUA DE LA PLATA')
    puts TypeProcess.find(9448).update(id: 9448,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA ESE')
    puts TypeProcess.find(9438).update(id: 9438,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9437).update(id: 9437,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9436).update(id: 9436,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9435).update(id: 9435,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9433).update(id: 9433,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA')
    puts TypeProcess.find(9398).update(id: 9398,passive_part: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PITALITO')
    puts TypeProcess.find(9347).update(id: 9347,passive_part: 'ESE HOSPITAL DEPARTAMENTAL SAN VICENTE DE PAUL DE GARZON HUILA')
    puts TypeProcess.find(9262).update(id: 9262,passive_part: 'ESE HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PADUA DE LA PLATA')
    puts TypeProcess.find(9244).update(id: 9244,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(9240).update(id: 9240,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(9236).update(id: 9236,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9203).update(id: 9203,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9199).update(id: 9199,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9195).update(id: 9195,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9191).update(id: 9191,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9190).update(id: 9190,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(9182).update(id: 9182,passive_part: 'ELECTRIFICADORA DEL CAQUETA')
    puts TypeProcess.find(9181).update(id: 9181,passive_part: 'ELECTRIFICADORA DEL CAQUETA SA ESP')
    puts TypeProcess.find(9172).update(id: 9172,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(9170).update(id: 9170,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(9111).update(id: 9111,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(9096).update(id: 9096,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(9033).update(id: 9033,passive_part: 'MUNICIPIO DE NEIVA - ELECTRIFICADORA DEL HUILA ')
    puts TypeProcess.find(9010).update(id: 9010,passive_part: 'EMPRESA SOCIAL DEL ESTADO CARMEN EMILIA OSPINA')
    puts TypeProcess.find(8846).update(id: 8846,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(8837).update(id: 8837,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(8683).update(id: 8683,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA')
    puts TypeProcess.find(8682).update(id: 8682,passive_part: 'ESE HOSPITAL DEL SARARE')
    puts TypeProcess.find(8660).update(id: 8660,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA')
    puts TypeProcess.find(8549).update(id: 8549,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(8375).update(id: 8375,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA ESE')
    puts TypeProcess.find(8362).update(id: 8362,passive_part: 'CONGREGACION DE DOMINICAS DE SANTA CATALINA SENA')
    puts TypeProcess.find(8350).update(id: 8350,passive_part: 'ESE HOSPITAL DEL SARARE')
    puts TypeProcess.find(8336).update(id: 8336,passive_part: 'ESE SORTERESA ADELE')
    puts TypeProcess.find(8332).update(id: 8332,passive_part: 'PROSEGUR VIGILANCIA Y SEGURIDAD PRIVADA LTDA')
    puts TypeProcess.find(8286).update(id: 8286,passive_part: 'ESE HOSPITAL MARIA INMACULADA DE FLORENCIA')
    puts TypeProcess.find(8285).update(id: 8285,passive_part: 'HOSPITAL SAN VICENTE DE ARAUCA')
    puts TypeProcess.find(8151).update(id: 8151,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(8117).update(id: 8117,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(7960).update(id: 7960,passive_part: 'SUBRED INTEGRADA DE SERVICIOS DE SALUD CENTRO ORIENTE ESE')
    puts TypeProcess.find(7930).update(id: 7930,passive_part: 'YANID PAOLA MONTERO GARCIA')
    puts TypeProcess.find(7894).update(id: 7894,passive_part: 'ELECTRIFICADORA DEL CAQUETA SAESP')
    puts TypeProcess.find(7893).update(id: 7893,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(7890).update(id: 7890,passive_part: 'MUNICIPIO DE FLORENCIA')
    puts TypeProcess.find(7784).update(id: 7784,passive_part: 'HOSPITAL DEL SARARE EMPRESA SOCIAL DEL ESTADO')
    puts TypeProcess.find(7688).update(id: 7688,passive_part: 'ASMET SALUD EPS')
    puts TypeProcess.find(7687).update(id: 7687,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(7643).update(id: 7643,passive_part: 'ESE SOR TERESA ADELA')
    puts TypeProcess.find(7642).update(id: 7642,passive_part: 'HOSPITAL MARIA INMACULADA DE FLORENCIA')
    puts TypeProcess.find(7641).update(id: 7641,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(7640).update(id: 7640,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(7639).update(id: 7639,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(7588).update(id: 7588,passive_part: 'CLINICA MEDILASER SA')
    puts TypeProcess.find(7425).update(id: 7425,passive_part: 'LA PREVISORA COMPANIA DE SEGUROS')
    puts TypeProcess.find(7181).update(id: 7181,passive_part: 'HOSPITAL MARIA INMACULADA ESE')
    puts TypeProcess.find(7142).update(id: 7142,passive_part: 'NUEVA EPS')
    puts TypeProcess.find(7109).update(id: 7109,passive_part: 'DEPARTAMENTO DEL CAQUETA')
    puts TypeProcess.find(7031).update(id: 7031,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6953).update(id: 6953,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6828).update(id: 6828,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6827).update(id: 6827,passive_part: 'ELECTRIFICADORA DEL CAQUETA SA ESP')
    puts TypeProcess.find(6801).update(id: 6801,passive_part: 'YANID PAOLA MONTERO GARCIA')
    puts TypeProcess.find(6715).update(id: 6715,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(6607).update(id: 6607,passive_part: 'HOSPITAL MILITAR CENTRAL')
    puts TypeProcess.find(6555).update(id: 6555,passive_part: 'ELECTRIFICADORA DEL CAQUETA SA ESP')
    puts TypeProcess.find(6439).update(id: 6439,passive_part: 'ELECTRIFICADORA DEL CAQUETA SA ESP')
    puts TypeProcess.find(6438).update(id: 6438,passive_part: 'ESE CARMEN EMILIA OSPINA')
    puts TypeProcess.find(6388).update(id: 6388,passive_part: 'ESE CARMEN EMILIA OSPINA')
    puts TypeProcess.find(6284).update(id: 6284,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6283).update(id: 6283,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6282).update(id: 6282,passive_part: 'HOSPITAL UNIVERSITARIO DEPARTAMENTAL DE NARINO ESE')
    puts TypeProcess.find(6270).update(id: 6270,passive_part: 'ESE HOSPITAL DEPARTAMENTAL SAN VICENTE DE PAUL DE GARZON HUI')
    puts TypeProcess.find(6251).update(id: 6251,passive_part: 'ESE HOSPITAL DEPARTAMENTAL DE SAN VICENTE DE PAUL')
    puts TypeProcess.find(6204).update(id: 6204,passive_part: 'ELECTRIFICADORA DEL CAQUETA SA ESP')
    puts TypeProcess.find(6116).update(id: 6116,passive_part: 'ESE HOSPITAL SAN VICENTE DE PAUL DE GARZON HUILA')
    puts TypeProcess.find(6102).update(id: 6102,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6090).update(id: 6090,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(6087).update(id: 6087,passive_part: 'ESE FABIO JARAMILLO LONDONO')
    puts TypeProcess.find(6058).update(id: 6058,passive_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6054).update(id: 6054,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6053).update(id: 6053,passive_part: 'ELECTRIFICADORA DEL CAQUETA')
    puts TypeProcess.find(6052).update(id: 6052,passive_part: 'ESE HOSPITAL MARIA INMACULADA DE FLORENCIA')
    puts TypeProcess.find(6051).update(id: 6051,passive_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(5223).update(id: 5223,passive_part: 'CAJA DE PREVISION SOCIAL DE COMUNICACIONES - CAPRECOM')
    puts TypeProcess.find(5193).update(id: 5193,passive_part: 'HOSPITAL FEDERICO LLERAS ACOSTA - IBAGUE')
    puts TypeProcess.find(5122).update(id: 5122,passive_part: 'O R INGENIERIA SAS')
    puts TypeProcess.find(5093).update(id: 5093,passive_part: 'CAJA DE PREVISION SOCIAL DE COMUNICACIONES CAPRECOM')
    puts TypeProcess.find(5037).update(id: 5037,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4207).update(id: 4207,passive_part: 'ESE HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO PERDOMO')
    puts TypeProcess.find(4201).update(id: 4201,passive_part: 'E S E HOSPITAL DEL ROSARIO')
    puts TypeProcess.find(4199).update(id: 4199,passive_part: 'ESE HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO PERDOMO')
    puts TypeProcess.find(4198).update(id: 4198,passive_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4197).update(id: 4197,passive_part: 'ESE HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO PERDOMO')
    puts TypeProcess.find(4196).update(id: 4196,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(4192).update(id: 4192,passive_part: 'MUNICIPIO DE  NEIVA')
    puts TypeProcess.find(4183).update(id: 4183,passive_part: 'SANTOFIMIO CARDOZO GILDARDO')
    puts TypeProcess.find(4179).update(id: 4179,passive_part: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PITALITO')
    puts TypeProcess.find(4178).update(id: 4178,passive_part: 'ASOCIACION PRO BIENESTAR DE LA FAMILIA COLOMBIANA PROFAMILIA')
    puts TypeProcess.find(4161).update(id: 4161,passive_part: 'TORO VALLEJO JAIME HUMBERTO')
    puts TypeProcess.find(4157).update(id: 4157,passive_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(4155).update(id: 4155,passive_part: 'MARTINEZ HERRERA CESAR ALEJANDRO')
    puts TypeProcess.find(4138).update(id: 4138,passive_part: 'SERVICIO OCCIDENTAL DE SALUD EPS SA')
    puts TypeProcess.find(4121).update(id: 4121,passive_part: 'COLLAZOS CERQUERA LUIS ALBERTO')
    puts TypeProcess.find(4119).update(id: 4119,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(4103).update(id: 4103,passive_part: 'CONTRALORIA GENERAL DE LA REPUBLICA')
    puts TypeProcess.find(4096).update(id: 4096,passive_part: 'ELECTRIFICADORA DEL HUILA SA ESP')
    puts TypeProcess.find(4082).update(id: 4082,passive_part: 'FLORIANO CABRERA MIGUEL')
    puts TypeProcess.find(4075).update(id: 4075,passive_part: 'CORPORACION VIDA EN PRIMAVERA - CORVIPRI -')
    puts TypeProcess.find(4073).update(id: 4073,passive_part: 'TORO VALLEJO JAIME HUMBERTO')
    puts TypeProcess.find(4072).update(id: 4072,passive_part: 'CABRERA CHARRY MANUEL MARIA')
    puts TypeProcess.find(4067).update(id: 4067,passive_part: 'DEPARTAMENTO DEL HUILA')
    puts TypeProcess.find(2548).update(id: 2548,passive_part: 'HOSPITAL DEPARTAMENTAL CENTENARIO DE SEVILLA')
    puts TypeProcess.find(2544).update(id: 2544,passive_part: 'HOSPITAL UNIVERSITARIO SAN JORGE')
    puts TypeProcess.find(2531).update(id: 2531,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2530).update(id: 2530,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2520).update(id: 2520,passive_part: 'HOSPITAL SAN VICENTE DE PAUL STA ROSA DE CABAL')
    puts TypeProcess.find(2515).update(id: 2515,passive_part: 'COMFAMILIAR RISARALDA')
    puts TypeProcess.find(2513).update(id: 2513,passive_part: 'HOSPITAL UNIVERSITARIO SAN JORGE')
    puts TypeProcess.find(2507).update(id: 2507,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2504).update(id: 2504,passive_part: 'SOC DE ACUEDUCTO Y ALCANTARILLADO DEL VALLE')
    puts TypeProcess.find(2496).update(id: 2496,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2490).update(id: 2490,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2474).update(id: 2474,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2469).update(id: 2469,passive_part: 'HOSPITAL SANTA MONICA DOSQUEBRADAS')
    puts TypeProcess.find(2466).update(id: 2466,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC')
    puts TypeProcess.find(2464).update(id: 2464,passive_part: 'ESE HOSPITAL SANTA ANA DE LOS CABALLEROS')
    puts TypeProcess.find(2456).update(id: 2456,passive_part: 'HOSPITAL NAZARETH DE QUINCHIA')
    puts TypeProcess.find(2452).update(id: 2452,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2442).update(id: 2442,passive_part: 'ESE HOSPITAL SANTA ANA DE LOS CABALLEROS')
    puts TypeProcess.find(2428).update(id: 2428,passive_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC')
    puts TypeProcess.find(2423).update(id: 2423,passive_part: 'COMFAMILIAR RISARALDA')
    puts TypeProcess.find(2421).update(id: 2421,passive_part: 'HOSPITAL NAZARETH DE QUINCHIA')
    puts TypeProcess.find(2418).update(id: 2418,passive_part: 'HOSPITAL UNIVERSITARIO SAN JORGE')
    puts TypeProcess.find(2415).update(id: 2415,passive_part: 'HOSPITAL UNIVERSITARIO SAN JORGE')
    puts TypeProcess.find(2408).update(id: 2408,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2383).update(id: 2383,passive_part: 'MUNICIPIO DE PEREIRA')
    puts TypeProcess.find(2372).update(id: 2372,passive_part: 'ESE SALUD PEREIRA')
    puts TypeProcess.find(390).update(id: 390,passive_part: 'COMFAMILIAR RISARALDA')
    puts TypeProcess.find(290).update(id: 290,passive_part: 'EMPRESA DE ENERGIA DE PEREIRA ')
    puts TypeProcess.find(122).update(id: 122,passive_part: 'PREVISORA DE SEGUROS SA')
    puts TypeProcess.find(95).update(id: 95,passive_part: 'ESE HOSPITAL SANTA MONICA DE DOSQUEBRADAS Y OTROS')
  end
end
