class Aleja03 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9918).update(case_id_ekogui: '954196',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9899).update(case_id_ekogui: '838360',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9740).update(case_id_ekogui: '768321',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9266).update(case_id_ekogui: '385549',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9031).update(case_id_ekogui: '869147',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9021).update(case_id_ekogui: '868111',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8883).update(case_id_ekogui: '683731',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8727).update(case_id_ekogui: '868658',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8471).update(case_id_ekogui: '811145',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6984).update(case_id_ekogui: '1198854',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6267).update(case_id_ekogui: '1031061',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6077).update(case_id_ekogui: '975132',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6044).update(case_id_ekogui: '975000',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1843).update(case_id_ekogui: '424108',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1694).update(case_id_ekogui: '1239536',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1661).update(case_id_ekogui: '423954',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1652).update(case_id_ekogui: '191129',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1624).update(case_id_ekogui: '347616',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1602).update(case_id_ekogui: '740187',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1458).update(case_id_ekogui: '423197',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1438).update(case_id_ekogui: '803547',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1428).update(case_id_ekogui: '423748',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1424).update(case_id_ekogui: '132110',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1423).update(case_id_ekogui: '854173',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1392).update(case_id_ekogui: '234976',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1326).update(case_id_ekogui: '409876',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1834).update(case_id_ekogui: '423556',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1726).update(case_id_ekogui: '794262',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1717).update(case_id_ekogui: '776310',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1672).update(case_id_ekogui: '739188',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
