class UpdateAttottornies < ActiveRecord::Migration[5.1]
  def change
    Attorny.delete_all
    Attorny.create(id: 1, name: 'ALBA INES GOMEZ VELEZ', code: '001')
    Attorny.create(id: 2, name: 'ALEX FONTALVO VELASQUEZ', code: '002')
    Attorny.create(id: 3, name: 'ALEXANDRA PATRICIA TORRES HERRERA', code: '003')
    Attorny.create(id: 4, name: 'ALMA ROCIO ARIZA FORTICH', code: '004')
    Attorny.create(id: 5, name: 'ALVARO ANDRES DIAZ PALACIOS', code: '005')
    Attorny.create(id: 6, name: 'ALVARO AUGUSTO GOMEZ MONTES', code: '006')
    Attorny.create(id: 7, name: 'ANA INES GOMEZ CALDERON', code: '007')
    Attorny.create(id: 8, name: 'ANA INES URIBE OSORIO', code: '008')
    Attorny.create(id: 9, name: 'ANA MILENA VELASCO MUNOZ', code: '009')
    Attorny.create(id: 10, name: 'ANA PIEDAD MONTANO COVALEDA', code: '010')
    Attorny.create(id: 11, name: 'ANDRES ORION ALVAREZ PEREZ', code: '011')
    Attorny.create(id: 12, name: 'ANGELA MARIA LOPEZ CASTANO', code: '012')
    Attorny.create(id: 13, name: 'ANTONIO ANDRADE DE AVILA', code: '013')
    Attorny.create(id: 14, name: 'ANTONIO LUIS DAVILA GARCIA', code: '014')
    Attorny.create(id: 15, name: 'ARTURO SANABRIA GOMEZ', code: '015')
    Attorny.create(id: 16, name: 'BEATRIZ ELENA ESTRADA TOBON', code: '016')
    Attorny.create(id: 17, name: 'BELLA SOBEIDA GOMEZ RODRIGUEZ', code: '017')
    Attorny.create(id: 18, name: 'BLANCA STELLA OROZCO RAMIREZ', code: '018')
    Attorny.create(id: 19, name: 'CARLOS ALFONSO CIFUENTES NEIRA', code: '019')
    Attorny.create(id: 20, name: 'CARLOS ANDRES VARGAS VARGAS', code: '020')
    Attorny.create(id: 21, name: 'CARLOS EDUARDO GOMEZ GUTIERREZ', code: '021')
    Attorny.create(id: 22, name: 'CARLOS ENRIQUE QUIJANO RUEDA', code: '022')
    Attorny.create(id: 23, name: 'CARLOS FRANCISCO GARCIA HARKER', code: '023')
    Attorny.create(id: 24, name: 'CATALINA BERNAL RINCON', code: '024')
    Attorny.create(id: 25, name: 'CHARLES CHAPMAN', code: '025')
    Attorny.create(id: 26, name: 'CLARA PATRICIA RUBIANO ZALAMEA', code: '026')
    Attorny.create(id: 27, name: 'CLARA SONIA PEREZ LOPEZ', code: '027')
    Attorny.create(id: 28, name: 'CLAUDIA LIEVANO TRIANA', code: '028')
    Attorny.create(id: 29, name: 'CLAUDIA PATRICIA ASTUDILLO TIGREROS', code: '029')
    Attorny.create(id: 30, name: 'CLAUDIA SOFIA FLOREZ MAHECHA', code: '030')
    Attorny.create(id: 31, name: 'CLAUDIO HENRY YAMA SANTACRUZ', code: '031')
    Attorny.create(id: 32, name: 'DANIEL ALEJANDRO PALACIOS BALLEN', code: '032')
    Attorny.create(id: 33, name: 'DIANA LESLIE BLANCO ARENAS', code: '033')
    Attorny.create(id: 34, name: 'DIANA MILENA PUENTES', code: '034')
    Attorny.create(id: 35, name: 'DIANA SANCLEMENTE TORRES', code: '035')
    Attorny.create(id: 36, name: 'DIEGO BUITRAGO FLOREZ', code: '036')
    Attorny.create(id: 37, name: 'DIEGO DE JESUS VELEZ ACEVEDO', code: '037')
    Attorny.create(id: 38, name: 'DILSON JAVIER RAMIREZ DEL TORO', code: '038')
    Attorny.create(id: 39, name: 'DIONISIO ARAUJO', code: '039')
    Attorny.create(id: 40, name: 'DORICELLI CHAVEZ JIMENEZ', code: '040')
    Attorny.create(id: 41, name: 'EDMER LEANDRO LOPEZ PENA', code: '041')
    Attorny.create(id: 42, name: 'EIDELMAN JAVIER GONZALEZ SANCHEZ', code: '042')
    Attorny.create(id: 43, name: 'ESPERANZA PARRA MARTINEZ', code: '043')
    Attorny.create(id: 44, name: 'ESTEBAN PARDO LANZETTA', code: '044')
    Attorny.create(id: 45, name: 'FABIO ALVAREZ LOPEZ', code: '045')
    Attorny.create(id: 46, name: 'FABIO BERMUDEZ SUAREZ', code: '046')
    Attorny.create(id: 47, name: 'FABIO PEREZ QUESADA', code: '047')
    Attorny.create(id: 48, name: 'FERNANDO AUGUSTO GARCIA MATAMOROS', code: '048')
    Attorny.create(id: 49, name: 'FRANCISCO YESIT FORERO GONZALEZ', code: '049')
    Attorny.create(id: 50, name: 'GERMAN EDUARDO PALACIO ZUNIGA', code: '050')
    Attorny.create(id: 51, name: 'GERMAN GONZALO VALDES SANCHEZ', code: '051')
    Attorny.create(id: 52, name: 'GERMAN MAURICIO OSPINA MUNOZ', code: '052')
    Attorny.create(id: 53, name: 'GERMAN RICARDO GALEANO SOTOMAYOR', code: '053')
    Attorny.create(id: 54, name: 'GINNY DAYANE ACOSTA AVILA', code: '054')
    Attorny.create(id: 55, name: 'GIOVANNY ALBERTO PENALOZA PABON', code: '055')
    Attorny.create(id: 56, name: 'GLORIA BARON LEMUS', code: '056')
    Attorny.create(id: 57, name: 'GLORIA MERCEDES BARON SERNA', code: '057')
    Attorny.create(id: 58, name: 'GLORIA SARMIENTO LOBO GUERRERO', code: '058')
    Attorny.create(id: 59, name: 'GUILLERMO ENRIQUE BURBANO CORTES', code: '059')
    Attorny.create(id: 60, name: 'GUSTAVO ALBERTO HERRERA AVILA', code: '060')
    Attorny.create(id: 61, name: 'HAROLD ARISTIZABAL MARIN', code: '061')
    Attorny.create(id: 62, name: 'HUGO HERNANDO MORENO ECHEVERRY', code: '062')
    Attorny.create(id: 63, name: 'HUGUES ALFONSO OLIVELLA VILORIA', code: '063')
    Attorny.create(id: 64, name: 'JACQUELINE ROMERO ESTRADA', code: '064')
    Attorny.create(id: 65, name: 'JAIME ANDRES VELASCO MUNOZ', code: '065')
    Attorny.create(id: 66, name: 'JAIRO CABEZAS LEON', code: '066')
    Attorny.create(id: 67, name: 'JAVIER LANDINEZ MONTANEZ', code: '067')
    Attorny.create(id: 68, name: 'JAVIER REALES ESPANA', code: '068')
    Attorny.create(id: 69, name: 'JAVIER VASQUEZ NEIRA', code: '069')
    Attorny.create(id: 70, name: 'JHON FREDY ALVAREZ CARMAGO', code: '070')
    Attorny.create(id: 71, name: 'JOAQUIN ANDRES CUELLAR SALAS', code: '071')
    Attorny.create(id: 72, name: 'JOAQUIN ANDRES SALAZAR CUELLAR', code: '072')
    Attorny.create(id: 73, name: 'JOAQUIN DE JESUS CASTANO RAMIREZ', code: '073')
    Attorny.create(id: 74, name: 'JOHN JAIRO CORREA ESCOBAR', code: '074')
    Attorny.create(id: 75, name: 'JORGE ANDRES TABORDA JIMENEZ', code: '075')
    Attorny.create(id: 76, name: 'JORGE ANTONIO VELEZ BARRERA', code: '076')
    Attorny.create(id: 77, name: 'JORGE AUGUSTO FRANCO GIRALDO', code: '077')
    Attorny.create(id: 78, name: 'JORGE ELIECER SALAZAR AVENIA', code: '078')
    Attorny.create(id: 79, name: 'JORGE LUIS SABOGAL SABOGAL', code: '079')
    Attorny.create(id: 80, name: 'JORGE MAURICIO BARRERA TAPIAS', code: '080')
    Attorny.create(id: 81, name: 'JOSE ANTONIO CACERES NINO', code: '081')
    Attorny.create(id: 82, name: 'JOSE DEL CARMEN BERNAL CALVO', code: '082')
    Attorny.create(id: 83, name: 'JOSE DEL CARMEN MUNOZ CRUZ', code: '083')
    Attorny.create(id: 84, name: 'JOSE FERNANDO TORRES FERNANDEZ DE CASTRO', code: '084')
    Attorny.create(id: 85, name: 'JOSE FERNANDO ZARTA ARIZABALETA', code: '085')
    Attorny.create(id: 86, name: 'JOSE HERNAN AREVALO RONCANCIO', code: '086')
    Attorny.create(id: 87, name: 'JOSE RIOS ALZATE', code: '087')
    Attorny.create(id: 88, name: 'JUAN CAMILO ARANGO RIOS', code: '088')
    Attorny.create(id: 89, name: 'JUAN CARLOS HURTADO RESTREPO', code: '089')
    Attorny.create(id: 90, name: 'JUAN DAVID ZARATE LOPEZ', code: '090')
    Attorny.create(id: 91, name: 'JUAN FERNANDO ARBELAEZ VILLADA', code: '091')
    Attorny.create(id: 92, name: 'JUAN MANUEL DIAZ GRANADOS ORTIZ', code: '092')
    Attorny.create(id: 93, name: 'JUAN PABLO ARAUJO', code: '093')
    Attorny.create(id: 94, name: 'JUAN PABLO GIRALDO PUERTA', code: '094')
    Attorny.create(id: 95, name: 'JUAN RICARDO PRIETO PELAEZ', code: '095')
    Attorny.create(id: 96, name: 'JULIO CESAR YEPES RESTREPO', code: '096')
    Attorny.create(id: 97, name: 'JULIO MAURICIO LOPEZ CIUFFETELLI', code: '097')
    Attorny.create(id: 98, name: 'JULY ALEXANDRA CIRO HIGUITA', code: '098')
    Attorny.create(id: 99, name: 'LIBARDO ANGEL GONZALEZ', code: '099')
    Attorny.create(id: 100, name: 'LIDIA MIREYA PILONIETA RUEDA', code: '100')
    Attorny.create(id: 101, name: 'LILLY ESTHER AYCARDI GALEANO', code: '101')
    Attorny.create(id: 102, name: 'LINA MARCELA GABELO VELASQUEZ', code: '102')
    Attorny.create(id: 103, name: 'LINA MARIA URIBE ZULUAGA', code: '103')
    Attorny.create(id: 104, name: 'LUIS ALBERTO GOMEZ BETANCURT', code: '104')
    Attorny.create(id: 105, name: 'LUIS FERNANDO MEJIA SERNA', code: '105')
    Attorny.create(id: 106, name: 'LUIS FERNANDO NOVOA VILLAMIL', code: '106')
    Attorny.create(id: 107, name: 'LUIS FERNANDO URIBE DE URBINA', code: '107')
    Attorny.create(id: 108, name: 'LUIS HELMER URRIAGO ZAPATA', code: '108')
    Attorny.create(id: 109, name: 'LUISA FERNANDA VELASQUEZ ANGEL', code: '109')
    Attorny.create(id: 110, name: 'LUZ ANGELA MILLAN CRUZ', code: '110')
    Attorny.create(id: 111, name: 'MANFRED CARLOS WAGENER HOLLMANN', code: '111')
    Attorny.create(id: 112, name: 'MARIA CAROLINA ECHEVERRI GONZALEZ', code: '112')
    Attorny.create(id: 113, name: 'MARIA CLAUDIA ROMERO', code: '113')
    Attorny.create(id: 114, name: 'MARIA DEL PILAR GALVIS SEGURA', code: '114')
    Attorny.create(id: 115, name: 'MARIA ELVIRA BOSSA MADRID', code: '115')
    Attorny.create(id: 116, name: 'MARIA PATRICIA RIOS CORREA', code: '116')
    Attorny.create(id: 117, name: 'MARIA PILIONETA ', code: '117')
    Attorny.create(id: 118, name: 'MARINA AREVALO TORRES', code: '118')
    Attorny.create(id: 119, name: 'MARISOL DUQUE OSSA', code: '119')
    Attorny.create(id: 120, name: 'MARLIO MORA CABRERA', code: '120')
    Attorny.create(id: 121, name: 'MARTHA LUCIA GARCIA TAVERA', code: '121')
    Attorny.create(id: 122, name: 'MATEO PELAEZ GARCIA', code: '122')
    Attorny.create(id: 123, name: 'MAURICIO PAVA LUGO', code: '123')
    Attorny.create(id: 124, name: 'MIGUEL ANGEL MARQUEZ SERRANO', code: '124')
    Attorny.create(id: 125, name: 'MIKY FERNANDO OLAYA CUERVO', code: '125')
    Attorny.create(id: 126, name: 'MILCIADES ALBERTO NOVOA VILLAMIL', code: '126')
    Attorny.create(id: 127, name: 'MIRNA PATRICIA WILCHES NAVARRO', code: '127')
    Attorny.create(id: 128, name: 'MYRIAM DE JESUS DONADO DONADO', code: '128')
    Attorny.create(id: 129, name: 'NATALIA BOTERO ZAPATA', code: '129')
    Attorny.create(id: 130, name: 'NELSON ROA REYES', code: '130')
    Attorny.create(id: 131, name: 'NOPE ORTEGA YURANY HASBLEIDI', code: '131')
    Attorny.create(id: 132, name: 'ODILA BARRERA BOHORQUEZ', code: '132')
    Attorny.create(id: 133, name: 'OLFA MARIA PEREZ', code: '133')
    Attorny.create(id: 134, name: 'OLGA LUCIA GOMEZ PINEDA', code: '134')
    Attorny.create(id: 135, name: 'OLGA LUCIA GOMEZ SALAZAR', code: '135')
    Attorny.create(id: 136, name: 'ORDONEZ ORDONEZ ANDRES E', code: '136')
    Attorny.create(id: 137, name: 'ORLANDO JESUS AMAYA OLARTE', code: '137')
    Attorny.create(id: 138, name: 'ORLANDO LASPRILLA VASQUEZ', code: '138')
    Attorny.create(id: 139, name: 'OSCAR ELIAS BOTERO CHALARCA', code: '139')
    Attorny.create(id: 140, name: 'OSCAR IVAN VILLANUEVA SEPULVEDA', code: '140')
    Attorny.create(id: 141, name: 'OSCAR ORLANDO RIOS SILVA', code: '141')
    Attorny.create(id: 142, name: 'PABLO ARTETA MANRIQUE', code: '142')
    Attorny.create(id: 143, name: 'PEDRO MARTIN QUINONES MACHLER', code: '143')
    Attorny.create(id: 144, name: 'RAFAEL ALBERTO ARIZA GOMEZ', code: '144')
    Attorny.create(id: 145, name: 'RAFAEL ENRIQUE SEVILLA AGUILAR', code: '145')
    Attorny.create(id: 146, name: 'RICARDO VELEZ OCHOA', code: '146')
    Attorny.create(id: 147, name: 'ROBERTO CARMELO NANDAR CASTELLANOS', code: '147')
    Attorny.create(id: 148, name: 'ROSARIO MULFORD CARBONELL', code: '148')
    Attorny.create(id: 149, name: 'SAUL GIRALDO GARCIA', code: '149')
    Attorny.create(id: 150, name: 'SERGIO ALEJANDRO VILLEGAS AGUDELO', code: '150')
    Attorny.create(id: 151, name: 'SERVIO TULIO CAICEDO VELASCO', code: '151')
    Attorny.create(id: 152, name: 'SIGIFREDO WILCHES BORNACELLI', code: '152')
    Attorny.create(id: 153, name: 'WILLIAM ADAN RODRIGUEZ CASTILLO', code: '153')
    Attorny.create(id: 154, name: 'WINSTON HERMINSUL RUBIO SEGURA', code: '154')
    Attorny.create(id: 155, name: 'YEZID GARCIA ARENAS', code: '155')
  end
end
