class Al18 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(2741).update(id: 2741,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3818).update(id: 3818,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3825).update(id: 3825,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3827).update(id: 3827,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3861).update(id: 3861,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3889).update(id: 3889,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3897).update(id: 3897,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3919).update(id: 3919,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4209).update(id: 4209,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4210).update(id: 4210,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4214).update(id: 4214,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4227).update(id: 4227,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4244).update(id: 4244,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4246).update(id: 4246,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4935).update(id: 4935,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4959).update(id: 4959,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4960).update(id: 4960,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7809).update(id: 7809,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7937).update(id: 7937,last_performance: 'RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8458).update(id: 8458,last_performance: 'AUTO QUE TERMINA PROCESO POR CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9054).update(id: 9054,last_performance: 'AUTO QUE TERMINA PROCESO POR CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9083).update(id: 9083,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9159).update(id: 9159,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9345).update(id: 9345,last_performance: 'RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9369).update(id: 9369,last_performance: 'RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9570).update(id: 9570,last_performance: 'AUTO QUE TERMINA PROCESO POR TRANSACCION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9716).update(id: 9716,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9779).update(id: 9779,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9781).update(id: 9781,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9924).update(id: 9924,last_performance: 'RECURSO DE APELACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10001).update(id: 10001,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10414).update(id: 10414,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11558).update(id: 11558,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11575).update(id: 11575,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11576).update(id: 11576,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11668).update(id: 11668,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11701).update(id: 11701,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11711).update(id: 11711,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11716).update(id: 11716,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11719).update(id: 11719,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11755).update(id: 11755,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11919).update(id: 11919,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12934).update(id: 12934,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13570).update(id: 13570,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13826).update(id: 13826,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13869).update(id: 13869,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14179).update(id: 14179,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14386).update(id: 14386,last_performance: 'DESCARGOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14618).update(id: 14618,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14794).update(id: 14794,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14998).update(id: 14998,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15019).update(id: 15019,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16258).update(id: 16258,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16272).update(id: 16272,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16411).update(id: 16411,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16468).update(id: 16468,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16749).update(id: 16749,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16795).update(id: 16795,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16799).update(id: 16799,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17030).update(id: 17030,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17046).update(id: 17046,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17048).update(id: 17048,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17049).update(id: 17049,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17106).update(id: 17106,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17128).update(id: 17128,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17129).update(id: 17129,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17142).update(id: 17142,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17149).update(id: 17149,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17176).update(id: 17176,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17329).update(id: 17329,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17332).update(id: 17332,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17339).update(id: 17339,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17371).update(id: 17371,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(id: 17402,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17409).update(id: 17409,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17421).update(id: 17421,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17464).update(id: 17464,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17466).update(id: 17466,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17487).update(id: 17487,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17490).update(id: 17490,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17530).update(id: 17530,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17551).update(id: 17551,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17572).update(id: 17572,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17628).update(id: 17628,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17634).update(id: 17634,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17650).update(id: 17650,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17677).update(id: 17677,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17687).update(id: 17687,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17691).update(id: 17691,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17726).update(id: 17726,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17751).update(id: 17751,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17901).update(id: 17901,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17918).update(id: 17918,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17936).update(id: 17936,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17952).update(id: 17952,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17978).update(id: 17978,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17983).update(id: 17983,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17988).update(id: 17988,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18011).update(id: 18011,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18013).update(id: 18013,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18034).update(id: 18034,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18064).update(id: 18064,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18085).update(id: 18085,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18109).update(id: 18109,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18128).update(id: 18128,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18155).update(id: 18155,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18165).update(id: 18165,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18200).update(id: 18200,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18201).update(id: 18201,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18223).update(id: 18223,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18224).update(id: 18224,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18314).update(id: 18314,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18382).update(id: 18382,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18481).update(id: 18481,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18496).update(id: 18496,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18520).update(id: 18520,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18583).update(id: 18583,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18609).update(id: 18609,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18632).update(id: 18632,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18646).update(id: 18646,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18717).update(id: 18717,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18748).update(id: 18748,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18778).update(id: 18778,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18839).update(id: 18839,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18851).update(id: 18851,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18856).update(id: 18856,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18943).update(id: 18943,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19043).update(id: 19043,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19063).update(id: 19063,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19286).update(id: 19286,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19288).update(id: 19288,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19305).update(id: 19305,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19760).update(id: 19760,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20207).update(id: 20207,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20254).update(id: 20254,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20308).update(id: 20308,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20340).update(id: 20340,last_performance: 'AUTO QUE TERMINA PROCESO POR CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20490).update(id: 20490,last_performance: 'AUTO QUE TERMINA PROCESO POR TRANSACCION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,last_performance: 'AUTO QUE TERMINA PROCESO POR CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20666).update(id: 20666,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20757).update(id: 20757,last_performance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21077).update(id: 21077,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21093).update(id: 21093,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21094).update(id: 21094,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21125).update(id: 21125,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21139).update(id: 21139,last_performance: 'ALEGATOS',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21158).update(id: 21158,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21159).update(id: 21159,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21160).update(id: 21160,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21164).update(id: 21164,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21265).update(id: 21265,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21266).update(id: 21266,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21321).update(id: 21321,last_performance: 'AUTO QUE TERMINA PROCESO POR CONCILIACION',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21334).update(id: 21334,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21337).update(id: 21337,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21338).update(id: 21338,last_performance: 'SENTENCIA Y AUTOS GENERALES',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
