class Aleja38 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(20484).update(id: 20484,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL PUTUMAYO')
    puts TypeProcess.find(20485).update(id: 20485,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL PUTUMAYO')
    puts TypeProcess.find(5652).update(id: 5652,active_part: 'MARIA DE LOS ANGELES JIMENEZ')
    puts TypeProcess.find(20063).update(id: 20063,active_part: 'CONTRALORIA DE CUNDINAMARCA')
    puts TypeProcess.find(20740).update(id: 20740,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAQUETA')
    puts TypeProcess.find(5486).update(id: 5486,active_part: 'HERNAN MARIA CARVAJAL')
    puts TypeProcess.find(5587).update(id: 5587,active_part: 'CRISTIAN CAMILO IDARRAGA MONTOYA')
    puts TypeProcess.find(20127).update(id: 20127,active_part: 'CONTRALORIA DE BOGOTA ')
    puts TypeProcess.find(20068).update(id: 20068,active_part: 'CONTRALORIA DE BOGOTA ')
    puts TypeProcess.find(5546).update(id: 5546,active_part: 'WILLIAM ARIZA TRIANA')
    puts TypeProcess.find(5903).update(id: 5903,active_part: 'MARLLY LORENA MONROY GIRALDO')
    puts TypeProcess.find(21020).update(id: 21020,active_part: 'CONTRALORIA DEPARTAMENTAL DE AMAZONAS')
    puts TypeProcess.find(5780).update(id: 5780,active_part: 'JOHANA KATHERINE HERRERA')
    puts TypeProcess.find(20193).update(id: 20193,active_part: 'BLANCA DORIS HENAO Y OTROS')
    puts TypeProcess.find(20194).update(id: 20194,active_part: 'ALVARO QUINTERO CANAVERAL')
    puts TypeProcess.find(20335).update(id: 20335,active_part: 'INVERSIONES MEDICAS BARU SAS')
    puts TypeProcess.find(20339).update(id: 20339,active_part: 'YUCELFI BARRIOS CARABALLO')
    puts TypeProcess.find(2852).update(id: 2852,active_part: 'DEMARCO LTDA ')
    puts TypeProcess.find(5862).update(id: 5862,active_part: 'LINDA SUSANA FERNANDEZ QUINTERO')
    puts TypeProcess.find(5533).update(id: 5533,active_part: 'DIRECCION SECCIONAL DE SALUD DE ANTIOQUIA')
    puts TypeProcess.find(18023).update(id: 18023,active_part: 'CONTRALORIA MUNICIPAL DE POPAYAN')
    puts TypeProcess.find(5932).update(id: 5932,active_part: 'IVAN DARIO ARREDONDO MUNOZ ')
    puts TypeProcess.find(21142).update(id: 21142,active_part: 'UNIDAD CLINICA LA MAGDALENA LTDA')
    puts TypeProcess.find(5329).update(id: 5329,active_part: 'ROMAN MAZO GRANDA Y OTROS')
    puts TypeProcess.find(18404).update(id: 18404,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA')
    puts TypeProcess.find(5445).update(id: 5445,active_part: 'JUAN ANDRES GOMEZ GARCES')
    puts TypeProcess.find(11339).update(id: 11339,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA')
    puts TypeProcess.find(2991).update(id: 2991,active_part: 'JULIO CESAR AGUIRRE VARGAS')
    puts TypeProcess.find(2908).update(id: 2908,active_part: 'EUNICE PERES BARONA Y OTROS')
    puts TypeProcess.find(3717).update(id: 3717,active_part: 'HERNANDO ALFARO FERREIRA')
    puts TypeProcess.find(2937).update(id: 2937,active_part: 'ALEXANDRA STERLING GOMEZ')
    puts TypeProcess.find(3118).update(id: 3118,active_part: 'EDUARDO ANDRES RAMIREZ QUIROZ')
    puts TypeProcess.find(2921).update(id: 2921,active_part: 'MARIA MARGOTH CORDOBA CAICEDO')
    puts TypeProcess.find(3220).update(id: 3220,active_part: 'JAIR EDUARDO QUINTERO VIVEROS')
    puts TypeProcess.find(9230).update(id: 9230,active_part: 'ANGIE CAROLINA PIANDA QUINTERO ')
    puts TypeProcess.find(3072).update(id: 3072,active_part: 'CESAR MANRQUE RUIZ')
    puts TypeProcess.find(3312).update(id: 3312,active_part: 'YESICA LISETH GUERRERO ESPONDA')
    puts TypeProcess.find(2700).update(id: 2700,active_part: 'ELEIDY PATRICIA AVIRAMA Y OTROS ')
    puts TypeProcess.find(3272).update(id: 3272,active_part: 'LUIS FERNANDO CALLEJAS RESTREPO')
    puts TypeProcess.find(2981).update(id: 2981,active_part: 'QUARZO AZUL PRODUCCIONES LTDA')
    puts TypeProcess.find(2949).update(id: 2949,active_part: 'MABEL TATIANA CABEZAS')
    puts TypeProcess.find(2945).update(id: 2945,active_part: 'SOLANY MARINEZ AROCA')
    puts TypeProcess.find(3245).update(id: 3245,active_part: 'JHON CARLOS CRUZ PENALOZA')
    puts TypeProcess.find(2721).update(id: 2721,active_part: 'MARIA ZORAIDA ESCOBAR')
    puts TypeProcess.find(3475).update(id: 3475,active_part: 'LUZ STELLA HERNANDEZ RAMIREZ Y OTROS')
    puts TypeProcess.find(3307).update(id: 3307,active_part: 'FRANKLIN ROSSEBEL CANAS RENTERIA ')
    puts TypeProcess.find(3074).update(id: 3074,active_part: 'CATALINA MARIN VAQUIRO')
    puts TypeProcess.find(3544).update(id: 3544,active_part: 'ELIZABETH RAMOS PARRAA')
    puts TypeProcess.find(3490).update(id: 3490,active_part: 'MARIA MERCEDES RAYO OSPINA ')
    puts TypeProcess.find(2883).update(id: 2883,active_part: 'GUSTAVO CANO PALACIOS')
    puts TypeProcess.find(2976).update(id: 2976,active_part: 'GRACIELA SANTACRUZ')
    puts TypeProcess.find(3489).update(id: 3489,active_part: 'FRANK RICHARD ESTUPINAN')
    puts TypeProcess.find(20846).update(id: 20846,active_part: 'SEGUNDO NEMESIO MARQUINEZ')
  end
end
