class Aleja06 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9918).update(active_part: 'JHON JAIRO ROBLES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9899).update(active_part: 'NURY PATRICIA HUERFANO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9740).update(active_part: 'SARA ESTHER RODRIGUEZ MARTINEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9545).update(active_part: 'MARIA TERESA TOVAR ROJAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9296).update(active_part: 'LEONOR GOMEZ DE VELEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9266).update(active_part: 'SILVANA GIANINA LANZIANO SANTOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9175).update(active_part: 'SIMS LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9031).update(active_part: 'EDWIN HERNANDEZ TURRIAGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9027).update(active_part: 'WLADIMIR CHAVEZ GONZALEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9021).update(active_part: 'QUINTILIANO AGUIRRE LARA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8883).update(active_part: 'NELSON NEVARDO NARANJO BECERRA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8816).update(active_part: 'PATRICIA MARCELA DELGADO OROZCO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8727).update(active_part: 'JOSE DANIEL MORALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8471).update(active_part: 'YADILE ACOSTA CARDOZO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8422).update(active_part: 'EMPRESA DE ENERGIA DEL PUTUMAYO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8268).update(active_part: 'ROBERTO POLO PION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8267).update(active_part: 'TEOBALDO SARMIENTO PAYARES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7961).update(active_part: 'MARIA RUBY CASTANO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7944).update(active_part: 'PATRIMONIO AUTONOMO FIDEICOMISO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7739).update(active_part: 'NUBIA ESPERANZA TORRES CHAPARRO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7714).update(active_part: 'GLORIA EDITH CARO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7665).update(active_part: 'RITA OMAIRA PITA HERNANDEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7624).update(active_part: 'MARIA VICTORIA DEVIA PENALOZA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7597).update(active_part: 'LEIDY JAZMIN GARCIA PENA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7579).update(active_part: 'AUTO FUSA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7327).update(active_part: 'MARIA LUCERO HOYOS HOYOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7271).update(active_part: 'INVIAS AUTO 120',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7127).update(active_part: 'MARIA ANUNCIACION CASTILLO ROJAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6985).update(active_part: 'JULIO CESAR APONTE MUNOZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6984).update(active_part: 'MARIA EMILIA IDARRAGA LOPEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6904).update(active_part: 'CABLES DE ENERGIA Y DE TELE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6542).update(active_part: 'MYRIAM CORTES RODRIGUEZ ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6511).update(active_part: 'NELSON ENRIQUE MARTINEZ HERNANDEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6475).update(active_part: 'ROSALBA PEREZ FLOREZ ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6423).update(active_part: 'CLINICA DE FRACTURAS Y ORTOPEDIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6418).update(active_part: 'CLINICA DE FRACTURAS Y ORTOPEDIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6360).update(active_part: 'TERMINAL DE TRANSPORTES DE BOGOTA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6267).update(active_part: 'ROSA AURA OTALORA DE QUIROGA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6153).update(active_part: 'OIC LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6077).update(active_part: 'JOSE RUDIGER CAMACHO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6044).update(active_part: 'PILAR VELASQUEZ FANDINO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1852).update(active_part: 'HERNANDO CASTIBLANCO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1847).update(active_part: 'NANCY SANCHEZ GRANADOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1843).update(active_part: 'HECTOR JOSE ALVARADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1775).update(active_part: 'LUCIA QUINTERO DE COLMENARES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1712).update(active_part: 'OMAIRA JIMENEZ RODRIGUEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1694).update(active_part: 'TRANSPORTES JOALCO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1661).update(active_part: 'MARIA FERNANDA ACEVEDO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1655).update(active_part: 'CARBOQUIMICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1652).update(active_part: 'JAIRO EMIRO CAICEDO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1624).update(active_part: 'ALMAGRARIO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1609).update(active_part: 'SUPERINTENDENCIA FINANCIERA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1602).update(active_part: 'INDUSTRIAS ROMIL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1596).update(active_part: 'RAUL HERNANDO FONSECA OCHOA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1538).update(active_part: 'BOGOTA  SDHD',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1458).update(active_part: 'JORGE RODRIGUEZ MOLANO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1438).update(active_part: 'JAVIER ALFONSO RINCON CAMELO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1428).update(active_part: 'HECTOR JAVIER MEDINA HERNANDEZ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1424).update(active_part: 'BANCO COMERCIAL AV VILLAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1423).update(active_part: 'LUZ ANGELICA LARGO LAGOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1414).update(active_part: 'TV CABLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1392).update(active_part: 'MIGUEL ANGEL QUELAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1326).update(active_part: 'MARIA ANGELICA BUITAGO BORRERO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1312).update(active_part: 'MARIA ANGELICA BUITAGO BORRERO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(102).update(active_part: 'JHON FREDY OSPINA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1834).update(active_part: 'EDITH URREGO CELIS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1726).update(active_part: 'JULIO CESAR MORALES MIRANDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1717).update(active_part: 'NATALIA SANCHEZ BORDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1672).update(active_part: 'KARIN GUERRERO OVIEDO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1591).update(active_part: 'DANILO CONTA',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
