class Aleja14 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,protection: ['', 'DANOS EXTRAPATRIMONIALES'])
    puts TypeProcess.find(18914).update(id: 18914,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18898).update(id: 18898,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18714).update(id: 18714,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18666).update(id: 18666,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18662).update(id: 18662,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18556).update(id: 18556,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18555).update(id: 18555,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18553).update(id: 18553,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18551).update(id: 18551,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18238).update(id: 18238,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18237).update(id: 18237,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18236).update(id: 18236,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18235).update(id: 18235,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(18078).update(id: 18078,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17866).update(id: 17866,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17642).update(id: 17642,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17641).update(id: 17641,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(9889).update(id: 9889,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(9722).update(id: 9722,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(9515).update(id: 9515,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(9395).update(id: 9395,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(8116).update(id: 8116,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(7996).update(id: 7996,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(7970).update(id: 7970,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(7876).update(id: 7876,protection: ['', 'DELITOS CONTRA LA ADMINISTRACION PUBLICA'])
    puts TypeProcess.find(7311).update(id: 7311,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(7222).update(id: 7222,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(7199).update(id: 7199,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(7162).update(id: 7162,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(7058).update(id: 7058,protection: ['', 'OTRO'])
    puts TypeProcess.find(6751).update(id: 6751,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(6514).update(id: 6514,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(286).update(id: 286,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(19750).update(id: 19750,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(19735).update(id: 19735,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(19287).update(id: 19287,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17480).update(id: 17480,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17441).update(id: 17441,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17218).update(id: 17218,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17146).update(id: 17146,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(17000).update(id: 17000,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16946).update(id: 16946,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16906).update(id: 16906,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16832).update(id: 16832,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(16759).update(id: 16759,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16710).update(id: 16710,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16700).update(id: 16700,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16514).update(id: 16514,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16510).update(id: 16510,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16410).update(id: 16410,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16367).update(id: 16367,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16359).update(id: 16359,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(16262).update(id: 16262,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(16254).update(id: 16254,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(15354).update(id: 15354,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(15339).update(id: 15339,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(15011).update(id: 15011,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL ', ' TERAPEUTICOS ', ' PENDIENTE'])
    puts TypeProcess.find(14987).update(id: 14987,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14986).update(id: 14986,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14985).update(id: 14985,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14983).update(id: 14983,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14982).update(id: 14982,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14981).update(id: 14981,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14980).update(id: 14980,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14977).update(id: 14977,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14976).update(id: 14976,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14973).update(id: 14973,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14972).update(id: 14972,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14936).update(id: 14936,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14821).update(id: 14821,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14791).update(id: 14791,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14790).update(id: 14790,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14788).update(id: 14788,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(14663).update(id: 14663,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13938).update(id: 13938,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13912).update(id: 13912,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13907).update(id: 13907,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13906).update(id: 13906,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13860).update(id: 13860,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13807).update(id: 13807,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13806).update(id: 13806,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13799).update(id: 13799,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13798).update(id: 13798,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13797).update(id: 13797,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13796).update(id: 13796,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13795).update(id: 13795,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13794).update(id: 13794,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13793).update(id: 13793,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13777).update(id: 13777,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13716).update(id: 13716,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13702).update(id: 13702,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13701).update(id: 13701,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13696).update(id: 13696,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13636).update(id: 13636,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13629).update(id: 13629,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13617).update(id: 13617,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13616).update(id: 13616,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13605).update(id: 13605,protection: ['', 'CUMPLIMIENTO ', ' CUMPLIMIENTO'])
    puts TypeProcess.find(13587).update(id: 13587,protection: ['', 'CUMPLIMIENTO'])
    puts TypeProcess.find(13569).update(id: 13569,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13561).update(id: 13561,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13556).update(id: 13556,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13530).update(id: 13530,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13524).update(id: 13524,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13523).update(id: 13523,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13504).update(id: 13504,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13503).update(id: 13503,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13490).update(id: 13490,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13423).update(id: 13423,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13422).update(id: 13422,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13412).update(id: 13412,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13389).update(id: 13389,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13387).update(id: 13387,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13386).update(id: 13386,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13385).update(id: 13385,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13381).update(id: 13381,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(13378).update(id: 13378,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13375).update(id: 13375,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13374).update(id: 13374,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13370).update(id: 13370,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13337).update(id: 13337,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(13333).update(id: 13333,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13304).update(id: 13304,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13296).update(id: 13296,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13289).update(id: 13289,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13280).update(id: 13280,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13256).update(id: 13256,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13225).update(id: 13225,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13222).update(id: 13222,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13202).update(id: 13202,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13191).update(id: 13191,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13168).update(id: 13168,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13134).update(id: 13134,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13133).update(id: 13133,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13129).update(id: 13129,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13120).update(id: 13120,protection: ['', 'CUMPLIMIENTO'])
    puts TypeProcess.find(13108).update(id: 13108,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13107).update(id: 13107,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13106).update(id: 13106,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13101).update(id: 13101,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13097).update(id: 13097,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13096).update(id: 13096,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13064).update(id: 13064,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(13052).update(id: 13052,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12988).update(id: 12988,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12932).update(id: 12932,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12834).update(id: 12834,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12671).update(id: 12671,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12429).update(id: 12429,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12421).update(id: 12421,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12417).update(id: 12417,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12401).update(id: 12401,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12399).update(id: 12399,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12396).update(id: 12396,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12392).update(id: 12392,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12391).update(id: 12391,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12384).update(id: 12384,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12375).update(id: 12375,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12373).update(id: 12373,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12363).update(id: 12363,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12362).update(id: 12362,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12359).update(id: 12359,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12358).update(id: 12358,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12357).update(id: 12357,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12356).update(id: 12356,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12353).update(id: 12353,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12349).update(id: 12349,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12343).update(id: 12343,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12342).update(id: 12342,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12329).update(id: 12329,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(12328).update(id: 12328,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10729).update(id: 10729,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10706).update(id: 10706,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10693).update(id: 10693,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10689).update(id: 10689,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10664).update(id: 10664,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10612).update(id: 10612,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10569).update(id: 10569,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10518).update(id: 10518,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10516).update(id: 10516,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10510).update(id: 10510,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10506).update(id: 10506,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10505).update(id: 10505,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10504).update(id: 10504,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10503).update(id: 10503,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10502).update(id: 10502,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10501).update(id: 10501,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10500).update(id: 10500,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10499).update(id: 10499,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10494).update(id: 10494,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(10230).update(id: 10230,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(7425).update(id: 7425,protection: ['', 'OTRO'])
    puts TypeProcess.find(6828).update(id: 6828,protection: ['', 'DANOS EXTRAPATRIMONIALES'])
    puts TypeProcess.find(6282).update(id: 6282,protection: ['', 'DANOS EXTRAPATRIMONIALES'])
    puts TypeProcess.find(4207).update(id: 4207,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4201).update(id: 4201,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4199).update(id: 4199,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4198).update(id: 4198,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4197).update(id: 4197,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4196).update(id: 4196,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4192).update(id: 4192,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4183).update(id: 4183,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4179).update(id: 4179,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4178).update(id: 4178,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(4161).update(id: 4161,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4157).update(id: 4157,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(4155).update(id: 4155,protection: ['', 'CUMPLIMIENTO'])
    puts TypeProcess.find(4121).update(id: 4121,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4119).update(id: 4119,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4103).update(id: 4103,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4096).update(id: 4096,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4075).update(id: 4075,protection: ['', 'COBERTURA GLOBAL DEL MANEJO'])
    puts TypeProcess.find(4073).update(id: 4073,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4072).update(id: 4072,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(4067).update(id: 4067,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2548).update(id: 2548,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2544).update(id: 2544,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2531).update(id: 2531,protection: ['', 'COBERTURA R.C EXTRACONTRACTUAL'])
    puts TypeProcess.find(2530).update(id: 2530,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2520).update(id: 2520,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2515).update(id: 2515,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2513).update(id: 2513,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2507).update(id: 2507,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2504).update(id: 2504,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2496).update(id: 2496,protection: ['', 'COBERTURA R.C EXTRACONTRACTUAL'])
    puts TypeProcess.find(2490).update(id: 2490,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2474).update(id: 2474,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2469).update(id: 2469,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2466).update(id: 2466,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2464).update(id: 2464,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2456).update(id: 2456,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2452).update(id: 2452,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2442).update(id: 2442,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2428).update(id: 2428,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2423).update(id: 2423,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2421).update(id: 2421,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2418).update(id: 2418,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2415).update(id: 2415,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(2408).update(id: 2408,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2383).update(id: 2383,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(2372).update(id: 2372,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(390).update(id: 390,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
    puts TypeProcess.find(290).update(id: 290,protection: ['', 'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL'])
    puts TypeProcess.find(122).update(id: 122,protection: ['', 'PERJUICIOS MODALIDAD DANO EMERGENTE'])
    puts TypeProcess.find(95).update(id: 95,protection: ['', 'COBERTURA R.C CLINICAS Y HOSPITALES'])
  end
end
