class Aleja48 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(20484).update(id: 20484,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(20485).update(id: 20485,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5652).update(id: 5652,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20063).update(id: 20063,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(20740).update(id: 20740,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5486).update(id: 5486,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5587).update(id: 5587,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20127).update(id: 20127,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(20068).update(id: 20068,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5546).update(id: 5546,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5903).update(id: 5903,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(21020).update(id: 21020,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5780).update(id: 5780,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20193).update(id: 20193,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20194).update(id: 20194,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20335).update(id: 20335,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDADO')
    puts TypeProcess.find(20339).update(id: 20339,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO ORDINARIO',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2852).update(id: 2852,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5862).update(id: 5862,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(5533).update(id: 5533,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(18023).update(id: 18023,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5932).update(id: 5932,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(21142).update(id: 21142,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO EJECUTIVO',link_type: 'DEMANDADO')
    puts TypeProcess.find(5329).update(id: 5329,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(18404).update(id: 18404,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(5445).update(id: 5445,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(11339).update(id: 11339,process_class: 'RESPONSABILIDAD FISCAL',subprocess_class: 'ORDINARIO',link_type: 'TERCERO CIVILMENTE RESPONSABLE')
    puts TypeProcess.find(2991).update(id: 2991,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2908).update(id: 2908,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3717).update(id: 3717,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2937).update(id: 2937,process_class: 'JURISDICCION CIVIL',subprocess_class: 'PROCESO VERBAL',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3118).update(id: 3118,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2921).update(id: 2921,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3220).update(id: 3220,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(9230).update(id: 9230,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3072).update(id: 3072,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3312).update(id: 3312,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2700).update(id: 2700,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3272).update(id: 3272,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2981).update(id: 2981,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2949).update(id: 2949,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2945).update(id: 2945,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3245).update(id: 3245,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2721).update(id: 2721,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3475).update(id: 3475,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3307).update(id: 3307,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3074).update(id: 3074,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3544).update(id: 3544,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3490).update(id: 3490,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2883).update(id: 2883,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(2976).update(id: 2976,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(3489).update(id: 3489,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
    puts TypeProcess.find(20846).update(id: 20846,process_class: 'JURISDICCION CONTENCIOSO ADMINISTRATIVO',subprocess_class: 'REPARACION DIRECTA',link_type: 'LLAMADA EN GARANTIA')
  end
end
