class Aleja19 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(18914).update(id: 18914,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(18898).update(id: 18898,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18714).update(id: 18714,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18666).update(id: 18666,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18662).update(id: 18662,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18556).update(id: 18556,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18555).update(id: 18555,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18553).update(id: 18553,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18552).update(id: 18552,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18551).update(id: 18551,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18238).update(id: 18238,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18237).update(id: 18237,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18236).update(id: 18236,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18235).update(id: 18235,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(18078).update(id: 18078,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17866).update(id: 17866,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(17642).update(id: 17642,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17641).update(id: 17641,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(14900).update(id: 14900,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(9889).update(id: 9889,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)')
    puts TypeProcess.find(9722).update(id: 9722,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9515).update(id: 9515,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)')
    puts TypeProcess.find(9395).update(id: 9395,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8805).update(id: 8805,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8116).update(id: 8116,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7996).update(id: 7996,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7970).update(id: 7970,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7876).update(id: 7876,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7789).update(id: 7789,current_stage: 'LIQUIDACION')
    puts TypeProcess.find(7311).update(id: 7311,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7222).update(id: 7222,current_stage: 'AUDIENCIA DE CONCILIACION (ART 70)')
    puts TypeProcess.find(7199).update(id: 7199,current_stage: 'PRUEBAS')
    puts TypeProcess.find(7162).update(id: 7162,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7058).update(id: 7058,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(6751).update(id: 6751,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6514).update(id: 6514,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(286).update(id: 286,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(19750).update(id: 19750,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(19735).update(id: 19735,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(19287).update(id: 19287,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(17480).update(id: 17480,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17441).update(id: 17441,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17218).update(id: 17218,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17146).update(id: 17146,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(17000).update(id: 17000,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16946).update(id: 16946,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16906).update(id: 16906,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16832).update(id: 16832,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16759).update(id: 16759,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16710).update(id: 16710,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16700).update(id: 16700,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16514).update(id: 16514,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16510).update(id: 16510,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16410).update(id: 16410,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16367).update(id: 16367,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16359).update(id: 16359,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16262).update(id: 16262,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(16254).update(id: 16254,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(15354).update(id: 15354,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(15339).update(id: 15339,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(15011).update(id: 15011,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(14987).update(id: 14987,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(14986).update(id: 14986,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14985).update(id: 14985,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14983).update(id: 14983,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14982).update(id: 14982,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(14981).update(id: 14981,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14980).update(id: 14980,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14977).update(id: 14977,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14976).update(id: 14976,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14973).update(id: 14973,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14972).update(id: 14972,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14936).update(id: 14936,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14821).update(id: 14821,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(14791).update(id: 14791,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA')
    puts TypeProcess.find(14790).update(id: 14790,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA')
    puts TypeProcess.find(14788).update(id: 14788,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA')
    puts TypeProcess.find(14663).update(id: 14663,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13938).update(id: 13938,current_stage: 'AUTO DE IMPUTACION')
    puts TypeProcess.find(13912).update(id: 13912,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13907).update(id: 13907,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13906).update(id: 13906,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13860).update(id: 13860,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13807).update(id: 13807,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13806).update(id: 13806,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13799).update(id: 13799,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13798).update(id: 13798,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13797).update(id: 13797,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13796).update(id: 13796,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13795).update(id: 13795,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13794).update(id: 13794,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13793).update(id: 13793,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13777).update(id: 13777,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13716).update(id: 13716,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13702).update(id: 13702,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13701).update(id: 13701,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(13696).update(id: 13696,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13636).update(id: 13636,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(13629).update(id: 13629,current_stage: 'AUTO QUE RESUELVE EL GRADO DE CONSULTA')
    puts TypeProcess.find(13617).update(id: 13617,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13616).update(id: 13616,current_stage: 'AUTO QUE RESUELVE LA REPOSICION')
    puts TypeProcess.find(13605).update(id: 13605,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13587).update(id: 13587,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13569).update(id: 13569,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13561).update(id: 13561,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13556).update(id: 13556,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13534).update(id: 13534,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13530).update(id: 13530,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13524).update(id: 13524,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13523).update(id: 13523,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13504).update(id: 13504,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13503).update(id: 13503,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13500).update(id: 13500,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13490).update(id: 13490,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13423).update(id: 13423,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13422).update(id: 13422,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13412).update(id: 13412,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13389).update(id: 13389,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13387).update(id: 13387,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13386).update(id: 13386,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13385).update(id: 13385,current_stage: 'RECURSO DE APELACION')
    puts TypeProcess.find(13381).update(id: 13381,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13378).update(id: 13378,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13375).update(id: 13375,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13374).update(id: 13374,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13370).update(id: 13370,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13337).update(id: 13337,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13333).update(id: 13333,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13304).update(id: 13304,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13296).update(id: 13296,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13289).update(id: 13289,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13280).update(id: 13280,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13256).update(id: 13256,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13225).update(id: 13225,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13222).update(id: 13222,current_stage: 'AUTO DE IMPUTACION')
    puts TypeProcess.find(13202).update(id: 13202,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13191).update(id: 13191,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13168).update(id: 13168,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13134).update(id: 13134,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13133).update(id: 13133,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13129).update(id: 13129,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13120).update(id: 13120,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13108).update(id: 13108,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13107).update(id: 13107,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13106).update(id: 13106,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13101).update(id: 13101,current_stage: 'AUTO DE APERTURA E IMPUTACION')
    puts TypeProcess.find(13097).update(id: 13097,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(13096).update(id: 13096,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13064).update(id: 13064,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(13052).update(id: 13052,current_stage: 'FALLO CON RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(12988).update(id: 12988,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12932).update(id: 12932,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(12834).update(id: 12834,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12671).update(id: 12671,current_stage: 'FALLO SIN RESPONSABILIDAD FISCAL')
    puts TypeProcess.find(12429).update(id: 12429,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12421).update(id: 12421,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12417).update(id: 12417,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12401).update(id: 12401,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12399).update(id: 12399,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12396).update(id: 12396,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12392).update(id: 12392,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12391).update(id: 12391,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12388).update(id: 12388,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12384).update(id: 12384,current_stage: 'RECURSO DE APELACION')
    puts TypeProcess.find(12375).update(id: 12375,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12373).update(id: 12373,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12363).update(id: 12363,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12362).update(id: 12362,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12359).update(id: 12359,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12358).update(id: 12358,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12357).update(id: 12357,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12356).update(id: 12356,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12353).update(id: 12353,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12349).update(id: 12349,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12343).update(id: 12343,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12342).update(id: 12342,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(12329).update(id: 12329,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(12328).update(id: 12328,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(10729).update(id: 10729,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10706).update(id: 10706,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10693).update(id: 10693,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(10689).update(id: 10689,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10612).update(id: 10612,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(10569).update(id: 10569,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(10518).update(id: 10518,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(10516).update(id: 10516,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10510).update(id: 10510,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10506).update(id: 10506,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10505).update(id: 10505,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10504).update(id: 10504,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10503).update(id: 10503,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10502).update(id: 10502,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10499).update(id: 10499,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10494).update(id: 10494,current_stage: 'AUTO DE APERTURA')
    puts TypeProcess.find(10230).update(id: 10230,current_stage: 'AUDIENCIA DE DECISION')
    puts TypeProcess.find(9609).update(id: 9609,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9602).update(id: 9602,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9600).update(id: 9600,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9598).update(id: 9598,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9570).update(id: 9570,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9502).update(id: 9502,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9474).update(id: 9474,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9448).update(id: 9448,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9438).update(id: 9438,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9437).update(id: 9437,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9436).update(id: 9436,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9435).update(id: 9435,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9433).update(id: 9433,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9398).update(id: 9398,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9347).update(id: 9347,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9262).update(id: 9262,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9244).update(id: 9244,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)')
    puts TypeProcess.find(9240).update(id: 9240,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9236).update(id: 9236,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9203).update(id: 9203,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9199).update(id: 9199,current_stage: 'APELACION')
    puts TypeProcess.find(9195).update(id: 9195,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9191).update(id: 9191,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9190).update(id: 9190,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9182).update(id: 9182,current_stage: 'PRUEBAS')
    puts TypeProcess.find(9181).update(id: 9181,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9172).update(id: 9172,current_stage: 'AUDIENCIA INICIAL, DE INSTRUCCION Y JUZGAMIENTO (SENTENCIA DE UNICA INSTANCIA)')
    puts TypeProcess.find(9170).update(id: 9170,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(9111).update(id: 9111,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(9096).update(id: 9096,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9033).update(id: 9033,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(9010).update(id: 9010,current_stage: 'PRUEBAS')
    puts TypeProcess.find(8846).update(id: 8846,current_stage: 'PRUEBAS')
    puts TypeProcess.find(8837).update(id: 8837,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8683).update(id: 8683,current_stage: 'PRUEBAS')
    puts TypeProcess.find(8682).update(id: 8682,current_stage: 'PRUEBAS')
    puts TypeProcess.find(8660).update(id: 8660,current_stage: 'PRUEBAS')
    puts TypeProcess.find(8549).update(id: 8549,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(8375).update(id: 8375,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8350).update(id: 8350,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8336).update(id: 8336,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8332).update(id: 8332,current_stage: 'AUDIENCIA PUBLICA')
    puts TypeProcess.find(8286).update(id: 8286,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8285).update(id: 8285,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8151).update(id: 8151,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(8117).update(id: 8117,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7960).update(id: 7960,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7930).update(id: 7930,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7894).update(id: 7894,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7893).update(id: 7893,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7784).update(id: 7784,current_stage: 'PRUEBAS')
    puts TypeProcess.find(7688).update(id: 7688,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7687).update(id: 7687,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7643).update(id: 7643,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7642).update(id: 7642,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7641).update(id: 7641,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7640).update(id: 7640,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7639).update(id: 7639,current_stage: 'PRUEBAS')
    puts TypeProcess.find(7588).update(id: 7588,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7425).update(id: 7425,current_stage: 'CONTESTACION DE LA DEMANDA')
    puts TypeProcess.find(7181).update(id: 7181,current_stage: 'PRUEBAS')
    puts TypeProcess.find(7142).update(id: 7142,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7109).update(id: 7109,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(7031).update(id: 7031,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6953).update(id: 6953,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6828).update(id: 6828,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6827).update(id: 6827,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(6801).update(id: 6801,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6715).update(id: 6715,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6607).update(id: 6607,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6555).update(id: 6555,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(6439).update(id: 6439,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(6438).update(id: 6438,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6388).update(id: 6388,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(6284).update(id: 6284,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6283).update(id: 6283,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6282).update(id: 6282,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6270).update(id: 6270,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6251).update(id: 6251,current_stage: 'AUDIENCIA INICIAL')
    puts TypeProcess.find(6204).update(id: 6204,current_stage: 'AUTO ADMITE LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6116).update(id: 6116,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6102).update(id: 6102,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6090).update(id: 6090,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6087).update(id: 6087,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6058).update(id: 6058,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(6054).update(id: 6054,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6053).update(id: 6053,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(6052).update(id: 6052,current_stage: 'PRUEBAS')
    puts TypeProcess.find(6051).update(id: 6051,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(5223).update(id: 5223,current_stage: 'OPOSICION DEMANDA DE CASACION')
    puts TypeProcess.find(5193).update(id: 5193,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(5122).update(id: 5122,current_stage: 'APELACION')
    puts TypeProcess.find(5093).update(id: 5093,current_stage: 'DEMANDA DE CASACION')
    puts TypeProcess.find(5037).update(id: 5037,current_stage: 'APELACION')
    puts TypeProcess.find(4207).update(id: 4207,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(4201).update(id: 4201,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(4199).update(id: 4199,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(4198).update(id: 4198,current_stage: 'ALEGATOS DE CONCLUSION SEGUNDA INSTANCIA')
    puts TypeProcess.find(4197).update(id: 4197,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(4196).update(id: 4196,current_stage: 'SENTENCIA SEGUNDA INSTANCIA')
    puts TypeProcess.find(4192).update(id: 4192,current_stage: 'CONTESTACION LLAMAMIENTO EN GARANTIA')
    puts TypeProcess.find(4183).update(id: 4183,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4179).update(id: 4179,current_stage: 'PRUEBAS')
    puts TypeProcess.find(4178).update(id: 4178,current_stage: 'PRUEBAS')
    puts TypeProcess.find(4161).update(id: 4161,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4157).update(id: 4157,current_stage: 'SENTENCIA SEGUNDA INSTANCIA')
    puts TypeProcess.find(4155).update(id: 4155,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4138).update(id: 4138,current_stage: 'AUDIENCIA Y FALLO')
    puts TypeProcess.find(4121).update(id: 4121,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4119).update(id: 4119,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4103).update(id: 4103,current_stage: 'SENTENCIA DE PRIMERA INSTANCIA')
    puts TypeProcess.find(4096).update(id: 4096,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4082).update(id: 4082,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4075).update(id: 4075,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4073).update(id: 4073,current_stage: 'SENTENCIA')
    puts TypeProcess.find(4072).update(id: 4072,current_stage: 'SENTENCIA')
    puts TypeProcess.find(2548).update(id: 2548,current_stage: 'APELACION')
    puts TypeProcess.find(2544).update(id: 2544,current_stage: 'APELACION')
    puts TypeProcess.find(2531).update(id: 2531,current_stage: 'APELACION')
    puts TypeProcess.find(2530).update(id: 2530,current_stage: 'APELACION')
    puts TypeProcess.find(2520).update(id: 2520,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(2515).update(id: 2515,current_stage: 'PRUEBAS')
    puts TypeProcess.find(2507).update(id: 2507,current_stage: 'APELACION')
    puts TypeProcess.find(2504).update(id: 2504,current_stage: 'APELACION')
    puts TypeProcess.find(2496).update(id: 2496,current_stage: 'APELACION')
    puts TypeProcess.find(2490).update(id: 2490,current_stage: 'APELACION')
    puts TypeProcess.find(2474).update(id: 2474,current_stage: 'PRUEBAS')
    puts TypeProcess.find(2466).update(id: 2466,current_stage: 'SENTENCIA SEGUNDA INSTANCIA')
    puts TypeProcess.find(2464).update(id: 2464,current_stage: 'APELACION')
    puts TypeProcess.find(2456).update(id: 2456,current_stage: 'APELACION')
    puts TypeProcess.find(2452).update(id: 2452,current_stage: 'APELACION')
    puts TypeProcess.find(2442).update(id: 2442,current_stage: 'ALEGATOS DE CONCLUSION PRIMERA INSTANCIA')
    puts TypeProcess.find(2428).update(id: 2428,current_stage: 'APELACION')
    puts TypeProcess.find(2423).update(id: 2423,current_stage: 'PRUEBAS')
    puts TypeProcess.find(2421).update(id: 2421,current_stage: 'APELACION')
    puts TypeProcess.find(2415).update(id: 2415,current_stage: 'APELACION')
    puts TypeProcess.find(2408).update(id: 2408,current_stage: 'APELACION')
    puts TypeProcess.find(2383).update(id: 2383,current_stage: 'APELACION')
    puts TypeProcess.find(2372).update(id: 2372,current_stage: 'PRUEBAS')
    puts TypeProcess.find(390).update(id: 390,current_stage: 'CONTESTACION DE LA DEMANDA')
    puts TypeProcess.find(290).update(id: 290,current_stage: 'CONTESTACION DE LA DEMANDA')
    puts TypeProcess.find(122).update(id: 122,current_stage: 'AUDIENCIA INICIAL')
    puts TypeProcess.find(95).update(id: 95,current_stage: 'CONTESTACION DE LA DEMANDA')
  end
end
