class Al04 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(2349).update(active_part: 'LA PREVISORA SA -CENTRALES ELECTRICAS DE NARINO S.A. ESP    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3275).update(active_part: 'LA PREVISORA SA -MUNICIPIO DE SANTIAGO DE CALI    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5558).update(active_part: 'LA PREVISORA SA -E.S.E. HOSPITAL SAN JUAN DE DIOS SANTAFE DE ANT    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2915).update(active_part: 'LA PREVISORA SA -INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2560).update(active_part: 'LA PREVISORA SA -EMPRESA SOCIAL DEL ESTADO SALUD PEREIRA    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5067).update(active_part: 'LA PREVISORA SA -HOSPITAL FEDERICO LLERAS ACOSTA E.S.E.    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5226).update(active_part: 'LA PREVISORA SA -HOSPITAL FEDERICO LLERAS ACOSTA - IBAGUE    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5502).update(active_part: 'LA PREVISORA SA -ORDEN HOSPITALARIA DE SAN JUAN DE DIOS Y LAS INSTITUCIONES    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5740).update(active_part: 'LA PREVISORA SA -INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2067).update(active_part: 'LA PREVISORA SA -HOSPITAL PIO X DE TEBAIDA QUINDIO    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20412).update(active_part: 'MONTES VELASQUEZ ROCIO DEL CARMEN',document_active_part: '43071970',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5425).update(active_part: 'LA PREVISORA SA -INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3033).update(active_part: 'LA PREVISORA SA -INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2992).update(active_part: 'LA PREVISORA SA -EMPRESAS MUNICIPALES DE CALI EMCALI    ',document_active_part: '8600024002',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20411).update(active_part: 'PACHECO RESTREPO VICTOR HUGO',document_active_part: '71589221',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20414).update(active_part: 'PEREA CORDOBA EMILIANO',document_active_part: '3480470',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1289).update(active_part: 'ETB  S.A. E.S.P    ',document_active_part: '8999991158',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20416).update(active_part: 'DISTRITO TURIST CULTURAL E HISTORICO DE SANTA MARTA    ',document_active_part: '8917800094',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20475).update(active_part: 'LONDONO RESTREPO HECTOR DE JESUS',document_active_part: '70554350',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20507).update(active_part: 'GARCIA DUQUE JUAN ALBERTO',document_active_part: '70165702',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20413).update(active_part: 'GARCES ESTRADA JUAN CARLOS',document_active_part: '71649158',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20415).update(active_part: 'LEON VANEGAS MARITZA DEL ROSARIO',document_active_part: '15056615',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5368).update(active_part: 'GARCIA AGUDELO RAUL',document_active_part: '890985703',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5421).update(active_part: 'ALIANZA COOPERATIVA EN SALUD    ',document_active_part: '8301422838',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5685).update(active_part: 'E.S.E. HOSPITAL SAN JUAN DE DIOS SANTAFE DE ANT    ',document_active_part: '8909822641',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11544).update(active_part: 'ESE HOSPITAL MATERNO INFANTIL DE SOLEDAD    ',document_active_part: '8020130235',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1626).update(active_part: 'DIEZ PALMA JUAN CARLOS',document_active_part: '79533172',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4546).update(active_part: 'E.S.E. HOSPITAL UNIVERSITARIO DE SANTANDER    ',document_active_part: '9000060374',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2996).update(active_part: 'MUNICIPIO DE TULUA    ',document_active_part: '8919002721',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3309).update(active_part: 'EMPRESAS MUNICIPALES DE CALI EMCALI    ',document_active_part: '8903990034',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5688).update(active_part: 'E.S.E. HOSPITAL MARCO FIDEL SUAREZ    ',document_active_part: '8909857035',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20471).update(active_part: 'INSTITUTO DE DEPORTES Y RECREACION DE TURBO    ',document_active_part: '8909853594',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4139).update(active_part: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PITALITO    ',document_active_part: '8911801342',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4084).update(active_part: 'EMPRESA SOCIAL DEL ESTADO CARMEN EMILIA OSPINA    ',document_active_part: '8130052657',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4611).update(active_part: 'E.S.E. HOSPITAL UNIVERSITARIO DE SANTANDER    ',document_active_part: '9000060374',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3346).update(active_part: 'MUNICIPIO DE SANTIAGO DE CALI    ',document_active_part: '8903990113',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5863).update(active_part: 'E.S.E. HOSPITAL EL SAGRADO CORAZON DE BRICENO    ',document_active_part: '8000443203',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5743).update(active_part: 'E.S.E. SANTA GERTRUDIS ENVIGADO    ',document_active_part: '9001257593',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5635).update(active_part: 'SOCIEDAD N.S.D.R. S.A.    ',document_active_part: '8050234231',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5402).update(active_part: 'E.S.E. HOSPITAL CESAR URIBE PIEDRAHITA CAUCASIA    ',document_active_part: '8909807571',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4177).update(active_part: 'E.S.E. HOSPITAL UNIVERSITARIO HERNANDO MONCALEANO PERDOMO    ',document_active_part: '8911802680',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2543).update(active_part: 'EMPRESA SOCIAL DEL ESTADO SALUD PEREIRA    ',document_active_part: '8160050035',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4259).update(active_part: 'HOSPITAL SAN RAFAEL DE TUNJA    ',document_active_part: '8918002310',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4292).update(active_part: 'HOSPITAL SAN RAFAEL DE TUNJA    ',document_active_part: '8918002310',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3366).update(active_part: 'CORPORACION AUTONOMA REGIONAL DEL VALLE DEL CAUCA C.V.C    ',document_active_part: '8903990027',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5114).update(active_part: 'HOSPITAL FEDERICO LLERAS ACOSTA E.S.E.    ',document_active_part: '8907068339',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2631).update(active_part: 'EMPRESA SOCIAL DEL ESTADO SALUD PEREIRA    ',document_active_part: '8160050035',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2360).update(active_part: 'COMFAMILIAR RISARALDA    ',document_active_part: '8914800001',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4291).update(active_part: 'HOSPITAL SAN RAFAEL DE TUNJA    ',document_active_part: '8918002310',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1657).update(active_part: 'HOSPITAL MEISSEN II NIVEL E.S.E.    ',document_active_part: '8002200117',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2855).update(active_part: 'MUNICIPIO DE SANTIAGO DE CALI    ',document_active_part: '8903990113',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3016).update(active_part: 'HOSPITAL SAN RAFAEL E.S.E. EL CERRITO    ',document_active_part: '8913801032',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5834).update(active_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8002155465',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3507).update(active_part: 'HOSPITAL PIO XII DE ARGELIA    ',document_active_part: '8919011015',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3646).update(active_part: 'CLINICA SANTA SOFIA DEL PACIFICO LTDA.    ',document_active_part: '9002289893',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3263).update(active_part: 'CORPORACION AUTONOMA REGIONAL DEL VALLE DEL CAUCA C.V.C    ',document_active_part: '8903990027',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4009).update(active_part: 'CLINICA CARTAGENA DEL MAR S.A.S.    ',document_active_part: '8060084391',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5867).update(active_part: 'IPS UNIVERSITARIA SERVICIOS DE SALUD UNIVERSIDAD DE ANT.    ',document_active_part: '8110161928',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4211).update(active_part: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE PITALITO    ',document_active_part: '8911801342',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4149).update(active_part: 'ELECTRIFICADORA DEL HUILA S.A. E.S.P.    ',document_active_part: '8911800011',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2216).update(active_part: 'EMPRESA SOCIAL DEL ESTADO PASTO SALUD E.S.E.    ',document_active_part: '9000911439',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2230).update(active_part: 'CENTRALES ELECTRICAS DE NARINO S.A. ESP    ',document_active_part: '8912002008',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2269).update(active_part: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC    ',document_active_part: '8002155465',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1180).update(active_part: 'CLINICA SANTA MARIA SAS    ',document_active_part: '800183943-7',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1742).update(active_part: 'ORDEN HOSPITALARIA SAN JUAN DE DIOS    ',document_active_part: '8600190147',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2064).update(active_part: 'HOSPITAL PIO X DE TEBAIDA QUINDIO    ',document_active_part: '8900009051',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4626).update(active_part: 'E.S.E. HOSPITAL UNIVERSITARIO DE SANTANDER    ',document_active_part: '9000060374',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
