class Al01 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(6059).update(id: 6059,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6076).update(id: 6076,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6249).update(id: 6249,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6295).update(id: 6295,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6297).update(id: 6297,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6303).update(id: 6303,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6310).update(id: 6310,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6457).update(id: 6457,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6499).update(id: 6499,link_type: 'DEMANDADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6507).update(id: 6507,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6637).update(id: 6637,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6658).update(id: 6658,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6852).update(id: 6852,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7032).update(id: 7032,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7112).update(id: 7112,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7125).update(id: 7125,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7166).update(id: 7166,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7381).update(id: 7381,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7447).update(id: 7447,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7477).update(id: 7477,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7634).update(id: 7634,link_type: 'DEMANDADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7694).update(id: 7694,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7695).update(id: 7695,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7772).update(id: 7772,link_type: 'DEMANDADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7800).update(id: 7800,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7866).update(id: 7866,link_type: 'DEMANDADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7877).update(id: 7877,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7920).update(id: 7920,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7940).update(id: 7940,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8052).update(id: 8052,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8160).update(id: 8160,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8162).update(id: 8162,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8329).update(id: 8329,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8370).update(id: 8370,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8458).update(id: 8458,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8577).update(id: 8577,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8794).update(id: 8794,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8908).update(id: 8908,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8917).update(id: 8917,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9083).update(id: 9083,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9159).update(id: 9159,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9329).update(id: 9329,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9354).update(id: 9354,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9781).update(id: 9781,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9813).update(id: 9813,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9857).update(id: 9857,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9858).update(id: 9858,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9881).update(id: 9881,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10015).update(id: 10015,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16478).update(id: 16478,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17176).update(id: 17176,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20462).update(id: 20462,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,link_type: 'LLAMADA EN GARANTIA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21149).update(id: 21149,link_type: 'DEMANDADO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20382).update(id: 20382,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20400).update(id: 20400,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20409).update(id: 20409,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20635).update(id: 20635,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20644).update(id: 20644,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20645).update(id: 20645,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20646).update(id: 20646,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20647).update(id: 20647,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20648).update(id: 20648,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20649).update(id: 20649,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20650).update(id: 20650,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20651).update(id: 20651,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20652).update(id: 20652,link_type: 'TERCERO CIVILMENTE RESPONSABLE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
