class Aleja16 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,office_name: 'PENDIENTE')
    puts TypeProcess.find(18914).update(id: 18914,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18898).update(id: 18898,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18714).update(id: 18714,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18666).update(id: 18666,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18662).update(id: 18662,office_name: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(18556).update(id: 18556,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18555).update(id: 18555,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA')
    puts TypeProcess.find(18553).update(id: 18553,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18552).update(id: 18552,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18551).update(id: 18551,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18238).update(id: 18238,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18237).update(id: 18237,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18236).update(id: 18236,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18235).update(id: 18235,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18078).update(id: 18078,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA')
    puts TypeProcess.find(17866).update(id: 17866,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17642).update(id: 17642,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17641).update(id: 17641,office_name: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(14900).update(id: 14900,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA')
    puts TypeProcess.find(9889).update(id: 9889,office_name: 'JUZGADO 035 ADMINISTRATIVO DE LA SECCION TERCERA DE BOGOTA')
    puts TypeProcess.find(9722).update(id: 9722,office_name: 'PENDIENTE')
    puts TypeProcess.find(9515).update(id: 9515,office_name: 'PENDIENTE')
    puts TypeProcess.find(9395).update(id: 9395,office_name: 'JUZGADO 014 LABORAL DE BOGOTA')
    puts TypeProcess.find(8805).update(id: 8805,office_name: 'JUZGADO 004 ADMINISTRATIVO DE VALLEDUPAR')
    puts TypeProcess.find(8116).update(id: 8116,office_name: 'PENDIENTE')
    puts TypeProcess.find(7996).update(id: 7996,office_name: 'PENDIENTE')
    puts TypeProcess.find(7970).update(id: 7970,office_name: 'JUZGADO 009 ADMINISTRATIVO DE BARRANQUILLA')
    puts TypeProcess.find(7876).update(id: 7876,office_name: 'PENDIENTE')
    puts TypeProcess.find(7789).update(id: 7789,office_name: 'JUZGADO 013 CIVIL MUNICIPAL DE BARRANQUILLA')
    puts TypeProcess.find(7311).update(id: 7311,office_name: 'PENDIENTE')
    puts TypeProcess.find(7222).update(id: 7222,office_name: 'PENDIENTE')
    puts TypeProcess.find(7199).update(id: 7199,office_name: 'JUZGADO 007 ADMINISTRATIVO DE BARRANQUILLA')
    puts TypeProcess.find(7162).update(id: 7162,office_name: 'PENDIENTE')
    puts TypeProcess.find(7058).update(id: 7058,office_name: 'PENDIENTE')
    puts TypeProcess.find(6751).update(id: 6751,office_name: 'PENDIENTE')
    puts TypeProcess.find(6514).update(id: 6514,office_name: 'PENDIENTE')
    puts TypeProcess.find(286).update(id: 286,office_name: 'PENDIENTE')
    puts TypeProcess.find(19750).update(id: 19750,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(19735).update(id: 19735,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(19287).update(id: 19287,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17480).update(id: 17480,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17441).update(id: 17441,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17218).update(id: 17218,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17146).update(id: 17146,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17000).update(id: 17000,office_name: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(16946).update(id: 16946,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16906).update(id: 16906,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16832).update(id: 16832,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16759).update(id: 16759,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16710).update(id: 16710,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16700).update(id: 16700,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16514).update(id: 16514,office_name: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(16510).update(id: 16510,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16410).update(id: 16410,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16367).update(id: 16367,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16359).update(id: 16359,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16262).update(id: 16262,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16254).update(id: 16254,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15354).update(id: 15354,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15339).update(id: 15339,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15011).update(id: 15011,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(14987).update(id: 14987,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14986).update(id: 14986,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14985).update(id: 14985,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14983).update(id: 14983,office_name: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14982).update(id: 14982,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14981).update(id: 14981,office_name: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14980).update(id: 14980,office_name: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14977).update(id: 14977,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14976).update(id: 14976,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14973).update(id: 14973,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14972).update(id: 14972,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14936).update(id: 14936,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14821).update(id: 14821,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(14791).update(id: 14791,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14790).update(id: 14790,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14788).update(id: 14788,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14663).update(id: 14663,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13938).update(id: 13938,office_name: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(13912).update(id: 13912,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13907).update(id: 13907,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13906).update(id: 13906,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13860).update(id: 13860,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13807).update(id: 13807,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13806).update(id: 13806,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13799).update(id: 13799,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13798).update(id: 13798,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13797).update(id: 13797,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13796).update(id: 13796,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13795).update(id: 13795,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13794).update(id: 13794,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13793).update(id: 13793,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13777).update(id: 13777,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13716).update(id: 13716,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13702).update(id: 13702,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13701).update(id: 13701,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13696).update(id: 13696,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13636).update(id: 13636,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13629).update(id: 13629,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13617).update(id: 13617,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13616).update(id: 13616,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13605).update(id: 13605,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13587).update(id: 13587,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13569).update(id: 13569,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13561).update(id: 13561,office_name: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13556).update(id: 13556,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13534).update(id: 13534,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13530).update(id: 13530,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13524).update(id: 13524,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13523).update(id: 13523,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13504).update(id: 13504,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13503).update(id: 13503,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13500).update(id: 13500,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13490).update(id: 13490,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13423).update(id: 13423,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13422).update(id: 13422,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13412).update(id: 13412,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13389).update(id: 13389,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13387).update(id: 13387,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13386).update(id: 13386,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13385).update(id: 13385,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13381).update(id: 13381,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13378).update(id: 13378,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13375).update(id: 13375,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13374).update(id: 13374,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13370).update(id: 13370,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13337).update(id: 13337,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13333).update(id: 13333,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13304).update(id: 13304,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13296).update(id: 13296,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13289).update(id: 13289,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13280).update(id: 13280,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13256).update(id: 13256,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13225).update(id: 13225,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13222).update(id: 13222,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13202).update(id: 13202,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13191).update(id: 13191,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13168).update(id: 13168,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13134).update(id: 13134,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13133).update(id: 13133,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13129).update(id: 13129,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13120).update(id: 13120,office_name: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13108).update(id: 13108,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13107).update(id: 13107,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13106).update(id: 13106,office_name: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(13101).update(id: 13101,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13097).update(id: 13097,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13096).update(id: 13096,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13064).update(id: 13064,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13052).update(id: 13052,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(12988).update(id: 12988,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12932).update(id: 12932,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(12834).update(id: 12834,office_name: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(12671).update(id: 12671,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(12429).update(id: 12429,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12424).update(id: 12424,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12421).update(id: 12421,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12417).update(id: 12417,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12401).update(id: 12401,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12399).update(id: 12399,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12396).update(id: 12396,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12392).update(id: 12392,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12391).update(id: 12391,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12388).update(id: 12388,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12384).update(id: 12384,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12375).update(id: 12375,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12373).update(id: 12373,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12363).update(id: 12363,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12362).update(id: 12362,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12359).update(id: 12359,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12358).update(id: 12358,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12357).update(id: 12357,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12356).update(id: 12356,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12353).update(id: 12353,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12349).update(id: 12349,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12343).update(id: 12343,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12342).update(id: 12342,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12329).update(id: 12329,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12328).update(id: 12328,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10729).update(id: 10729,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10706).update(id: 10706,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10693).update(id: 10693,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10689).update(id: 10689,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10664).update(id: 10664,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10612).update(id: 10612,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10569).update(id: 10569,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10518).update(id: 10518,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10516).update(id: 10516,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10510).update(id: 10510,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10506).update(id: 10506,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10505).update(id: 10505,office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10504).update(id: 10504,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10503).update(id: 10503,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10502).update(id: 10502,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10501).update(id: 10501,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10500).update(id: 10500,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10499).update(id: 10499,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10494).update(id: 10494,office_name: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10230).update(id: 10230,office_name: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(9609).update(id: 9609,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9602).update(id: 9602,office_name: 'JUZGADO 003 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9600).update(id: 9600,office_name: 'JUZGADO 002 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9598).update(id: 9598,office_name: 'JUZGADO 002 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9570).update(id: 9570,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9502).update(id: 9502,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9474).update(id: 9474,office_name: 'JUZGADO 003 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9448).update(id: 9448,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(9438).update(id: 9438,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  CAQUETA')
    puts TypeProcess.find(9437).update(id: 9437,office_name: 'JUZGADO 003 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9436).update(id: 9436,office_name: 'JUZGADO 003 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9435).update(id: 9435,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  CAQUETA')
    puts TypeProcess.find(9433).update(id: 9433,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(9398).update(id: 9398,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9347).update(id: 9347,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(9262).update(id: 9262,office_name: 'JUZGADO 009 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9244).update(id: 9244,office_name: 'JUZGADO 036 CIVIL DEL CIRCUITO DE BOGOTA')
    puts TypeProcess.find(9240).update(id: 9240,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9236).update(id: 9236,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9203).update(id: 9203,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9199).update(id: 9199,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9195).update(id: 9195,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9191).update(id: 9191,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9190).update(id: 9190,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9182).update(id: 9182,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(9181).update(id: 9181,office_name: 'PENDIENTE')
    puts TypeProcess.find(9172).update(id: 9172,office_name: 'JUZGADO PENDIENTE CIVIL DEL CIRCUITO DE FLORENCIA')
    puts TypeProcess.find(9170).update(id: 9170,office_name: 'JUZGADO 005 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9111).update(id: 9111,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9096).update(id: 9096,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(9033).update(id: 9033,office_name: 'JUZGADO 002 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(9010).update(id: 9010,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8846).update(id: 8846,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8837).update(id: 8837,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8683).update(id: 8683,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(8682).update(id: 8682,office_name: 'PENDIENTE')
    puts TypeProcess.find(8660).update(id: 8660,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(8549).update(id: 8549,office_name: 'JUZGADO 003 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8375).update(id: 8375,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(8362).update(id: 8362,office_name: 'JUZGADO 041 CIVIL DEL CIRCUITO DE BOGOTA')
    puts TypeProcess.find(8350).update(id: 8350,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(8336).update(id: 8336,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8332).update(id: 8332,office_name: 'JUZGADO 002 LABORAL DE FLORENCIA')
    puts TypeProcess.find(8286).update(id: 8286,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(8285).update(id: 8285,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(8151).update(id: 8151,office_name: 'PENDIENTE')
    puts TypeProcess.find(8117).update(id: 8117,office_name: 'JUZGADO 006 CIVIL DEL CIRCUITO DE BOGOTA')
    puts TypeProcess.find(7960).update(id: 7960,office_name: 'PENDIENTE')
    puts TypeProcess.find(7930).update(id: 7930,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7894).update(id: 7894,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7893).update(id: 7893,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7890).update(id: 7890,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7784).update(id: 7784,office_name: 'JUZGADO 002 ADMINISTRATIVO DE ARAUCA')
    puts TypeProcess.find(7688).update(id: 7688,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7687).update(id: 7687,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7643).update(id: 7643,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7642).update(id: 7642,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7641).update(id: 7641,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7640).update(id: 7640,office_name: 'JUZGADO 003 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7639).update(id: 7639,office_name: 'PENDIENTE')
    puts TypeProcess.find(7588).update(id: 7588,office_name: 'PENDIENTE')
    puts TypeProcess.find(7425).update(id: 7425,office_name: 'JUZGADO 004 CIVIL DEL CIRCUITO DE BOGOTA')
    puts TypeProcess.find(7181).update(id: 7181,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(7142).update(id: 7142,office_name: 'JUZGADO 005 ADMINISTRATIVO DE VILLAVICENCIO')
    puts TypeProcess.find(7109).update(id: 7109,office_name: 'PENDIENTE')
    puts TypeProcess.find(7031).update(id: 7031,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6953).update(id: 6953,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6828).update(id: 6828,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6827).update(id: 6827,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6801).update(id: 6801,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  CAQUETA')
    puts TypeProcess.find(6715).update(id: 6715,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(6607).update(id: 6607,office_name: 'JUZGADO 005 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6555).update(id: 6555,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6439).update(id: 6439,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6438).update(id: 6438,office_name: 'JUZGADO 004 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6388).update(id: 6388,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6284).update(id: 6284,office_name: 'PENDIENTE')
    puts TypeProcess.find(6283).update(id: 6283,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6282).update(id: 6282,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6270).update(id: 6270,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6251).update(id: 6251,office_name: 'JUZGADO 002 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6204).update(id: 6204,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6116).update(id: 6116,office_name: 'JUZGADO 003 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6102).update(id: 6102,office_name: 'JUZGADO 002 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6090).update(id: 6090,office_name: 'JUZGADO 003 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(6087).update(id: 6087,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6058).update(id: 6058,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6054).update(id: 6054,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6053).update(id: 6053,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6052).update(id: 6052,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(6051).update(id: 6051,office_name: 'JUZGADO 004 ADMINISTRATIVO DE FLORENCIA')
    puts TypeProcess.find(5223).update(id: 5223,office_name: 'DESPACHO PENDIENTE DE LA SALA DE CASACION LABORAL DE LA CORTE SUPREMA DE JUSTICIA   ')
    puts TypeProcess.find(5193).update(id: 5193,office_name: 'JUZGADO 008 ADMINISTRATIVO DE IBAGUE')
    puts TypeProcess.find(5122).update(id: 5122,office_name: 'DESPACHO PENDIENTE DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE IBAGUE ')
    puts TypeProcess.find(5093).update(id: 5093,office_name: 'DESPACHO PENDIENTE DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE IBAGUE ')
    puts TypeProcess.find(5037).update(id: 5037,office_name: 'DESPACHO PENDIENTE DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE MANIZALES ')
    puts TypeProcess.find(4207).update(id: 4207,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4201).update(id: 4201,office_name: 'JUZGADO 003 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4199).update(id: 4199,office_name: 'JUZGADO 005 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4198).update(id: 4198,office_name: 'JUZGADO 002 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4197).update(id: 4197,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4196).update(id: 4196,office_name: 'JUZGADO 006 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4192).update(id: 4192,office_name: 'JUZGADO 003 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4183).update(id: 4183,office_name: 'JUZGADO 006 CIVIL MUNICIPAL DE NEIVA')
    puts TypeProcess.find(4179).update(id: 4179,office_name: 'JUZGADO 004 ADMINISTRATIVO DE NEIVA')
    puts TypeProcess.find(4178).update(id: 4178,office_name: 'JUZGADO 005 CIVIL DEL CIRCUITO DE NEIVA')
    puts TypeProcess.find(4161).update(id: 4161,office_name: 'JUZGADO PENDIENTE PROMISCUO MUNICIPAL DE IQUIRA')
    puts TypeProcess.find(4157).update(id: 4157,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(4155).update(id: 4155,office_name: 'JUZGADO 002 CIVIL DEL CIRCUITO DE NEIVA')
    puts TypeProcess.find(4138).update(id: 4138,office_name: 'JUZGADO 002 LABORAL DE NEIVA')
    puts TypeProcess.find(4121).update(id: 4121,office_name: 'JUZGADO 003 CIVIL DEL CIRCUITO DE NEIVA')
    puts TypeProcess.find(4119).update(id: 4119,office_name: 'JUZGADO PENDIENTE CIVIL MUNICIPAL DE GARZON')
    puts TypeProcess.find(4103).update(id: 4103,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(4096).update(id: 4096,office_name: 'JUZGADO PENDIENTE PROMISCUO MUNICIPAL DE PALERMO')
    puts TypeProcess.find(4082).update(id: 4082,office_name: 'JUZGADO PENDIENTE PROMISCUO MUNICIPAL DE GUADALUPE')
    puts TypeProcess.find(4075).update(id: 4075,office_name: 'JUZGADO 004 CIVIL MUNICIPAL DE NEIVA')
    puts TypeProcess.find(4073).update(id: 4073,office_name: 'JUZGADO PENDIENTE PROMISCUO MUNICIPAL DE IQUIRA')
    puts TypeProcess.find(4072).update(id: 4072,office_name: 'JUZGADO PENDIENTE PROMISCUO MUNICIPAL DE AIPE')
    puts TypeProcess.find(4067).update(id: 4067,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  HUILA')
    puts TypeProcess.find(2548).update(id: 2548,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2544).update(id: 2544,office_name: 'JUZGADO 002 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2531).update(id: 2531,office_name: 'JUZGADO 007 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2530).update(id: 2530,office_name: 'DESPACHO 003  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2520).update(id: 2520,office_name: 'JUZGADO 002 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2515).update(id: 2515,office_name: 'JUZGADO PENDIENTE CIVIL DEL CIRCUITO DE PEREIRA')
    puts TypeProcess.find(2513).update(id: 2513,office_name: 'DESPACHO 002  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2507).update(id: 2507,office_name: 'JUZGADO 007 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2504).update(id: 2504,office_name: 'JUZGADO 002 ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2496).update(id: 2496,office_name: 'JUZGADO 003 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2490).update(id: 2490,office_name: 'DESPACHO 002  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2474).update(id: 2474,office_name: 'JUZGADO 002 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2469).update(id: 2469,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2466).update(id: 2466,office_name: 'JUZGADO 002 ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2464).update(id: 2464,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2456).update(id: 2456,office_name: 'JUZGADO 006 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2452).update(id: 2452,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2442).update(id: 2442,office_name: 'JUZGADO 002 ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2428).update(id: 2428,office_name: 'JUZGADO 002 ADMINISTRATIVO DE CARTAGO')
    puts TypeProcess.find(2423).update(id: 2423,office_name: 'JUZGADO PENDIENTE CIVIL DEL CIRCUITO DE PEREIRA')
    puts TypeProcess.find(2421).update(id: 2421,office_name: 'JUZGADO 006 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2418).update(id: 2418,office_name: 'DESPACHO 002  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2415).update(id: 2415,office_name: 'DESPACHO 002  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2408).update(id: 2408,office_name: 'DESPACHO PENDIENTE  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(2383).update(id: 2383,office_name: 'JUZGADO 007 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(2372).update(id: 2372,office_name: 'JUZGADO 006 ADMINISTRATIVO DE PASTO')
    puts TypeProcess.find(390).update(id: 390,office_name: 'DESPACHO 002  DEL TRIBUNAL ADMINISTRATIVO DE  RISARALDA')
    puts TypeProcess.find(290).update(id: 290,office_name: 'JUZGADO 002 ADMINISTRATIVO DE PEREIRA')
    puts TypeProcess.find(122).update(id: 122,office_name: 'JUZGADO 005 CIVIL MUNICIPAL DE PEREIRA')
    puts TypeProcess.find(95).update(id: 95,office_name: 'JUZGADO PENDIENTE ADMINISTRATIVO DE PEREIRA')
  end
end
