class Aleja04 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9918).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9899).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9740).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9545).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9296).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9266).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9175).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9031).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9027).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9021).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8883).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8816).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8727).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8471).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8422).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8268).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8267).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7961).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7944).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7739).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7714).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7665).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7624).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7597).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7579).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7327).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7271).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7127).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6985).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6984).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6904).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6542).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6511).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6475).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6423).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6418).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6360).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6267).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6153).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6077).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6044).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1852).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1847).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1843).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1775).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1712).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1694).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1661).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1655).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1652).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1624).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1609).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1602).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1596).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1538).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1458).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1438).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1428).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1424).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1423).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1414).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1392).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1326).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1312).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(102).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1834).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1726).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1717).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1672).update(case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1591).update(case_state: 'TERMINADO',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
