class Aleja13 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19817).update(id: 19817,policy_taker: 'INVERSIONES QSB SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19804).update(id: 19804,policy_taker: 'GOBERNACION DEL HUILA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19777).update(id: 19777,policy_taker: 'INVIMA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8670).update(id: 8670,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19996).update(id: 19996,policy_taker: 'TV ISLA LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19995).update(id: 19995,policy_taker: 'COMERCIALIZADORA NAVE LTDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19994).update(id: 19994,policy_taker: 'DIAN LOGISTICA TOTAL SAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19993).update(id: 19993,policy_taker: 'PETROTECH DE COLOMBIA SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19992).update(id: 19992,policy_taker: 'PETROTECH DE COLOMBIA SAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19991).update(id: 19991,policy_taker: ' CITITEX SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19990).update(id: 19990,policy_taker: 'TC UAP SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19989).update(id: 19989,policy_taker: 'PETROTECH DE COLOMBIA SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19988).update(id: 19988,policy_taker: '57421 SOTRAEX 10324120164001 AA 1658',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19987).update(id: 19987,policy_taker: 'IGM INGENIERIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19986).update(id: 19986,policy_taker: 'PETROTECH DE COLOMBIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19985).update(id: 19985,policy_taker: ' CARGO FMA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19984).update(id: 19984,policy_taker: ' CESCOL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19983).update(id: 19983,policy_taker: 'CONCRETOS DEL CARIBE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19982).update(id: 19982,policy_taker: ' VIDRIOSUR COLOMBIA SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19981).update(id: 19981,policy_taker: ' T C UAP SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19980).update(id: 19980,policy_taker: '135235419435 0000835 TC UAP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19978).update(id: 19978,policy_taker: ' VIDRIOS COLOMBIA SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19975).update(id: 19975,policy_taker: 'VIDRIOS DE LA SABANA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19973).update(id: 19973,policy_taker: 'MUNICIPIO DE DIBULLA LA GUAJIRA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19972).update(id: 19972,policy_taker: ' CAICEDONIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19966).update(id: 19966,policy_taker: 'T Y C UAP SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19965).update(id: 19965,policy_taker: ' CESCOL DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19963).update(id: 19963,policy_taker: 'CONTRATO DE OBRA MO 1064 DE 2013 REDES ELECRTICS DPTO DE CORDOBA  ASOMOR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19962).update(id: 19962,policy_taker: 'ASOCIACION DE MUNICIPIOS DEL GOLFO DE MORROSQUILLO ASOMOR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19961).update(id: 19961,policy_taker: 'SENA Y UNIVERSIDAD AUTONOMA DEL CARIBE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19958).update(id: 19958,policy_taker: 'MUNICIPIO PUERTO LIBERTADOR CORDOBA FONADE CONTRATO 2131644',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19957).update(id: 19957,policy_taker: 'MUNICIPIO DE MADRID CUNDINAMARCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19956).update(id: 19956,policy_taker: 'AERONAUTICA CIVIL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19955).update(id: 19955,policy_taker: ' GOBERNACION DE BOYACA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19954).update(id: 19954,policy_taker: ' DPTO DEL HUILA FONADE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19953).update(id: 19953,policy_taker: 'EMPRESA SOCIAL DEL ESTADO HOSPITAL DE GIRARDOT DUMIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19952).update(id: 19952,policy_taker: 'DIAN TC UAP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19950).update(id: 19950,policy_taker: 'INSTITUTO PARA LA RECREACION Y EL DEPORTE DE DUITAMA CTO 001 2016',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19949).update(id: 19949,policy_taker: 'CONSORCIO COLEGIOS DE BOLIVAR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19947).update(id: 19947,policy_taker: 'CONVENIO NO 013 DE 2015 MUNICIPIO DE MADRID',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19946).update(id: 19946,policy_taker: 'REQUERIMIENTO DIAN ACTO ADMINISTRATIVO 163 DE ENERO 2018 RAD 0011259',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19941).update(id: 19941,policy_taker: 'ALCALDIA MAYOR DE BOGOTA CTO NO 058 2017',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19940).update(id: 19940,policy_taker: 'COMANDO GENERAL DE LAS FUERZAS MILITARES RADICADO 03874 TRATA AGUAS RESIDUALES ASPC 29',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19939).update(id: 19939,policy_taker: 'AGENCIA DE ADUANAS SOCIEDAD DE TRAMITESLIQUIDACION OFICIAL DE REVISION 1623 DE 2017 RA 2014 2017 516',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19938).update(id: 19938,policy_taker: 'AGENCIA DE ADUANAS SOCIEDAD DE TRALIQUIDACION OFICIAL DE REVISION 1650 DEL 13 DE SEPTIEMBRE DE 2017 ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19937).update(id: 19937,policy_taker: 'CESCOL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19936).update(id: 19936,policy_taker: 'INTEGRAL DRILLING COMUNICADO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19935).update(id: 19935,policy_taker: 'UNIVERSIDAD NUEVA GRANADA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19934).update(id: 19934,policy_taker: 'MUNICIPIO DE AYAPEL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19933).update(id: 19933,policy_taker: 'UNINAL CONTRATO NO 2013 02 0812',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19928).update(id: 19928,policy_taker: 'ESE HOSPITAL DEL CARMEN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19926).update(id: 19926,policy_taker: 'AGENCIA LOGISTICA DE LAS FUERZAS MILITARES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19925).update(id: 19925,policy_taker: 'GOBERNACION DEL CESAR HIPODROMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19924).update(id: 19924,policy_taker: 'GOBERNACION DEL META',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19922).update(id: 19922,policy_taker: 'CONTRATO 038 DISAN ARC HONAM 2017 HOSPITAL NAVAL BAHIA MALAGA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19921).update(id: 19921,policy_taker: 'RADICADO 51009 DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19920).update(id: 19920,policy_taker: 'RADICADO 51014 DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19919).update(id: 19919,policy_taker: 'RADICADO 51012 DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19918).update(id: 19918,policy_taker: 'RADICADO 51062 DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19917).update(id: 19917,policy_taker: 'ALCALDIA DE BARRANCAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19915).update(id: 19915,policy_taker: 'MUNCIPIO DE GUAMAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19914).update(id: 19914,policy_taker: 'DEPARTAMENTO DE CORDOBA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19913).update(id: 19913,policy_taker: 'EMPRESA MUNICIPAL DE IPIALES GOBERNACION DE NARINO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19910).update(id: 19910,policy_taker: 'SOCIEDAD TECNICA DE LA INDUSTRIA PETROLERA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19907).update(id: 19907,policy_taker: 'MUNICIPIO DE CHIPAQUE CUNDINAMARCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19906).update(id: 19906,policy_taker: 'HOSPITAL FRANCISCO VALDERRAMA SOAT TURBO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19904).update(id: 19904,policy_taker: 'MUNICIPIO DE QUEBRADANEGRA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19902).update(id: 19902,policy_taker: 'DIAN GESTION ADMINISTRATIVA Y FINANCIERA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19897).update(id: 19897,policy_taker: 'FONADE LA RIVIERA HUILA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19896).update(id: 19896,policy_taker: 'MUNICIPIO DE PATIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19892).update(id: 19892,policy_taker: 'SOCIEDAD AEROPORTUARIA DE LA COSTA AEROCIVIL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19891).update(id: 19891,policy_taker: 'FONTUR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19889).update(id: 19889,policy_taker: 'TRANSPORTES LOGISPETROL DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19886).update(id: 19886,policy_taker: 'TC TRADING GROUP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19885).update(id: 19885,policy_taker: 'EMPRESA DISTRIBUIDORA DE SUMINISTROS LA HACIENDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19881).update(id: 19881,policy_taker: 'DIAN CITITEX',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19876).update(id: 19876,policy_taker: 'EMPRESA DE SERVICIOS PUBLICOS DE TOCANCIPA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19875).update(id: 19875,policy_taker: 'DIAN JV TRADING GROUP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19868).update(id: 19868,policy_taker: 'CONSORCIO INTERLOMAS PROVIDENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19867).update(id: 19867,policy_taker: 'VICTORIA CARGO TRANSPORTES SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19865).update(id: 19865,policy_taker: 'CITITEX UAP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19864).update(id: 19864,policy_taker: 'JV TRADING GROUP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19863).update(id: 19863,policy_taker: 'JV TRADING GROUP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19862).update(id: 19862,policy_taker: 'TC UAP CITITEX',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19861).update(id: 19861,policy_taker: 'SUPERINTENDENCIA DE NOTARIADO Y REGISTRO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19860).update(id: 19860,policy_taker: 'COMISSION NACIONAL DE TELEVISION TV PAU',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19854).update(id: 19854,policy_taker: 'GOBERNACION DEL CESAR',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19852).update(id: 19852,policy_taker: 'ORGANIZACION JUVENIL JUCAPROY',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19851).update(id: 19851,policy_taker: 'SERLOGISTICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19850).update(id: 19850,policy_taker: 'DIAN CARGO FMA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19849).update(id: 19849,policy_taker: 'EJERCITO NACIONAL JEFATURA DE INGENIEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19848).update(id: 19848,policy_taker: 'GOBERNACION DE CUNDINAMARCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19847).update(id: 19847,policy_taker: 'DIAN CITITEX',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19846).update(id: 19846,policy_taker: 'GHC TRANSPORTES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19845).update(id: 19845,policy_taker: 'MUNICIPIO DE BUENAVENTURA INVIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19844).update(id: 19844,policy_taker: 'DIAN TC UAP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19843).update(id: 19843,policy_taker: 'GOBERNACION DEL HUILA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19842).update(id: 19842,policy_taker: 'CONSORCIO HIDRICO Q YS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19841).update(id: 19841,policy_taker: 'FONSECON SAN MARCOS SUCRE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19840).update(id: 19840,policy_taker: 'MUNICIPIO DE TURBO PUERTO COLOMBIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19838).update(id: 19838,policy_taker: 'FONSECON MUNICIPIO DE TOCANCIPA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19834).update(id: 19834,policy_taker: 'FONADE CONTEIN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19832).update(id: 19832,policy_taker: 'ALCALDIA MUNICIPAL DE PROVIDENCIA Y SANTA CATALINA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19827).update(id: 19827,policy_taker: 'INTEGRSL DE CARGA CARGRANEL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19825).update(id: 19825,policy_taker: 'MUNICIPIO DE OVEJAS SUCRE FONSECON',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19824).update(id: 19824,policy_taker: 'MUNICIPIO DE MONTERIA FONSECON BARRIO MOGAMBO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19823).update(id: 19823,policy_taker: 'GLOBAL ANDINO DE CARGA DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19822).update(id: 19822,policy_taker: 'INTERNACIONAL DE NEGOCIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19821).update(id: 19821,policy_taker: 'INTERNACIONAL DE NEGOCIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19820).update(id: 19820,policy_taker: 'SERLOGISTICA OTM',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19815).update(id: 19815,policy_taker: 'MUNICIPIO DE CONCEPCION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19814).update(id: 19814,policy_taker: 'AGENCIA DE ADUANAS ASESOREX DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19813).update(id: 19813,policy_taker: 'SAN ROQUE ANTIOQUIA FONSECON',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19809).update(id: 19809,policy_taker: 'INPOREXPORT ASESORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19808).update(id: 19808,policy_taker: 'CONSTRUCTORA METROPOLITANO LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19806).update(id: 19806,policy_taker: 'EXXE LOGISTICA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19805).update(id: 19805,policy_taker: 'CONSTRUCCIONES CF',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19803).update(id: 19803,policy_taker: 'AGENCIA DE ADUANAS IMPOREXPORT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19802).update(id: 19802,policy_taker: 'CORPORACION AUTONOMA REGIONAL DE LOS VALLES DEL SINU',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19800).update(id: 19800,policy_taker: 'DIAN ASESORES SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19798).update(id: 19798,policy_taker: 'ICBF CONSORCIO CORDOBA TU FUTURO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19797).update(id: 19797,policy_taker: 'ECOPETROL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19795).update(id: 19795,policy_taker: 'TRANSPORTES 3T',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19791).update(id: 19791,policy_taker: 'CRISTACARGO LOGISTIC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19789).update(id: 19789,policy_taker: 'CNSROCIO ARAUCA 2010',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19788).update(id: 19788,policy_taker: 'AGENCIA DE ADUANAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19787).update(id: 19787,policy_taker: 'INGENIERIA COMERCIAL ELECTRONICA Y ELECTRICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19786).update(id: 19786,policy_taker: 'CONSTRUCTORA METROPOLITANO SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19785).update(id: 19785,policy_taker: 'CONSTRUCTORA METROPOLITANO SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19783).update(id: 19783,policy_taker: 'COMPANIA MINERA TREVISO COLOMBIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19782).update(id: 19782,policy_taker: 'MONTAJE E INGENIERIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19781).update(id: 19781,policy_taker: 'CONSTRUCTORA METROPOLITANO LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19779).update(id: 19779,policy_taker: 'UNITED LOGISTIC SERVICE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19778).update(id: 19778,policy_taker: 'INGENIERIA COLOMBIANA DE TRAZADOS INCOLTES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19776).update(id: 19776,policy_taker: 'CONSORCIO MAGDALENA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14222).update(id: 14222,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE  POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14015).update(id: 14015,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10029).update(id: 10029,policy_taker: 'MUNICIPIO DE LA VICTORIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10008).update(id: 10008,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10000).update(id: 10000,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9994).update(id: 9994,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9989).update(id: 9989,policy_taker: 'SOCIEDAD PORTUARIA REGIONAL DE BUENAVENTURA SA SPRBUN SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9984).update(id: 9984,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9929).update(id: 9929,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9928).update(id: 9928,policy_taker: 'HOSPITAL LOCAL DE CANDELARIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9914).update(id: 9914,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9909).update(id: 9909,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9863).update(id: 9863,policy_taker: 'EMCALI EICE ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9862).update(id: 9862,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE  POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9819).update(id: 9819,policy_taker: 'HOSPITAL FRANCISCO DE PAULA DE SANTANDER ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9814).update(id: 9814,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9811).update(id: 9811,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9794).update(id: 9794,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9791).update(id: 9791,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9751).update(id: 9751,policy_taker: 'OCCIDENTAL DE INVERSIONES MEDICO QUIRURGICAS SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9741).update(id: 9741,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9730).update(id: 9730,policy_taker: 'TREN DE OCCIDENTE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9726).update(id: 9726,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9719).update(id: 9719,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9714).update(id: 9714,policy_taker: 'HOSPITAL BENJAMIN BARNEY GASCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9712).update(id: 9712,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE  POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9711).update(id: 9711,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9708).update(id: 9708,policy_taker: 'UNIVERSIDAD DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9684).update(id: 9684,policy_taker: 'HOSPITAL UNIVESITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9683).update(id: 9683,policy_taker: 'FUNDACION SALUD BOSQUE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9679).update(id: 9679,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9676).update(id: 9676,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9675).update(id: 9675,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9662).update(id: 9662,policy_taker: 'JUAN CARLOS RAMIREZ CARDONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9653).update(id: 9653,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9610).update(id: 9610,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARLEARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9608).update(id: 9608,policy_taker: 'EL MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9588).update(id: 9588,policy_taker: 'RED DE SALUD DEL ORIENTE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9568).update(id: 9568,policy_taker: 'HOSPITAL BENJAMIN BARNEY GASCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9564).update(id: 9564,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9554).update(id: 9554,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9534).update(id: 9534,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9513).update(id: 9513,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9511).update(id: 9511,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9503).update(id: 9503,policy_taker: 'FUNDACION UNIVERSIDAD DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9470).update(id: 9470,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9446).update(id: 9446,policy_taker: 'HOSPITAL DE SARARE EMPRESA SOCIAL DEL ESTADO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9432).update(id: 9432,policy_taker: 'HOSPITAL SAN VICENTE DE ARAUCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9431).update(id: 9431,policy_taker: 'CLINICA LA ESTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9401).update(id: 9401,policy_taker: 'QUILISALUD ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9393).update(id: 9393,policy_taker: 'ATENCION EN SEGURIDAD SOCIAL BIENES Y SALUD ESE Y DIRECCION TERRITORIAL DE SALUD DE CALDAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9382).update(id: 9382,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9369).update(id: 9369,policy_taker: 'RED DE SALUD DEL ORIENTE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9350).update(id: 9350,policy_taker: 'RED DE SALUD DEL ORIENTE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9343).update(id: 9343,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9295).update(id: 9295,policy_taker: 'EPS CAJA DE COMPENSACION FAMILIAR COMFENALCO ANTIOQUIA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9284).update(id: 9284,policy_taker: 'HOSPITAL DEL SARARE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9278).update(id: 9278,policy_taker: 'HOSPITAL DIVINO NINO DE BUGA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9277).update(id: 9277,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9261).update(id: 9261,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9215).update(id: 9215,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9208).update(id: 9208,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9202).update(id: 9202,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9188).update(id: 9188,policy_taker: 'EMPRESA SOCIAL DEL ESTADO ESE NORTE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9183).update(id: 9183,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9169).update(id: 9169,policy_taker: 'HOSPITAL UNIVERSITARIO DEPARTAMENTAL DE NARINO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9157).update(id: 9157,policy_taker: 'FUNDACION HOSPITAL SAN PEDRO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9140).update(id: 9140,policy_taker: 'HOSPITAL JOSE RUFINO VIVAS DE DAGUA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9039).update(id: 9039,policy_taker: 'SERLOGISTICA OTM SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9028).update(id: 9028,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9023).update(id: 9023,policy_taker: 'FUNDACION UNIVERSIDAD DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9005).update(id: 9005,policy_taker: 'MUNICIPIO DE MANIZALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8999).update(id: 8999,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8988).update(id: 8988,policy_taker: 'HOSPITAL SAN JUAN DE DIOS DE CALIRED DE SALUD DEL ORIENTE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8986).update(id: 8986,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8983).update(id: 8983,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8981).update(id: 8981,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8980).update(id: 8980,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8974).update(id: 8974,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8943).update(id: 8943,policy_taker: 'HOSPITAL LOCAL DE CANDELARIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8941).update(id: 8941,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8895).update(id: 8895,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8881).update(id: 8881,policy_taker: 'EMPRESA SOCIAL DEL ESTADO NORTE 3 ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8877).update(id: 8877,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8875).update(id: 8875,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EMCALI EICE ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8841).update(id: 8841,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8835).update(id: 8835,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8824).update(id: 8824,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8821).update(id: 8821,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8798).update(id: 8798,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8797).update(id: 8797,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8796).update(id: 8796,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8789).update(id: 8789,policy_taker: 'EMPRESA SOCIAL DEL ESTADO NORTE 3 ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8773).update(id: 8773,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8769).update(id: 8769,policy_taker: 'HOSPITAL SAN JOSE DE AGUADAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8749).update(id: 8749,policy_taker: 'HOSPITAL CXAYU’CE JXUT ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8725).update(id: 8725,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8713).update(id: 8713,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8708).update(id: 8708,policy_taker: 'MUNICIPIO DE MANIZALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8684).update(id: 8684,policy_taker: 'HOSPITAL SAN VICENTE DE ARAUCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8663).update(id: 8663,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8623).update(id: 8623,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8610).update(id: 8610,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8608).update(id: 8608,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8603).update(id: 8603,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8600).update(id: 8600,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8599).update(id: 8599,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8580).update(id: 8580,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8573).update(id: 8573,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8571).update(id: 8571,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8551).update(id: 8551,policy_taker: 'HOSPITAL UNIVERSITARIO  SAN JOSE DE POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8529).update(id: 8529,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8526).update(id: 8526,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8520).update(id: 8520,policy_taker: 'COSMITET LTDA CORPORACION DE SERVICIOS MEDICOS INTERNACIONALES THEM Y CIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8514).update(id: 8514,policy_taker: 'HOSPITAL FRANCSICO DE PAULA SANTANDER',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8509).update(id: 8509,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8488).update(id: 8488,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8475).update(id: 8475,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8466).update(id: 8466,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7826).update(id: 7826,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7815).update(id: 7815,policy_taker: 'EMPRESA SOCIAL DEL ESTADO NORTE 3 ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7358).update(id: 7358,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7248).update(id: 7248,policy_taker: 'LLANERA DE AVIACION SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7007).update(id: 7007,policy_taker: 'RED DE SALUD DEL ORIENTE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6911).update(id: 6911,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6767).update(id: 6767,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EMCALI EICE ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6623).update(id: 6623,policy_taker: 'HOSPITAL DEPARTAMENTAL TOMAS URIBE URIBE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6437).update(id: 6437,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6436).update(id: 6436,policy_taker: 'INSTITUTO NACIONAL Y PENITENCIARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6428).update(id: 6428,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6419).update(id: 6419,policy_taker: 'TRANSPORTES TEV SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6416).update(id: 6416,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6413).update(id: 6413,policy_taker: 'INSTITUTO NACIONAL PENINTENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6403).update(id: 6403,policy_taker: 'HOSPITAL SAN RAFAEL DE EL CERRITO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6398).update(id: 6398,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6394).update(id: 6394,policy_taker: 'HOSPITAL SAN VICENTE DE ARAUCA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6393).update(id: 6393,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6363).update(id: 6363,policy_taker: 'ESE HOSPITAL BENJAMIN BARNEY GASCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6329).update(id: 6329,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6328).update(id: 6328,policy_taker: ' EMPRESAS MUNICIPALES DE CALI EMCALI EICE ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6287).update(id: 6287,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6285).update(id: 6285,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6281).update(id: 6281,policy_taker: 'OBEIDA CLEMENCIA TEJADA VICTORIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6277).update(id: 6277,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6272).update(id: 6272,policy_taker: 'CENTRALES ELECTRICAS DE NARINO SA ESP CEDENAR SA ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6263).update(id: 6263,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6253).update(id: 6253,policy_taker: 'HOSPITAL SAN VICENTE DE ARAUCA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6229).update(id: 6229,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6214).update(id: 6214,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6206).update(id: 6206,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6205).update(id: 6205,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6192).update(id: 6192,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6174).update(id: 6174,policy_taker: 'HOSPITAL SUSANA LOPEZ VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6170).update(id: 6170,policy_taker: 'INSTITUTO NACIONAL PENINTENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6164).update(id: 6164,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE POPAYAN ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6158).update(id: 6158,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6150).update(id: 6150,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6140).update(id: 6140,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6118).update(id: 6118,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6113).update(id: 6113,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6094).update(id: 6094,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6089).update(id: 6089,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6078).update(id: 6078,policy_taker: 'CLINICA LA ESTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6073).update(id: 6073,policy_taker: 'ACUEDUCTO Y ALCANTARILLADO DE POPAYAN CAUCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6049).update(id: 6049,policy_taker: 'ACUEDUCTO Y ALCANTARILLADO DE POPAYAN CAUCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6038).update(id: 6038,policy_taker: 'CLINICA SANTA SOFIA DEL PACIFICO LTDA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6037).update(id: 6037,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6031).update(id: 6031,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4661).update(id: 4661,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4606).update(id: 4606,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4039).update(id: 4039,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE   ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3807).update(id: 3807,policy_taker: 'MUNICIPIO SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3800).update(id: 3800,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3796).update(id: 3796,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3786).update(id: 3786,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3785).update(id: 3785,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3781).update(id: 3781,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3770).update(id: 3770,policy_taker: 'HOSPITAL SAN JUAN DE DIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3767).update(id: 3767,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3766).update(id: 3766,policy_taker: 'HOSPITAL SANTA MARGARITA ESE DE LA CUMBRE VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3765).update(id: 3765,policy_taker: 'CLINICA LA ESTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3761).update(id: 3761,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3759).update(id: 3759,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3750).update(id: 3750,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3723).update(id: 3723,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3718).update(id: 3718,policy_taker: 'HOSPITAL UNIVERSITARIO DEPARTAMENTAL DE NARINO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3714).update(id: 3714,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3710).update(id: 3710,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3709).update(id: 3709,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3700).update(id: 3700,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3695).update(id: 3695,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3676).update(id: 3676,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3669).update(id: 3669,policy_taker: 'EL HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3661).update(id: 3661,policy_taker: 'MINISTERIO DE HACIENDA Y CREDITO PUBLICO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3617).update(id: 3617,policy_taker: 'INSTITUTO NACIONAL PENINTENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3614).update(id: 3614,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3611).update(id: 3611,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3591).update(id: 3591,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3575).update(id: 3575,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3565).update(id: 3565,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3563).update(id: 3563,policy_taker: 'POLICIA NACIONAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3556).update(id: 3556,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3538).update(id: 3538,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3536).update(id: 3536,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3520).update(id: 3520,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3512).update(id: 3512,policy_taker: 'CLINICA ORIENTE LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3494).update(id: 3494,policy_taker: 'PEDRO JOAQUIN SILVA PAMPLONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3491).update(id: 3491,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3468).update(id: 3468,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3461).update(id: 3461,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3453).update(id: 3453,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3450).update(id: 3450,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3444).update(id: 3444,policy_taker: 'ALBERTO JOSE DURAN BUITRAGO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3423).update(id: 3423,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3420).update(id: 3420,policy_taker: 'CLINICA PALMA REAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3414).update(id: 3414,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESEHOSPITAL LA BUENA ESPERANZA DE YUMBO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3413).update(id: 3413,policy_taker: 'HOSPITAL SAN RAFAEL DE ZARZAL ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3409).update(id: 3409,policy_taker: 'CLINICA SANTA SOFIA DEL PACIFICO LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3404).update(id: 3404,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3403).update(id: 3403,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE   ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3402).update(id: 3402,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3392).update(id: 3392,policy_taker: 'EL HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3391).update(id: 3391,policy_taker: 'MUNICIPIO DEL VALLE DEL CAUCA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3390).update(id: 3390,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3386).update(id: 3386,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3358).update(id: 3358,policy_taker: 'DIRECCION DE IMPUESTOS Y ADUANAS NACIONALES DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3338).update(id: 3338,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3326).update(id: 3326,policy_taker: 'MUNICIPIO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3325).update(id: 3325,policy_taker: 'HOSPITAL SAN VICENTE FERRER DE ANDALUCIA VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3320).update(id: 3320,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3319).update(id: 3319,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3297).update(id: 3297,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EMCALI EICE ESP',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3295).update(id: 3295,policy_taker: 'HOSPITAL DEPARTAMENTAL CENTENARIO DE SEVILLA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3290).update(id: 3290,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3286).update(id: 3286,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3285).update(id: 3285,policy_taker: 'HOSPITAL LA BUENA ESPERANZA DE YUMBO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3284).update(id: 3284,policy_taker: 'HOSPITAL DEPARTAMENTAL SAN ANTONIO DE ROLDANILLO ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3280).update(id: 3280,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3277).update(id: 3277,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3269).update(id: 3269,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3262).update(id: 3262,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3261).update(id: 3261,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3259).update(id: 3259,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3255).update(id: 3255,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3254).update(id: 3254,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3253).update(id: 3253,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3249).update(id: 3249,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3246).update(id: 3246,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3243).update(id: 3243,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3238).update(id: 3238,policy_taker: 'HOSITAL PSIQUIATRICO UNIVERSITARIO DEL VALLE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3231).update(id: 3231,policy_taker: 'HOSPITAL SANTA ANA DE LOS CABALLEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3219).update(id: 3219,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3216).update(id: 3216,policy_taker: 'EL HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3215).update(id: 3215,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3212).update(id: 3212,policy_taker: 'SOCIEDAD DE ACUEDUCTOS Y ALCANTARILLADOS DEL VALLE DEL CAUCA SA ESP ACUAVALLE SA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3205).update(id: 3205,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3202).update(id: 3202,policy_taker: 'RED DE SALUD SURORIENTE ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3201).update(id: 3201,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3192).update(id: 3192,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALIHOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3191).update(id: 3191,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3177).update(id: 3177,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3169).update(id: 3169,policy_taker: 'HOSPITAL SAN JUAN DE DIOS DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3167).update(id: 3167,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3164).update(id: 3164,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3163).update(id: 3163,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALIEMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3161).update(id: 3161,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3152).update(id: 3152,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3138).update(id: 3138,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3123).update(id: 3123,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3117).update(id: 3117,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3113).update(id: 3113,policy_taker: 'HOSPITAL MUNICIPAL LUIS ABLANQUE DE LA PLATA DE BUENAVENTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3108).update(id: 3108,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3104).update(id: 3104,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3099).update(id: 3099,policy_taker: 'HOSPITAL SAN JUAN DE DIOS DE CALI   ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3098).update(id: 3098,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3097).update(id: 3097,policy_taker: 'SINERGIA GLOBAL EN SALUD SAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3095).update(id: 3095,policy_taker: 'MULTIPLES ASEGURADOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3087).update(id: 3087,policy_taker: 'HOSPITAL LA BUENA ESPERANZA DE YUMBO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3081).update(id: 3081,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3079).update(id: 3079,policy_taker: 'LA RED DE SALUD ESE   HOSPITAL UNIVERSITARIO DEL VALLE  MUNICIPIO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3078).update(id: 3078,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3066).update(id: 3066,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3065).update(id: 3065,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3046).update(id: 3046,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3042).update(id: 3042,policy_taker: 'HOSPITAL MUNICIPAL LUIS ABLANQUE DE LA PLATA DE BUENAVENTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3034).update(id: 3034,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3032).update(id: 3032,policy_taker: 'CLINICA SANTA SOFIA DEL PACIFICO LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3031).update(id: 3031,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3024).update(id: 3024,policy_taker: 'INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3022).update(id: 3022,policy_taker: 'HOSPITAL SAN ROQUE DE PRADERA VALLE ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3017).update(id: 3017,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3015).update(id: 3015,policy_taker: 'HOSPITAL DEPARTAMENTAL PSIQUIATRICO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3011).update(id: 3011,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3006).update(id: 3006,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3001).update(id: 3001,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2999).update(id: 2999,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2997).update(id: 2997,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2993).update(id: 2993,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2982).update(id: 2982,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2979).update(id: 2979,policy_taker: 'HOSPITAL MUNICIPAL LUIS ABLANQUE DE LA PLATA DE BUENAVENTURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2978).update(id: 2978,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2964).update(id: 2964,policy_taker: 'ANDRES FERNANDO GALLEGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2963).update(id: 2963,policy_taker: 'HOSPITAL SAN JUAN DE DIOS DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2958).update(id: 2958,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2955).update(id: 2955,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2946).update(id: 2946,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2940).update(id: 2940,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2930).update(id: 2930,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2926).update(id: 2926,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2923).update(id: 2923,policy_taker: 'EMPRESA SOCIAL DEL ESTADO TIEERADENTRO ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2917).update(id: 2917,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2916).update(id: 2916,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2913).update(id: 2913,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2909).update(id: 2909,policy_taker: 'ARRASTRE ALVAREZ PERLAZA LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2906).update(id: 2906,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2903).update(id: 2903,policy_taker: 'FERROCARRIL DEL OESTE SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2900).update(id: 2900,policy_taker: 'HOSPITAL DEPARTAMENTAL SAN RAFAEL DE ZARZAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2894).update(id: 2894,policy_taker: 'CLINICA LA ESTANCIA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2884).update(id: 2884,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2873).update(id: 2873,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2866).update(id: 2866,policy_taker: 'DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2856).update(id: 2856,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2844).update(id: 2844,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2834).update(id: 2834,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2799).update(id: 2799,policy_taker: 'HOSPITAL NIVEL II SUSANA LOPEZ DE VALENCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2787).update(id: 2787,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2785).update(id: 2785,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2784).update(id: 2784,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2780).update(id: 2780,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2774).update(id: 2774,policy_taker: 'COSMITET LTDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2773).update(id: 2773,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE  ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2766).update(id: 2766,policy_taker: 'EMPRESAS MUNICIPALES DE CALI EICE ESP EMCALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2756).update(id: 2756,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2749).update(id: 2749,policy_taker: 'HOSPITAL SAN JUAN DE DIOS DE CALI   ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2745).update(id: 2745,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2743).update(id: 2743,policy_taker: 'EL HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2737).update(id: 2737,policy_taker: 'CLINICA LA ESTANCIA SA ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2736).update(id: 2736,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2730).update(id: 2730,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2728).update(id: 2728,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2726).update(id: 2726,policy_taker: 'EMPRESA SOCIAL DEL ESTADO ESE NORTE 3',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2723).update(id: 2723,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2722).update(id: 2722,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2717).update(id: 2717,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2716).update(id: 2716,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2712).update(id: 2712,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2708).update(id: 2708,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2704).update(id: 2704,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2703).update(id: 2703,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2702).update(id: 2702,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2701).update(id: 2701,policy_taker: 'INSTITUTO NACIONAL PENITENCIARIO Y CARCELARIO INPEC',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2698).update(id: 2698,policy_taker: 'HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2696).update(id: 2696,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2690).update(id: 2690,policy_taker: 'EL HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE  ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2689).update(id: 2689,policy_taker: 'HOSPITAL SUSANA LOPEZ DE VALENCIA ESE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2673).update(id: 2673,policy_taker: 'HOSPITAL UNIVERSITARIO DEL VALLE EVARISTO GARCIA ESE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2671).update(id: 2671,policy_taker: 'MUNICIPIO DE SANTIAGO DE CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2663).update(id: 2663,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2660).update(id: 2660,policy_taker: 'HOSPITAL SAN RAFAEL ESE DE EL CERRITO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2659).update(id: 2659,policy_taker: 'CLINICA LA ESTANCIA SA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1457).update(id: 1457,policy_taker: 'HOSPITAL SAN JUAN DE DIOS CALI',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(295).update(id: 295,policy_taker: 'SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(141).update(id: 141,policy_taker: 'AGENCIA DE ADUANAS SOTRAEZ ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(110).update(id: 110,policy_taker: 'EL HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN ESE  ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(72).update(id: 72,policy_taker: 'CLINICA LA ESTANCIA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(70).update(id: 70,policy_taker: 'DIAN',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
