class Aleja01 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(18985).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18983).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18977).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18976).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18974).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18973).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18972).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18970).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18964).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18963).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18955).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18937).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18915).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18913).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18912).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18676).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18515).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18493).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18492).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18489).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18488).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18479).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18477).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18476).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18461).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18445).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18433).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18431).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18428).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18420).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18132).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18130).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18121).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18107).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18106).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18099).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18098).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18091).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18090).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18049).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18048).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18047).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18046).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18045).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18037).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18026).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18025).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18024).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18007).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18005).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17984).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17967).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17954).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17943).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17942).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17922).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17894).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17892).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17891).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17890).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17889).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17888).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17887).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17886).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17885).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17884).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17849).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17848).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17847).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17846).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17844).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17830).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17829).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17821).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17815).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17814).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17805).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17804).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17803).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17802).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17801).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17800).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17798).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17797).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17796).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17794).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17780).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17779).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17778).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17777).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17757).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17756).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17755).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17738).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17737).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17720).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17715).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17710).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17707).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17706).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17704).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17703).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17702).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17694).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17690).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17681).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17680).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17663).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17647).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17646).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17644).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17627).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17625).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17621).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17620).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17619).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17618).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17610).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17605).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17591).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17583).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17577).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17576).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17570).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17558).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17553).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17552).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17549).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17546).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17545).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19743).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19669).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17500).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17494).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17493).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17462).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17459).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17432).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17427).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17415).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17414).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17403).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17387).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17377).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17375).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17374).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17370).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17367).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17358).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17357).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17356).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17352).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17349).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17348).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17342).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17341).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17327).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17282).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17281).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17273).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17272).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17271).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17270).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17269).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17268).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17267).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17266).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17265).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17264).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17263).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17262).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17261).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17250).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17249).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17248).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17247).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17246).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17245).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17244).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17243).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17242).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17241).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17239).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17236).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17235).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17211).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17188).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17187).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17186).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17185).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17184).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17182).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17181).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17180).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17179).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17178).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17177).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17171).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17164).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17157).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17156).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17145).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17131).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17122).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17116).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17115).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17114).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17113).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17112).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17108).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17107).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17094).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17082).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17081).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17080).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17055).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17054).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17053).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17052).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17051).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17050).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17027).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17019).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17016).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17003).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16968).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16967).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16768).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16756).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16748).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16747).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16746).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16745).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16744).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16743).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16742).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16664).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16663).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16661).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16660).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16659).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16658).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16657).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16656).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16655).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16552).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16501).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16474).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16394).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16345).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16343).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16275).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16250).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16231).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16230).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16229).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16228).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16227).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16213).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16212).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16211).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16210).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16209).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16207).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16206).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16204).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16186).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14344).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14336).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13753).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11906).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11905).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11904).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11902).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11901).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11899).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11897).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11895).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11894).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11893).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11892).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11891).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11890).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11889).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11887).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11886).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11883).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11881).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11880).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11875).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11874).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11872).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11871).update(office_name: 'CONTRALORIA DEPARTAMENTAL DE CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10767).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10704).update(office_name: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CASANARE',case_state: 'EN CURSO',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
