class Fix03 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(22665).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22664).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22663).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22662).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22661).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22659).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22582).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22581).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22541).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22525).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22524).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22522).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22520).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22519).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22518).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22517).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22516).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22514).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22513).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22512).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22511).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(22510).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(185).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(147).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(113).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(81).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(64).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(63).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(40).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(39).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(36).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(35).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(32).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(30).update(coactive_radicate: 'PENDIENTE',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
