class Aleja18 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(9615).update(id: 9615,more_protections: '-RESPONSABILIDAD CIVIL - SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9080).update(id: 9080,more_protections: '-INCENDIO O EXPLOSION ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7521).update(id: 7521,more_protections: '-AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7409).update(id: 7409,more_protections: '-AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7387).update(id: 7387,more_protections: '-AUTOMOVILES COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7121).update(id: 7121,more_protections: '-AUTOMOVILES INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7013).update(id: 7013,more_protections: '-SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6865).update(id: 6865,more_protections: '-COLECTIVA AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6743).update(id: 6743,more_protections: '-COLECTIVA AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6740).update(id: 6740,more_protections: '-GASTOS MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5883).update(id: 5883,more_protections: '-RESPONSABILIDAD CIVIL PROFESIONAL MEDICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5824).update(id: 5824,more_protections: '-RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5783).update(id: 5783,more_protections: '-RESPONSABILIDAD CIVIL CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5756).update(id: 5756,more_protections: '-RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5687).update(id: 5687,more_protections: '-RESPONSABILIDAD CIVIL DE CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4448).update(id: 4448,more_protections: '-FALLAS EN SUMINISTRO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1844).update(id: 1844,more_protections: '-RESPONSABILIDAD CIVIL - SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1638).update(id: 1638,more_protections: '-RCC Y RCE PARA OPERADORES DE TRANSPORTE MULIMODAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(53).update(id: 53,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19694).update(id: 19694,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19391).update(id: 19391,more_protections: '-ACTOS INCORRECTOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19385).update(id: 19385,more_protections: '-RESPONSABILIDAD CIVIL DE SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18876).update(id: 18876,more_protections: '-PREVIALCALDIAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17722).update(id: 17722,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17118).update(id: 17118,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15741).update(id: 15741,more_protections: '-MANEJO OFICIAL   COBERTURA GLOBAL DE MANEJO OFICIAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15739).update(id: 15739,more_protections: '-MANEJO OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15661).update(id: 15661,more_protections: '-PREVIALCALDIAS POLIZA MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15476).update(id: 15476,more_protections: '-RESPONSABILIDAD CIVIL SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15474).update(id: 15474,more_protections: '-MANEJO SECTOR OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15426).update(id: 15426,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15424).update(id: 15424,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15223).update(id: 15223,more_protections: '-PREVIALCALDIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15184).update(id: 15184,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14887).update(id: 14887,more_protections: '-MANEJO OFICIAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14718).update(id: 14718,more_protections: '-COBERTURA RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14691).update(id: 14691,more_protections: '-MANEJO DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14670).update(id: 14670,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14635).update(id: 14635,more_protections: '-DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14386).update(id: 14386,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13624).update(id: 13624,more_protections: '-INCENDIO  SUSTRACCION  CORRIENTE DEBIL  MANEJO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13622).update(id: 13622,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13621).update(id: 13621,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13598).update(id: 13598,more_protections: '-INCENDIO SUSTRACCION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13567).update(id: 13567,more_protections: '-COBERTURA GLOBAL DE MANEJO OFICIAL ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13250).update(id: 13250,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13114).update(id: 13114,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13017).update(id: 13017,more_protections: '-DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13006).update(id: 13006,more_protections: '-DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12999).update(id: 12999,more_protections: '-DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11408).update(id: 11408,more_protections: '-DELITOS CONTRA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(11386).update(id: 11386,more_protections: '-DELITOS CONTRA LA ADMINISTRACION PUBLICA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10045).update(id: 10045,more_protections: '-RESPONSABILIDAD CIVIL DE SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9970).update(id: 9970,more_protections: '-SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9790).update(id: 9790,more_protections: '-TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9592).update(id: 9592,more_protections: '-MUERTE ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9301).update(id: 9301,more_protections: '-SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9293).update(id: 9293,more_protections: '-PERDIDA MENOR POR DANOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8974).update(id: 8974,more_protections: '-RC PROFESIONAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8858).update(id: 8858,more_protections: '-POLIZA COLECTIVA DE AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8711).update(id: 8711,more_protections: '-RESPONSABILIDAD CIVIL SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8653).update(id: 8653,more_protections: '-SEGURO PREVIHOSPITAL MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8444).update(id: 8444,more_protections: '-RESPONSABILIDAD CIVIL PARA MIEMBROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8400).update(id: 8400,more_protections: '-SEGURO DE VIDA GRUPO FUNCIONARIOS CONSEJO SUPERIOR DE LA JUDICATURA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8259).update(id: 8259,more_protections: '-SEGURO PREVIALCALDIAS POLIZA MULTIERIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8166).update(id: 8166,more_protections: '-PERDIDA POR ACTOS DELICTIVOS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8060).update(id: 8060,more_protections: '-POLIZA MULTIRIESGO PREVIALCALDIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8023).update(id: 8023,more_protections: '-MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8005).update(id: 8005,more_protections: '-SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7982).update(id: 7982,more_protections: '-SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7900).update(id: 7900,more_protections: '-SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7794).update(id: 7794,more_protections: '-SEGURO DE VIDA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7758).update(id: 7758,more_protections: '-DANOS MATERIALES COMBINADOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7754).update(id: 7754,more_protections: '-SEGURO AUTOMOVILES POLIZA INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7658).update(id: 7658,more_protections: '-SEGURO AUTOMOVILES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7623).update(id: 7623,more_protections: '-AVIACION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7595).update(id: 7595,more_protections: '-POLIZA MULTIRIESGO PREVIALCALDIAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7536).update(id: 7536,more_protections: '-RCE NO 3910 BAJO LA MODALIDAD DE COASEGURO EXPEDIDA POR COLSEGUROS SA -HOY ALLIANZ SEGUROS SA LIDER EN UN 60 PORCIENTO- JUNTO CON LAS COMPANIAS SEGUROS GENERALES SURAMERICANA SA -20 PORCIENTO- Y LA PREVISORA SA COMPANIA DE SEGUROS 20 PORCIENTO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7462).update(id: 7462,more_protections: '-SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7405).update(id: 7405,more_protections: '-COBERTURA RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7396).update(id: 7396,more_protections: '-SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7391).update(id: 7391,more_protections: '-SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7367).update(id: 7367,more_protections: '-ESTUDIANTES INSTITUCIONES EDUCATIVAS MUNICIPIO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7366).update(id: 7366,more_protections: '-MULTIRRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7351).update(id: 7351,more_protections: '-SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7254).update(id: 7254,more_protections: '-MUERTE',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7137).update(id: 7137,more_protections: '-RESPONSABILIDAD CIVIL DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7060).update(id: 7060,more_protections: '-SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7029).update(id: 7029,more_protections: '-CUMPLIMIENTO Y BUEN MANEJO DE ANTICIPO ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6956).update(id: 6956,more_protections: '-DAÑOS Y',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6855).update(id: 6855,more_protections: '-PREVIPYME POLIZA MULTIRIESGO RC EXTRACONTRACTUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6846).update(id: 6846,more_protections: '-RESPONSABILIDAD CIVIL PROFESIONALES MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6826).update(id: 6826,more_protections: '-EN EL PRESENTE PROCESO NO HAY POLIZA CON LA CUAL SE NOS HAYA VINCULADO SOMOS DEMANDOS DIRECTOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6690).update(id: 6690,more_protections: '-SEGURO AUTOMOVILES POLIZA INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6669).update(id: 6669,more_protections: '-COBERTURA RC DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6661).update(id: 6661,more_protections: '-COBERTURA RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6613).update(id: 6613,more_protections: '-PFREVIALCALDIAS MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6612).update(id: 6612,more_protections: '-AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6570).update(id: 6570,more_protections: '-PREVIALCALDIAS MULTIRIESGO CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6473).update(id: 6473,more_protections: '-INEXISTENCIA DE COBERTURA EN RAZON AL OBJETO DE LA POLIZA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6381).update(id: 6381,more_protections: '-RC SERVIDORES PUBLICOS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6291).update(id: 6291,more_protections: '-RESPONSABILIDAD CIVIL CONTRACTUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6281).update(id: 6281,more_protections: '-MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6230).update(id: 6230,more_protections: '-AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6227).update(id: 6227,more_protections: '-AUTOMOVILES POLIZA INDIVIDUAL',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5942).update(id: 5942,more_protections: '-SOAT',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5723).update(id: 5723,more_protections: '-DANOS MORALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5541).update(id: 5541,more_protections: '-RESPONSABILIDAD PARA SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4653).update(id: 4653,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4651).update(id: 4651,more_protections: '-RC SERVIDORES PUBLICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4621).update(id: 4621,more_protections: '-CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4562).update(id: 4562,more_protections: '-POLIZA DE SEGURO DE ACCIDENTES PERSONALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(4393).update(id: 4393,more_protections: '-SUSTRACCION',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3672).update(id: 3672,more_protections: '-RC VEHICULOS PROPIOS Y NO PROPIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3661).update(id: 3661,more_protections: '-COBERTURA BASICA DE TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3563).update(id: 3563,more_protections: '-MUERTE O LESION A UNA PERSONA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3494).update(id: 3494,more_protections: '-DANOS A BIENES DE TERCEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3480).update(id: 3480,more_protections: '-RC  CONTRATISTA DEPENDIENTE Y  SUBCONTRATISTAS INDEPENDIENTES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(3302).update(id: 3302,more_protections: '-SEGURO CUMPLIMIENTO POLIZA UNICA A FAVOR DE ENTIDADES ESTATALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2964).update(id: 2964,more_protections: '-GASTOS MEDICOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2955).update(id: 2955,more_protections: '-VEHICULOS PROPIOS Y NO PROPIOS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2591).update(id: 2591,more_protections: '-SEGURO AUTOMOVILES POLIZA COLECTIVA',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2472).update(id: 2472,more_protections: '-RESPONSABILIDAD CIVIL CONTRATISTAS Y SUBCONTRATISTAS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2207).update(id: 2207,more_protections: '-DANOS CORPORALES CAUSADOS E ACCIDENTE DE TRANSITO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(2201).update(id: 2201,more_protections: '-TERRORISMO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1857).update(id: 1857,more_protections: '-RC SERVIDORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1856).update(id: 1856,more_protections: '-RC SERVIDORES Y ADMINISTRADORES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1803).update(id: 1803,more_protections: '-RC DIRECTORES Y ADMINISTRADORES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1779).update(id: 1779,more_protections: '-CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1750).update(id: 1750,more_protections: '-PREDIOS LABORES Y OPERACIONES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1739).update(id: 1739,more_protections: '-ERRORES U OMISIONES PROFESIONALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1681).update(id: 1681,more_protections: '-MUERTE O LESIONES A DOS O MAS PERSONAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1680).update(id: 1680,more_protections: '-CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1677).update(id: 1677,more_protections: '-CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1671).update(id: 1671,more_protections: '-CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1658).update(id: 1658,more_protections: '-CLINICAS Y HOSPITALES',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1473).update(id: 1473,more_protections: '-INFIDELIDAD Y RIESGOS FINANCIEROS',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1382).update(id: 1382,more_protections: '-RESPONSABILIDAD CIVIL PROFESIONAL PARA INSTITUCIONES MEDICAS ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1351).update(id: 1351,more_protections: '-POLIZA MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(1350).update(id: 1350,more_protections: '-RC SERVIDORES ',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(482).update(id: 482,more_protections: '-SEGURO OBLITARORIO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(305).update(id: 305,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(256).update(id: 256,more_protections: '-MANEJO',state: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19).update(id: 19,more_protections: '-MULTIRIESGO',state: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
