class Aleja08 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(19102).update(id: 19102,active_part: 'ALFONSO CRISMATT JARAMILLO')
    puts TypeProcess.find(18914).update(id: 18914,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18898).update(id: 18898,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18714).update(id: 18714,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18666).update(id: 18666,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18662).update(id: 18662,active_part: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(18556).update(id: 18556,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18555).update(id: 18555,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18553).update(id: 18553,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18552).update(id: 18552,active_part: 'UNIVERSIDAD SURCOLOMBIANA')
    puts TypeProcess.find(18238).update(id: 18238,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18237).update(id: 18237,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18236).update(id: 18236,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(18235).update(id: 18235,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(18078).update(id: 18078,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17866).update(id: 17866,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17642).update(id: 17642,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17641).update(id: 17641,active_part: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(14900).update(id: 14900,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL CAUCA')
    puts TypeProcess.find(9889).update(id: 9889,active_part: 'YASMIN HELENA ECHEVERRI VASQUEZ')
    puts TypeProcess.find(9722).update(id: 9722,active_part: 'CARLOS ALFONSO GONZALEZ VARGAS')
    puts TypeProcess.find(9515).update(id: 9515,active_part: 'CLARA INES SANCHEZ CALDERIN')
    puts TypeProcess.find(9395).update(id: 9395,active_part: 'SISLEY DAYANA RUEDAS ZAMORA')
    puts TypeProcess.find(8805).update(id: 8805,active_part: 'SABAS RUFINO GOMEZ Y OTROS')
    puts TypeProcess.find(8116).update(id: 8116,active_part: 'EUDORO CABEZAS LOZANO')
    puts TypeProcess.find(7996).update(id: 7996,active_part: 'CARLOS ALBERTO CABRERA BUSTOS')
    puts TypeProcess.find(7970).update(id: 7970,active_part: 'ALDA MARIA CASTILLO GONZALEZ')
    puts TypeProcess.find(7876).update(id: 7876,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA')
    puts TypeProcess.find(7789).update(id: 7789,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(7311).update(id: 7311,active_part: 'ENILSA TOBIO ALVAREZ')
    puts TypeProcess.find(7222).update(id: 7222,active_part: 'AURA CECILIA RUIZ TRIANA')
    puts TypeProcess.find(7199).update(id: 7199,active_part: 'ALBA LUZ GUTIERREZ CARRILLO')
    puts TypeProcess.find(7162).update(id: 7162,active_part: 'ESGAR MONSALVE HERRERA')
    puts TypeProcess.find(7058).update(id: 7058,active_part: 'VICTOR MANUEL HERNANDEZ RICO')
    puts TypeProcess.find(6751).update(id: 6751,active_part: 'BOOM LOGISTIC SAS')
    puts TypeProcess.find(6514).update(id: 6514,active_part: 'JAVIER SAMPER BARBA')
    puts TypeProcess.find(286).update(id: 286,active_part: 'ELIAS SANTIAGO  JIMENEZ')
    puts TypeProcess.find(19750).update(id: 19750,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(19735).update(id: 19735,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(19287).update(id: 19287,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17480).update(id: 17480,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(17441).update(id: 17441,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17218).update(id: 17218,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17146).update(id: 17146,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(17000).update(id: 17000,active_part: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(16946).update(id: 16946,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16906).update(id: 16906,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16832).update(id: 16832,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16759).update(id: 16759,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16710).update(id: 16710,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16700).update(id: 16700,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16514).update(id: 16514,active_part: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(16510).update(id: 16510,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16410).update(id: 16410,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16367).update(id: 16367,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(16359).update(id: 16359,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16262).update(id: 16262,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(16254).update(id: 16254,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15354).update(id: 15354,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15339).update(id: 15339,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(15011).update(id: 15011,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(14987).update(id: 14987,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14986).update(id: 14986,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14985).update(id: 14985,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14983).update(id: 14983,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14982).update(id: 14982,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14981).update(id: 14981,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14980).update(id: 14980,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(14977).update(id: 14977,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14976).update(id: 14976,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14973).update(id: 14973,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14972).update(id: 14972,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14936).update(id: 14936,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(14821).update(id: 14821,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(14791).update(id: 14791,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14790).update(id: 14790,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14788).update(id: 14788,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(14663).update(id: 14663,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13938).update(id: 13938,active_part: 'CONTRALORIA DEPARTAMENTAL DE BOLIVAR')
    puts TypeProcess.find(13912).update(id: 13912,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13907).update(id: 13907,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13906).update(id: 13906,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13860).update(id: 13860,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13807).update(id: 13807,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13806).update(id: 13806,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13799).update(id: 13799,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13798).update(id: 13798,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13797).update(id: 13797,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13796).update(id: 13796,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13795).update(id: 13795,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13794).update(id: 13794,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13793).update(id: 13793,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13777).update(id: 13777,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13716).update(id: 13716,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13702).update(id: 13702,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13701).update(id: 13701,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13696).update(id: 13696,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13636).update(id: 13636,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13629).update(id: 13629,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13617).update(id: 13617,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13616).update(id: 13616,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13605).update(id: 13605,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13587).update(id: 13587,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13569).update(id: 13569,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13561).update(id: 13561,active_part: 'CONTRALORIA DISTRITAL DE CARTAGENA DE INDIAS')
    puts TypeProcess.find(13556).update(id: 13556,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13534).update(id: 13534,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13530).update(id: 13530,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13524).update(id: 13524,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13523).update(id: 13523,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13504).update(id: 13504,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13503).update(id: 13503,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13500).update(id: 13500,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13490).update(id: 13490,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13423).update(id: 13423,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13422).update(id: 13422,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13412).update(id: 13412,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13389).update(id: 13389,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13387).update(id: 13387,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13386).update(id: 13386,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13385).update(id: 13385,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13381).update(id: 13381,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13378).update(id: 13378,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13375).update(id: 13375,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13374).update(id: 13374,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13370).update(id: 13370,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13337).update(id: 13337,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13333).update(id: 13333,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13304).update(id: 13304,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13296).update(id: 13296,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13289).update(id: 13289,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13280).update(id: 13280,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13256).update(id: 13256,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13225).update(id: 13225,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13222).update(id: 13222,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13202).update(id: 13202,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(13191).update(id: 13191,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13168).update(id: 13168,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(13134).update(id: 13134,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13133).update(id: 13133,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13129).update(id: 13129,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13120).update(id: 13120,active_part: 'CONTRALORIA GENERAL DE LA REPULICA GERENCIA DEPARTAMENTAL BOLIVAR')
    puts TypeProcess.find(13108).update(id: 13108,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13107).update(id: 13107,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13106).update(id: 13106,active_part: 'CONTRALORIA MUNICIPAL DE NEIVA')
    puts TypeProcess.find(13101).update(id: 13101,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13097).update(id: 13097,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(13096).update(id: 13096,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(13064).update(id: 13064,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(13052).update(id: 13052,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(12988).update(id: 12988,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12932).update(id: 12932,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(12834).update(id: 12834,active_part: 'CONTRALORIA DEPARTAMENTAL DEL HUILA')
    puts TypeProcess.find(12671).update(id: 12671,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL HUILA')
    puts TypeProcess.find(12429).update(id: 12429,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12424).update(id: 12424,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12421).update(id: 12421,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12417).update(id: 12417,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12401).update(id: 12401,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12399).update(id: 12399,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12396).update(id: 12396,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12392).update(id: 12392,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12391).update(id: 12391,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12388).update(id: 12388,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12384).update(id: 12384,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12375).update(id: 12375,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12373).update(id: 12373,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12363).update(id: 12363,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12362).update(id: 12362,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12359).update(id: 12359,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12358).update(id: 12358,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12357).update(id: 12357,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12356).update(id: 12356,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(12353).update(id: 12353,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12349).update(id: 12349,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12343).update(id: 12343,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(12342).update(id: 12342,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12329).update(id: 12329,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(12328).update(id: 12328,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10729).update(id: 10729,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10706).update(id: 10706,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10693).update(id: 10693,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10689).update(id: 10689,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10664).update(id: 10664,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10612).update(id: 10612,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10569).update(id: 10569,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10518).update(id: 10518,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10516).update(id: 10516,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10510).update(id: 10510,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10506).update(id: 10506,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10505).update(id: 10505,active_part: 'CONTRALORIA GENERAL DE LA REPUBLICA GERENCIA DEPARTAMENTAL TOLIMA')
    puts TypeProcess.find(10504).update(id: 10504,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10503).update(id: 10503,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10502).update(id: 10502,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10501).update(id: 10501,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10500).update(id: 10500,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10499).update(id: 10499,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(10494).update(id: 10494,active_part: 'CONTRALORIA MUNICIPAL DE IBAGUE')
    puts TypeProcess.find(10230).update(id: 10230,active_part: 'CONTRALORIA DEPARTAMENTAL DE TOLIMA')
    puts TypeProcess.find(9609).update(id: 9609,active_part: 'JOSE CAMILO PERDOMO SANCHEZ')
    puts TypeProcess.find(9602).update(id: 9602,active_part: 'MARIA MESTIL DURAN LOPEZ')
    puts TypeProcess.find(9600).update(id: 9600,active_part: 'ARGEMIRO FERRO ROJAS')
    puts TypeProcess.find(9598).update(id: 9598,active_part: 'MARIA EUGENIA OLIVEROS - SERRANO CHAUX LUZ MARINA')
    puts TypeProcess.find(9570).update(id: 9570,active_part: 'OLIVERIO BAHAMON MEDINA')
    puts TypeProcess.find(9502).update(id: 9502,active_part: 'FRANKLIN DIAZ ALBA')
    puts TypeProcess.find(9474).update(id: 9474,active_part: 'QUINTERO TITIMBO ERIBERTO')
    puts TypeProcess.find(9448).update(id: 9448,active_part: 'HILDA PATRICIA DELGADO BENAVIDES')
    puts TypeProcess.find(9438).update(id: 9438,active_part: 'ESTEBAN PERDOMO')
    puts TypeProcess.find(9437).update(id: 9437,active_part: 'ORDONEZ OLIVERA MARIA PAOLA')
    puts TypeProcess.find(9436).update(id: 9436,active_part: 'JHON JAIRO DELGADO TENORIO')
    puts TypeProcess.find(9435).update(id: 9435,active_part: 'TOVAR MANCHOLA JAMES')
    puts TypeProcess.find(9433).update(id: 9433,active_part: 'ROSALBA CISNEROS DE CUADROS')
    puts TypeProcess.find(9398).update(id: 9398,active_part: 'JAINOVER ANDRES REBELLON CLAROS')
    puts TypeProcess.find(9347).update(id: 9347,active_part: 'BLANCA NUBIA RAMOS SEPULVEDA')
    puts TypeProcess.find(9262).update(id: 9262,active_part: 'LUIS ENRIQUE ROJAS PITA')
    puts TypeProcess.find(9244).update(id: 9244,active_part: 'CABRERA LARA REINALDO')
    puts TypeProcess.find(9240).update(id: 9240,active_part: 'ANA LEIDA VASQUEZ GIRALDO')
    puts TypeProcess.find(9236).update(id: 9236,active_part: 'CERQUERA MONJE NOHORA')
    puts TypeProcess.find(9203).update(id: 9203,active_part: 'ROSARIO CUELLAR CUELLAR')
    puts TypeProcess.find(9199).update(id: 9199,active_part: 'MARIA YOLANDA TORRES FAJARDO - YOLANDA TORRES FAJARDO ')
    puts TypeProcess.find(9195).update(id: 9195,active_part: 'YATE OLARTE VICTOR ALFONSO')
    puts TypeProcess.find(9191).update(id: 9191,active_part: 'LUZ YENNY GALINDO QUINTERO')
    puts TypeProcess.find(9190).update(id: 9190,active_part: 'PARRA RAMOS ROSALINDA')
    puts TypeProcess.find(9182).update(id: 9182,active_part: 'FLOR DALIA MANDRONERO LEON')
    puts TypeProcess.find(9181).update(id: 9181,active_part: 'CALDERON RAUL - OSCAR MAURICIO CALDERON')
    puts TypeProcess.find(9172).update(id: 9172,active_part: 'JENNIFER TATIANA CALDERON CUELLAR')
    puts TypeProcess.find(9170).update(id: 9170,active_part: 'BEATRIZ RANGEL TOVAR')
    puts TypeProcess.find(9111).update(id: 9111,active_part: 'VEGA MORA GERARDO')
    puts TypeProcess.find(9096).update(id: 9096,active_part: 'CHARRY QUIROGA MARIA EUGENIA')
    puts TypeProcess.find(9033).update(id: 9033,active_part: 'BLANCA MARIA GONZALEZ DE PERDOMO')
    puts TypeProcess.find(9010).update(id: 9010,active_part: 'YULI ALEJANDRA PEREZ MURILLO')
    puts TypeProcess.find(8846).update(id: 8846,active_part: 'RADA BARBOSA MARLY YURANY')
    puts TypeProcess.find(8837).update(id: 8837,active_part: 'JOSE ERNESTO ALVAREZ GODOY')
    puts TypeProcess.find(8683).update(id: 8683,active_part: 'LAURA VANESA GOMEZ NAVARRO')
    puts TypeProcess.find(8682).update(id: 8682,active_part: 'PENALOZA PENALOZA GLORIA EUGENIA')
    puts TypeProcess.find(8660).update(id: 8660,active_part: 'SEVERICHE RUIZ KEVIN RAFAEL')
    puts TypeProcess.find(8549).update(id: 8549,active_part: 'FACUNDO GARCIA JONATAN FABIAN - MARCO TULIO FACUNDO ')
    puts TypeProcess.find(8375).update(id: 8375,active_part: 'MARIA MERIDA PARALES')
    puts TypeProcess.find(8362).update(id: 8362,active_part: 'ARISTARCO CASAS GOMEZ')
    puts TypeProcess.find(8350).update(id: 8350,active_part: 'LUIS ARTURO PEREZ')
    puts TypeProcess.find(8336).update(id: 8336,active_part: 'AUBERLYS PERTUZ VILLAREAL')
    puts TypeProcess.find(8332).update(id: 8332,active_part: 'JAMINTON HURTADO RIVERA')
    puts TypeProcess.find(8286).update(id: 8286,active_part: 'JOSE WILLIAM LONDONO PARRA')
    puts TypeProcess.find(8285).update(id: 8285,active_part: 'ANGELICA MARIA PATINO QUENEJA')
    puts TypeProcess.find(8151).update(id: 8151,active_part: 'ALVARO YOBANI ESCOBAR QUINTERO')
    puts TypeProcess.find(8117).update(id: 8117,active_part: 'CARLOS JULIO SANDOVAL')
    puts TypeProcess.find(7960).update(id: 7960,active_part: 'VANESSA JUANCHO MOSQUERA')
    puts TypeProcess.find(7930).update(id: 7930,active_part: 'HOSPITAL MARIA INMACULADA ')
    puts TypeProcess.find(7894).update(id: 7894,active_part: 'ANDERSON DEVIA MAJE')
    puts TypeProcess.find(7893).update(id: 7893,active_part: 'JACKELINE VERGARA TOBAR')
    puts TypeProcess.find(7890).update(id: 7890,active_part: 'MARIA EUGENIA LOPEZ CAMACHO')
    puts TypeProcess.find(7784).update(id: 7784,active_part: 'ELIZABETH ROZO MEDINA')
    puts TypeProcess.find(7688).update(id: 7688,active_part: 'MILLER CABRERA BUSTAMANTE')
    puts TypeProcess.find(7687).update(id: 7687,active_part: 'ESPERANZA CUELLAR SILVA')
    puts TypeProcess.find(7643).update(id: 7643,active_part: 'LUIS DANIEL POSADA AGUDELO')
    puts TypeProcess.find(7642).update(id: 7642,active_part: 'SAMUEL BARRAGAN GALINDO')
    puts TypeProcess.find(7641).update(id: 7641,active_part: 'MARIA CLARETH FIGUEROA')
    puts TypeProcess.find(7640).update(id: 7640,active_part: 'CARLOS ARTURO GARCIA MEJIA')
    puts TypeProcess.find(7639).update(id: 7639,active_part: 'MARTHA CECILIA PACHECO')
    puts TypeProcess.find(7588).update(id: 7588,active_part: 'LEONARDO FABIO GARCIA')
    puts TypeProcess.find(7425).update(id: 7425,active_part: 'GASODUCTO MOVIL DE COLOMBIA SA ESP')
    puts TypeProcess.find(7181).update(id: 7181,active_part: 'NELSON ENRIQUE RAMIREZ GASCA')
    puts TypeProcess.find(7142).update(id: 7142,active_part: 'LUZ ALBA VANEGAS RAMIREZ')
    puts TypeProcess.find(7109).update(id: 7109,active_part: 'SALVADOR SAAVEDRA')
    puts TypeProcess.find(7031).update(id: 7031,active_part: 'REGULO PERDOMO QUIROGA')
    puts TypeProcess.find(6953).update(id: 6953,active_part: 'SANDRA MILENA PARRA TABORDA ')
    puts TypeProcess.find(6828).update(id: 6828,active_part: 'SANDRA MILENA PARRA TABORDA')
    puts TypeProcess.find(6827).update(id: 6827,active_part: 'JAIME EDUARDO CARDENAS HURTADO')
    puts TypeProcess.find(6801).update(id: 6801,active_part: 'ESE HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(6715).update(id: 6715,active_part: 'CARLOS ALBERTO FLOREZ')
    puts TypeProcess.find(6607).update(id: 6607,active_part: 'JOHN FREDY BENITEZ MORALES')
    puts TypeProcess.find(6555).update(id: 6555,active_part: 'ARIEL RODRIGO REAL RINCON')
    puts TypeProcess.find(6439).update(id: 6439,active_part: 'ANAEL NULEZ MONTILLA')
    puts TypeProcess.find(6438).update(id: 6438,active_part: 'JOSE GABRIEL DIAZ SANCHEZ')
    puts TypeProcess.find(6388).update(id: 6388,active_part: 'JUAN FRANCISCO DIAZ VERGARA')
    puts TypeProcess.find(6284).update(id: 6284,active_part: 'FERNANDO FACUNDO APRAEZ')
    puts TypeProcess.find(6283).update(id: 6283,active_part: 'YUBER HERNEY CASIANO MEDINA')
    puts TypeProcess.find(6282).update(id: 6282,active_part: 'PAOLA ANDREA CALDERON GONZALEZ')
    puts TypeProcess.find(6270).update(id: 6270,active_part: 'RIOS PRIETO JOSE WILSON')
    puts TypeProcess.find(6251).update(id: 6251,active_part: 'LUIS ALFREDO CHACON CHACON')
    puts TypeProcess.find(6204).update(id: 6204,active_part: 'NARVAEZ GUZMAN ANGELA PATRICIA')
    puts TypeProcess.find(6116).update(id: 6116,active_part: 'MAURICIO LOPEZ OVALLE')
    puts TypeProcess.find(6102).update(id: 6102,active_part: 'JAMES ALDUBAR GIRALDO CORREA')
    puts TypeProcess.find(6090).update(id: 6090,active_part: 'ESE HOSPITAL DEPARTAMENTAL SAN VICENTE DE PAUL DE GARZON')
    puts TypeProcess.find(6087).update(id: 6087,active_part: 'CARLOS ARTURO DIAZ URREA')
    puts TypeProcess.find(6058).update(id: 6058,active_part: 'MARTHA ISABEL TEJADA PERDOMO')
    puts TypeProcess.find(6054).update(id: 6054,active_part: 'VALENZUELA ESCOBAR FRANCISCO JAVIER')
    puts TypeProcess.find(6053).update(id: 6053,active_part: 'ELVIRA CALDERON')
    puts TypeProcess.find(6052).update(id: 6052,active_part: 'CENAIDA VARGAS PERDOMO')
    puts TypeProcess.find(6051).update(id: 6051,active_part: 'HEIDY LORENA ERAZO ORTIZ')
    puts TypeProcess.find(5223).update(id: 5223,active_part: 'LOZANO PARGA DIEGO ANDRES')
    puts TypeProcess.find(5193).update(id: 5193,active_part: 'LEONEL SIERRA JAIME ALIRIO')
    puts TypeProcess.find(5122).update(id: 5122,active_part: 'REINA PINZON CARLOS')
    puts TypeProcess.find(5093).update(id: 5093,active_part: 'RICO URUENA ANA YOLIMA')
    puts TypeProcess.find(5037).update(id: 5037,active_part: 'HOSPITAL MARIA INMACULADA')
    puts TypeProcess.find(4207).update(id: 4207,active_part: 'GARCIA FIRIGUA EDILMA')
    puts TypeProcess.find(4201).update(id: 4201,active_part: 'LOSADA SILVA ALBERTO')
    puts TypeProcess.find(4199).update(id: 4199,active_part: 'QUEVEDO PERDOMO DIANID')
    puts TypeProcess.find(4198).update(id: 4198,active_part: 'VARGAS OSPINA GERMAN')
    puts TypeProcess.find(4197).update(id: 4197,active_part: 'POLANIA CARDOSO FELIX HUMBERTO')
    puts TypeProcess.find(4196).update(id: 4196,active_part: 'PARRA PATINO RAQUEL')
    puts TypeProcess.find(4192).update(id: 4192,active_part: 'MARIA ALEJANDRA VARGAS CORRALES')
    puts TypeProcess.find(4183).update(id: 4183,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4179).update(id: 4179,active_part: 'MUNOZ PENA DIXON JADER')
    puts TypeProcess.find(4178).update(id: 4178,active_part: 'GARCIA PEREZ RUBY ESTERLY GARCIA PEREZ')
    puts TypeProcess.find(4161).update(id: 4161,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4157).update(id: 4157,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4155).update(id: 4155,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4138).update(id: 4138,active_part: 'LUNA MONTOYA NINI ASIRIA')
    puts TypeProcess.find(4121).update(id: 4121,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4119).update(id: 4119,active_part: 'MASTER COLOR DIGITAL LTDA  MASTER COLOR DIGITAL')
    puts TypeProcess.find(4103).update(id: 4103,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4096).update(id: 4096,active_part: 'SOCIEDAD MG SPRING BUILDING SA')
    puts TypeProcess.find(4082).update(id: 4082,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4075).update(id: 4075,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4073).update(id: 4073,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4072).update(id: 4072,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(4067).update(id: 4067,active_part: 'LA PREVISORA SA COMPANIA DE SEGUROS')
    puts TypeProcess.find(2548).update(id: 2548,active_part: 'NAVARRO RAMIREZ JORGE ENRIQUE')
    puts TypeProcess.find(2544).update(id: 2544,active_part: 'ECHEVERRI AGUIRRE LUZ MAIRA')
    puts TypeProcess.find(2531).update(id: 2531,active_part: 'VARGAS SEPULVEDA JOSE AINES')
    puts TypeProcess.find(2530).update(id: 2530,active_part: 'RODRIGUEZ CAPERA MARIA DEL CARMEN')
    puts TypeProcess.find(2520).update(id: 2520,active_part: 'LIZ JOHANNA OSPINA RIOS')
    puts TypeProcess.find(2515).update(id: 2515,active_part: 'MONTOYA PALACIOS OSCAR FERNANDO')
    puts TypeProcess.find(2513).update(id: 2513,active_part: 'AGUDELO CARDONA HECTOR JAIME')
    puts TypeProcess.find(2507).update(id: 2507,active_part: 'SAAVEDRA CRUZ CARLOS EDUIN')
    puts TypeProcess.find(2504).update(id: 2504,active_part: 'GOMEZ GIRALDO RUBEN DARIO')
    puts TypeProcess.find(2496).update(id: 2496,active_part: 'QUINTERO SANTOFIMIO DIEGO JAVIER')
    puts TypeProcess.find(2490).update(id: 2490,active_part: 'MURILLO CARDENAS NOHORA LUZ')
    puts TypeProcess.find(2474).update(id: 2474,active_part: 'SANCHEZ RUGE NANCY MIREYA')
    puts TypeProcess.find(2469).update(id: 2469,active_part: 'MARIA LIBIA SUAREZ TREJOS')
    puts TypeProcess.find(2466).update(id: 2466,active_part: 'PINEDA HERRERA CARLOS HUMBERTO')
    puts TypeProcess.find(2464).update(id: 2464,active_part: 'ARCE FUENTES SEBASTIAN')
    puts TypeProcess.find(2456).update(id: 2456,active_part: 'TREJOS TAPASCO LAZARO ANTONIO')
    puts TypeProcess.find(2452).update(id: 2452,active_part: 'ROA SALGADO REGINA')
    puts TypeProcess.find(2442).update(id: 2442,active_part: 'MARIN AGUDELO ANA MARIA')
    puts TypeProcess.find(2428).update(id: 2428,active_part: 'RAMIREZ FERNANDEZ GUSTAVO ADOLFO')
    puts TypeProcess.find(2423).update(id: 2423,active_part: 'LOPEZ LOPEZ HECTOR AUGUSTO')
    puts TypeProcess.find(2421).update(id: 2421,active_part: 'BURGOS PULGARIN NOELBA')
    puts TypeProcess.find(2418).update(id: 2418,active_part: 'SANTAMARIA GONZALEZ JUAN MANUEL')
    puts TypeProcess.find(2415).update(id: 2415,active_part: 'FLOREZ CARMONA LEIDY YULIANA')
    puts TypeProcess.find(2408).update(id: 2408,active_part: 'CARDONA LOAIZA LUCILA')
    puts TypeProcess.find(2383).update(id: 2383,active_part: 'AGUIRRE ALZATE MEDARDO ANTONIO')
    puts TypeProcess.find(2372).update(id: 2372,active_part: 'HENAO VASCO JAIRO HERNADO HENAO VASCO')
    puts TypeProcess.find(390).update(id: 390,active_part: 'MARTHA CECILIA CRUZ VILLADA')
    puts TypeProcess.find(290).update(id: 290,active_part: 'EDISON ALBERTO GARCIA LOZADA Y OTROS')
    puts TypeProcess.find(122).update(id: 122,active_part: 'IMAGENES DIAGNOSTICAS SA')
    puts TypeProcess.find(95).update(id: 95,active_part: 'MARTHA HEDILIA ROMAN MEDINA Y OTROS')
  end
end
