class Al16 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(118).update(id: 118,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(119).update(id: 119,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(394).update(id: 394,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5734).update(id: 5734,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(5818).update(id: 5818,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6295).update(id: 6295,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6297).update(id: 6297,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6303).update(id: 6303,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6310).update(id: 6310,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6426).update(id: 6426,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6457).update(id: 6457,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6499).update(id: 6499,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6507).update(id: 6507,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6637).update(id: 6637,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6658).update(id: 6658,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6852).update(id: 6852,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(6961).update(id: 6961,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7085).update(id: 7085,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7125).update(id: 7125,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7166).update(id: 7166,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7381).update(id: 7381,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7447).update(id: 7447,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7477).update(id: 7477,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7634).update(id: 7634,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7694).update(id: 7694,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7695).update(id: 7695,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7772).update(id: 7772,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7800).update(id: 7800,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7866).update(id: 7866,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7875).update(id: 7875,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7877).update(id: 7877,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7920).update(id: 7920,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(7937).update(id: 7937,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8052).update(id: 8052,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8057).update(id: 8057,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8160).update(id: 8160,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8162).update(id: 8162,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8264).update(id: 8264,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8329).update(id: 8329,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8331).update(id: 8331,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8370).update(id: 8370,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8660).update(id: 8660,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8786).update(id: 8786,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8794).update(id: 8794,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8908).update(id: 8908,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(8917).update(id: 8917,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9083).update(id: 9083,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9159).update(id: 9159,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9190).update(id: 9190,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9325).update(id: 9325,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9329).update(id: 9329,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9354).update(id: 9354,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9490).update(id: 9490,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9716).update(id: 9716,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9779).update(id: 9779,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9782).update(id: 9782,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9813).update(id: 9813,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9822).update(id: 9822,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9857).update(id: 9857,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9894).update(id: 9894,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(9919).update(id: 9919,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10001).update(id: 10001,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10015).update(id: 10015,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10046).update(id: 10046,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10071).update(id: 10071,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(10072).update(id: 10072,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12934).update(id: 12934,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(12962).update(id: 12962,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13004).update(id: 13004,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13053).update(id: 13053,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13111).update(id: 13111,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13150).update(id: 13150,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13192).update(id: 13192,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13209).update(id: 13209,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13229).update(id: 13229,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13263).update(id: 13263,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13393).update(id: 13393,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13408).update(id: 13408,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13411).update(id: 13411,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13437).update(id: 13437,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13440).update(id: 13440,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13441).update(id: 13441,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13470).update(id: 13470,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13570).update(id: 13570,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13574).update(id: 13574,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13819).update(id: 13819,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13826).update(id: 13826,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13869).update(id: 13869,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13873).update(id: 13873,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13876).update(id: 13876,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13879).update(id: 13879,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13880).update(id: 13880,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(13990).update(id: 13990,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14084).update(id: 14084,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14179).update(id: 14179,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14223).update(id: 14223,instance: 'PRIMERA ',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14245).update(id: 14245,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14348).update(id: 14348,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14397).update(id: 14397,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14431).update(id: 14431,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14441).update(id: 14441,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14505).update(id: 14505,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14524).update(id: 14524,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14602).update(id: 14602,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14664).update(id: 14664,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14679).update(id: 14679,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14680).update(id: 14680,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14682).update(id: 14682,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14684).update(id: 14684,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14689).update(id: 14689,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14741).update(id: 14741,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14783).update(id: 14783,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14794).update(id: 14794,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14819).update(id: 14819,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14895).update(id: 14895,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14918).update(id: 14918,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14958).update(id: 14958,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(14998).update(id: 14998,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15017).update(id: 15017,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15018).update(id: 15018,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15019).update(id: 15019,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15020).update(id: 15020,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15025).update(id: 15025,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15027).update(id: 15027,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(15224).update(id: 15224,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16186).update(id: 16186,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16190).update(id: 16190,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16204).update(id: 16204,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16206).update(id: 16206,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16207).update(id: 16207,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16209).update(id: 16209,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16210).update(id: 16210,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16211).update(id: 16211,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16212).update(id: 16212,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16213).update(id: 16213,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16218).update(id: 16218,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16227).update(id: 16227,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16228).update(id: 16228,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16229).update(id: 16229,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16230).update(id: 16230,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16231).update(id: 16231,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16234).update(id: 16234,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16250).update(id: 16250,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16258).update(id: 16258,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16264).update(id: 16264,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16272).update(id: 16272,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16307).update(id: 16307,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16317).update(id: 16317,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16318).update(id: 16318,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16373).update(id: 16373,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16382).update(id: 16382,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16411).update(id: 16411,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16431).update(id: 16431,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16468).update(id: 16468,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16478).update(id: 16478,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16501).update(id: 16501,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16519).update(id: 16519,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16544).update(id: 16544,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16554).update(id: 16554,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16555).update(id: 16555,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16578).update(id: 16578,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16584).update(id: 16584,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16615).update(id: 16615,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16654).update(id: 16654,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16688).update(id: 16688,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16737).update(id: 16737,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16749).update(id: 16749,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16751).update(id: 16751,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16795).update(id: 16795,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16798).update(id: 16798,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16799).update(id: 16799,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16800).update(id: 16800,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16827).update(id: 16827,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16888).update(id: 16888,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(16921).update(id: 16921,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17012).update(id: 17012,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17013).update(id: 17013,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17014).update(id: 17014,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17027).update(id: 17027,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17028).update(id: 17028,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17030).update(id: 17030,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17046).update(id: 17046,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17048).update(id: 17048,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17049).update(id: 17049,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17095).update(id: 17095,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17096).update(id: 17096,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17098).update(id: 17098,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17099).update(id: 17099,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17103).update(id: 17103,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17106).update(id: 17106,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17113).update(id: 17113,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17114).update(id: 17114,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17117).update(id: 17117,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17123).update(id: 17123,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17127).update(id: 17127,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17128).update(id: 17128,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17129).update(id: 17129,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17142).update(id: 17142,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17166).update(id: 17166,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17173).update(id: 17173,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17176).update(id: 17176,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17189).update(id: 17189,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17199).update(id: 17199,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17288).update(id: 17288,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17292).update(id: 17292,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17329).update(id: 17329,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17332).update(id: 17332,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17339).update(id: 17339,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17340).update(id: 17340,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17350).update(id: 17350,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17367).update(id: 17367,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17371).update(id: 17371,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17382).update(id: 17382,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17399).update(id: 17399,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17401).update(id: 17401,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17402).update(id: 17402,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17403).update(id: 17403,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17409).update(id: 17409,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17411).update(id: 17411,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17412).update(id: 17412,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17427).update(id: 17427,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17428).update(id: 17428,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17431).update(id: 17431,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17432).update(id: 17432,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17433).update(id: 17433,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17438).update(id: 17438,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17439).update(id: 17439,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17440).update(id: 17440,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17442).update(id: 17442,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17454).update(id: 17454,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17455).update(id: 17455,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17456).update(id: 17456,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17464).update(id: 17464,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17466).update(id: 17466,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17467).update(id: 17467,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17473).update(id: 17473,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17475).update(id: 17475,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17477).update(id: 17477,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17481).update(id: 17481,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17482).update(id: 17482,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17488).update(id: 17488,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17490).update(id: 17490,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17497).update(id: 17497,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17498).update(id: 17498,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17499).update(id: 17499,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17502).update(id: 17502,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17507).update(id: 17507,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17530).update(id: 17530,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17551).update(id: 17551,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17555).update(id: 17555,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17556).update(id: 17556,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17563).update(id: 17563,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17564).update(id: 17564,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17571).update(id: 17571,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17572).update(id: 17572,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17576).update(id: 17576,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17589).update(id: 17589,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17599).update(id: 17599,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17600).update(id: 17600,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17602).update(id: 17602,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17603).update(id: 17603,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17615).update(id: 17615,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17620).update(id: 17620,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17628).update(id: 17628,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17634).update(id: 17634,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17650).update(id: 17650,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17654).update(id: 17654,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17655).update(id: 17655,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17658).update(id: 17658,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17665).update(id: 17665,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17667).update(id: 17667,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17670).update(id: 17670,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17672).update(id: 17672,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17673).update(id: 17673,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17675).update(id: 17675,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17677).update(id: 17677,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17678).update(id: 17678,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17687).update(id: 17687,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17691).update(id: 17691,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17692).update(id: 17692,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17693).update(id: 17693,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17712).update(id: 17712,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17725).update(id: 17725,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17726).update(id: 17726,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17744).update(id: 17744,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17746).update(id: 17746,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17749).update(id: 17749,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17751).update(id: 17751,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17770).update(id: 17770,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17775).update(id: 17775,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17786).update(id: 17786,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17787).update(id: 17787,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17795).update(id: 17795,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17813).update(id: 17813,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17816).update(id: 17816,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17853).update(id: 17853,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17859).update(id: 17859,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17865).update(id: 17865,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17874).update(id: 17874,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17879).update(id: 17879,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17883).update(id: 17883,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17884).update(id: 17884,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17885).update(id: 17885,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17886).update(id: 17886,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17887).update(id: 17887,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17889).update(id: 17889,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17890).update(id: 17890,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17891).update(id: 17891,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17892).update(id: 17892,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17901).update(id: 17901,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17918).update(id: 17918,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17923).update(id: 17923,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17926).update(id: 17926,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17931).update(id: 17931,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17936).update(id: 17936,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17952).update(id: 17952,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17953).update(id: 17953,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17975).update(id: 17975,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17978).update(id: 17978,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17983).update(id: 17983,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17985).update(id: 17985,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(17988).update(id: 17988,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18008).update(id: 18008,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18010).update(id: 18010,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18011).update(id: 18011,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18012).update(id: 18012,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18013).update(id: 18013,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18034).update(id: 18034,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18036).update(id: 18036,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18043).update(id: 18043,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18064).update(id: 18064,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18081).update(id: 18081,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18084).update(id: 18084,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18085).update(id: 18085,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18087).update(id: 18087,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18088).update(id: 18088,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18089).update(id: 18089,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18095).update(id: 18095,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18109).update(id: 18109,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18116).update(id: 18116,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18123).update(id: 18123,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18125).update(id: 18125,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18126).update(id: 18126,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18127).update(id: 18127,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18128).update(id: 18128,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18143).update(id: 18143,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18147).update(id: 18147,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18150).update(id: 18150,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18153).update(id: 18153,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18154).update(id: 18154,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18155).update(id: 18155,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18156).update(id: 18156,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18157).update(id: 18157,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18165).update(id: 18165,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18179).update(id: 18179,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18180).update(id: 18180,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18181).update(id: 18181,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18183).update(id: 18183,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18184).update(id: 18184,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18187).update(id: 18187,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18188).update(id: 18188,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18189).update(id: 18189,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18192).update(id: 18192,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18193).update(id: 18193,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18200).update(id: 18200,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18201).update(id: 18201,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18202).update(id: 18202,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18203).update(id: 18203,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18220).update(id: 18220,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18223).update(id: 18223,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18245).update(id: 18245,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18249).update(id: 18249,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18250).update(id: 18250,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18251).update(id: 18251,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18268).update(id: 18268,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18273).update(id: 18273,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18289).update(id: 18289,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18293).update(id: 18293,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18296).update(id: 18296,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18303).update(id: 18303,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18307).update(id: 18307,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18308).update(id: 18308,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18309).update(id: 18309,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18311).update(id: 18311,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18312).update(id: 18312,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18314).update(id: 18314,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18315).update(id: 18315,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18316).update(id: 18316,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18317).update(id: 18317,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18319).update(id: 18319,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18320).update(id: 18320,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18321).update(id: 18321,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18340).update(id: 18340,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18344).update(id: 18344,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18346).update(id: 18346,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18347).update(id: 18347,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18349).update(id: 18349,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18350).update(id: 18350,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18353).update(id: 18353,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18354).update(id: 18354,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18375).update(id: 18375,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18376).update(id: 18376,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18377).update(id: 18377,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18378).update(id: 18378,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18379).update(id: 18379,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18380).update(id: 18380,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18382).update(id: 18382,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18384).update(id: 18384,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18385).update(id: 18385,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18398).update(id: 18398,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18425).update(id: 18425,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18435).update(id: 18435,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18439).update(id: 18439,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18441).update(id: 18441,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18442).update(id: 18442,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18469).update(id: 18469,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18478).update(id: 18478,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18495).update(id: 18495,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18502).update(id: 18502,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18515).update(id: 18515,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18520).update(id: 18520,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18524).update(id: 18524,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18525).update(id: 18525,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18527).update(id: 18527,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18535).update(id: 18535,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18604).update(id: 18604,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18609).update(id: 18609,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18621).update(id: 18621,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18624).update(id: 18624,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18632).update(id: 18632,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18639).update(id: 18639,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18640).update(id: 18640,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18646).update(id: 18646,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18682).update(id: 18682,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18711).update(id: 18711,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18717).update(id: 18717,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18745).update(id: 18745,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18748).update(id: 18748,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18751).update(id: 18751,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18778).update(id: 18778,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18793).update(id: 18793,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18806).update(id: 18806,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18830).update(id: 18830,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18839).update(id: 18839,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18851).update(id: 18851,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18854).update(id: 18854,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18856).update(id: 18856,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18873).update(id: 18873,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18874).update(id: 18874,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18880).update(id: 18880,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18943).update(id: 18943,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18953).update(id: 18953,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(18970).update(id: 18970,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19043).update(id: 19043,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19110).update(id: 19110,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19286).update(id: 19286,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19288).update(id: 19288,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19305).update(id: 19305,instance: 'GRADO DE CONSULTA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19474).update(id: 19474,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19481).update(id: 19481,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19483).update(id: 19483,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19487).update(id: 19487,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19488).update(id: 19488,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19490).update(id: 19490,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19530).update(id: 19530,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(19760).update(id: 19760,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20095).update(id: 20095,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20166).update(id: 20166,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20167).update(id: 20167,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20168).update(id: 20168,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20216).update(id: 20216,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20217).update(id: 20217,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20218).update(id: 20218,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20220).update(id: 20220,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20221).update(id: 20221,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20225).update(id: 20225,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20235).update(id: 20235,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20243).update(id: 20243,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20245).update(id: 20245,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20246).update(id: 20246,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20247).update(id: 20247,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20249).update(id: 20249,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20250).update(id: 20250,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20251).update(id: 20251,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20254).update(id: 20254,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20260).update(id: 20260,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20262).update(id: 20262,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20265).update(id: 20265,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20271).update(id: 20271,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20283).update(id: 20283,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20284).update(id: 20284,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20285).update(id: 20285,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20286).update(id: 20286,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20290).update(id: 20290,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20291).update(id: 20291,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20301).update(id: 20301,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20302).update(id: 20302,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20303).update(id: 20303,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20304).update(id: 20304,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20307).update(id: 20307,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20308).update(id: 20308,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20334).update(id: 20334,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20354).update(id: 20354,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20372).update(id: 20372,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20380).update(id: 20380,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20381).update(id: 20381,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20382).update(id: 20382,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20387).update(id: 20387,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20388).update(id: 20388,instance: 'RECURSO EXTRAORDINARIO',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20400).update(id: 20400,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20409).update(id: 20409,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20462).update(id: 20462,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20478).update(id: 20478,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20480).update(id: 20480,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20481).update(id: 20481,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20482).update(id: 20482,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20536).update(id: 20536,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20577).update(id: 20577,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20578).update(id: 20578,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20579).update(id: 20579,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20593).update(id: 20593,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20596).update(id: 20596,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20635).update(id: 20635,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20644).update(id: 20644,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20645).update(id: 20645,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20646).update(id: 20646,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20647).update(id: 20647,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20648).update(id: 20648,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20649).update(id: 20649,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20650).update(id: 20650,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20651).update(id: 20651,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20652).update(id: 20652,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20658).update(id: 20658,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20661).update(id: 20661,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20753).update(id: 20753,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20756).update(id: 20756,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20769).update(id: 20769,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20770).update(id: 20770,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20787).update(id: 20787,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20807).update(id: 20807,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20817).update(id: 20817,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20904).update(id: 20904,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20973).update(id: 20973,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20979).update(id: 20979,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20980).update(id: 20980,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(20992).update(id: 20992,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21017).update(id: 21017,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21024).update(id: 21024,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21106).update(id: 21106,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21108).update(id: 21108,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21109).update(id: 21109,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21139).update(id: 21139,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21140).update(id: 21140,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21143).update(id: 21143,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21144).update(id: 21144,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21149).update(id: 21149,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21171).update(id: 21171,instance: 'UNICA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21180).update(id: 21180,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21382).update(id: 21382,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21383).update(id: 21383,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21398).update(id: 21398,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21399).update(id: 21399,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21402).update(id: 21402,instance: 'SEGUNDA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21403).update(id: 21403,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21408).update(id: 21408,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21430).update(id: 21430,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
    puts TypeProcess.find(21434).update(id: 21434,instance: 'PRIMERA',state_db: 'REGISTRO MIGRADO SOBRESCRITO')
  end
end
