class MayraTutelas < ActiveRecord::Migration[5.1]
  def change
TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '06/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47182',creation_date: '06/08/2018',link_type: 'ACCIONADO',active_part: 'JOSE ORLANDO JOVEN GIL ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 007 ADMINISTRATIVO ORAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00316',answer_date: '08/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '06/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47183',creation_date: '06/08/2018',link_type: 'ACCIONADO',active_part: 'ALICIA RIOS HERRERA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 PENAL DEL CIRCUITO PARA ADOLESCENTES CON FUNCIONES DE CONOCIMIENTO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00073',answer_date: '08/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47407',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'JOAQUIN MIGUEL MARRUGO BERRIO ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 DE PEQUENAS CAUSAS LABORALES DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00055',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47360',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'EVANHGELINA SANCHEZ DE TELLEZ ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 007 CIVIL MUNICIPAL DE ORALIDAD DE CUCUTA',departament: '54',city_case: '001',process_radicate: '2018-00715',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47361',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'RUDENCINO RUBIO GALINDO ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 CIVIL DEL CIRCUITO ESPECIALIZADO EN RESTITUCION DE TIERRAS DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00093',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47362',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'JORGE ELIECER GONZALEZ CORDERO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 014 CIVIL MUNICIPAL DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00571',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47363',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'EDUARDO ALONSO CHIQUILLO PADILLA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 CIVIL MUNICIPAL DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00687',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47364',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'MARCO FIDEL GUTIERREZ ALVAREZ ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 LABORAL DEL CIRCUITO DE BARRANQUILLA',departament: '08',city_case: '001',process_radicate: '2018-00258',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47365',creation_date: '08/08/2018',link_type: 'ACCIONADO',active_part: 'ALEXANDER DE JESUS ARIZA MORALES',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 021 CIVIL MUNICIPAL DE BARRANQUILLA',departament: '08',city_case: '001',process_radicate: '2018-00690',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '09/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47372',creation_date: '09/08/2018',link_type: 'ACCIONADO',active_part: 'HERNAN PERDOMO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 006 ADMINISTRATIVO ORAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00320',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '09/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47373',creation_date: '09/08/2018',link_type: 'ACCIONADO',active_part: 'DIONISIO RAMON TORRES LORA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 011 CIVIL MUNICIPAL DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00275',answer_date: '13/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '09/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47374',creation_date: '09/08/2018',link_type: 'ACCIONADO',active_part: 'AGRIPINA HERRERA PADILLA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 005 DE PEQUENAS CAUSAS LABORALES DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00328',answer_date: '13/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '10/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47375',creation_date: '10/08/2018',link_type: 'ACCIONADO',active_part: 'ELIGIO VALOYES MORENO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 013 CIVIL MUNICIPAL DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00601',answer_date: '13/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47377',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'ENEIDER ALEJANDRO SUAREZ FUENTES',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 004 PENAL MUNICIPAL CON FUNCIONES DE CONTROL DE GARANTIAS DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00162',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47378',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'OVIDIO RAFAEL MARTINEZ GUERRERO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 005 PENAL MUNICIPAL CON FUNCIONES DE CONOCIMIENTO DE BARRANQUILLA',departament: '08',city_case: '001',process_radicate: '2018-00118',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47379',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'ORLANDO CRIOLLO CUBILLOS ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00045',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47380',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'JHON EDWARD CASTIBLANCO PARDO ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 003 CIVIL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00236',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47381',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'ORLINDA BERNAL SANCHEZ ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 CIVIL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00240',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47382',creation_date: '13/08/2018',link_type: 'ACCIONADO',active_part: 'JUAN CARLOS CHAPARRO QUINTERO ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 010 CIVIL MUNICIPAL DE CARTAGENA',departament: '13',city_case: '001',process_radicate: '2018-00551',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '15/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47386',creation_date: '15/08/2018',link_type: 'ACCIONADO',active_part: 'CLAUDIA PATRICIA AVILA CUEVAS ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PENAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00073',answer_date: '16/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '16/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47408',creation_date: '16/08/2018',link_type: 'ACCIONADO',active_part: 'JOSE ELIEL MINA PALACIO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 004 PENAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00075',answer_date: '16/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '16/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47409',creation_date: '16/08/2018',link_type: 'ACCIONADO',active_part: 'LIZETH VIVIANA MENDEZ POSADA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00046',answer_date: '16/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47595',creation_date: '17/08/2018',link_type: 'ACCIONADO',active_part: 'MARIA PAULA LONDOÑO GAITAN',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 005 CIVIL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00249',answer_date: '21/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47596',creation_date: '17/08/2018',link_type: 'ACCIONADO',active_part: 'HEBER ELIAS VILLERO MENDOZA',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 003 PENAL MUNICIPAL PARA LA ADOLESCENCIA CON FUNCIONES DE CONTROL DE GARANTIAS DE VALLEDUPAR',departament: '20',city_case: '001',process_radicate: '2018-00225',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47597',creation_date: '17/08/2018',link_type: 'ACCIONADO',active_part: 'CRISTIAN ENRIQUE CUELLAR DIAZ ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 PENAL DEL CIRCUITO PARA ADOLESCENTES CON FUNCIONES DE CONOCIMIENTO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00077',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47598',creation_date: '17/08/2018',link_type: 'ACCIONADO',active_part: 'GERARDO SANCHEZ BALLESTEROS ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 PENAL DEL CIRCUITO ESPECIALIZADO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00177',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47599',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'ELCY PAOLA PARRA CARRILLO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 013 PENAL MUNICIPAL CON FUNCION DE CONTROL DE GARANTIAS DE BUCARAMANGA',departament: '68',city_case: '001',process_radicate: '2018-00101',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47600',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'LUIS EDUARDO ROJAS ALVAREZ ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 PENAL MUNICIPAL PARA ADOLESCENTES CON FUNCIONES DE CONTROL DE GARANTIAS DE BUCARAMANGA',departament: '68',city_case: '001',process_radicate: '2018-00117',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47601',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'ALEJANDRO SALGADO RIVERA ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 PENAL MUNICIPAL CON FUNCIONES DE CONTROL DE GARANTIAS DE BARRANQUILLA',departament: '08',city_case: '001',process_radicate: '2018-00141',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '22/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47607',creation_date: '22/08/2018',link_type: 'ACCIONADO',active_part: 'JOSE FARID TOCORA ORTEGON',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 006 ADMINISTRATIVO ORAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00338',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '23/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47608',creation_date: '23/08/2018',link_type: 'ACCIONADO',active_part: 'LUCIA MARICELA MEDINA PASCUAS ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 001 DE EJECUCION DE PENAS Y MEDIDAS DE SEGURIDAD DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00048',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'JUNTA DE CALIFICACION',notification_date: '24/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47614',creation_date: '24/08/2018',link_type: 'ACCIONADO',active_part: 'AGUSTIN BAEZ ARAQUE',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 002 DE FAMILIA DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00297',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '06/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47179',creation_date: '06/08/2018',link_type: 'VINCULADO',active_part: 'JAVIER ALEXANDER NIETO QUEVEDO ',passive_part: 'ESE HOSPITAL SAN ANTONIO DE MITU Y OTROS',office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL DE MITU',departament: '97',city_case: '001',process_radicate: '2018-00099',answer_date: '08/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'FALTA DE LEGITIMACION',notification_date: '06/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47180',creation_date: '06/08/2018',link_type: 'VINCULADO',active_part: 'JOHNATTAN JESUS SUAREZ ',passive_part: 'ECO CAPITAL SA',office_name: 'JUZGADO 050 CIVIL MUNICIPAL DE BOGOTA',departament: '11',city_case: '001',process_radicate: '2018-00887',answer_date: '08/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION ',notification_date: '06/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47181',creation_date: '06/08/2018',link_type: 'ACCIONADO',active_part: 'JOHN JAIRO SERNA GUISAO',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 008 LABORAL DEL CIRCUITO DE CALI',departament: '76',city_case: '001',process_radicate: '2018-00429',answer_date: '08/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47366',creation_date: '08/08/2018',link_type: 'VINCULADO',active_part: 'JAMES CLINGER MOSQUERA PEREA ',passive_part: 'COMFACHOCO EPS Y OTRO',office_name: 'JUZGADO 007 ADMINISTRATIVO DE MEDELLIN',departament: '05',city_case: '001',process_radicate: '2018-00322',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47367',creation_date: '08/08/2018',link_type: 'VINCULADO',active_part: 'RAMIRO ANTONIO MUNERA ROJO',passive_part: 'FUNDACION SAN VICENTE DE PAUL Y OTRO',office_name: 'JUZGADO 001 PROMISCUO MUNICIPAL CON FUNCIONES DE CONTROL DE GARANTIAS DE BARBOSA',departament: '05',city_case: '079',process_radicate: '2018-00224',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRA PROVIDENCIA JUDICIAL',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47368',creation_date: '08/08/2018',link_type: 'VINCULADO',active_part: 'LUZ AMPARO FLOREZ LOPEZ ',passive_part: 'JUZGADO 005 CIVIL DEL CIRCUITO DE PEREIRA',office_name: 'TRIBUNA  TRIBUNAL SUPERIOR SALA UNITARIA CIVIL DE FAMILIA DE PEREIRA',departament: '66',city_case: '001',process_radicate: '2018-00598',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '08/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47369',creation_date: '08/08/2018',link_type: 'VINCULADO',active_part: 'MARIA DEPSI CASTILLO ',passive_part: 'CLINICA MEDILASER FLORENCIA Y OTROS',office_name: 'JUZGADO 002 CIVIL MUNICIPAL DE FLORENCIA',departament: '18',city_case: '001',process_radicate: '2018-00521',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '09/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47370',creation_date: '09/08/2018',link_type: 'VINCULADO',active_part: 'KUUING EDINSON VILLOTA MOZOMBITE',passive_part: 'DORECCION DE SANIDAD DE LA POLICIA NACIONAL ',office_name: 'JUZGADO 003 LABORAL DEL CIRCUITO DE CALI',departament: '76',city_case: '001',process_radicate: '2018-00408',answer_date: '09/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION ',notification_date: '09/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47371',creation_date: '09/08/2018',link_type: 'ACCIONADO',active_part: 'ABEL MENESES GALVIS ',passive_part: 'LA PREVISORA SA',office_name: 'JUZGADO 012 CIVIL MUNICIPAL DE BUCARAMANGA',departament: '68',city_case: '001',process_radicate: '2018-00538',answer_date: '13/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '10/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47376',creation_date: '10/08/2018',link_type: 'VINCULADO',active_part: 'HENRY ALEXANDER VARGAS VALBUENA',passive_part: 'MEDIMAS EPS',office_name: 'JUZGADO 004 PENAL MUNICIPAL CON FUNCION DE CONOCIMIENTO DE TUNJA',departament: '15',city_case: '001',process_radicate: '2018-00069',answer_date: '13/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'INCAPACIDAD TEMPORAL',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47383',creation_date: '13/08/2018',link_type: 'VINCULADO',active_part: 'HUGO HERMISON HENAO CARDENAS ',passive_part: 'SERVICIO OCCIDENTAL DE SALUD SOS EPS',office_name: 'JUZGADO  JUZGADO PROMISCUO MUNICIPAL DE LA UNION ',departament: '76',city_case: '400',process_radicate: '2018-00287',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '13/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47384',creation_date: '13/08/2018',link_type: 'VINCULADO',active_part: 'YHANA MILET ALARCON POLO ',passive_part: 'CENTRO MEDICO IMBANACO',office_name: 'JUZGADO 011 DE PEQUENAS CAUSAS Y COMPETENCIA MULTIPLE DE CALI',departament: '76',city_case: '001',process_radicate: '2018-00638',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '14/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47385',creation_date: '14/08/2018',link_type: 'ACCIONADO',active_part: 'YORYI ALEJANDRO ROJAS LASSO',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 002 PROMISCUO MUNICIPAL DE VILLAGARZON',departament: '86',city_case: '885',process_radicate: '2018-00152',answer_date: '14/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGUROS',notification_date: '16/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47591',creation_date: '16/08/2018',link_type: 'ACCIONADO',active_part: 'LUIS ENRIQUE RIOS BETANCOURTH ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 001 PENAL DEL CIRCUITO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00074',answer_date: '21/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'FALTA DE LEGITIMACION',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47592',creation_date: '17/08/2018',link_type: 'VINCULADO',active_part: 'JOSE ANTONIO DUQUE BELTRAN ',passive_part: 'CONSEJO SECCIONAL DE LA JUDICATURA DEL META',office_name: 'TRIBUNA  TRIBUNAL SUPERIOR DE VILLAVICENCIO ',departament: '50',city_case: '001',process_radicate: '2018-00044',answer_date: '21/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRA PROVIDENCIA JUDICIAL',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47593',creation_date: '17/08/2018',link_type: 'VINCULADO',active_part: 'NOHORA CRISTINA GUTIERREZ BARRERA',passive_part: 'JUZGADO 002 CIVIL DEL CIRCUITO DE BUCARAMANGA',office_name: 'TRIBUNA  TRIBUNAL SUPERIOR SALA CIVIL FAMILIA DE BUCARAMANGA ',departament: '68',city_case: '001',process_radicate: '2018-00319',answer_date: '21/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGUROS',notification_date: '17/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47594',creation_date: '17/08/2018',link_type: 'ACCIONADO',active_part: 'LUZ MARINA PEDROZA TRILLOS ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 001 CIVIL MUNICIPAL DE ORALIDAD DE OCANA',departament: '54',city_case: '498',process_radicate: '2018-00641',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47602',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'YENIFER ROJAS CLAROS ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 003 PENAL MUNICIPAL DE FLORENCIA',departament: '18',city_case: '001',process_radicate: '2018-00139',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGUROS',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47603',creation_date: '21/08/2018',link_type: 'VINCULADO',active_part: 'ANA BELISA SOTELO GOMEZ ',passive_part: 'FONDO NACIONAL DEL AHORRO Y OTRO',office_name: 'JUZGADO 006 PENAL DEL CIRCUITO DE POPAYAN',departament: '19',city_case: '001',process_radicate: '2018-00244',answer_date: '22/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47604',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'MARCO ANTONIO MAYORGA',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 007 ADMINISTRATIVO ORAL DEL CIRCUITO DE CALI',departament: '76',city_case: '001',process_radicate: '2018-00208',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGUROS',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47605',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'ELDER ALONSO MONTOYA PIEDRAHITA',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 021 PENAL DEL CIRCUITO CON FUNCIONES DE CONOCIMIENTO DE MEDELLIN',departament: '05',city_case: '001',process_radicate: '2018-00169',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION ',notification_date: '21/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47606',creation_date: '21/08/2018',link_type: 'ACCIONADO',active_part: 'LUIS ALBERTO ALBORNOZ SILVA ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO  JUZGADO PROMISCUO MUNICIPAL DE CURITI',departament: '68',city_case: '229',process_radicate: '2018-00040',answer_date: '23/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '23/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47609',creation_date: '23/08/2018',link_type: 'VINCULADO',active_part: 'JOSE ELDER VIGOYA CAMARGO',passive_part: 'EPS SANITAS',office_name: 'JUZGADO 005 PENAL MUNICIPAL CON FUNCIONES DE CONOCIMIENTO MIXTO DE VILLAVICENCIO',departament: '50',city_case: '001',process_radicate: '2018-00182',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION ',notification_date: '23/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47610',creation_date: '23/08/2018',link_type: 'ACCIONADO',active_part: 'CARLOS ARTURO MARTINEZ PAYANENE',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 056 PENAL DEL CIRCUITO CON FUNCION DE CONOCIMIENTO DE BOGOTA',departament: '11',city_case: '001',process_radicate: '2018-00161',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '24/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47611',creation_date: '24/08/2018',link_type: 'VINCULADO',active_part: 'ALEJANDRO VIDALES CARDONA',passive_part: 'EPS CM ALIANZA MEDELLIN SAVIA SALUD',office_name: 'JUZGADO  JUZGADO PROMISCUO MUNICIPAL DE VEGACHI',departament: '05',city_case: '858',process_radicate: '2018-00186',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '24/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47612',creation_date: '24/08/2018',link_type: 'VINCULADO',active_part: 'JOSE MIGUEL GARCIA MORALES',passive_part: 'CLINICA SANTA GRACIA POPAYAN',office_name: 'JUZGADO  JUZGADO MUNICIPAL DE PEQUENAS CAUSAS LABORALES DE POPAYAN',departament: '19',city_case: '001',process_radicate: '2018-00427',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'SOAT - AUTORIZACIONES EPS',notification_date: '24/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47613',creation_date: '24/08/2018',link_type: 'ACCIONADO',active_part: 'JOSE ANTONIO LOPEZ BRAVO',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 003 DE PEQUENAS CAUSAS Y COMPETENCIA MULTIPLE DE CUCUTA',departament: '54',city_case: '001',process_radicate: '2018-00918',answer_date: '27/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'DERECHO DE PETICION ',notification_date: '24/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47638',creation_date: '24/08/2018',link_type: 'ACCIONADO',active_part: 'GILBERTO SANDOVAL FIGEREDO ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 005 PENAL MUNICIPAL CON FUNCIONES DE CONTROL DE GARANTIAS DE BUCARAMANGA',departament: '68',city_case: '001',process_radicate: '2018-00106',answer_date: '28/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')

TypeProcess.create(process_class: 'TUTELA',subprocess_class: 'CONTRATO DE SEGUROS',notification_date: '27/08/2018',has_correspondency_radicate: true,correspondency_radicate: '47666',creation_date: '27/08/2018',link_type: 'ACCIONADO',active_part: 'MARTHA LUZ MARTINEZ ',passive_part: 'LA PREVISORA SA ',office_name: 'JUZGADO 003 PENAL DEL CIRCUITO CON FUNCION DE CONOCIMIENTO DE BOGOTA',departament: '11',city_case: '001',process_radicate: '2018-00089',answer_date: '28/08/2018',desition_date: 'PENDIENTE ',instance: 'PENDIENTE ',case_termination: 'PENDIENTE ',has_impug: false,imp_date: 'NO PRESENTA',tutelage_imp: 'NO PRESENTA',objection_date_desition: 'DD/MM/YYYY',date_notification_desition_desacate: 'DD/MM/YYYY',setence_type_second_company: 'NO PRESENTA',has_desacate: false,date_notification_desacate: 'DD/MM/YYYY',date_answer_desacate: 'DD/MM/YYYY',objection_date_desition_notification: 'DD/MM/YYYY',sentence_type_desacate: 'NO PRESENTA',user_id: 21,state: 'REGISTRO NUEVO')
  end
end
