class Aleja25 < ActiveRecord::Migration[5.1]
  def change
    puts TypeProcess.find(7425).update(id: 7425,reason_conc: ' SI BIEN SE DIO LA TERMINACION DE LOS CONTRATOS DE SEGURO MATERIALIZADOS EN LAS POLIZAS 1001335 Y 1001436 POR FALTA DE NOTIFICACION DE LA AGRAVACION DEL ESTADO DEL RIESGO LAS POLIZAS FUERON RENOVADAS')
  end
end
